### ISSUE TITLE
pkg/test/framework/components/apps/local/agent::TestFull is flaky

### ISSUE THREAD

**Issue by ayj** [istio/istio#10023]
xref: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10021/istio-unit-tests/16875

```
--- FAIL: TestFull (10.28s)
	pilot_agent_test.go:62: failed to start envoy after 10s. Error: Get http://127.0.0.1:43401/server_info: dial tcp 127.0.0.1:43401: connect: connection refused
```

**Comment by ayj** [comment]
xref: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10025/istio-unit-tests/16882

```
--- FAIL: TestFull (10.50s)
	pilot_agent_test.go:62: failed to configure Envoys: service a missing config for outbound listener 0.0.0.0_41113
```

**Comment by hzxuzhonghu** [comment]
`TestMinimal` also failed

**Comment by ayj** [comment]
Confirmed. I renamed the PR to indicate the test is flaky. 

Most recent flake: https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/10004/istio-unit-tests/17106

```
--- FAIL: TestFull (10.30s)
	pilot_agent_test.go:62: failed to start envoy after 10s. Error: Get http://127.0.0.1:42887/server_info: dial tcp 127.0.0.1:42887: connect: connection refused
FAIL
```

**Comment by nmittler** [comment]
Great - thanks, @ayj

**Comment by irisdingbj** [comment]
@nmittler now every agent will have his own portManager.  When envoy starts the port reserved by his portManager might be reserved by another portManager. So it will have error like" external/envoy/source/server/server.cc:84] error initializing configuration '/tmp/istio_agent_envoy_config879447953.yaml': cannot bind '127.0.0.1:36463': Address already in use"
I have submitted a PR https://github.com/istio/istio/pull/10718 to make all agents in testing use one portManager. Can you review it?

**Comment by nmittler** [comment]
@irisdingbj approved ... thanks!

**Comment by smawson** [comment]
Is this issue fixed?

**Comment by hklai** [comment]
Still happening in postsubmit.
https://gubernator.k8s.io/build/istio-prow/logs/istio-postsubmit/4160

**Comment by ozevren** [comment]
FWIW, I've ran into a panic when trying to run the agent tests locally:
```
2019-01-31T20:39:28.471078Z	info	starting discovery service at http=[::]:59244 grpc=[::]:59245
Listening HTTP/1.1 on 59247
Listening GRPC on 59248
--- FAIL: TestMinimal (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1cc93e6]

goroutine 15 [running]:
testing.tRunner.func1(0xc4203b00f0)
/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x257b7a0, 0x35c4c80)
/usr/local/go/src/runtime/panic.go:502 +0x229
istio.io/istio/pkg/test/envoy.isEnvoyBinary(0x0, 0x0, 0x10906ed)
/Users/ozben/go/src/istio.io/istio/pkg/test/envoy/envoy.go:204 +0x26
istio.io/istio/pkg/test/envoy.findEnvoyBinaries.func1(0x0, 0x0, 0x0, 0x0, 0x2980b40, 0xc4205133e0, 0x10, 0x25f1c20)
/Users/ozben/go/src/istio.io/istio/pkg/test/envoy/envoy.go:214 +0x42
path/filepath.Walk(0x0, 0x0, 0xc4204938d0, 0x3604060, 0x0)
/usr/local/go/src/path/filepath/path.go:401 +0x6c
istio.io/istio/pkg/test/envoy.findEnvoyBinaries(0xc4204a2580, 0xc4204a2580, 0xc4202077e0, 0xc4202077e8, 0x102b8a9)
/Users/ozben/go/src/istio.io/istio/pkg/test/envoy/envoy.go:213 +0xdb
istio.io/istio/pkg/test/envoy.getDefaultEnvoyBinaryPath(0xc4200f07e0, 0x0, 0x0, 0xc4200f07e0)
/Users/ozben/go/src/istio.io/istio/pkg/test/envoy/envoy.go:245 +0x26
istio.io/istio/pkg/test/envoy.(*Envoy).Start(0xc4200f07e0, 0x0, 0x0)
/Users/ozben/go/src/istio.io/istio/pkg/test/envoy/envoy.go:101 +0x1ab
istio.io/istio/pkg/test/framework/runtime/components/apps/agent.(*pilotAgent).start(0xc42002a000, 0x27f3050, 0x1, 0x0, 0x0, 0xc4202f5730, 0xc42028ab70, 0xc42005c258, 0xc42005c260)
/Users/ozben/go/src/istio.io/istio/pkg/test/framework/runtime/components/apps/agent/pilot_agent.go:406 +0x538
```

**Comment by kyessenov** [comment]
Still flakes as of now:
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10630/istio-unit-tests/20558

**Comment by nmittler** [comment]
The test in question no longer exists and the apps component has been replaced with Echo. Closing.
