### ISSUE TITLE
Galley crashes in 1.1.0-snapshot.3

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#10226]
**Describe the bug**
Galley is crashing with the following stack trace,
```
2018-12-01T01:24:37.241379Z	error	Observed a panic: "index out of range" (runtime error: index out of range)
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:28
/workspace/go/src/istio.io/istio/galley/pkg/kube/source/source.go:152
/workspace/go/src/istio.io/istio/galley/pkg/kube/source/source.go:105
/workspace/go/src/istio.io/istio/galley/pkg/kube/source/source.go:66
/workspace/go/src/istio.io/istio/galley/pkg/kube/source/listener.go:190
/workspace/go/src/istio.io/istio/galley/pkg/kube/source/listener.go:125
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/controller.go:209
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/shared_informer.go:556
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:2361

panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 427 [running]:
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1b26340, 0x2d20ec0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
istio.io/istio/galley/pkg/kube/source.ProcessEvent(0xc42040cb40, 0x1e00691, 0x7, 0x1e0392c, 0x9, 0x1e0522a, 0xa, 0x1e01031, 0x7, 0x1dffaf2, ...)
	/workspace/go/src/istio.io/istio/galley/pkg/kube/source/source.go:152 +0x81f
istio.io/istio/galley/pkg/kube/source.(*sourceImpl).process(0xc42084ef00, 0xc420553520, 0x3, 0xc425581940, 0x20, 0xc423b11cb8, 0x8, 0xc42295f978)
	/workspace/go/src/istio.io/istio/galley/pkg/kube/source/source.go:105 +0x112
istio.io/istio/galley/pkg/kube/source.(*sourceImpl).(istio.io/istio/galley/pkg/kube/source.process)-fm(0xc420553520, 0x3, 0xc425581940, 0x20, 0xc423b11cb8, 0x8, 0xc42295f978)
	/workspace/go/src/istio.io/istio/galley/pkg/kube/source/source.go:66 +0x73
istio.io/istio/galley/pkg/kube/source.(*listener).handleEvent(0xc420553520, 0x3, 0x1de3f00, 0xc42295f978)
	/workspace/go/src/istio.io/istio/galley/pkg/kube/source/listener.go:190 +0x1ec
istio.io/istio/galley/pkg/kube/source.(*listener).start.func5(0x1de3f00, 0xc42295f978)
	/workspace/go/src/istio.io/istio/galley/pkg/kube/source/listener.go:125 +0x47
istio.io/istio/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(0xc4206534a0, 0xc4206534b0, 0xc4206534c0, 0x1de3f00, 0xc42295f978)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/controller.go:209 +0x49
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x4298ff, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/shared_informer.go:556 +0x1d8
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc42599fdf0, 0x429449, 0xc420b87110)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0x9c
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x81
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420b35f68)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42599ff68, 0xdf8475800, 0x0, 0x1ade701, 0xc420028d80)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420b35f68, 0xdf8475800, 0xc420028d80)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc4206d7e00)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x78
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*processorListener).(istio.io/istio/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390 +0x2a
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc4201c7640, 0xc420696c70)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Steps to reproduce the bug**
Deployed via Helm and ran a number of pod applications.

**Version**
**Istio**: 1.1.0-snapshot.3
**Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
via Helm

**Environment**
GKE

**Comment by nixgadget** [comment]
Also observing the error,
```
Warning  Unhealthy  3m (x6845 over 18h)  kubelet, gke-riro-cluster-control-pool-84b1419b-xxs8  Readiness probe failed: fail on inspecting path /healthready: stat /healthready: no such file or directory
```

**Comment by GregHanson** [comment]
@hzxuzhonghu ok to close this one?

**Comment by hzxuzhonghu** [comment]
Weird the bot did not auto close this
