### ISSUE TITLE
 Pilot 1.0.5: concurrent map iteration and map write

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#10868]
**Describe the bug**
{{ Succinctly describe the bug }}
pilot restart at times and the logs:

```
{"log":"fatal error: concurrent map iteration and map write\n","stream":"stderr","time":"2019-01-10T09:07:52.665818414Z"}
{"log":"\n","stream":"stderr","time":"2019-01-10T09:07:52.668998878Z"}
{"log":"goroutine 2204965 [running]:\n","stream":"stderr","time":"2019-01-10T09:07:52.669004619Z"}
{"log":"runtime.throw(0x18ed2ba, 0x26)\n","stream":"stderr","time":"2019-01-10T09:07:52.669007767Z"}
{"log":"  /usr/local/go/1.10.1/libexec/src/runtime/panic.go:616 +0x81 fp=0xc42182d590 sp=0xc42182d570 pc=0x42ac81\n","stream":"stderr","time":"2019-01-10T09:07:52.669010681Z"}
{"log":"runtime.mapiternext(0xc42182d858)\n","stream":"stderr","time":"2019-01-10T09:07:52.669016044Z"}
{"log":"  /usr/local/go/1.10.1/libexec/src/runtime/hashmap.go:747 +0x55c fp=0xc42182d620 sp=0xc42182d590 pc=0x408aec\n","stream":"stderr","time":"2019-01-10T09:07:52.669019086Z"}
{"log":"runtime.mapiterinit(0x168b780, 0xc421007200, 0xc42182d858)\n","stream":"stderr","time":"2019-01-10T09:07:52.669023642Z"}
{"log":"  /usr/local/go/1.10.1/libexec/src/runtime/hashmap.go:737 +0x1f1 fp=0xc42182d648 sp=0xc42182d620 pc=0x4084a1\n","stream":"stderr","time":"2019-01-10T09:07:52.669027306Z"}
{"log":"istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).updateClusterInc(0xc4203fee10, 0xc421114410, 0xc4216aa510, 0x29, 0xc42091bea0, 0x0, 0x0)\n","stream":"stderr","time":"2019-01-10T09:07:52.669059509Z"}
{"log":"  /Users/devspace/gospace/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:222 +0x274 fp=0xc42182d998 sp=0xc42182d648 pc=0x1456994\n","stream":"stderr","time":"2019-01-10T09:07:52.669071627Z"}
{"log":"istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).edsIncremental(0xc4203fee10, 0xc422fe5920, 0x19, 0xc421114410, 0xc4217869c0)\n","stream":"stderr","time":"2019-01-10T09:07:52.669076469Z"}
{"log":"  /Users/devspace/gospace/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:451 +0x473 fp=0xc42182dcb0 sp=0xc42182d998 pc=0x1458ce3\n","stream":"stderr","time":"2019-01-10T09:07:52.66909105Z"}
{"log":"istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).AdsPushAll(0xc4203fee10, 0xc422fe5920, 0x19, 0xc421114410, 0xc422728300, 0xc4217869c0)\n","stream":"stderr","time":"2019-01-10T09:07:52.669095129Z"}
{"log":"  /Users/devspace/gospace/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:628 +0x6ed fp=0xc42182dfb0 sp=0xc42182dcb0 pc=0x144980d\n","stream":"stderr","time":"2019-01-10T09:07:52.669121326Z"}
```
**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
istio 1.0.5
**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by hzxuzhonghu** [comment]
this can also occur in release-1.1
