### ISSUE TITLE
Fluentd mixer adapter can stall Mixer

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#11057]
Fluent adapter sends one instance at a time over http to the fluentd server. This is inefficient and the adapter can stall progress of mixer when this happens.

The adapter is unable to keep up with 1k rps of mesh traffic.

connection write has stalled for 8 minutes
```
GOSkVvoASpTVVRGbi45DEg== 1 times:goroutine 181 [IO wait, 8 minutes]:internal/poll.runtime_pollWait(0x7f99f0838e50, 0x77, 0xc4205e97c0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420f4f318, 0x77, 0xffffffffffffff00, 0x1c6a8c0, 0x2757740)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitWrite(0xc420f4f318, 0xc468f74100, 0xd7, 0x95eb9)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:94 +0x3d
internal/poll.(*FD).Write(0xc420f4f300, 0xc468f74000, 0x21e, 0x96000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:264 +0x237
net.(*netFD).Write(0xc420f4f300, 0xc468f74000, 0x21e, 0x96000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:220 +0x4f
net.(*conn).Write(0xc420a95c58, 0xc468f74000, 0x21e, 0x96000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:188 +0x6a
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).send(0xc420cc00c0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:323 +0x20e
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).postRawData(0xc420cc00c0, 0xc4695f8600, 0x220, 0x2c9, 0xed3d1c90b, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:193 +0x6a
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).EncodeAndPostData(0xc420cc00c0, 0xc429225a00, 0x20, 0x22a5b907, 0xed3d1c90b, 0x0, 0x182ed40, 0xc43a0dfd10, 0x94, 0xc4205e9b38)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:181 +0x182
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).PostWithTime(0xc420cc00c0, 0xc429225a00, 0x20, 0x22a5b907, 0xed3d1c90b, 0x0, 0x182ed40, 0xc47e3042d0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:172 +0x767
istio.io/istio/mixer/adapter/fluentd.(*handler).HandleLogEntry(0xc42fbea000, 0x1c8fd80, 0xc468431350, 0xc47f0b5cc0, 0x27, 0x27, 0x0, 0xc4205e9d80)
	/workspace/go/src/istio.io/istio/mixer/adapter/fluentd/fluentd.go:147 +0x53f
istio.io/istio/mixer/template.glob..func47(0x1c8fd80, 0xc468431350, 0x1c656e0, 0xc42fbea000, 0xc454ea4400, 0x27, 0x40, 0xbf081272fac7fe18, 0x23be7bfe65f26)
	/workspace/go/src/istio.io/istio/mixer/template/template.gen.go:1648 +0x143
istio.io/istio/mixer/pkg/runtime/dispatcher.(*dispatchState).invokeHandler(0xc45b032480, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/dispatcher/dispatchstate.go:119 +0x4c7
istio.io/istio/mixer/pkg/runtime/dispatcher.(*dispatchState).(istio.io/istio/mixer/pkg/runtime/dispatcher.invokeHandler)-fm(0x0, 0x0)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/dispatcher/session.go:231 +0x3e
istio.io/istio/mixer/pkg/pool.(*GoroutinePool).AddWorkers.func1(0xc42045a220)
	/workspace/go/src/istio.io/istio/mixer/pkg/pool/goroutine.go:82 +0x6f
created by istio.io/istio/mixer/pkg/pool.(*GoroutinePool).AddWorkers
	/workspace/go/src/istio.io/istio/mixer/pkg/pool/goroutine.go:80 +0x6c
```

getting lock to the connection
```
WcQ37I03jTMdDyHGYBTHiA== 1011 times:goroutine 41 [semacquire, 8 minutes]:sync.runtime_SemacquireMutex(0xc420cc015c, 0xc442bd1800)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420cc0158)
	/usr/local/go/src/sync/mutex.go:134 +0x108
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).send(0xc420cc00c0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:301 +0x45
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).postRawData(0xc420cc00c0, 0xc478c02900, 0x220, 0x2c9, 0xed3d1c725, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:193 +0x6a
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).EncodeAndPostData(0xc420cc00c0, 0xc429225a00, 0x20, 0x273b41cd, 0xed3d1c725, 0x0, 0x182ed40, 0xc47e253ce0, 0x94, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:181 +0x182
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).PostWithTime(0xc420cc00c0, 0xc429225a00, 0x20, 0x273b41cd, 0xed3d1c725, 0x0, 0x182ed40, 0xc44b0292c0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:172 +0x767
istio.io/istio/mixer/adapter/fluentd.(*handler).HandleLogEntry(0xc42fbea000, 0x1c8fd80, 0xc445db34a0, 0xc420224300, 0xd5, 0xd5, 0x0, 0xc442bd1d80)
	/workspace/go/src/istio.io/istio/mixer/adapter/fluentd/fluentd.go:147 +0x53f
istio.io/istio/mixer/template.glob..func47(0x1c8fd80, 0xc445db34a0, 0x1c656e0, 0xc42fbea000, 0xc42d3f7000, 0xd5, 0x100, 0xbf0811e9afcbe17b, 0x23b67e1f7108b)
	/workspace/go/src/istio.io/istio/mixer/template/template.gen.go:1648 +0x143
istio.io/istio/mixer/pkg/runtime/dispatcher.(*dispatchState).invokeHandler(0xc449b490e0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/dispatcher/dispatchstate.go:119 +0x4c7
istio.io/istio/mixer/pkg/runtime/dispatcher.(*dispatchState).(istio.io/istio/mixer/pkg/runtime/dispatcher.invokeHandler)-fm(0x0, 0x0)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/dispatcher/session.go:231 +0x3e
istio.io/istio/mixer/pkg/pool.(*GoroutinePool).AddWorkers.func1(0xc42045a220)
	/workspace/go/src/istio.io/istio/mixer/pkg/pool/goroutine.go:82 +0x6f
created by istio.io/istio/mixer/pkg/pool.(*GoroutinePool).AddWorkers
	/workspace/go/src/istio.io/istio/mixer/pkg/pool/goroutine.go:80 +0x6c
```

getting lock on the buffer
```
QKiEI6rCfKcv4b/eKpi5yA== 13 times:goroutine 86 [semacquire, 8 minutes]:sync.runtime_SemacquireMutex(0xc420cc013c, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420cc0138)
	/usr/local/go/src/sync/mutex.go:134 +0x108
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).appendBuffer(0xc420cc00c0, 0xc469480300, 0x220, 0x2c9, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:241 +0x56
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).postRawData(0xc420cc00c0, 0xc469480300, 0x220, 0x2c9, 0xed3d1c8db, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:190 +0x4d
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).EncodeAndPostData(0xc420cc00c0, 0xc429225a00, 0x20, 0x1a6cefcb, 0xed3d1c8db, 0x0, 0x182ed40, 0xc47ff3b5f0, 0x94, 0x0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:181 +0x182
istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).PostWithTime(0xc420cc00c0, 0xc429225a00, 0x20, 0x1a6cefcb, 0xed3d1c8db, 0x0, 0x182ed40, 0xc46c344db0, 0x1ca8e60, 0xc481a034a0)
	/workspace/go/src/istio.io/istio/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:172 +0x767
istio.io/istio/mixer/adapter/fluentd.(*handler).HandleLogEntry(0xc42fbea000, 0x1c8fd80, 0xc47ff3b5c0, 0xc4210af2b0, 0x1a, 0x1a, 0x0, 0xc480eb3d80)
	/workspace/go/src/istio.io/istio/mixer/adapter/fluentd/fluentd.go:147 +0x53f
istio.io/istio/mixer/template.glob..func47(0x1c8fd80, 0xc47ff3b5c0, 0x1c656e0, 0xc42fbea000, 0xc498c58000, 0x1a, 0x20, 0xbf0812e04078b32f, 0x23c4d806cb066)
	/workspace/go/src/istio.io/istio/mixer/template/template.gen.go:1648 +0x143
istio.io/istio/mixer/pkg/runtime/dispatcher.(*dispatchState).invokeHandler(0xc45e4bf0e0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/dispatcher/dispatchstate.go:119 +0x4c7
istio.io/istio/mixer/pkg/runtime/dispatcher.(*dispatchState).(istio.io/istio/mixer/pkg/runtime/dispatcher.invokeHandler)-fm(0x0, 0x0)
	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/dispatcher/session.go:231 +0x3e
istio.io/istio/mixer/pkg/pool.(*GoroutinePool).AddWorkers.func1(0xc42045a220)
	/workspace/go/src/istio.io/istio/mixer/pkg/pool/goroutine.go:82 +0x6f
created by istio.io/istio/mixer/pkg/pool.(*GoroutinePool).AddWorkers
	/workspace/go/src/istio.io/istio/mixer/pkg/pool/goroutine.go:80 +0x6c

```

This stalls all forward progress of mixer.

**Comment by mandarjog** [comment]
Reported by knative... @tcnghia

**Comment by douglas-reid** [comment]
I'm testing a workaround now specifically for `fluentd` adapter. Longer term, we may want to look a broader solution.
