### ISSUE TITLE
Problems connecting to redis cluster on 1.1.0-snapshot.4

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#11140]
**Provider**: EKS
**Kubernetes version**: v1.11.5
**mTLS**: enabled
**Istio**: 1.1.0-snapshot.4

I'm trying to connect a java application (running inside the mesh) to a redis cluster (running outside the mesh).
redis cluster is in the namespace `storage` while application is running in `apps` namespace.
As I have mTLS enabled in the mesh I disabled it specifically for `storage` namespace with the following,
```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "storage"
spec:
  host: "*.storage.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
```

This works perfectly fine in `1.1.0-snapshot.3` however I'm running into the following problem with `1.1.0-snapshot.4`.

```
2019-01-22 08:22:09.903 ERROR [authorization-service,,,] 1 --- [sson-netty-11-2] o.r.client.handler.CommandPubSubDecoder  : Error: unsupported command 'SUBSCRIBE' channel: [id: 0x605a8390, L:/192.168.46.120:39384 - R:rc-redis-server-master-svc.storage.svc.cluster.local/10.100.89.36:6379] data: null
....
Caused by: org.redisson.client.RedisTimeoutException: Subscribe timeout: (10500ms)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:128)
	at org.redisson.RedissonTopic.addListener(RedissonTopic.java:105)
	at org.redisson.RedissonTopic.addListener(RedissonTopic.java:94)
	at org.redisson.RedissonLocalCachedMap.addListeners(RedissonLocalCachedMap.java:222)
	at org.redisson.RedissonLocalCachedMap.init(RedissonLocalCachedMap.java:215)
	at org.redisson.RedissonLocalCachedMap.<init>(RedissonLocalCachedMap.java:192)
	at org.redisson.Redisson.getLocalCachedMap(Redisson.java:255)
	at co.riro.authorizationservice.db.redis.RedisUserDaoImpl.initialise(RedisUserDaoImpl.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	... 72 common frames omitted
```

Istio proxy (envoy) logging just shows the following,
```
[2019-01-22T07:02:01.729Z] "- - -" 0 - 0 0 11401 - "-" "-" "-" "-" "192.168.2.225:6379" outbound|6379||rc-redis-server-master-svc.storage.svc.cluster.local 192.168.7.17:55120 10.100.89.36:6379 192.168.7.17:57224 -
[2019-01-22T07:02:01.449Z] "- - -" 0 - 0 0 11688 - "-" "-" "-" "-" "192.168.2.225:6379" outbound|6379||rc-redis-server-master-svc.storage.svc.cluster.local 192.168.7.17:55108 10.100.89.36:6379 192.168.7.17:57212 -
[2019-01-22T07:02:01.453Z] "- - -" 0 - 0 0 11684 - "-" "-" "-" "-" "192.168.2.225:6379" outbound|6379||rc-redis-server-master-svc.storage.svc.cluster.local 192.168.7.17:55112 10.100.89.36:6379 192.168.7.17:57216 -
[2019-01-22T07:02:01.537Z] "- - -" 0 - 0 0 11601 - "-" "-" "-" "-" "192.168.2.225:6379" outbound|6379||rc-redis-server-master-svc.storage.svc.cluster.local 192.168.7.17:55116 10.100.89.36:6379 192.168.7.17:57220 -
```

**Comment by hzxuzhonghu** [comment]
`DestinationRule` is not necessary

**Comment by nixgadget** [comment]
@hzxuzhonghu reason i have the `DestinationRule` is to disable TLS in `storage` namespace. You think this is what is causing this ?

**Comment by nixgadget** [comment]
The storage layer (which consists of Redis, Cassandra, Kafka e.t.c), that the java services connect to, sit out the mesh. Hence why `TLS` is disabled. I don't want TLS enabled for any of the storage services.

The point is with `DestinationRule`, I see two different results with `1.1.0-snapshot.3` and `1.1.0-snapshot.4` when it comes to Redis. So the question is there anything special happening with `1.1.0-snapshot.4` ?

**Comment by hzxuzhonghu** [comment]
@nixgadget You mean the service with named port `redis-` can work well on `1.1.0-snapshot.3` but not on `1.1.0-snapshot.4`?

**Comment by nixgadget** [comment]
@hzxuzhonghu the other way around. If I have `redis-` in the named port then the java application breaks with the above stack error in `1.1.0-snapshot.4`.  Im assuming it treats it as `redis` protocol rather than tcp ?. Not sure.
Works fine with `1.1.0-snapshot.3`.

Some changes in `envoy` perhaps ?

**Comment by hzxuzhonghu** [comment]
If it is this, I think I find the cause
https://github.com/istio/istio/blob/e661de08e04e78e60f7fbec067e4357974fa27c3/pilot/pkg/networking/core/v1alpha3/networkfilter.go#L181-L194

**Comment by hzxuzhonghu** [comment]
@venilnoronha the redis filter added by you, any comment?

**Comment by XBeg9** [comment]
Have the same issue here, envoy proxy intercepts my request to Redis and says it's not implementing AUTH command. I found that [Envoy Redis](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/redis#arch-overview-redis) is not implementing `AUTH`. Do you have any ideas how to fix that?

**Comment by venilnoronha** [comment]
@XBeg9 this needs to be fixed in the Redis filter implementation in Envoy. See https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/network/redis_proxy. As a workaround, you should be able to connect to Redis by replacing the `redis-` prefix in the service port name with something else.

**Comment by nixgadget** [comment]
@venilnoronha any documentation around the redis proxy ? Is it https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/redis ?

**Comment by venilnoronha** [comment]
Then there is 

https://www.envoyproxy.io/docs/envoy/latest/configuration/network_filters/redis_proxy_filter#config-network-filters-redis-proxy

and

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/redis_proxy/v2/redis_proxy.proto#envoy-api-msg-config-filter-network-redis-proxy-v2-redisproxy.
