### ISSUE TITLE
Galley segfault under kubernetes integration2 testing framework

### ISSUE THREAD

**Issue by incfly** [istio/istio#12265]
When I tried to use new testing framework for my test, I ran cmd as below
```
 go test -v ./tests/integration2/security/healthcheck  -istio.test.noCleanup   -istio.test.env  kubernetes \
-istio.test.kube.helm.values "global.hub=gcr.io/jianfeih-test,global.tag=0302a"  \
--istio.test.kube.suiteNamespace  istio-suite   --istio.test.kube.testNamespace istio-test  
```

Istio system can not be marked as ready, and Pilot is haning on Galley's readiness. While I found errors about mcp connection
```
2019-03-05T19:04:23.127428Z     info    Handling event update for pod istio-galley-74b55bf8df-9gwqw in namespace istio-system -> 10.40.1.16
2019-03-05T19:04:23.286403Z     info    mcp     (re)trying to establish new MCP stream
2019-03-05T19:04:23.286755Z     error   mcp     Failed to create a new MCP stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.43.250.92:9901: connect: connection refused"
```

I looked at Galley side, it seems  that has been restarted several times. Look at logs, I found some null pointer dereference.

```
2019-03-05T19:01:33.045645Z     info    Istio Galley: root@8723422f-3682-11e9-8dad-0a580a2c0205-docker.io/istio-master-20190222-09-16-f385a88421d6854f4eacada9f6f090c4563a224c-dirty-Modified
Starting gRPC server on tcp://0.0.0.0:9901
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a798b2]

goroutine 34 [running]:
istio.io/istio/galley/pkg/server.(*Server).Run(0x0)
        /workspace/go/src/istio.io/istio/galley/pkg/server/server.go:217 +0x22
istio.io/istio/galley/pkg/server.RunServer(0xc4200decc0, 0x21fad00, 0xc42001ee10, 0x21fad00, 0xc42001ee60)
        /workspace/go/src/istio.io/istio/galley/pkg/server/server.go:277 +0x1b3
created by istio.io/istio/galley/cmd/galley/cmd.GetRootCmd.func2
        /workspace/go/src/istio.io/istio/galley/cmd/galley/cmd/root.go:88 +0x3c8
```

**Comment by howardjohn** [comment]
What Istio version are you using? This should be fixed now https://github.com/istio/istio/issues/11748

**Comment by incfly** [comment]
Figured it out, due to image was stale. Closing.
