### ISSUE TITLE
Pilot segfault when starting under heavy load

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12275]
**Describe the bug**
First, I created around 100 services, then I set Pilots CPU limit to `10m`. Upon start up, discovery logs show `Work item handle failed (waiting till full synchronization), retry after delay 1s` repeatedly. 

After 20s, Pilot crashes

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x148bffb]
goroutine 1984 [running]:
istio.io/istio/pilot/pkg/serviceregistry/kube.(*Controller).getProxyServiceInstancesByPod(0xc42046e400, 0xc420cd2250, 0xc420a80740, 0xc4202ca6e0, 0x1, 0x0, 0x0)
  /workspace/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:592 +0x22b
istio.io/istio/pilot/pkg/serviceregistry/kube.(*Controller).GetProxyServiceInstances(0xc42046e400, 0xc4202ca6e0, 0x3, 0x4, 0x0, 0x0, 0xc420406c00)
  /workspace/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:508 +0x953
istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).GetProxyServiceInstances(0xc42064a1e0, 0xc4202ca6e0, 0xc4215574b0, 0x138e6b0, 0x1956bc0, 0xc420e5b230, 0x1be74b8)
  /workspace/go/src/istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:225 +0x142
istio.io/istio/pilot/pkg/model.(*Proxy).SetServiceInstances(0xc4202ca6e0, 0xc4200b8b40, 0xf, 0xc4202ca6e0)
  /workspace/go/src/istio.io/istio/pilot/pkg/model/context.go:192 +0x41
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).initConnectionNode(0xc42047bb80, 0xc420e11300, 0xc4209e6540, 0x0, 0xc420ebce00)
  /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:626 +0x188
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc42047bb80, 0x1d9cbc0, 0xc42108bd80, 0x0, 0x0)
  /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:417 +0x3ff
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1bc7980, 0xc42047bb80, 0x1d96620, 0xc420d51130, 0x29e1918, 0xc420f2d1d0)
  /workspace/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:173 +0xb2
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4203be780, 0x1d9ed20, 0xc42149be00, 0xc420558a00, 0xc42064b350, 0x29a9be0, 0xc420f2d1a0, 0x0, 0x0)
  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1124 +0x911
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4203be780, 0x1d9ed20, 0xc42149be00, 0xc420558a00, 0xc420f2d1a0)
  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1212 +0x12b1
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42055d890, 0xc4203be780, 0x1d9ed20, 0xc42149be00, 0xc420558a00)
  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:686 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:684 +0xa1
```

**Version**
1.1 rc2

**Comment by duderino** [comment]
This is super important because if you have to add a bunch of pilots to relieve heavy load, you may not be able to add them successfully without temporarily diverting or dropping traffic.

**Comment by howardjohn** [comment]
fwiw, I have not been able to reproduce this after many attempts. Obviously still an issue, but I think it may be a rare one

**Comment by howardjohn** [comment]
Spoke too soon...
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x148c1ab]
istio-system/istio-pilot-859f68449b-2lzpf[discovery]:
goroutine 1207 [running]:
istio.io/istio/pilot/pkg/serviceregistry/kube.(*Controller).getProxyServiceInstancesByPod(0xc4205b6900, 0xc4208fa240, 0xc4209c9fa0, 0xc42096d810, 0x1, 0x0, 0x0)
  /workspace/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:592 +0x22b
istio.io/istio/pilot/pkg/serviceregistry/kube.(*Controller).GetProxyServiceInstances(0xc4205b6900, 0xc42096d810, 0x3, 0x4, 0x0, 0x0, 0xc42020e000)
  /workspace/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:508 +0x953
istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).GetProxyServiceInstances(0xc4204ce0f0, 0xc42096d810, 0xc42150d4b0, 0x138e6b0, 0x1957bc0, 0xc421169bf0, 0x1be84b8)
  /workspace/go/src/istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:225 +0x142
istio.io/istio/pilot/pkg/model.(*Proxy).SetServiceInstances(0xc42096d810, 0xc420432730, 0xf, 0xc42096d810)
  /workspace/go/src/istio.io/istio/pilot/pkg/model/context.go:192 +0x41
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).initConnectionNode(0xc420562370, 0xc42098d600, 0xc4208ad500, 0x0, 0xc42185a2b0)
  /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:626 +0x188
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc420562370, 0x1d9dc20, 0xc421610480, 0x0, 0x0)
  /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:417 +0x3ff
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1bc8980, 0xc420562370, 0x1d97680, 0xc420a3f550, 0x29e2918, 0xc421632750)
  /workspace/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:173 +0xb2
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420640180, 0x1d9fd80, 0xc421503200, 0xc421487a00, 0xc42061e8d0, 0x29aabe0, 0xc421632720, 0x0, 0x0)
  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1124 +0x911
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420640180, 0x1d9fd80, 0xc421503200, 0xc421487a00, 0xc421632720)
  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1212 +0x12b1
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420862330, 0xc420640180, 0x1d9fd80, 0xc421503200, 0xc421487a00)
  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:686 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:684 +0xa1
```

Exact reproduction steps:
* Generate large service `https://github.com/istio/tools/tree/master/perf/servicegraph/setup_large_test.sh 2`
* Set Pilot CPU limit to `10m`
* Restart Pilot repeatedly

**Comment by howardjohn** [comment]
Closed by https://github.com/istio/istio/pull/12279

**Comment by duderino** [comment]
nice one.  thanks @howardjohn
