### ISSUE TITLE
1.1-RC2: Pilot SIGSEGV due to concurrent map access

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#12339]
`EndpointShardsByService` is left unprotected in `loadAssignmentsForClusterIsolated()`

```
fatal error: concurrent map read and map write

goroutine 14483 [running]:
runtime.throw(0x1c12d2d, 0x21)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:608 +0x72 fp=0xc01dcb6e98 sp=0xc01dcb6e68 pc=0x42c0c2
runtime.mapaccess2_faststr(0x194d5c0, 0xc0005d6c00, 0xc0047f348e, 0x32, 0xc00751b5c0, 0x1)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/map_faststr.go:110 +0x458 fp=0xc01dcb6f08 sp=0xc01dcb6e98 pc=0x412368
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).loadAssignmentsForClusterIsolated(0xc000345c30, 0xc008ec3340, 0xc005eb0600, 0xc0047f3480, 0x40, 0x0, 0xc0047f348e)
        /Users/shriramr/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:708 +0x197 fp=0xc01dcb7268 sp=0xc01dcb6f08 pc=0x170b8f7
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushEds(0xc000345c30, 0xc005eb0600, 0xc00906e8c0, 0x0, 0x19, 0x0)
        /Users/shriramr/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:797 +0xc98 fp=0xc01dcb74a8 sp=0xc01dcb7268 pc=0x170d078
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushConnection(0xc000345c30, 0xc00906e8c0, 0xc01507b710, 0x0, 0x0)
        /Users/shriramr/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:735 +0x5aa fp=0xc01dcb7560 sp=0xc01dcb74a8 pc=0x16fd43a
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc000345c30, 0x1e51aa0, 0xc0081b4890, 0x0, 0x0)
        /Users/shriramr/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:597 +0x2fe6 fp=0xc01dcb7c10 sp=0xc01dcb7560 pc=0x16fc956
```

**Comment by duderino** [comment]
This will be in 1.1RC4

**Comment by howardjohn** [comment]
This is fixed right? Closing
