### ISSUE TITLE
Critical Bug: when create a invalid multicluster secret

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#12376]
**Describe the bug**
when create a invalid multicluster secret, the pilot and mixer are all down.

istio-pilot-55df5c797f-gs749                  2/2     Running            0          4m33s
istio-policy-5f9b54b85f-f7mjj                 1/2     CrashLoopBackOff   4          34m
istio-sidecar-injector-5769c94686-kr57n       1/1     Running            0          3d18h
istio-telemetry-69d8bcdb95-9wkjj              1/2     CrashLoopBackOff   4          34m

logs are :+1: 

```
2019-03-09T04:13:02.121558Z	info	Adding new cluster member: n2-k8s-config
2019-03-09T04:13:02.121699Z	info	adapters	Waiting for kubernetes cache sync...	{"adapter": "kubernetesenv.istio-system"}
2019-03-09T04:13:02.122094Z	error	Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/informers/core/v1/replicationcontroller.go:64
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/pager/pager.go:38
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/pager/pager.go:76
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/listwatch.go:106
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/reflector.go:249
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/reflector.go:204
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/reflector.go:203
/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/controller.go:122
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54
/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:2361

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x129b939]

goroutine 2220 [running]:
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1cbdc60, 0x2fd0b90)
	/usr/local/go/src/runtime/panic.go:502 +0x229
istio.io/istio/vendor/k8s.io/client-go/informers/core/v1.NewFilteredReplicationControllerInformer.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1fc2147, ...)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/informers/core/v1/replicationcontroller.go:64 +0xd9
istio.io/istio/vendor/k8s.io/client-go/tools/pager.SimplePageFunc.func1(0x21f4800, 0xc420056028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/pager/pager.go:38 +0x64
istio.io/istio/vendor/k8s.io/client-go/tools/pager.(*ListPager).List(0xc420bbb9f8, 0x21f4800, 0xc420056028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/pager/pager.go:76 +0x105
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*ListWatch).List(0xc420e8bde0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/listwatch.go:106 +0x147
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc42050ce60, 0xc420a83440, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/reflector.go:249 +0x208
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/reflector.go:204 +0x33
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420ae2f18)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420bbbf18, 0x3b9aca00, 0x0, 0x1, 0xc420a83440)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420ae2f18, 0x3b9aca00, 0xc420a83440)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run(0xc42050ce60, 0xc420a83440)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/reflector.go:203 +0x157
istio.io/istio/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run-fm(0xc420a83440)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/client-go/tools/cache/controller.go:122 +0x34
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x31
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc420de9bf0, 0xc420e76160)
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

```

**Expected behavior**
Not to process the invalid secret, but keep pilot and mixer work well.

**Steps to reproduce the bug**

```
cat <<EOF > n2-k8s-config
apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data:
      server:
    name:
contexts:
  - context:
      cluster:
      user:
    name:
current-context:
users:
  - name:
    user:
      token:
EOF

$ kubectl create secret generic n2-k8s-secret --from-file n2-k8s-config -n istio-system
$ kubectl label  secret n2-k8s-secret istio/multiCluster=true -n istio-system
```

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
any 1.1 version, and I think 1.0 has also same problem

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by hzxuzhonghu** [comment]
I find the root cause, we do not validate the kubeconfig and also not check the err when creating kube interface.

**Comment by mandarjog** [comment]
This is an unusual condition, however you clearly hit  it. 
Given the fact that if this happens the failures do not clearly state what went wrong and how to fix it, I vote for merging the PR.
