### ISSUE TITLE
Locality LB Distribute SIGSEGV

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12570]
```
goroutine 272 [running]:
istio.io/istio/pilot/pkg/networking/core/v1alpha3/loadbalancer.applyLocalityWeight(0xc0000d9450, 0xc00082a660, 0xc00000c3c8, 0x1, 0x1)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go:78 +0x4f8
istio.io/istio/pilot/pkg/networking/core/v1alpha3/loadbalancer.ApplyLocalityLBSetting(0xc0000d9450, 0xc00082a660, 0xc000510b40)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go:43 +0x11d
istio.io/istio/pilot/pkg/networking/core/v1alpha3.applyLocalityLBSetting(0xc0000d9450, 0xc00024b940, 0x7, 0x8, 0xc000510b40, 0x0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:849 +0x20e
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters(0xc00043fc80, 0xc00054dcc0, 0xc00053cd10, 0xc000a50200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:104 +0x95f
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawClusters(0xc00053cbb0, 0xc00053cd10, 0xc000a50200, 0xbf1b2a41dbb381c1, 0x992e3b20e, 0x2fa0960, 0x1c2b2c9, 0x3)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:74 +0x6e
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds(0xc00053cbb0, 0xc0004ca700, 0xc000a50200, 0xc000b3f1c0, 0x16, 0x4, 0xc000206240)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:51 +0x5e
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc00053cbb0, 0x1e99220, 0xc00081e240, 0x0, 0x0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:441 +0x120d
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1c1b540, 0xc00053cbb0, 0x1e92b00, 0xc00053cb00, 0x2fbf4d0, 0xc0007dad50)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:197 +0xad
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003fd980, 0x1e9b440, 0xc0005f4480, 0xc0005dbb00, 0xc00062fcb0, 0x2f87420, 0xc0007dad20, 0x0, 0x0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1124 +0x8bd
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0003fd980, 0x1e9b440, 0xc0005f4480, 0xc0005dbb00, 0xc0007dad20)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1212 +0x12aa
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00046d2f0, 0xc0003fd980, 0x1e9b440, 0xc0005f4480, 0xc0005dbb00)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:686 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:684 +0xa1
```

If distribute is used, Pilot will crash every time, because we try to access the current weight which is nil.

I have a fix for this, just documenting this here.

**Comment by howardjohn** [comment]
Fixed in 1.1.1
