### ISSUE TITLE
nil pointer dereference panic in TestProcessor_EventAccumulation

### ISSUE THREAD

**Issue by esnible** [istio/istio#12677]
A test flaked in TestProcessor_EventAccumulation.  See https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/12458/istio-unit-tests/22388/build-log.txt based on https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12458/istio-unit-tests/22388

The failure suggests a possible new or rare bug in galley:

```
=== RUN   TestProcessor_EventAccumulation
2019-03-21T17:39:52.103522Z	info	runtime	Starting processor...
2019-03-21T17:39:52.103546Z	debug	runtime	Starting process loop
2019-03-21T17:39:52.103654Z	debug	runtime	Incoming source event: [Event](FullSync)
2019-03-21T17:39:52.103725Z	info	runtime	Synchronization is complete, starting distribution.
2019-03-21T17:39:52.103873Z	debug	runtime	Incoming source event: [Event](Added: [VKey](empty:r1 @v1))
2019-03-21T17:39:52.103952Z	debug	runtime	In-memory State has changed:
[State @1]
[0] (empty @1)
  [0] (r1)
[1] (struct @0)


2019-03-21T17:39:53.109767Z	info	runtime	Stopping processor...
2019-03-21T17:39:53.109816Z	debug	runtime	Processor.process: done
2019-03-21T17:39:53.109832Z	debug	runtime	Process.process: Exiting worker thread
--- PASS: TestProcessor_EventAccumulation (1.01s)
=== RUN   TestProcessor_EventAccumulation_WithFullSync
2019-03-21T17:39:53.109972Z	info	runtime	Starting processor...
2019-03-21T17:39:53.109979Z	debug	runtime	Starting process loop
2019-03-21T17:39:53.109993Z	debug	runtime	Incoming source event: [Event](FullSync)
2019-03-21T17:39:53.110000Z	info	runtime	Synchronization is complete, starting distribution.
2019-03-21T17:39:53.110031Z	debug	runtime	Processor.process: publish
2019-03-21T17:39:53.110344Z	debug	runtime	Incoming source event: [Event](Added: [VKey](empty:r1 @v1))
2019-03-21T17:39:53.110399Z	debug	runtime	In-memory State has changed:
[State @1]
[0] (empty @1)
  [0] (r1)
[1] (struct @0)


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x477a96]

goroutine 817 [running]:
time.(*Timer).Reset(0x0, 0xf4240, 0x19112c0)
	/usr/local/go/src/time/sleep.go:124 +0x26
istio.io/istio/galley/pkg/runtime/publish.(*Strategy).onTimer(0xc4203004d0)
	/home/prow/go/src/istio.io/istio/galley/pkg/runtime/publish/strategy.go:132 +0x225
istio.io/istio/galley/pkg/runtime/publish.(*Strategy).(istio.io/istio/galley/pkg/runtime/publish.onTimer)-fm()
	/home/prow/go/src/istio.io/istio/galley/pkg/runtime/publish/strategy.go:98 +0x2a
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
FAIL	istio.io/istio/galley/pkg/runtime	1.516s
```

**Comment by esnible** [comment]
Closing as a duplicate of https://github.com/istio/istio/issues/12628
