### ISSUE TITLE
Pilot 1.1.4-pre panic - concurrent map read and map write

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#13566]
`push.ServicePort2Name` is not protected correctly across all accesses.
eds.go:707. It is updated in `svcUpdate` and accessed in `loadAssignmentsForClusterIsolated` and  `updateClusterInc` in eds.go.

```
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1c08d20, 0xc4206151e0, 0x1ddb140, 0xc4224ec160, 0x2a45498, 0xc423d1e600)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:597 +0x2fe8 fp=0xc42a579c10 sp=0xc42a579518 pc=0x170b698
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc4206151e0, 0x1de1740, 0xc422e32160, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:742 +0x5c5 fp=0xc42a579518 sp=0xc42a579458 pc=0x170c1b5
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushConnection(0xc4206151e0, 0xc424febdc0, 0xc420af67e0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:810 +0x72b fp=0xc42a579458 sp=0xc42a5791e8 pc=0x171bc0b
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushEds(0xc4206151e0, 0xc422b5e300, 0xc424febdc0, 0x0, 0x18, 0x0)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:707 +0x109 fp=0xc42a5791e8 sp=0xc42a578e68 pc=0x171a939
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).loadAssignmentsForClusterIsolated(0xc4206151e0, 0xc4218ba540, 0xc422b5e300, 0xc4225a48c0, 0x42, 0x0, 0xc4225a48cf)
        /usr/local/go/src/runtime/hashmap_fast.go:270 +0x461 fp=0xc42a578e68 sp=0xc42a578df8 pc=0x40abb1
runtime.mapaccess2_faststr(0x1991e00, 0xc4215a9ec0, 0xc4225a48cf, 0x33, 0xc4225a48cf, 0x33)
        /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc42a578df8 sp=0xc42a578dd8 pc=0x42ac81
runtime.throw(0x1c44e4b, 0x21)
goroutine 108117 [running]:

fatal error: concurrent map read and map write
```

**Comment by mandarjog** [comment]
@ymesika Please check this concurrent map access.

**Comment by kyessenov** [comment]
I think (and correct me if I'm wrong) @ymesika has left the project.

**Comment by hzxuzhonghu** [comment]
duplicate with #13545 ?

**Comment by mandarjog** [comment]
Yup, thanks. Closing.

Can anyone volunteer to go thru eds.go and review it again?
This is the 4th or the 5th error of this kind, and review is the only real way of fixing it.

@nmittler
