### ISSUE TITLE
Prow Internal Server Error -- Cannot view test results

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13890]
Example: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13849/istio-integ-k8s-tests/7860

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~k8s-gubernator/v20190412-f1ffa5e9b.417445111776570698/view_base.py", line 85, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~k8s-gubernator/v20190412-f1ffa5e9b.417445111776570698/view_build.py", line 233, in get
    testgrid_query = testgrid.path_to_query(job_dir)
  File "/base/data/home/apps/s~k8s-gubernator/v20190412-f1ffa5e9b.417445111776570698/testgrid.py", line 116, in path_to_query
    tabs = dashboard['dashboard_tab']
KeyError: 'dashboard_tab'
```

Seems to apply to every PR

**Comment by icygalz** [comment]
The error is in testgrid's config. We are sharing/using k8s' testgrid and k8s engineers have been informed and fix is on the way.
The report page should come back like before once testgrid's config is fixed.

**Comment by icygalz** [comment]
The result are back. Closing the issue.
