### ISSUE TITLE
istio-pilot crash in loop after Istio upgrade

### ISSUE THREAD

**Issue by sharon-vendrov** [istio/istio#14040]
### Describe the bug ###
istio-pilot  is crashing with the same error after upgrading from istio 1.0.2
the upgrade has been made with helm.

### version ###
Istioctl version: 1.0.6
Kubernetes version: 1.11.8-eks

### Environment ###
AWS EKS 1.11.8
nodes are running with official EKS-AMI

I ran the pilot in "debug" log level:

```
2019-05-13T14:34:28.478461Z	info	ads	CDS: PUSH 2019-05-13T14:33:51Z/3 for istio-internalingressgateway-dd6c56b78-rtg7f.istio-system "172.22.50.93:49920", Clusters: 66, Services 42
2019-05-13T14:34:28.479133Z	info	ads	EDS: PUSH for router~172.22.50.93~istio-internalingressgateway-dd6c56b78-rtg7f.istio-system~istio-system.svc.cluster.local-16 clusters 63 endpoints 100 empty 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x113a1f5]

goroutine 893 [running]:
istio.io/istio/pilot/pkg/model.MergeGateways(0xc420dc2000, 0x12, 0x20, 0x8)
	/workspace/go/src/istio.io/istio/pilot/pkg/model/gateway.go:58 +0x395
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildGatewayListeners(0xc4200f8b90, 0xc4205cb9e0, 0xc420dab7a0, 0xc420018d00, 0x7fae6eae1b90, 0x0, 0x0, 0xc421b672e0, 0xc421b67320)
	/workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/gateway.go:63 +0x1c9
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildListeners(0xc4200f8b90, 0xc4205cb9e0, 0xc420dab7a0, 0xc420018d00, 0x10000000043b6cc, 0x0, 0x10, 0xc420d81840, 0x0)
	/workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:115 +0x74
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawListeners(0xc420507a40, 0xc4211eea80, 0xc420018d00, 0x120, 0x1767dc0, 0x1, 0xc420a77200, 0xc421b67468)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/lds.go:60 +0x72
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushLds(0xc420507a40, 0xc4211eea80, 0xc420018d00, 0xc421b67801, 0xc420aadd00, 0x16, 0xc4207cc547, 0xc)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/lds.go:30 +0x5d
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc420507a40, 0x1a499e0, 0xc420cfc7f0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:439 +0xdf5
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x18a45a0, 0xc420507a40, 0x1a43560, 0xc4215024d0, 0x25041c8, 0xc420b4a3f0)
	/workspace/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:160 +0xb2
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4202ac540, 0x1a4b7e0, 0xc421053c00, 0xc4200fb590, 0xc42068fc80, 0x24d0e60, 0xc420b4a3c0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1160 +0xa2d
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4202ac540, 0x1a4b7e0, 0xc421053c00, 0xc4200fb590, 0xc420b4a3c0)
	/workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1253 +0x12b1
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420dc66e0, 0xc4202ac540, 0x1a4b7e0, 0xc421053c00, 0xc4200fb590)
	/workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:678 +0xa1
```

**Comment by howardjohn** [comment]
This is in 1.0.6? That doesn't seem right - the line numbers don't match up https://github.com/istio/istio/blob/1.0.6/pilot/pkg/networking/core/v1alpha3/gateway.go#L58

can you run `istioctl version --remote`

**Comment by sharon-vendrov** [comment]
istioctl 1.0.x doesn't offer --remote flag.

But this is the output of: `kubectl --namespace istio-system describe pod istio-pilot`

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
    sidecar.istio.io/inject: "false"
  creationTimestamp: 2019-05-13T14:33:28Z
  generateName: istio-pilot-595cd88694-
  labels:
    app: pilot
    istio: pilot
    pod-template-hash: "1517844250"
  name: istio-pilot-595cd88694-jtp5g
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istio-pilot-595cd88694
    uid: 12f62643-758c-11e9-a6bc-0a503940b260
  resourceVersion: "39381734"
  selfLink: /api/v1/namespaces/istio-system/pods/istio-pilot-595cd88694-jtp5g
  uid: 12fedd43-758c-11e9-a6bc-0a503940b260
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  containers:
  - args:
    - discovery
    - --log_output_level
    - default:debug
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: PILOT_CACHE_SQUASH
      value: "5"
    - name: GODEBUG
      value: gctrace=2
    - name: PILOT_PUSH_THROTTLE_COUNT
      value: "100"
    - name: PILOT_TRACE_SAMPLING
      value: "1"
    image: docker.io/istio/pilot:1.0.6
    imagePullPolicy: IfNotPresent
    name: discovery
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 15010
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: "2"
        memory: 2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/istio/config
      name: config-volume
    - mountPath: /etc/certs
      name: istio-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: istio-pilot-service-account-token-vgl4d
      readOnly: true
  - args:
    - proxy
    - --serviceCluster
    - istio-pilot
    - --templateFile
    - /etc/istio/proxy/envoy_pilot.yaml.tmpl
    - --controlPlaneAuthPolicy
    - NONE
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: docker.io/istio/proxyv2:1.0.6
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    ports:
    - containerPort: 15003
      protocol: TCP
    - containerPort: 15005
      protocol: TCP
    - containerPort: 15007
      protocol: TCP
    - containerPort: 15011
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/certs
      name: istio-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: istio-pilot-service-account-token-vgl4d
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: ip-172-22-52-162.ec2.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: istio-pilot-service-account
  serviceAccountName: istio-pilot-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: istio
    name: config-volume
  - name: istio-certs
    secret:
      defaultMode: 420
      optional: true
      secretName: istio.istio-pilot-service-account
  - name: istio-pilot-service-account-token-vgl4d
    secret:
      defaultMode: 420
      secretName: istio-pilot-service-account-token-vgl4d
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T14:33:28Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T15:54:16Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T14:33:28Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5dd01bbda91a402c8c9ac9c2075b743ddec8990092fdca576a48edae89031a76
    image: istio/pilot:1.0.6
    imageID: docker-pullable://istio/pilot@sha256:46a9b4508681cedead581080487aa1aa7e32368f4fbe4ac331e9f7727643d3b2
    lastState:
      terminated:
        containerID: docker://ec7b1ed2b013cf637a8af83e02f93903c0597dd660df88463f665ead77c0e07f
        exitCode: 2
        finishedAt: 2019-05-13T15:48:41Z
        reason: Error
        startedAt: 2019-05-13T15:47:57Z
    name: discovery
    ready: true
    restartCount: 19
    state:
      running:
        startedAt: 2019-05-13T15:53:47Z
  - containerID: docker://0ee17aa8507a1a1d3c1c08d49918523ceb61f1f74e94122d5c703078b71b0133
    image: istio/proxyv2:1.0.6
    imageID: docker-pullable://istio/proxyv2@sha256:e15655ef8e86276012a12ef74ec690b1ea52f98a299c183993be052ac6f070c4
    lastState: {}
    name: istio-proxy
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-05-13T14:33:29Z
  hostIP: 172.22.52.162
  phase: Running
  podIP: 172.22.52.32
  qosClass: Burstable
  startTime: 2019-05-13T14:33:28Z
```

**Comment by howardjohn** [comment]
Forgot about the istioctl version, thanks for the describe. I was looking at the wrong gateway.go file ws the issues.

https://github.com/istio/istio/blob/1.0.6/pilot/pkg/model/gateway.go#L58

It looks like it is crashing on server.Port.Protocol. Both of these are required (https://github.com/istio/istio/blob/1.0.6/vendor/istio.io/api/networking/v1alpha3/gateway.proto#L302) are you missing one in a Gateway?

**Comment by sharon-vendrov** [comment]
@howardjohn U de Best!
Thanks!!!
