### ISSUE TITLE
1.2 nodeagent panic

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#14454]
```
fatal error: concurrent map read and map write

goroutine 75 [running]:
runtime.throw(0x19195a5, 0x21)
        /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc4208219f0 sp=0xc4208219d0 pc=0x429d51
runtime.mapaccess1(0x16d66a0, 0xc4200ee4b0, 0xc420821ac8, 0x19d92013c7b8)
        /usr/local/go/src/runtime/hashmap.go:357 +0x216 fp=0xc420821a38 sp=0xc4208219f0 pc=0x4071e6
istio.io/istio/security/pkg/nodeagent/sds.NotifyProxy(0xc42142a1e0, 0x5e, 0xc4204667f0, 0x7, 0x0, 0x250c2a0, 0x250c200)
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/sds/sdsservice.go:280 +0x98 fp=0xc420821af8 sp=0xc420821a38 pc=0x14a37b8
istio.io/istio/security/pkg/nodeagent/cache.(*SecretCache).rotate.func1(0x1755da0, 0xc420286a60, 0x182dc40, 0xc420db24d0, 0x7fec7b130c01)
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/cache/secretcache.go:477 +0x8c7 fp=0xc420821dc0 sp=0xc420821af8 pc=0x10e6b77
sync.(*Map).Range(0xc4203677a0, 0xc420821ee0)
        /usr/local/go/src/sync/map.go:337 +0x136 fp=0xc420821e98 sp=0xc420821dc0 pc=0x46b6d6
istio.io/istio/security/pkg/nodeagent/cache.(*SecretCache).rotate(0xc4203677a0, 0x0)
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/cache/secretcache.go:420 +0xf3 fp=0xc420821f18 sp=0xc420821e98 pc=0x10e2b93
istio.io/istio/security/pkg/nodeagent/cache.(*SecretCache).keyCertRotationJob(0xc4203677a0)
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/cache/secretcache.go:312 +0x15d fp=0xc420821fd8 sp=0xc420821f18 pc=0x10e27fd
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420821fe0 sp=0xc420821fd8 pc=0x456571
created by istio.io/istio/security/pkg/nodeagent/cache.NewSecretCache
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/cache/secretcache.go:177 +0x219

goroutine 1 [chan receive, 136 minutes]:
istio.io/istio/pkg/cmd.WaitSignal(0xc4200ec4e0)
        /workspace/go/src/istio.io/istio/pkg/cmd/cmd.go:33 +0xb6
main.glob..func1(0x24f9940, 0x252af28, 0x0, 0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/security/cmd/node_agent_k8s/main.go:164 +0x30c
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).execute(0x24f9940, 0xc4200381b0, 0x0, 0x0, 0x24f9940, 0xc4200381b0)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:762 +0x468
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x24f9940, 0x0, 0xc4201d4780, 0x24f9a90)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:852 +0x30a
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).Execute(0x24f9940, 0xc420605f58, 0x1)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /workspace/go/src/istio.io/istio/security/cmd/node_agent_k8s/main.go:368 +0x9e8

```

**Comment by mandarjog** [comment]
[istio-nodeagent-7t5kr.log](https://github.com/istio/istio/files/3238275/istio-nodeagent-7t5kr.log)

[istio-nodeagent-7t5kr.log](https://github.com/istio/istio/files/3238279/istio-nodeagent-7t5kr.log)

**Comment by quanjielin** [comment]
fix is in, close this for now, do reopen it if still see in latest build.
