### ISSUE TITLE
self signed certificate with empty subject and SAN not marked as critical

### ISSUE THREAD

**Issue by hezise** [istio/istio#14624]
**Bug description**
When I'm using JAVA to connect our system I'm getting the below exception.
The thing is that in Java I can bypass non matching name and self signed certificate but I can't bypass nor ignore any certificate issues.

Couldn't open connection: X.509 Certificate is incomplete: SubjectAlternativeName extension MUST be marked critical when subject field is empty
Exception in thread "main" javax.net.ssl.SSLProtocolException: X.509 Certificate is incomplete: SubjectAlternativeName extension MUST be marked critical when subject field is empty
	at sun.security.ssl.HandshakeMessage$CertificateMsg.<init>(HandshakeMessage.java:456)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at JavaApplication1.main(JavaApplication1.java:39)
Caused by: java.security.cert.CertificateParsingException: X.509 Certificate is incomplete: SubjectAlternativeName extension MUST be marked critical when subject field is empty
	at sun.security.x509.X509CertInfo.verifyCert(X509CertInfo.java:744)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:706)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at sun.security.ssl.HandshakeMessage$CertificateMsg.<init>(HandshakeMessage.java:453)
	... 11 more
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[X ] Test and Release
[ X] User Experience

**Expected behavior**
SAN marked critical
**Steps to reproduce the bug**
use istio certificate and connect using JAVA
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
HELM
**Environment where bug was observed (cloud vendor, OS, etc)**
kubespary on vmware
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by incfly** [comment]
Seems a legit requirement, go-x509 library and SPIRE both make corresponding change, https://github.com/spiffe/spire/issues/330
https://github.com/golang/go/commit/3a395e22832774ff56d6b82cb8d91bc31167bd8e
we might update the citadel go library version to get the fix..

**Comment by hezise** [comment]
Thanks for the help.
I'll update once it's done

**Comment by incfly** [comment]
This seems to be done already,  https://github.com/istio/istio/pull/12838

**Comment by incfly** [comment]
Released as part of 1.2
