### ISSUE TITLE
Flake due to NewStatsContext

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#15142]
Cause: Race between register and prior de-register of stats views.

recommended fix
 * Move all view registrations to `init` method of the module.

This pattern is followed elsewhere in the code.

https://circleci.com/gh/istio/istio/449828?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
--- FAIL: TestWildcardHostSidecarRouterWithMockCopilot (0.00s)
    copilot_test.go:223: internal backend is running on port 6868
panic: pilot/mcp/sink/clients_total: cannot register view "pilot/mcp/sink/clients_total"; a different view with the same name is already registered [recovered]
	panic: pilot/mcp/sink/clients_total: cannot register view "pilot/mcp/sink/clients_total"; a different view with the same name is already registered

goroutine 201 [running]:
testing.tRunner.func1(0xc0005e8000)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x1c7f700, 0xc0004815c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
istio.io/istio/pkg/mcp/monitoring.(*StatsContext).addView(0xc0006483c0, 0x2293f80, 0xc0000c7300, 0x37ef680, 0x0, 0x0, 0xc0005ee420)
	/go/src/istio.io/istio/pkg/mcp/monitoring/monitoring.go:226 +0x3ee
istio.io/istio/pkg/mcp/monitoring.NewStatsContext(0xc0005ea370, 0xf, 0x22a7900)
	/go/src/istio.io/istio/pkg/mcp/monitoring/monitoring.go:205 +0x67c
istio.io/istio/pilot/pkg/bootstrap.(*Server).initMCPConfigController(0xc0005fc1e0, 0xc00000c5a0, 0x2030f50, 0x225fae0)
	/go/src/istio.io/istio/pilot/pkg/bootstrap/server.go:527 +0x1ec
istio.io/istio/pilot/pkg/bootstrap.(*Server).initConfigController(0xc0005fc1e0, 0xc00000c5a0, 0x0, 0x0)
	/go/src/istio.io/istio/pilot/pkg/bootstrap/server.go:688 +0x953
istio.io/istio/pilot/pkg/bootstrap.NewServer(0xc0005ea320, 0xe, 0xc0005ea330, 0xf, 0x1f521a2, 0x2, 0x0, 0x0, 0x101, 0x1f5780e, ...)
	/go/src/istio.io/istio/pilot/pkg/bootstrap/server.go:255 +0x4db
istio.io/istio/tests/util.setup(0xc0002f5d18, 0x3, 0x3, 0xc0002f5c70, 0x40e128, 0x20, 0x1d27be0)
	/go/src/istio.io/istio/tests/util/pilot_server.go:121 +0x45c
istio.io/istio/tests/util.EnsureTestServer(0xc0002f5d18, 0x3, 0x3, 0x1, 0x1)
	/go/src/istio.io/istio/tests/util/pilot_server.go:57 +0x49
istio.io/istio/tests/e2e/tests/pilot/cloudfoundry_test.initLocalPilotTestEnv(0xc0005e8000, 0xa236, 0x3aa2, 0x15b3, 0xc000480f80, 0x1f5236c)
	/go/src/istio.io/istio/tests/e2e/tests/pilot/cloudfoundry/copilot_test.go:329 +0x1e4
istio.io/istio/tests/e2e/tests/pilot/cloudfoundry_test.TestWildcardHostSidecarRouterWithMockCopilot(0xc0005e8000)
	/go/src/istio.io/istio/tests/e2e/tests/pilot/cloudfoundry/copilot_test.go:237 +0x7d7
testing.tRunner(0xc0005e8000, 0x202dd70)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
FAIL	istio.io/istio/tests/e2e/tests/pilot/cloudfoundry	1.762s
```

**Comment by mandarjog** [comment]
@douglas-reid
