### ISSUE TITLE
http2 not supported as gateway port protocol specifier

### ISSUE THREAD

**Issue by hanoisteve** [istio/istio#15365]
**Bug description**
For allowing GRPC traffic the Gateway only supports specifying HTTP, http, HTTPS, https for the port protocol.  Using HTTP2, or GRPC does not appear to be supported and will cause error.  I have confirmed this on my cluster for Istio 1.1.7 and have not yet tested on 1.2.1

This behavior was first noticed in Istio version 1.0

https://github.com/istio/istio/issues/7843

Its a high priority for many clients to use GRPC as primary implementation of micro services allowing multiple languages to be used.  External clients may opt for direct GRPC calls over HTTP2 vs HTTP rest for performance reasons or simplicity of using just one access mechanism.  

Using http for the port protocol specifier is confusing in terms of what protocol is actually in use end to end so it would be good to have clarification on this.  Also need clarification on TLS vs HTTPS as port protocol specifier for GRPC when TLS is enabled.

**Affected product area (please put an X in all that apply)**

[X ] Configuration Infrastructure
[ X] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
We should be able to specify the Gateway port using HTTP2 as the protocol.  How this gets implemented should be transparent to the developer/deployer of the service.  Documentation should clearly indicate which protocol to designate for GRPC traffic, and which protocol is in use for that designation.  If only http or https should be specified then it should be clarified if in fact Envoy is converting this traffic to http2.  Using http2 as the protocol for the gateway port results in error in grpc connection request not reaching the service or even the envoy proxy of the service.  

**Steps to reproduce the bug**
Just create a simple Echo service with the following for gateway, virtual service, and deployment:

1) Deployment

```
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  ports:
  - name: grpc
    port: 9009
  selector:
    app: echo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-deployment
  labels:
    app: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo-container
        image: harbor/test/echo/0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 9009
          name: grpc
```
2)   Gateway (NOTE the use of http2 or HTTP2 causes unexpected behavior).
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: grpc
      protocol: http2
    hosts:
    - "*"
```
3) Virtual Service. (Not clear how to specify different grpc services using http and uri mapping to service. GRPC section or HTTP2 section possible here instead of http: ?)
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - grpc-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: echo
        port:
          number: 9009
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo-destination
spec:
  host: echo
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
```

Same service works if Gateway uses http as the protocol for the port.

Here are the error messages:  

External Client sees:
```
io.grpc.StatusRuntimeException: UNIMPLEMENTED
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)11:22:45.206 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0xdf1ff566, L:/10.11.x.xx:53579 - R:/10.10.1.xx:31380] OUTBOUND RST_STREAM: streamId=3 errorCode=8
```
Istio Ingress Gateway Logs:
```
[2019-07-04T16:59:53.936Z] "POST /com.test.echo.EchoService/echo HTTP/2" 200 NR "-" 0 0 0 - "10.10.20.88" "grpc-java-netty/1.21.0" "3bfe3020-12ee-9942-91c6-d152730ffc20" "10.10.20.88:31380" "-" - - 10.244.0.20:80 10.10.20.88:63654 -

2019-07-04T17:01:36.695343Z    info    Envoy proxy is NOT ready: failed retrieving Envoy stats: Get http://127.0.0.1:15000/stats?usedonly: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

2019-07-04T17:01:37.068043Z    info    Envoy proxy is ready

[```[2019-07-04T16:59:53.936Z] "POST /com.test.echo.EchoService/echo HTTP/2" 200 NR "-" 0 0 0 - "10.10.20.88" "grpc-java-netty/1.21.0" "3bfe3020-12ee-9942-91c6-d152730ffc20" "10.10.20.88:31380" "-" - - 10.244.0.20:80 10.10.20.88:63654 -

2019-07-04T17:01:36.695343Z    info    Envoy proxy is NOT ready: failed retrieving Envoy stats: Get http://127.0.0.1:15000/stats?usedonly: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

2019-07-04T17:01:37.068043Z    info    Envoy proxy is ready

[22019-07-04 17:01:57.907][23][debug][filter] [src/envoy/http/mixer/filter.cc:39] Called Mixer::Filter : Filter

[2019-07-04 17:01:57.954][23][debug][filter] [src/envoy/http/mixer/filter.cc:146] Called Mixer::Filter : setDecoderFilterCallbacks

[2019-07-04 17:01:58.095][23][debug][filter] [src/envoy/http/mixer/filter.cc:62] Called Mixer::Filter : decodeHeaders

[2019-07-04 17:01:58.114][23][debug][filter] [./src/envoy/utils/header_update.h:46] Mixer forward attributes set: Ck8KCnNvdXJjZS51aWQSQRI/a3ViZXJuL2lzdGlvLWluZ3Jlc3NnYXRld2F5LTU5Y2M2Y2NiY2Itdmx4c2wuaXN0aW8tc3lzdGVt

[2019-07-04 17:01:58.114][23][debug][filter] [src/envoy/http/mixer/filter.cc:154] Called Mixer::Filter : check complete OK

[2019-07-04 17:01:58.114][23][debug][filter] [src/envoy/http/mixer/filter.cc:133] Called Mixer::Filter : encodeHeaders 2

[2019-07-04 17:01:58.114][23][debug][filter] [src/envoy/http/mixer/filter.cc:205] Called Mixer::Filter : onDestroy state: 2

[2019-07-04 17:01:58.114][23][debug][filter] [src/envoy/http/mixer/filter.cc:219] Called Mixer::Filter : log

[2019-07-04 17:01:58.114][23][debug][filter] [./src/envoy/http/mixer/report_data.h:132] No dynamic_metadata found for filter envoy.filters.http.rbac

[2019-07-04 17:01:58.125][23][debug][filter] [src/istio/control/client_context_base.cc:125] Report attributes: attributes {

  key: "connection.mtls"

  value {

    bool_value: false

  }

}

attributes {

  key: "context.protocol"    bool_value: false

  }

}

attributes {

  key: "context.protocol"

  value {


  value {

    string_value: "grpc"

  }

}

attributes {

  key: "context.prox

[2019-07-04 17:01:58.822][23][debug][filter] [./src/envoy/utils/header_update.h:46] Mixer forward attributes set: Ck8KCnNvdXJjZS51aWQSQRI/a3ViZXJuZXRlczovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LTU5Y2M2Y2NiY2Itdmx4c2wuaXN0aW8tc3lzdGVt

[2019-07-04T17:01:57.792Z] "POST /com.test.echo.EchoService/echo HTTP/2" 200 NR "-" 0 0 321 - "10.10.20.88" "grpc-java-netty/1.21.0" "d12fbddd-1b63-906a-a193-d8e1513518f4" "10.10.20.88:31380" "-" - - 10.244.0.20:80 10.10.20.88:63681 -
```
Echo Service Pod Logs and Istio Proxy Logs
Does not reach. Nothing appears on the pod logs.

Switching Gateway port protocol to http works and echo is received on the client.  

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**
Bare metal install.    KubeAdmin
**Environment where bug was observed (cloud vendor, OS, etc)**
VMs run on hypervisor Citrix Xen installed No cloud vendor involved. Three Ubuntu machines.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by hanoisteve** [comment]
When I use http for the gateway protocol port the logs at the echo service pod proxy does show that HTTP2 protocol is in use: 

[2019-07-05T07:01:38.428Z] "POST /com.test.echo.EchoService/echo HTTP/2" 200 - "-" 12 26 4 3 "10.10.x.xx” "grpc-go/1.21.0" "c1cd647d-f4da-99de-a666-7b0aad6bafa78” “myserver.com:31380" "127.0.0.1:9009" inbound|9009|grpc|echo.default.svc.cluster.local - 10.241.32.xx:9009 10.10.1.68:0 outbound_.9009_._.echo.default.svc.cluster.local

**Comment by phanama** [comment]
I also experienced the same problem.
The problem resolved if we specify `http` instead of `http2` or `grpc` in the gateway protocol, even though they are http2 and grpc traffics!

**Comment by phanama** [comment]
FYI this problem emerges when upgrading from 1.1.0 to 1.1.1 and above

**Comment by pen-pal** [comment]
were you able to resolve this issue?
