### ISSUE TITLE
Envoy drops connection to PostgreSQL database

### ISSUE THREAD

**Issue by suneeshkumar-urolime** [istio/istio#15773]
**Bug description**

Envoy is randomly dropping the connection between Jboss client and PostgreSQL database and gets many connection destroy warnings in the application logs. This is start happening when we migrated the application to the Istio Mesh. There is no issue or log in the application when we remove the Istio sidecar and the application directly connects to the Database. It seems like the sidecar reload drop the idle connections, The pilot  push the configuration update to the sidecar which causes the drop in connection and the Jboss JDBC connection validator will verify the connection and mark this as invalid and open a new connection to the PostgreSQL. 

Sample client log:

02:03:13,160 WARN  [org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory] (ConnectionValidator) IJ030027: Destroying connection that is not valid, due to the following exception: org.postgresql.jdbc.PgConnection@53142b4: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:333)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jboss.jca.adapters.jdbc.CheckValidConnectionSQL.isValidConnection(CheckValidConnectionSQL.java:74)
	at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnectionFactory.isValidConnection(BaseWrapperManagedConnectionFactory.java:1273)
	at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnectionFactory.getInvalidConnections(BaseWrapperManagedConnectionFactory.java:1086)
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.validateConnections(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1442)
	at org.jboss.jca.core.connectionmanager.pool.validator.ConnectionValidator$ConnectionValidatorRunner.run(ConnectionValidator.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:295)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1947)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)

**Expected behavior**

After migrating to Istio the applications should work as before, there shouldn't be any connection drops between applications and database.

**Steps to reproduce the bug**

Install the keycloak identity provider using the helm chart and after sometime you will start seeing the above mentioned logs. When we remove the sidecar proxy the application works normally and there are no errors in the application logs.

To install the chart with the release name keycloak:

$ helm install --name keycloak codecentric/keycloak

Chart reference link: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak

**Version**

Istio version: 

client version: 1.2.0
citadel version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
nodeagent version: 1.2.0
nodeagent version: 1.2.0
nodeagent version: 1.2.0
nodeagent version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
sidecar-injector version: 1.2.0
telemetry version: 1.2.0

kubectl Version: 

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Istio was installed using Helm template option mentioned in the installation documentation.

**Comment by rshriram** [comment]
how frequentlu is this happening?

**Comment by suneeshkumar-urolime** [comment]
It is happening randomly, like 2 or 3 times in an hour.

**Comment by xeor** [comment]
I got the same problem. Keycloak works fine on the admin-page, but when keycloak-gatekeeper tries to use it for some part of the authentication, keycloak-postgres fails..
Might be some sorts of postgres queries? query-sizes? similar?
I didn't debug this that much, so some details might be wrong..

**Comment by howardjohn** [comment]
Sounds like we are sending some different LDS/CDS config causing the connections to be dropped?

**Comment by c4po** [comment]
same issue here, on istio 1.4.3

**Comment by offero** [comment]
I'm seeing similar issues from nodejs to aws postgres.

**Comment by jameslombard** [comment]
Solved it through applying the following config in the istio-discovery helm-chart:

```
proxy:
    excludeOutboundPorts: "5432" #port where SQL server is running
```
This tells the side-car proxy to allow any traffic on the specified port to access the service directly.

**Comment by aramhakobyan** [comment]
Same here, this issue impacts us!  @rshriram  - the transaction drops every hour, tcp_keepalive on the envoy does not help. our developers are keeping the transaction open by firing some dummy queries. Note - this is not about connection drop, but about transaction drop!
