### ISSUE TITLE
server_source_test test failures

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15798]
Example failure:
` server_source_test.go:125: Stream exited with error: got <nil> want unknown`

This is a caused by a race here: https://github.com/istio/istio/blob/1106c76d6bbed8d4f788737072b50ffb0a2f1217/pkg/mcp/source/server_source_test.go#L127

We have no way to guarantee that an error has not already been received at this point

Failures:
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15484/istio-racetest-master/1968
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15486/istio-racetest-master/1607
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15501/istio-codecov-master/2079
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15501/istio-racetest-master/1692
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15501/istio-racetest-master/1861
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15501/istio-unit-tests-master/3592
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15515/istio-racetest-master/1703
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15555/istio-racetest-master/1791
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15608/istio-racetest-master/2157
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15632/istio-racetest-master/1944
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15685/istio-racetest-master/2191
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15687/istio-racetest-master/2103
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15781/istio-racetest-master/2205

**Comment by howardjohn** [comment]
Also a segfault
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9aa702]
 goroutine 14 [running]:
istio.io/istio/pkg/mcp/source.(*serverHarness).SendHeader(0xc00000ec60, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0x32
istio.io/istio/pkg/mcp/source.(*Server).EstablishResourceStream(0xc000113a70, 0xbdc0e0, 0xc00000ec60, 0xbc6960, 0xc000129df0)
	/home/prow/go/src/istio.io/istio/pkg/mcp/source/server_source.go:91 +0x16d
istio.io/istio/pkg/mcp/source.TestServerSource.func1(0xc000037140, 0xc000113a70, 0xc00000ec60)
	/home/prow/go/src/istio.io/istio/pkg/mcp/source/server_source_test.go:108 +0x41
created by istio.io/istio/pkg/mcp/source.TestServerSource
	/home/prow/go/src/istio.io/istio/pkg/mcp/source/server_source_test.go:107 +0x620
```
from https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15501/istio-unit-tests-master/3592

**Comment by howardjohn** [comment]
Nevermind, the segfault was from a pr affecting this code (its a presubmit)
