### ISSUE TITLE
istio redis Connection refused

### ISSUE THREAD

**Issue by jeremyzhou** [istio/istio#16397]
a cronjob in kubernetes execute some lua script in redis. 
It can not connect redis server when enabled istio-injection.
but It works when disabled istio-injection.

**prints:**
Traceback (most recent call last):
  File "/root/gc/main.py", line 276, in <module>
    cleanup_online_device_in_redis()
  File "/root/gc/main.py", line 105, in cleanup_online_device_in_redis
    result = cmd(args=[strTimestamp,connection_event_json])
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 3575, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2761, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 497, in connect
redis.exceptions.ConnectionError: Error 111 connecting to dev-redis.********.0031.use2.cache.amazonaws.com:6379. Connection refused.

**version**: 
istio          1               Tue Aug 20 03:27:37 2019        DEPLOYED        istio-1.2.4                                     1.2.4           istio-system

**Comment by rokrokss** [comment]
I'm facing the same issue, can you give me some advice?
