### ISSUE TITLE
TestAddToMesh panic

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16639]
```
$ go test ./istioctl/cmd -run TestAddToMesh
panic: cannot deep copy *v1alpha3.ServiceEntry [recovered]
        panic: cannot deep copy *v1alpha3.ServiceEntry

goroutine 14 [running]:
testing.tRunner.func1(0xc0007a3500)
        /usr/lib/google-golang/src/testing/testing.go:830 +0x392
panic(0x2368c00, 0xc0004aeaa0)
        /usr/lib/google-golang/src/runtime/panic.go:522 +0x1b5
istio.io/istio/vendor/k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x2644800, 0xc000606480, 0x26dd2ad, 0x8)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/runtime/converter.go:474 +0x572
istio.io/istio/vendor/k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x23594a0, 0xc000335590, 0x5218f8, 0x25b9660)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/runtime/converter.go:458 +0x149
istio.io/istio/vendor/k8s.io/apimachinery/pkg/runtime.DeepCopyJSON(...)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/runtime/converter.go:443
istio.io/istio/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopy(0xc0001442e0, 0x25b9660)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go:135 +0x76
istio.io/istio/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopyObject(0xc0001442e0, 0xc0005bb0e8, 0x2b48ec0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/zz_generated.deepcopy.go:36 +0x2b
istio.io/istio/vendor/k8s.io/client-go/testing.CreateActionImpl.DeepCopy(0xc0007c9378, 0x4, 0x26d9662, 0x6, 0x26f2094, 0x13, 0x26dd825, 0x8, 0x26e7dc7, 0xe, ...)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/client-go/testing/actions.go:524 +0xd8
istio.io/istio/vendor/k8s.io/client-go/testing.(*Fake).Invokes(0xc0007bc280, 0x2b48f20, 0xc0003a7280, 0x2adbda0, 0xc0001442e0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/client-go/testing/fake.go:134 +0x91
istio.io/istio/vendor/k8s.io/client-go/dynamic/fake.(*dynamicResourceClient).Create(0xc00029d040, 0xc0001442e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/client-go/dynamic/fake/simple.go:108 +0x5de
istio.io/istio/istioctl/cmd.createServiceEntry(0x2acb2e0, 0xc0007bc280, 0xc0007c9378, 0x4, 0xc0001442e0, 0x278b06d, 0xc, 0x2ac8340, 0xc0007cf440, 0x0, ...)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/istioctl/cmd/add-to-mesh.go:490 +0x183
istio.io/istio/istioctl/cmd.addServiceOnVMToMesh(0x2acb2e0, 0xc0007bc280, 0x2babd20, 0xc0007bc1e0, 0xc0007c9378, 0x4, 0xc000792a20, 0x3, 0x3, 0x0, ...)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/istioctl/cmd/add-to-mesh.go:383 +0xab4
istio.io/istio/istioctl/cmd.externalSvcMeshifyCmd.func1(0xc00078e500, 0xc000792a20, 0x3, 0x3, 0x0, 0x0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/istioctl/cmd/add-to-mesh.go:168 +0x4f7
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).execute(0xc00078e500, 0xc000792900, 0x3, 0x3, 0xc00078e500, 0xc000792900)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:762 +0x465
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000fd900, 0x6, 0x6, 0xc0000fd900)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:800
istio.io/istio/istioctl/cmd.verifyAddToMeshOutput(0xc0007a3500, 0x26f8922, 0x16, 0x1, 0xc0000a33e0, 0x6, 0x6, 0x4670cc0, 0x3, 0x3, ...)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/istioctl/cmd/add-to-mesh_test.go:220 +0x146
istio.io/istio/istioctl/cmd.TestAddToMesh.func1(0xc0007a3500)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/istioctl/cmd/add-to-mesh_test.go:206 +0x75
testing.tRunner(0xc0007a3500, 0xc000686040)
        /usr/lib/google-golang/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/lib/google-golang/src/testing/testing.go:916 +0x35a
FAIL    istio.io/istio/istioctl/cmd     0.399s
```

This happens on master branch consistently for me. It doesn't happen on CI which is weird

```
$ go version
go version go1.12.5 linux/amd64
```

`docker run -v "${PWD}":"${PWD}" -w "${PWD}" -e GOPATH=$GOPATH golang:1.12.5 go test ./istioctl/cmd -run TestAddToMesh` DOES pass, so its likely a local environmental issue

**Comment by howardjohn** [comment]
Looks like this test is using my kubeconfig! Added recently in #16156

@irisdingbj please make this test not rely on kubeconfig or if it has to move it to an integration test. A unit test should not be accessing my kubernetes cluster...

**Comment by irisdingbj** [comment]
@howardjohn the TestAddToMesh will not rely on KUBECONFIG since it is based on fake client from kubernetes.  Also I have tried using the same exact steps with you but can not reproduce.

**Comment by howardjohn** [comment]
The test fails but if I set KUBECONFIG=fake it passes. so somewhere it is reading kube config.

I reproduced it on 2 machines as well btw

**Comment by irisdingbj** [comment]
TestAddToMesh will not call into add-to-mesh.go:490 as there is already a SE exists in the fake config. ```cannedDynamicConfigs = []runtime.Object{
		&unstructured.Unstructured{
			Object: map[string]interface{}{
				"apiVersion": "networking.istio.io/" + schemas.ServiceEntry.Version,
				"kind":       schemas.ServiceEntry.VariableName,
				"metadata": map[string]interface{}{
					"namespace": "default",
					"name":      "mesh-expansion-vmtest",
				},
			},
		},
	}```

**Comment by irisdingbj** [comment]
Tried in different machines and using latest master codes. No KubeConfig available in my Env. Still can not reproduce. @howardjohn can you check the add-to-mesh_test.go is latest and run using verbose to see which case it fais in your machine?

**Comment by howardjohn** [comment]
it's on the case 8 where service entry already exists . I used latest code.

note that it fails when I DONT set KUBECONFIG var (using ~/.kube/config then I assume) and passes when I set a bogus value

**Comment by esnible** [comment]
@howardjohn The backtrace shows Iris' code is calling `        /usr/local/google/home/howardjohn/go/src/istio.io/istio/vendor/k8s.io/client-go/testing/fake.go:134 +0x91`

The fact that is is in _fake.go_ means she is correctly mocking.  So I am confused how you could be getting this.  For me it passes if I unset KUBECONFIG, set it it to a bogus value, or set it to a valid value.

**Comment by howardjohn** [comment]
Weird.. since it happened on both my laptop and desktop I figured it was a universal thing. Ill look into it since it seems only I run into this

**Comment by howardjohn** [comment]
So it fails on:
* GKE cluster 1 with istio
* GKE cluster 2 with istio

Passes with
* Bogus kubeconfig
* Kind cluster with no istio
* Kind cluster with Istio

Maybe GKE related
