### ISSUE TITLE
istioctl does not work within cluster

### ISSUE THREAD

**Issue by kameshsampath** [istio/istio#1734]
When we try to execute `istioctl` from within kubernetes cluster it fails with the following error searching for default NS.  IMHO the tool should try to fallback to incluster configurations something like https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go#L32  when its not able to find the configuration in default location `~/.kube/config` or via `-c` prameter

```
[vagrant@localhost ~]$ ./istioctl version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x11f21d9]

goroutine 1 [running]:
main.getDefaultNamespace(0xc420322800, 0x1a, 0x0, 0x0)
	cmd/istioctl/main.go:700 +0x99
main.glob..func4(0x1c32de0, 0x1c5ebe8, 0x0, 0x0)
	cmd/istioctl/main.go:86 +0x39
github.com/spf13/cobra.(*Command).execute(0x1c32de0, 0x1c5ebe8, 0x0, 0x0, 0x1c32de0, 0x1c5ebe8)
	external/com_github_spf13_cobra/command.go:637 +0x549
github.com/spf13/cobra.(*Command).ExecuteC(0x1c319a0, 0x11f7c53, 0x0, 0x0)
	external/com_github_spf13_cobra/command.go:729 +0x339
github.com/spf13/cobra.(*Command).Execute(0x1c319a0, 0x0, 0x154)
	external/com_github_spf13_cobra/command.go:688 +0x2b
main.main()
	cmd/istioctl/main.go:531 +0xc0
```

**Comment by ayj** [comment]
See https://github.com/istio/istio/pull/1735 for fix cherry-picked from old pilot repo.
