### ISSUE TITLE
VirtualService regexes longer than 1024 bytes cause Pilot to panic

### ISSUE THREAD

**Issue by samuelyallop-pusher** [istio/istio#17411]
**Bug description**

Virtualservice CRDS which contain a regex match greater than 1024 bytes will cause Pilot to panic when generating routes with an error like:

```
2019-09-25T14:51:08.685755Z	error	ads	RDS: Generated invalid routes for route:https.443.https.NAME.NAMESPACE for node:istio-ingressgateway-d879fcbdc-tcmfm.NAMESPACE: invalid RouteConfiguration.VirtualHosts[0]: embedded message failed validation | caused by: invalid VirtualHost.Routes[2]: embedded message failed validation | caused by: invalid Route.Match: embedded message failed validation | caused by: invalid RouteMatch.Regex: value length must be at most 1024 bytes

goroutine 417 [running]:
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawRoutes(0xc42055bee0, 0xc422a83b00, 0xc4215ebd00, 0x0, 0x1, 0xc4237d5440, 0x4eb497, 0xc4237d5498)
	/home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/rds.go:94 +0x9b6
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushRoute(0xc42055bee0, 0xc422a83b00, 0xc4215ebd00, 0xc420dc08e0, 0x16, 0x3, 0x0)
	/home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/rds.go:30 +0x68
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc42055bee0, 0x1f7adc0, 0xc42282dd40, 0x0, 0x0)
	/home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:542 +0x22e3
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1d87f80, 0xc42055bee0, 0x1f73f20, 0xc4234146c0, 0x2d3c548, 0xc4229c97d0)
	/home/prow/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:197 +0xb2
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4204e1200, 0x1f7cf80, 0xc42340be00, 0xc423627600, 0xc420779da0, 0x2d02c00, 0xc42284ee00, 0x0, 0x0)
	/home/prow/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1176 +0xb0d
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4204e1200, 0x1f7cf80, 0xc42340be00, 0xc423627600, 0xc42284ee00)
	/home/prow/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1256 +0xd9b
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc423376dd0, 0xc4204e1200, 0x1f7cf80, 0xc42340be00, 0xc423627600)
	/home/prow/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:691 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/prow/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:689 +0xa1
```

Envoys https://github.com/envoyproxy/envoy/pull/4215 suggests regexes may be no longer than 1024.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Either a Validating Admission Controller rejects VirtualServices using regexes longer than 1024 bytes or Pilot does not panic when asked to generate the route.

**Steps to reproduce the bug**
- Apply a VirtualService with a regex match statement exceeding 1024 bytes.
- Observe Pilot panic

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio built off 1.2.4

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes

**Comment by howardjohn** [comment]
2 things to do here :

- not panic on invalid config (already merged)
- fix our validation to catch this

**Comment by VitaliyRT** [comment]
✋️👍

**Comment by bharaththiruveedula** [comment]
Can I work on this?

**Comment by howardjohn** [comment]
That would be great!
