### ISSUE TITLE
Open Injection, Connect RocketMQ Error

### ISSUE THREAD

**Issue by 1032231418** [istio/istio#17436]
hi:

Close the injection is normal, the container is connected to the external mysql normal
I asked the operator, they said that istio disassembled the packet and caused the unpacking error.

Request domain name format:

MQ_INST_xxxxxxxxxxxxxx_Ba5pnOzQ.mq-internet-access.mq-internet.aliyuncs.com

```

com.aliyun.openservices.shade.io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 16777216: 1213486164 - discarded
at com.aliyun.openservices.shade.io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:499) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:477) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:403) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.com.alibaba.rocketmq.remoting.netty.NettyDecoder.decode(NettyDecoder.java:43) ~[ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:36) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:358) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:41) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at com.aliyun.openservices.shade.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [ons-client-1.8.2.Final.jar!/:1.8.2.Final]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

```

**Comment by howardjohn** [comment]
Can you provide more info about your setup, what you did, what went wrong, what version you are using, etc?
