### ISSUE TITLE
invalid memory address or nil pointer dereference when enabling SDS

### ISSUE THREAD

**Issue by echavez** [istio/istio#17602]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I can't enable SDS on istio 1.1.15 running on Openshift.
I always get the same error on the istio-nodeagent pods
```

2019-10-03T20:52:40.051254Z	info	parsed scheme: ""
--
  | 2019-10-03T20:52:40.051355Z	info	scheme "" not registered, fallback to default scheme
  | 2019-10-03T20:52:40.051403Z	info	ccResolverWrapper: sending update to cc: {[{istio-citadel:8060 0  <nil>}] <nil>}
  | 2019-10-03T20:52:40.051423Z	info	ClientConn switching balancer to "pick_first"
  | 2019-10-03T20:52:40.051941Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc00003a030, CONNECTING
  | 2019-10-03T20:52:40.264684Z	error	Failed to listen on unix socket "/var/run/sds/uds_path": listen unix /var/run/sds/uds_path: bind: permission denied
  | 2019-10-03T20:52:40.264712Z	error	SDS grpc server for workload proxies failed to start: listen unix /var/run/sds/uds_path: bind: permission denied
  | 2019-10-03T20:52:40.264721Z	info	SDS gRPC server start, listen "/var/run/sds/uds_path"
  |  
  | 2019-10-03T20:52:40.264881Z	info	Start SDS grpc server
  | panic: runtime error: invalid memory address or nil pointer dereference
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x104ba1d]
  |  
  | goroutine 27 [running]:
  | istio.io/istio/vendor/google.golang.org/grpc.(*listenSocket).Close(0xc000311880, 0xc0004e5200, 0xc0000b2d60)
  | /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:533 +0x2d
  | istio.io/istio/vendor/google.golang.org/grpc.(*Server).Serve.func2(0xc0003006e0, 0xc000311880)
  | /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:577 +0x78
  | panic(0x1477260, 0x253daa0)
  | /usr/local/go/src/runtime/panic.go:522 +0x1b5
  | istio.io/istio/vendor/google.golang.org/grpc.(*Server).Serve(0xc0003006e0, 0x0, 0x0, 0x0, 0x0)
  | /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:586 +0x1e0
  | istio.io/istio/security/pkg/nodeagent/sds.(*Server).initWorkloadSdsService.func1(0xc0000d71c0, 0xc0003e8da0, 0xc00038e000)
  | /workspace/go/src/istio.io/istio/security/pkg/nodeagent/sds/server.go:170 +0x6f
  | created by istio.io/istio/security/pkg/nodeagent/sds.(*Server).initWorkloadSdsService
  | /workspace/go/src/istio.io/istio/security/pkg/nodeagent/sds/server.go:166 +0x1a7


```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version --remote:
```
client version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.14-2-gb12614c"}
citadel version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e-dirty", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.14-2-gb12614c"}
egressgateway version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.14-2-gb12614c"}
galley version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e-dirty", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.14-2-gb12614c"}
ingressgateway version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.14-2-gb12614c"}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
pilot version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e-dirty", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.14-2-gb12614c"}
policy version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e-dirty", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.14-2-gb12614c"}
sidecar-injector version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e-dirty", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.14-2-gb12614c"}
telemetry version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e-dirty", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.14-2-gb12614c"}
```
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-03-19T15:41:07Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Istio installed using helm
**Environment where bug was observed (cloud vendor, OS, etc)**
Openshift

**Comment by JimmyCYJ** [comment]
@echavez could you please install 1.4 and try again? 1.1.15 is pretty old. There is also a permission issue by looking at the log.
```  | 2019-10-03T20:52:40.264684Z	error	Failed to listen on unix socket "/var/run/sds/uds_path": listen unix /var/run/sds/uds_path: bind: permission denied
  | 2019-10-03T20:52:40.264712Z	error	SDS grpc server for workload proxies failed to start: listen unix /var/run/sds/uds_path: bind: permission denied```

**Comment by incfly** [comment]
I'm closing this, but reopen if you see it on 1.4 1.5 as well
