### ISSUE TITLE
Istio 1.3.1 - Envoy segfaults

### ISSUE THREAD

**Issue by JRBANCEL** [istio/istio#17699]
**Bug description**
```
Caught Segmentation fault, suspect faulting address 0x0
Backtrace (use tools/stack_decode.py to get line numbers):
#0: __restore_rt [0x7fde03bcc390]
#1: std::__1::__function::__func<>::operator()() [0x1ac08a6]
#2: Envoy::Event::DispatcherImpl::runPostCallbacks() [0x1aab376]
#3: event_process_active_single_queue [0x1d73871]
#4: event_base_loop [0x1d72360]
#5: Envoy::Server::WorkerImpl::threadRoutine() [0x1aa434c]
#6: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x1fdf053]
#7: start_thread [0x7fde03bc26ba]
```

2 core dumps can be found [here](https://console.cloud.google.com/storage/browser/bancel-public/envoy-core-dumps/).

**Affected product area (please put an X in all that apply)**

[X] Networking
[X] Performance and Scalability

**Expected behavior**
Envoy doesn't crash.

**Steps to reproduce the bug**
Run Knative E2E tests: in `https://github.com/knative/serving/`, `./test/e2e-tests.sh --istio-version 1.3-latest --no-mesh`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`istio-1.3.1-12c4d01552363362b49fce86f83b847b308b9b0d-Clean`

```
client version: 1.3.1
cluster-local-gateway version: 
cluster-local-gateway version: 
ingressgateway version: 1.3.1
ingressgateway version: 1.3.1
pilot version: 1.3.1
pilot version: 1.3.1
pilot version: 1.3.1
```
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
See `e2e-tests.sh`.

**Environment where bug was observed (cloud vendor, OS, etc)**
`GKE 1.14.6-gke.2`

**Comment by jplevyak** [comment]
AFAICT this is caused by memory corruption in a post() to a Dispatcher coming out of  Envoy::Router::RdsRouteConfigSubscription::onConfigUpdate. 

Both cores have the SEGV in DispatcherImpl::runPostCallback. 

The only other active threads have stacks pointing to Envoy::Router::RdsRouteConfigSubscription::onConfigUpdate:

#0  0x00000000020c7704 in google::protobuf::Value::~Value() ()
#1  0x0000000000be2f54 in google::protobuf::MapPair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, google::protobuf::Value>::~MapPair (this=0x130457c0) at external/com_google_protobuf/src/google/protobuf/map.h:102
#2  google::protobuf::Map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, google::protobuf::Value>::erase (this=<optimized out>, pos=...) at external/com_google_protobuf/src/google/protobuf/map.h:1132
#3  google::protobuf::Map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, google::protobuf::Value>::erase (this=<optimized out>, first=..., last=...) at external/com_google_protobuf/src/google/protobuf/map.h:1139
#4  google::protobuf::Map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, google::protobuf::Value>::clear (this=0x1fa4a3e0) at external/com_google_protobuf/src/google/protobuf/map.h:1142
#5  google::protobuf::Map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, google::protobuf::Value>::~Map (this=0x1fa4a3e0) at external/com_google_protobuf/src/google/protobuf/map.h:178
#6  0x00000000020c5f46 in google::protobuf::Struct::~Struct() ()
#7  0x0000000002033eb1 in envoy::api::v2::core::Metadata_FilterMetadataEntry_DoNotUse::~Metadata_FilterMetadataEntry_DoNotUse() ()
#8  0x00000000020be550 in google::protobuf::internal::MapFieldBase::~MapFieldBase() ()
#9  0x000000000202c00e in envoy::api::v2::core::Metadata::~Metadata() ()
#10 0x0000000001f1f194 in envoy::api::v2::route::Route::SharedDtor() ()
#11 0x0000000001f1efaa in envoy::api::v2::route::Route::~Route() ()
#12 0x0000000001f1f1fe in envoy::api::v2::route::Route::~Route() ()
#13 0x0000000001f19990 in envoy::api::v2::route::VirtualHost::~VirtualHost() ()
#14 0x0000000001f199de in envoy::api::v2::route::VirtualHost::~VirtualHost() ()
#15 0x0000000001f0f600 in envoy::api::v2::RouteConfiguration::~RouteConfiguration() ()
#16 0x0000000001abd607 in Envoy::Router::RdsRouteConfigSubscription::onConfigUpdate (this=<optimized out>, resources=..., version_info=...) at external/envoy/source/common/router/rds_impl.cc:126
#17 0x0000000001c337ca in Envoy::Config::GrpcMuxSubscriptionImpl::onConfigUpdate (this=0x39bfcb0, resources=..., version_info=...) at external/envoy/source/common/config/grpc_mux_subscription_impl.cc:56
#18 0x0000000001c30572 in Envoy::Config::GrpcMuxImpl::onDiscoveryResponse (this=0x3824c60, message=...) at external/envoy/source/common/config/grpc_mux_impl.cc:191
#19 0x0000000001c3146b in Envoy::Grpc::AsyncStreamCallbacks<envoy::api::v2::DiscoveryResponse>::onReceiveMessageRaw (this=0x3824c70, response=...) at bazel-out/k8-opt/bin/external/envoy/source/common/grpc/_virtual_includes/typed_async_client_lib/common/grpc/typed_async_client.h:89
#20 0x0000000001c54837 in Envoy::Grpc::AsyncStreamImpl::onData (this=0x37eea80, data=..., end_stream=<optimized out>) at external/envoy/source/common/grpc/async_client_impl.cc:138
#21 0x0000000001c58e44 in Envoy::Http::AsyncStreamImpl::encodeData (this=0xe28c880, data=..., end_stream=<optimized out>) at external/envoy/source/common/http/async_client_impl.cc:101
#22 0x0000000001c66698 in Envoy::Router::Filter::onUpstreamData (this=0xe28c8d0, data=..., upstream_request=..., end_stream=<optimized out>) at external/envoy/source/common/router/router.cc:1132
#23 Envoy::Router::Filter::UpstreamRequest::decodeData (this=0x3bc8000, data=..., end_stream=<optimized out>) at external/envoy/source/common/router/router.cc:1371
#24 0x0000000001cd095c in Envoy::Http::Http2::ConnectionImpl::onFrameReceived (this=0x387d990, frame=0x38969a0) at external/envoy/source/common/http/http2/codec_impl.cc:583
#25 0x0000000001d3b23f in session_call_on_frame_received (session=<optimized out>, frame=<optimized out>) at /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/836/execroot/__main__/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:3295
#26 nghttp2_session_on_data_received (session=0x3896800, frame=0x38969a0) at /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/836/execroot/__main__/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:4966
#27 0x0000000001d3cf17 in session_process_data_frame (session=<optimized out>) at /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/836/execroot/__main__/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:4986
#28 nghttp2_session_mem_recv (session=<optimized out>, in=0xa7c5c06 "", inlen=<optimized out>) at /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/836/execroot/__main__/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:6607
#29 0x0000000001cd0039 in Envoy::Http::Http2::ConnectionImpl::dispatch (this=0x387d990, data=...) at external/envoy/source/common/http/http2/codec_impl.cc:412
#30 0x0000000001c4a926 in Envoy::Http::CodecClient::onData (this=0x3bb22d0, data=...) at external/envoy/source/common/http/codec_client.cc:116
#31 0x0000000001c4b31d in Envoy::Http::CodecClient::CodecReadFilter::onData (this=<optimized out>, data=...) at bazel-out/k8-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_client_lib/common/http/codec_client.h:172
#32 0x0000000001ab4c11 in Envoy::Network::FilterManagerImpl::onContinueReading (this=0x39896a8, filter=<optimized out>, buffer_source=...) at external/envoy/source/common/network/filter_manager_impl.cc:65
#33 0x0000000001ab1cac in Envoy::Network::ConnectionImpl::onRead (this=<optimized out>, read_buffer_size=<optimized out>) at external/envoy/source/common/network/connection_impl.cc:271
#34 Envoy::Network::ConnectionImpl::onReadReady (this=0x3989680) at external/envoy/source/common/network/connection_impl.cc:515
#35 0x0000000001ab1771 in Envoy::Network::ConnectionImpl::onFileEvent (this=0x3989680, events=<optimized out>) at external/envoy/source/common/network/connection_impl.cc:491
#36 0x0000000001aac1e0 in std::__1::__function::__value_func<void (unsigned int)>::operator()(unsigned int&&) const (this=0x2608d880, __args=<optimized out>) at /usr/lib/llvm-8/bin/../include/c++/v1/functional:1799
#37 std::__1::function<void (unsigned int)>::operator()(unsigned int) const (this=0x2608d880, __arg=<optimized out>) at /usr/lib/llvm-8/bin/../include/c++/v1/functional:2347
#38 Envoy::Event::FileEventImpl::assignEvents(unsigned int)::$_0::operator()(int, short, void*) const (this=<optimized out>, what=<optimized out>, arg=0x2608d800) at external/envoy/source/common/event/file_event_impl.cc:65
#39 Envoy::Event::FileEventImpl::assignEvents(unsigned int)::$_0::__invoke(int, short, void*) (what=<optimized out>, arg=0x2608d800) at external/envoy/source/common/event/file_event_impl.cc:49
#40 0x0000000001d73dad in event_process_active_single_queue ()
#41 0x0000000001d72360 in event_base_loop ()



#0  0x0000000002196076 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) ()
#1  0x00000000021a4171 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int, void* (*)(unsigned long)) ()
#2  0x0000000000bad9db in google::protobuf::Map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, google::protobuf::Struct>::CreateValueTypeInternal (this=<optimized out>, key=...) at external/com_google_protobuf/src/google/protobuf/map.h:1179
#3  0x0000000000bce703 in google::protobuf::Map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, google::protobuf::Struct>::operator[] (this=0x59e89b48, key=...) at external/com_google_protobuf/src/google/protobuf/map.h:1051
#4  0x000000000202bf50 in google::protobuf::internal::MapField<envoy::api::v2::core::Metadata_FilterMetadataEntry_DoNotUse, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, google::protobuf::Struct, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>::MergeFrom(google::protobuf::internal::MapFieldBase const&) ()
#5  0x000000000202be7c in envoy::api::v2::core::Metadata::Metadata(envoy::api::v2::core::Metadata const&) ()
#6  0x0000000001cdecfd in Envoy::Router::RouteEntryImplBase::RouteEntryImplBase (this=0x59e89700, vhost=..., route=..., factory_context=...) at external/envoy/source/common/router/config_impl.cc:399
#7  0x0000000001ce2c12 in Envoy::Router::PrefixRouteEntryImpl::PrefixRouteEntryImpl (this=0x59e89700, vhost=..., route=..., factory_context=...) at external/envoy/source/common/router/config_impl.cc:839
#8  Envoy::Router::VirtualHostImpl::VirtualHostImpl (this=0xde7cc40, virtual_host=..., global_route_config=..., factory_context=..., validate_clusters=<optimized out>) at external/envoy/source/common/router/config_impl.cc:977
#9  0x0000000001ce391f in Envoy::Router::RouteMatcher::RouteMatcher (this=0x354d6700, route_config=..., global_route_config=..., factory_context=..., validate_clusters=<optimized out>) at external/envoy/source/common/router/config_impl.cc:1047
#10 0x0000000001ce48b9 in std::__1::make_unique<Envoy::Router::RouteMatcher, envoy::api::v2::RouteConfiguration const&, Envoy::Router::ConfigImpl&, Envoy::Server::Configuration::FactoryContext&, bool> (__args=<optimized out>, __args=<optimized out>, __args=<optimized out>, __args=<optimized out>) at /usr/lib/llvm-8/bin/../include/c++/v1/memory:3132
#11 Envoy::Router::ConfigImpl::ConfigImpl (this=0x4cb19860, config=..., factory_context=..., validate_clusters_default=<optimized out>) at external/envoy/source/common/router/config_impl.cc:1176
#12 0x0000000001abe2aa in Envoy::Router::RdsRouteConfigProviderImpl::onConfigUpdate (this=0x1ed78750) at external/envoy/source/common/router/rds_impl.cc:196
#13 0x0000000001abd5e2 in Envoy::Router::RdsRouteConfigSubscription::onConfigUpdate (this=0x30eb3b0, resources=..., version_info=...) at external/envoy/source/common/router/rds_impl.cc:119
#14 0x0000000001c337ca in Envoy::Config::GrpcMuxSubscriptionImpl::onConfigUpdate (this=0x312dcb0, resources=..., version_info=...) at external/envoy/source/common/config/grpc_mux_subscription_impl.cc:56
#15 0x0000000001c30572 in Envoy::Config::GrpcMuxImpl::onDiscoveryResponse (this=0x2f92c60, message=...) at external/envoy/source/common/config/grpc_mux_impl.cc:191
#16 0x0000000001c3146b in Envoy::Grpc::AsyncStreamCallbacks<envoy::api::v2::DiscoveryResponse>::onReceiveMessageRaw (this=0x2f92c70, response=...) at bazel-out/k8-opt/bin/external/envoy/source/common/grpc/_virtual_includes/typed_async_client_lib/common/grpc/typed_async_client.h:89
#17 0x0000000001c54837 in Envoy::Grpc::AsyncStreamImpl::onData (this=0x2f5ca80, data=..., end_stream=<optimized out>) at external/envoy/source/common/grpc/async_client_impl.cc:138
#18 0x0000000001c58e44 in Envoy::Http::AsyncStreamImpl::encodeData (this=0x30f7680, data=..., end_stream=<optimized out>) at external/envoy/source/common/http/async_client_impl.cc:101
#19 0x0000000001c66698 in Envoy::Router::Filter::onUpstreamData (this=0x30f76d0, data=..., upstream_request=..., end_stream=<optimized out>) at external/envoy/source/common/router/router.cc:1132
#20 Envoy::Router::Filter::UpstreamRequest::decodeData (this=0x3336380, data=..., end_stream=<optimized out>) at external/envoy/source/common/router/router.cc:1371
#21 0x0000000001cd095c in Envoy::Http::Http2::ConnectionImpl::onFrameReceived (this=0x2feb990, frame=0x30049a0) at external/envoy/source/common/http/http2/codec_impl.cc:583
#22 0x0000000001d3b23f in session_call_on_frame_received (session=<optimized out>, frame=<optimized out>) at /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/836/execroot/__main__/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:3295
#23 nghttp2_session_on_data_received (session=0x3004800, frame=0x30049a0) at /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/836/execroot/__main__/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:4966
#24 0x0000000001d3cf17 in session_process_data_frame (session=<optimized out>) at /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/836/execroot/__main__/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:4986
#25 nghttp2_session_mem_recv (session=<optimized out>, in=0x35e382d8 "", inlen=<optimized out>) at /home/bootstrap/.cache/bazel/_bazel_bootstrap/45ae47b4a0e12d1e81c831ece04d820d/sandbox/linux-sandbox/836/execroot/__main__/external/com_github_nghttp2_nghttp2/lib/nghttp2_session.c:6607
#26 0x0000000001cd0039 in Envoy::Http::Http2::ConnectionImpl::dispatch (this=0x2feb990, data=...) at external/envoy/source/common/http/http2/codec_impl.cc:412
#27 0x0000000001c4a926 in Envoy::Http::CodecClient::onData (this=0x3320240, data=...) at external/envoy/source/common/http/codec_client.cc:116
#28 0x0000000001c4b31d in Envoy::Http::CodecClient::CodecReadFilter::onData (this=<optimized out>, data=...) at bazel-out/k8-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_client_lib/common/http/codec_client.h:172
#29 0x0000000001ab4c11 in Envoy::Network::FilterManagerImpl::onContinueReading (this=0x30f7b28, filter=<optimized out>, buffer_source=...) at external/envoy/source/common/network/filter_manager_impl.cc:65
#30 0x0000000001ab1cac in Envoy::Network::ConnectionImpl::onRead (this=<optimized out>, read_buffer_size=<optimized out>) at external/envoy/source/common/network/connection_impl.cc:271
#31 Envoy::Network::ConnectionImpl::onReadReady (this=0x30f7b00) at external/envoy/source/common/network/connection_impl.cc:515
#32 0x0000000001ab1771 in Envoy::Network::ConnectionImpl::onFileEvent (this=0x30f7b00, events=<optimized out>) at external/envoy/source/common/network/connection_impl.cc:491
#33 0x0000000001aac1e0 in std::__1::__function::__value_func<void (unsigned int)>::operator()(unsigned int&&) const (this=0x236e23a0, __args=<optimized out>) at /usr/lib/llvm-8/bin/../include/c++/v1/functional:1799
#34 std::__1::function<void (unsigned int)>::operator()(unsigned int) const (this=0x236e23a0, __arg=<optimized out>) at /usr/lib/llvm-8/bin/../include/c++/v1/functional:2347
#35 Envoy::Event::FileEventImpl::assignEvents(unsigned int)::$_0::operator()(int, short, void*) const (this=<optimized out>, what=<optimized out>, arg=0x236e2320) at external/envoy/source/common/event/file_event_impl.cc:65
#36 Envoy::Event::FileEventImpl::assignEvents(unsigned int)::$_0::__invoke(int, short, void*) (what=<optimized out>, arg=0x236e2320) at external/envoy/source/common/event/file_event_impl.cc:49
#37 0x0000000001d73dad in event_process_active_single_queue ()
#38 0x0000000001d72360 in event_base_loop ()


The most likely culprit is:

void RdsRouteConfigProviderImpl::onConfigUpdate() {
  ConfigConstSharedPtr new_config(
      new ConfigImpl(config_update_info_->routeConfiguration(), factory_context_, false));
  tls_->runOnAllThreads(
      [this, new_config]() -> void { tls_->getTyped<ThreadLocalConfig>().config_ = new_config; });
}

However it is difficult to say since the SEGV occurs in another thread with a corrupted stack which is handling a post() of a std::function<>.

**Comment by jplevyak** [comment]
It should be noted that this code (RDS) has undergone a good deal of change since the 1.3 was forked.  There may be some clues in the history.  I will investigate.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy/issues/7902

**Comment by jplevyak** [comment]
The fix is available:  https://github.com/envoyproxy/envoy/pull/8290

**Comment by rlenglet** [comment]
This can be closed?
