### ISSUE TITLE
missing kubeconfig crashes istioctl

### ISSUE THREAD

**Issue by tdeckers** [istio/istio#1855]
When launching istioctl without a kubeconfig file available, it panics with following message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x12152f0]

goroutine 1 [running]:
main.getDefaultNamespace(0xc04239c7c0, 0x3a, 0x0, 0x0)
        /home/sebastienvas/go/src/istio.io/pilot/cmd/istioctl/main.go:700 +0xa0
main.glob..func4(0x1cbc640, 0x1ce8f58, 0x0, 0x0)
        /home/sebastienvas/go/src/istio.io/pilot/cmd/istioctl/main.go:86 +0x40
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).execute(0x1cbc640, 0x1ce8f58, 0x0, 0x0, 0x1cbc640, 0x1ce8f58)
        /home/sebastienvas/go/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:637 +0x550
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1cbbf80, 0x121ae0a, 0x0, 0x0)
        /home/sebastienvas/go/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:729 +0x340
istio.io/pilot/vendor/github.com/spf13/cobra.(*Command).Execute(0x1cbbf80, 0x0, 0x154)
        /home/sebastienvas/go/src/istio.io/pilot/vendor/github.com/spf13/cobra/command.go:688 +0x32
main.main()
        /home/sebastienvas/go/src/istio.io/pilot/cmd/istioctl/main.go:531 +0xc7
```

When adding the --kubeconfig parameter, things work as expected.  Likely need to add proper checks for config file.

**Comment by ayj** [comment]
Dup of istio/istio#1734 and istio/istio#1734
