### ISSUE TITLE
istioctl version throws the 'index out of range' panic if a user does not have the 'pods/exec' permission

### ISSUE THREAD

**Issue by georgyturevich** [istio/istio#18925]
**Bug description**
istioctl version throws the 'index out of range' panic if a user does not have the 'pods/exec' permission

```
panic: runtime error: index out of range

goroutine 1 [running]:
istio.io/istio/vendor/istio.io/pkg/version.identicalVersions(0x4708070, 0x0, 0x0, 0x2)
        /workspace/go/src/istio.io/istio/vendor/istio.io/pkg/version/cobra.go:136 +0x142
istio.io/istio/vendor/istio.io/pkg/version.coalesceVersions(...)
        /workspace/go/src/istio.io/istio/vendor/istio.io/pkg/version/cobra.go:123
istio.io/istio/vendor/istio.io/pkg/version.CobraCommandWithOptions.func1(0xc00051a280, 0x4708070, 0x0, 0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/istio.io/pkg/version/cobra.go:80 +0x115
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).execute(0xc00051a280, 0x4708070, 0x0, 0x0, 0xc00051a280, 0x4708070)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:762 +0x46c
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00051a000, 0x1, 0x1, 0xc00051a000)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:852 +0x2f3
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /workspace/go/src/istio.io/istio/istioctl/cmd/istioctl/main.go:28 +0x7c
```

I am not 100% sure what I should mark here

**Expected behavior**
If a user does not have enough permission I expect to see the error message like this:
```
Error: 6 errors occurred:
	* error execing into istio-citadel-aaa-bbb citadel container: pods "istio-citadel-aaa-bbb" is forbidden: User "georgy" cannot create resource "pods/exec" in API group "" in the namespace "istio-system"
	* error execing into istio-galley-aaa-bbb galley container: pods "istio-galley-aaa-bbb" is forbidden: User "georgy" cannot create resource "pods/exec" in API group "" in the namespace "istio-system"
	* error execing into istio-ingressgateway-aaa-bbb istio-proxy container: pods "istio-ingressgateway-aaa-bbb" is forbidden: User "georgy" cannot create resource "pods/exec" in API group "" in the namespace "istio-system"
	* error execing into istio-pilot-aaa-bbb discovery container: pods "istio-pilot-aaa-bbb" is forbidden: User "georgy" cannot create resource "pods/exec" in API group "" in the namespace "istio-system"
	* error execing into istio-policy-aaa-bbb mixer container: pods "istio-policy-aaa-bbb" is forbidden: User "georgy" cannot create resource "pods/exec" in API group "" in the namespace "istio-system"
	* error execing into istio-telemetry-aaa-bbb mixer container: pods "istio-telemetry-aaa-bbb" is forbidden: User "georgy" cannot create resource "pods/exec" in API group "" in the namespace "istio-system"

```

**Steps to reproduce the bug**

Run `istioctl version` command by a Kubernetes user who does not have a permission to create "pods/exec" resources

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
The output of `istioctl.exe version --remote=false` is
```
1.3.4
```

I also see the same error in `master` version.

**How was Istio installed?**
With the help of helm as describe in quickstart documentation.

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS cluster

**Comment by georgyturevich** [comment]
I provided a Pull Request here https://github.com/istio/pkg/pull/90 with a simple fix
