### ISSUE TITLE
mixer: panic when adding a new remote cluster

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#19158]
**Bug description**

Installing a new multi-cluster secret for a new remote cluster causes mixer to panic.

**Expected behavior**

Mixer should not panic when adding a new remote cluster.

**Steps to reproduce the bug**

Set up a remote cluster by creating a new configuration Secret for it.

Observe the following:

```
2019-11-23T00:48:32.876629Z     info    Processing add: istio-system/gke-prod-asia-east2-cluster
2019-11-23T00:48:32.876687Z     info    Processing add: istio-system/gke-prod-asia-east2-cluster
2019-11-23T00:48:32.876640Z     info    Processing add: istio-system/gke-prod-asia-east2-cluster
2019-11-23T00:48:32.878143Z     info    Adding new cluster member: gke_prod_asia-east2-cluster
2019-11-23T00:48:32.878186Z     info    Adding new cluster member: gke_prod_asia-east2-cluster
2019-11-23T00:48:32.878310Z     info    Adding new cluster member: gke_prod_asia-east2-cluster
2019-11-23T00:48:32.879721Z     info    adapters        Waiting for kubernetes cache sync...    {"adapter": "kubernetesenv.istio-system"}
2019-11-23T00:48:32.879738Z     error   Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```

Backtrace:

```
goroutine 4154 [running]:
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x21d1ee0, 0x42f0d20)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x21d1ee0, 0x42f0d20)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
istio.io/istio/mixer/adapter/kubernetesenv.(*builder).createCacheController(0xc005b8d800, 0x2a4f480, 0xc0051f6d80, 0xc0079b8000, 0x2b, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/mixer/adapter/kubernetesenv/kubernetesenv.go:360 +0x3b
istio.io/istio/pkg/kube/secretcontroller.(*Controller).addMemberCluster(0xc001c294a0, 0xc00383a9c0, 0x38, 0xc004a4da40)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:248 +0x822
istio.io/istio/pkg/kube/secretcontroller.(*Controller).processItem(0xc001c294a0, 0xc00383a9c0, 0x38, 0x20f47e0, 0xc007209ea0)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:209 +0xe3
istio.io/istio/pkg/kube/secretcontroller.(*Controller).processNextItem(0xc001c294a0, 0xc004286700)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:186 +0xd3
istio.io/istio/pkg/kube/secretcontroller.(*Controller).runWorker(0xc001c294a0)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:174 +0x2b
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0051e5f98)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00415ff98, 0x12a05f200, 0x0, 0x1, 0xc002b9a300)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
istio.io/istio/pkg/kube/secretcontroller.(*Controller).Run(0xc001c294a0, 0xc002b9a300)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:156 +0x297
created by istio.io/istio/pkg/kube/secretcontroller.StartSecretController
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:168 +0xf4
```

This is probably crashing due to `b.kubeHandler` or `.env` being `nil` here:
https://github.com/istio/istio/blob/1.3.5/mixer/adapter/kubernetesenv/kubernetesenv.go#L360

Based on some other tickets I've opened in the past, both mixer and pilot seem succeptible to race conditions when setting up multi-cluster environments:
- #15663
- #13412

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: unknown
control plane version: 1.3.5
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

**How was Istio installed?**

Helm.

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE.

**Comment by mandarjog** [comment]
@carolynhu  can you investigate? Per report, this seems like a generic race affecting all kubeAPI consumers.

**Comment by carolynhu** [comment]
@mandarjog sure, let me look into this issue.

**Comment by carolynhu** [comment]
@nicktrav Could you elaborate the way that you enable multi-cluster. And the steps to reproduce your error. Thanks.

**Comment by nicktrav** [comment]
@carolynhu - we enable multi-cluster via the instructions detailed here (i.e. create Secret in the control plane cluster, etc.):
https://istio.io/docs/setup/install/multicluster/shared-vpn/

Specifically, in this case, we were linking a new cluster for the _first_ time.

Let me poke around and see if I can get this to happen again when I re-link.

**Comment by nicktrav** [comment]
I was able to get mixer to crash again in the case where I _unlinked_ a cluster:

```
goroutine 2167 [running]:
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x21d1ee0, 0x42f0d20)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x21d1ee0, 0x42f0d20)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
istio.io/istio/mixer/adapter/kubernetesenv.(*builder).deleteCacheController(0xc000cbcd80, 0xc0017b0440, 0x33, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/mixer/adapter/kubernetesenv/kubernetesenv.go:382 +0x8b
istio.io/istio/pkg/kube/secretcontroller.(*Controller).deleteMemberCluster(0xc0016a07e0, 0xc00331e7c0, 0x40)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:264 +0x17b
istio.io/istio/pkg/kube/secretcontroller.(*Controller).processItem(0xc0016a07e0, 0xc00331e7c0, 0x40, 0x20f47e0, 0xc0054d3930)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:211 +0x129
istio.io/istio/pkg/kube/secretcontroller.(*Controller).processNextItem(0xc0016a07e0, 0xc0004a5600)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:186 +0xd3
istio.io/istio/pkg/kube/secretcontroller.(*Controller).runWorker(0xc0016a07e0)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:174 +0x2b
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00074ff98)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00176df98, 0x12a05f200, 0x0, 0x1, 0xc000c86060)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
istio.io/istio/pkg/kube/secretcontroller.(*Controller).Run(0xc0016a07e0, 0xc000c86060)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:156 +0x297
created by istio.io/istio/pkg/kube/secretcontroller.StartSecretController
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:168 +0xf4
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x21d1ee0, 0x42f0d20)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x21d1ee0, 0x42f0d20)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
istio.io/istio/mixer/adapter/kubernetesenv.(*builder).deleteCacheController(0xc000282000, 0xc00116ca00, 0x33, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/mixer/adapter/kubernetesenv/kubernetesenv.go:382 +0x8b
istio.io/istio/pkg/kube/secretcontroller.(*Controller).deleteMemberCluster(0xc001861140, 0xc003330400, 0x40)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:264 +0x17b
istio.io/istio/pkg/kube/secretcontroller.(*Controller).processItem(0xc001861140, 0xc003330400, 0x40, 0x20f47e0, 0xc003862830)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:211 +0x129
istio.io/istio/pkg/kube/secretcontroller.(*Controller).processNextItem(0xc001861140, 0xc00195b500)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:186 +0xd3
istio.io/istio/pkg/kube/secretcontroller.(*Controller).runWorker(0xc001861140)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:174 +0x2b
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc001078f98)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00317bf98, 0x12a05f200, 0x0, 0x1, 0xc0000a38c0)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /workspace/go/src/istio.io/istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
istio.io/istio/pkg/kube/secretcontroller.(*Controller).Run(0xc001861140, 0xc0000a38c0)
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:156 +0x297
created by istio.io/istio/pkg/kube/secretcontroller.StartSecretController
        /workspace/go/src/istio.io/istio/pkg/kube/secretcontroller/secretcontroller.go:168 +0xf4
```

Still trying to reproduce the case where linking a new cluster causes a crash, but I suspect it's the same underlying issue.

**Comment by nicktrav** [comment]
The same race condition for cluster deletion is also present in 1.4.0 (deleting the Secret for a remote cluster triggers a crash of all mixer Pods):

```
goroutine 2177 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x2065920, 0x3b29c50)
        runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x2065920, 0x3b29c50)
        runtime/panic.go:679 +0x1b2
istio.io/istio/mixer/adapter/kubernetesenv.(*builder).deleteCacheController(0xc000b72090, 0xc00107b680, 0x31, 0x0, 0x0)
        istio.io/istio@/mixer/adapter/kubernetesenv/kubernetesenv.go:382 +0xb6
istio.io/istio/pkg/kube/secretcontroller.(*Controller).deleteMemberCluster(0xc000a76ae0, 0xc0060c0580, 0x3e)
        istio.io/istio@/pkg/kube/secretcontroller/secretcontroller.go:265 +0x17b
istio.io/istio/pkg/kube/secretcontroller.(*Controller).processItem(0xc000a76ae0, 0xc0060c0580, 0x3e, 0x0, 0x0)
        istio.io/istio@/pkg/kube/secretcontroller/secretcontroller.go:212 +0x115
istio.io/istio/pkg/kube/secretcontroller.(*Controller).processNextItem(0xc000a76ae0, 0x0)
        istio.io/istio@/pkg/kube/secretcontroller/secretcontroller.go:187 +0xfa
istio.io/istio/pkg/kube/secretcontroller.(*Controller).runWorker(0xc000a76ae0)
        istio.io/istio@/pkg/kube/secretcontroller/secretcontroller.go:175 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a84f98)
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002343f98, 0x12a05f200, 0x0, 0x1, 0xc00087a840)
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88
istio.io/istio/pkg/kube/secretcontroller.(*Controller).Run(0xc000a76ae0, 0xc00087a840)
        istio.io/istio@/pkg/kube/secretcontroller/secretcontroller.go:157 +0x23e
created by istio.io/istio/pkg/kube/secretcontroller.StartSecretController
        istio.io/istio@/pkg/kube/secretcontroller/secretcontroller.go:169 +0xf4
```
