### ISSUE TITLE
first-party-jwt seg fault in pilot

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20384]
```
2020-01-21T22:58:15.005051Z	info	FLAG: --appNamespace=""
2020-01-21T22:58:15.005072Z	info	FLAG: --clusterRegistriesNamespace=""
2020-01-21T22:58:15.005076Z	info	FLAG: --configDir=""
2020-01-21T22:58:15.005078Z	info	FLAG: --consulserverURL=""
2020-01-21T22:58:15.005082Z	info	FLAG: --ctrlz_address="localhost"
2020-01-21T22:58:15.005087Z	info	FLAG: --ctrlz_port="9876"
2020-01-21T22:58:15.005092Z	info	FLAG: --disable-install-crds="true"
2020-01-21T22:58:15.005096Z	info	FLAG: --domain="cluster.local"
2020-01-21T22:58:15.005098Z	info	FLAG: --grpcAddr=":15010"
2020-01-21T22:58:15.005102Z	info	FLAG: --help="false"
2020-01-21T22:58:15.005105Z	info	FLAG: --httpAddr=":8080"
2020-01-21T22:58:15.005108Z	info	FLAG: --httpsAddr=":15017"
2020-01-21T22:58:15.005113Z	info	FLAG: --keepaliveInterval="30s"
2020-01-21T22:58:15.005117Z	info	FLAG: --keepaliveMaxServerConnectionAge="30m0s"
2020-01-21T22:58:15.005120Z	info	FLAG: --keepaliveTimeout="10s"
2020-01-21T22:58:15.005123Z	info	FLAG: --kubeconfig=""
2020-01-21T22:58:15.005127Z	info	FLAG: --log_as_json="false"
2020-01-21T22:58:15.005130Z	info	FLAG: --log_caller=""
2020-01-21T22:58:15.005134Z	info	FLAG: --log_output_level="default:info"
2020-01-21T22:58:15.005139Z	info	FLAG: --log_rotate=""
2020-01-21T22:58:15.005144Z	info	FLAG: --log_rotate_max_age="30"
2020-01-21T22:58:15.005148Z	info	FLAG: --log_rotate_max_backups="1000"
2020-01-21T22:58:15.005151Z	info	FLAG: --log_rotate_max_size="104857600"
2020-01-21T22:58:15.005155Z	info	FLAG: --log_stacktrace_level="default:none"
2020-01-21T22:58:15.005163Z	info	FLAG: --log_target="[stdout]"
2020-01-21T22:58:15.005168Z	info	FLAG: --mcpInitialConnWindowSize="1048576"
2020-01-21T22:58:15.005172Z	info	FLAG: --mcpInitialWindowSize="1048576"
2020-01-21T22:58:15.005175Z	info	FLAG: --mcpMaxMsgSize="4194304"
2020-01-21T22:58:15.005179Z	info	FLAG: --meshConfig="/etc/istio/config/mesh"
2020-01-21T22:58:15.005183Z	info	FLAG: --monitoringAddr=":15014"
2020-01-21T22:58:15.005186Z	info	FLAG: --namespace=""
2020-01-21T22:58:15.005190Z	info	FLAG: --networksConfig="/etc/istio/config/meshNetworks"
2020-01-21T22:58:15.005197Z	info	FLAG: --plugins="[authn,authz,health,mixer]"
2020-01-21T22:58:15.005203Z	info	FLAG: --profile="true"
2020-01-21T22:58:15.005208Z	info	FLAG: --registries="[Kubernetes]"
2020-01-21T22:58:15.005213Z	info	FLAG: --resync="1m0s"
2020-01-21T22:58:15.005216Z	info	FLAG: --secureGrpcAddr=""
2020-01-21T22:58:15.005219Z	info	FLAG: --trust-domain="cluster.local"
2020-01-21T22:58:15.005243Z	info	Primary Cluster name: Kubernetes
2020-01-21T22:58:15.007262Z	info	mesh configuration: {
    "mixerReportServer": "istio-telemetry.istio-system.svc.cluster.local:9091",
    "disablePolicyChecks": true,
    "proxyListenPort": 15001,
    "connectTimeout": "1s",
    "protocolDetectionTimeout": "0.100s",
    "ingressClass": "istio",
    "ingressService": "istio-ingressgateway",
    "ingressControllerMode": "STRICT",
    "enableTracing": true,
    "defaultConfig": {
        "configPath": "/etc/istio/proxy",
        "binaryPath": "/usr/local/bin/envoy",
        "serviceCluster": "istio-proxy",
        "drainDuration": "45s",
        "parentShutdownDuration": "60s",
        "discoveryAddress": "istio-pilot.istio-system.svc:15012",
        "connectTimeout": "10s",
        "proxyAdminPort": 15000,
        "statNameLength": 189,
        "concurrency": 2,
        "tracing": {
            "zipkin": {
                "address": "zipkin.istio-system:9411"
            }
        },
        "envoyAccessLogService": {

        },
        "envoyMetricsService": {

        }
    },
    "outboundTrafficPolicy": {
        "mode": "ALLOW_ANY"
    },
    "sdsUdsPath": "unix:/etc/istio/proxy/SDS",
    "enableAutoMtls": true,
    "trustDomain": "cluster.local",
    "trustDomainAliases": [
    ],
    "defaultServiceExportTo": [
        "*"
    ],
    "defaultVirtualServiceExportTo": [
        "*"
    ],
    "defaultDestinationRuleExportTo": [
        "*"
    ],
    "rootNamespace": "istio-system",
    "localityLbSetting": {
        "enabled": true
    },
    "dnsRefreshRate": "5s",
    "reportBatchMaxEntries": 100,
    "reportBatchMaxTime": "1s",
    "certificates": [
    ]
}
2020-01-21T22:58:15.007273Z	info	version: 1.5-alpha.517b14c37e5988e3dfbcb700530d1fcbbb5af6ea-517b14c37e5988e3dfbcb700530d1fcbbb5af6ea-Clean
2020-01-21T22:58:15.007584Z	info	flags: {
   "DiscoveryOptions": {
      "HTTPAddr": ":8080",
      "HTTPSAddr": ":15017",
      "GrpcAddr": ":15010",
      "SecureGrpcAddr": "",
      "SecureGrpcDNSAddr": "",
      "MonitoringAddr": ":15014",
      "EnableProfiling": true
   },
   "InjectionOptions": {
      "InjectionDirectory": "./var/lib/istio/inject"
   },
   "ValidationOptions": {
      "ValidationDirectory": "./var/lib/istio/validation"
   },
   "Namespace": "istio-system",
   "Mesh": {
      "ConfigFile": "/etc/istio/config/mesh",
      "MixerAddress": ""
   },
   "Config": {
      "ControllerOptions": {
         "WatchedNamespace": "",
         "ResyncPeriod": 60000000000,
         "DomainSuffix": "cluster.local",
         "ClusterID": "",
         "Metrics": null,
         "XDSUpdater": null,
         "TrustDomain": "cluster.local",
         "NetworksWatcher": null,
         "EndpointMode": 0
      },
      "ClusterRegistriesNamespace": "istio-system",
      "KubeConfig": "",
      "FileDir": "",
      "DistributionCacheRetention": 60000000000,
      "DisableInstallCRDs": true,
      "DistributionTrackingEnabled": true
   },
   "Service": {
      "Registries": [
         "Kubernetes"
      ],
      "Consul": {
         "ServerURL": ""
      }
   },
   "MeshConfig": null,
   "NetworksConfigFile": "/etc/istio/config/meshNetworks",
   "CtrlZOptions": {
      "Port": 9876,
      "Address": "localhost"
   },
   "Plugins": [
      "authn",
      "authz",
      "health",
      "mixer"
   ],
   "MCPMaxMessageSize": 4194304,
   "MCPInitialWindowSize": 1048576,
   "MCPInitialConnWindowSize": 1048576,
   "KeepaliveOptions": {
      "Time": 30000000000,
      "Timeout": 10000000000,
      "MaxServerConnectionAge": 1800000000000,
      "MaxServerConnectionAgeGrace": 10000000000
   },
   "ForceStop": false,
   "BasePort": 15000
}
2020-01-21T22:58:15.007685Z	info	mesh networks configuration: {
   "networks": {
   }
}
2020-01-21T22:58:15.007718Z	info	No certificates specified, skipping DNS certificate controller
2020-01-21T22:58:15.009042Z	info	CRD controller watching namespaces ""
2020-01-21T22:58:15.009156Z	info	Ingress controller watching namespaces ""
2020-01-21T22:58:15.009249Z	info	Adding Kubernetes registry adapter
2020-01-21T22:58:15.009259Z	info	Service controller watching namespace "" for services, endpoints, nodes and pods, refresh 1m0s
2020-01-21T22:58:15.009485Z	info	Setting up event handlers
2020-01-21T22:58:15.009501Z	info	Starting Secrets controller
2020-01-21T22:58:15.009513Z	warn	istiod running without access to K8S tokens (jwt path ./var/run/secrets/tokens/istio-token); disable the CA functionality
2020-01-21T22:58:15.009515Z	info	Waiting for informer caches to sync
2020-01-21T22:58:15.009527Z	info	Generating Citadel-signed cert for [istio-pilot.istio-system.svc istiod.istio-system.svc]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x114bc1a]

goroutine 1 [running]:
istio.io/istio/security/pkg/pki/ca.(*IstioCA).Sign(0x0, 0xc000934000, 0x36f, 0x3c0, 0xc0004ba200, 0x2, 0x2, 0x460623fc85e0000, 0x600, 0x7c0, ...)
	istio.io/istio@/security/pkg/pki/ca/ca.go:270 +0x3a
istio.io/istio/security/pkg/pki/ca.(*IstioCA).SignWithCertChain(0x0, 0xc000934000, 0x36f, 0x3c0, 0xc0004ba200, 0x2, 0x2, 0x460623fc85e0000, 0x0, 0x0, ...)
	istio.io/istio@/security/pkg/pki/ca/ca.go:307 +0xa7
istio.io/istio/security/pkg/pki/ca.(*IstioCA).GenKeyCert(0x0, 0xc0004ba200, 0x2, 0x2, 0x460623fc85e0000, 0x2b, 0x40000, 0x460623fc85e0000, 0x0, 0xc000609d10, ...)
	istio.io/istio@/security/pkg/pki/ca/ca.go:341 +0x110
istio.io/istio/pilot/pkg/bootstrap.(*Server).initDNSCerts(0xc0005e6420, 0xc00005209c, 0x1c, 0x0, 0x0)
	istio.io/istio@/pilot/pkg/bootstrap/certcontroller.go:149 +0x6e0
istio.io/istio/pilot/pkg/bootstrap.(*Server).initDNSListener(0xc0005e6420, 0x3dd2020, 0x0, 0x0)
	istio.io/istio@/pilot/pkg/bootstrap/server.go:758 +0x2f3
istio.io/istio/pilot/pkg/bootstrap.NewServer(0x3dd2020, 0x0, 0xc0004641e0, 0x24f4d7c)
	istio.io/istio@/pilot/pkg/bootstrap/server.go:219 +0xbb1
main.glob..func1(0x3dd2980, 0xc00058eb40, 0x0, 0xa, 0x0, 0x0)
	istio.io/istio@/pilot/cmd/pilot-discovery/main.go:86 +0xef
github.com/spf13/cobra.(*Command).execute(0x3dd2980, 0xc00058e6e0, 0xa, 0xa, 0x3dd2980, 0xc00058e6e0)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x3dd2700, 0x0, 0x0, 0x0)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	istio.io/istio@/pilot/cmd/pilot-discovery/main.go:192 +0x2d
```

From master: `ik manifest apply --set values.global.jwtPolicy=first-party-jwt -y`

**Comment by howardjohn** [comment]
@lei-tang

**Comment by lei-tang** [comment]
The support of first party JWT is a work-in-progress. Before it is completed, please keep the jwtPolicy=third-party-jwt.

**Comment by howardjohn** [comment]
Ok, makes sense. What is the status of this? We cannot ship 1.5 without it

**Comment by lei-tang** [comment]
The first part of the implementation has been merged to master. I will complete the implementation before 1.5.

**Comment by howardjohn** [comment]
Ok cool. Thanks!

**Comment by howardjohn** [comment]
Presumed fixed

**Comment by howardjohn** [comment]
This happens for other reasons as well, ill send a fix

**Comment by howardjohn** [comment]
Basically if we don't have CA functionality enabled, but we have citadel as the CA provider, things go bad

**Comment by lei-tang** [comment]
With https://github.com/istio/istio/pull/20401, will this problem still occur? All tests in https://github.com/istio/istio/pull/20401 passes, which has first-party-jwt enabled and Citadel as pilotCertProvider. What are the steps to reproduce this problem? If you need any assistance for this issue, please ping me.

**Comment by howardjohn** [comment]
I am not sure if there is any settings that a user can pass to run into this, but I was developing some local changes that resulted in not having the jwt mounted. So not a P0

**Comment by howardjohn** [comment]
We have tests now so I think this is resolved
