### ISSUE TITLE
envoyfilter.ApplyClusterPatches panics 

### ISSUE THREAD

**Issue by ayj** [istio/istio#20762]
envoyfilter.ApplyClusterPatches panics with the default configuration using commit 481dd36b2d2388921fdad4fd8bc7ebeb955e873c from the release-1.5 branch. I used the default profile.

```
&reflect.ValueError{Method:"reflect.Value.Type", Kind:0x0} (reflect: call of reflect.Value.Type on zero Value)
```

```bash
$ kubectl get envoyfilters.networking.istio.io --all-namespaces
NAMESPACE      NAME                        AGE
default        tcp-stats-filter-1.5        15m
istio-system   metadata-exchange-1.4       15m
istio-system   metadata-exchange-1.5       15m
istio-system   metadata-exchange-1.6       15m
istio-system   stats-filter-1.4            15m
istio-system   stats-filter-1.5            15m
istio-system   stats-filter-1.6            15m
istio-system   tcp-metadata-exchange-1.5   15m
```

Looks like one of the envoyfilters is invalid. It doesn't get caught during the initial install because the validatingwebhookconfiguration hasn't been created yet.

```bash
error: envoyfilters.networking.istio.io "tcp-metadata-exchange-1.5" could not be patched: admission webhook "validation.istio.io" denied the request: configuration is invalid: 2 errors occurred:
        * Envoy filter: unknown message type "envoy.tcp.metadataexchange.config.MetadataExchange"
        * Envoy filter: unknown message type "envoy.tcp.metadataexchange.config.MetadataExchange"
```

<details>

```
2020-01-31T23:17:02.658579Z     error   Observed a panic: &reflect.ValueError{Method:"reflect.Value.Type", Kind:0x0} (reflect: call of reflect.Value.Type on zero Value)
goroutine 730 [running]:
istio.io/istio/pilot/pkg/util/runtime.logPanic(0x222ae00, 0xc000283a20)
        istio.io/istio@/pilot/pkg/util/runtime/runtime.go:29 +0x6d
istio.io/istio/pilot/pkg/util/runtime.HandleCrash(0xc0015113a8, 0x1, 0x1)
        istio.io/istio@/pilot/pkg/util/runtime/runtime.go:36 +0x48
panic(0x222ae00, 0xc000283a20)
        runtime/panic.go:679 +0x1b2
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
        reflect/value.go:1877 +0x166
github.com/gogo/protobuf/proto.Merge(0x2a18240, 0xc000cf21e0, 0x0, 0x0)
        github.com/gogo/protobuf@v1.3.0/proto/clone.go:88 +0x220
istio.io/istio/pilot/pkg/networking/core/v1alpha3/envoyfilter.ApplyClusterPatches(0x3, 0xc001172480, 0xc001570840, 0xc0011c2c00, 0x2d, 0x40, 0xc0011c2c00, 0x2d, 0x40)
        istio.io/istio@/pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go:63 +0x256
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters(0xc0003a2dc0, 0xc001172480, 0xc001570840, 0x2743af8, 0x29e4a40, 0xc0003a2c40)
        istio.io/istio@/pilot/pkg/networking/core/v1alpha3/cluster.go:137 +0xb5e
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawClusters(0xc0007f0700, 0xc001172480, 0xc001570840, 0xa30903e2c, 0x2651329, 0x13)
        istio.io/istio@/pilot/pkg/proxy/envoy/v2/cds.go:73 +0x63
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds(0xc0007f0700, 0xc000b60480, 0xc001570840, 0xc000ec7b80, 0x17, 0x1, 0xc000a57c38)
        istio.io/istio@/pilot/pkg/proxy/envoy/v2/cds.go:51 +0x83
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushConnection(0xc0007f0700, 0xc000b60480, 0xc00124eaa0, 0x1, 0x1)
        istio.io/istio@/pilot/pkg/proxy/envoy/v2/ads.go:536 +0x6ac
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc0007f0700, 0x2a67b20, 0xc000f7bc60, 0x0, 0x0)
        istio.io/istio@/pilot/pkg/proxy/envoy/v2/ads.go:391 +0x273c
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x2623ee0, 0xc0007f0700, 0x2a58d00, 0xc0011723
c0, 0x40a6878, 0xc0009fd400)
        github.com/envoyproxy/go-control-plane@v0.9.2-0.20200122210702-14108a6abe04/envoy/service/discovery/v2/ads.pb.go:194 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000561e00, 0x2a6e300, 0xc000b72510, 0xc0009fd400, 0xc0008307b0, 0x405aa20, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.26.0/server.go:1237 +0xb42
google.golang.org/grpc.(*Server).handleStream(0xc000561e00, 0x2a6e300, 0xc000b72510, 0xc0009fd400, 0x0)
        google.golang.org/grpc@v1.26.0/server.go:1317 +0xd30
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001400670, 0xc000561e00, 0x2a6e300, 0xc000b72510, 0xc0009fd400)
        google.golang.org/grpc@v1.26.0/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.26.0/server.go:720 +0xa1
```

**Comment by howardjohn** [comment]
@gargnupur

**Comment by gargnupur** [comment]
@ayj : can we get a config dump please? We using TypedStruct so this message should not come...

**Comment by ayj** [comment]
Closing this for now. I haven't been able to reproduce. I'll re-open if it happens again.
