### ISSUE TITLE
TestClientSink flakes

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#21260]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21024/unit-tests_istio/8808

```
=== RUN   TestClientSink
2020-02-19T08:18:27.656232Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.656554Z	info	mcp	New MCP sink stream created
2020-02-19T08:18:27.658256Z	error	mcp	Error receiving MCP resource: non-EOF error
2020-02-19T08:18:27.658335Z	error	mcp	Error receiving MCP response: non-EOF error
2020-02-19T08:18:27.658647Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.658719Z	error	mcp	Failed to create a new MCP sink stream: fake connection error
2020-02-19T08:18:27.658787Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.658828Z	info	mcp	New MCP sink stream created
2020-02-19T08:18:27.659364Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.659421Z	info	mcp	New MCP sink stream created
2020-02-19T08:18:27.660754Z	error	mcp	Error sending MCP request: EOF
2020-02-19T08:18:27.661716Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.661807Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.661957Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.662049Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.662103Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.662186Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.662236Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.662295Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.662343Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.662392Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.662443Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.662501Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.662538Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.662588Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.662676Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.662721Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.662769Z	info	mcp	(re)trying to establish new MCP sink stream
2020-02-19T08:18:27.662818Z	error	mcp	Failed to create a new MCP sink stream: done
2020-02-19T08:18:27.662885Z	info	mcp	(re)trying to establish new MCP sink stream
panic: test timed out after 10m0s
goroutine 28 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0x11c
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x52
```

**Comment by hzxuzhonghu** [comment]
The timeout is caused by sending to the channel blocked.
