### ISSUE TITLE
Egress checks still happening even though Egress is disabled by default on version 1.3.x 

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#21952]
**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ Y] Networking
[ ] Performance and Scalability
[ Y] Policies and Telemetry
[ Y] Security
[ ] Test and Release
[ Y] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Since now egress is disabled by default egress checks should be disabled. 
2 Scenarios 
1>While accessing external ssl it is validating 
```Certificate for <ssm.us-west-2.amazonaws.com> doesn't match any of the subject alternative names: [kms.us-west-2.amazonaws.com, kms-a.us-west-2.amazonaws.com, kms-b.us-west-2.amazonaws.com, kms-c.us-west-2.amazonaws.com, kms-d.us-west-2.amazonaws.com, kms-e.us-west-2.amazonaws.com, kms-f.us-west-2.amazonaws.com, kms-g.us-west-2.amazonaws.com, *.kms.us-west-2.vpce.amazonaws.com]

com.amazonaws.SdkClientException: Unable to execute HTTP request: Certificate for <ssm.us-west-2.amazonaws.com> doesn't match any of the subject alternative names: [kms.us-west-2.amazonaws.com, kms-a.us-west-2.amazonaws.com, kms-b.us-west-2.amazonaws.com, kms-c.us-west-2.amazonaws.com, kms-d.us-west-2.amazonaws.com, kms-e.us-west-2.amazonaws.com, kms-f.us-west-2.amazonaws.com, kms-g.us-west-2.amazonaws.com, *.kms.us-west-2.vpce.amazonaws.com]

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175) ~[aws-java-sdk-core-1.11.651.jar!/:?]

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121) ~[aws-java-sdk-core-1.11.651.jar!/:?]

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.651.jar!/:?]

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.651.jar!/:?]

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726) ~[aws-java-sdk-core-1.11.651.jar!/:?]

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.651.jar!/:?]

	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668) ~[aws-java-sdk-core-1.11.651.jar!/:?]
```

2>
2020-03-06 13:57:57,577 ERROR safePageThread1  Failed to receive message from queueUrl: http://sqs.us-west-2.amazonaws.com/179355710817/DYNQ_ADMIN_2020-03-06_c3e47a66-acfb-48cc-b961-4cb920369685, exception: com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 504; Error Code: 504 Gateway Timeout; Request ID: null)
Calling a SQS leads to this 

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Version 1.3.8

**How was Istio installed?**
helm install
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

Work around was to use the istio annotation 
```
3:24
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0

```

**Comment by pc-rshetty** [comment]
We can close this issue. We had some  left over ServiceEntries etc for egress rule which we had to put in early days of istio on this 1 cluster.
