### ISSUE TITLE
Istio 1.5 prevents all connection attempts to Redis (headless) service

### ISSUE THREAD

**Issue by cober** [istio/istio#21964]
**Bug description**
While everything worked fine, we decided to update Istio to 1.5 on test environment with default profile, however all the microservices that need a connection to Redis (which is in another namespace and doesn't have any Istio sidecar injected) stopped working.

```
Caused by: java.util.concurrent.CompletionException: java.io.IOException: Connection reset by peer
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
        ... 25 more
Caused by: java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1140)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        ... 8 more
```

**Expected behavior**
Pods with injected Istio 1.5 proxy shall be able to establish a connection to a headless service, normal behavior was in all previous versions (ie. 1.4.6)

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (32 proxies), 1.4.5 (1 proxies), 1.2.2 (2 proxies)

Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.12", GitCommit:"4dde8f42b43042db3e662cdd2e707c0f922cae6e", GitTreeState:"clean", BuildDate:"2020-02-13T18:39:12Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Istio 1.5 installation with default profile (istioctl x upgrade)

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE v1.15.9-gke.12

**Comment by howardjohn** [comment]
Can you add the Service spec and a config dump from the client if possible? see https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by cober** [comment]
This is the service that we use for our redis:
```
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-player
  namespace: redis
spec:
  clusterIP: None
  ports:
  - name: client
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: gossip
    port: 16379
    protocol: TCP
    targetPort: 16379
  selector:
    app: redis-cluster-player
  sessionAffinity: None
  type: ClusterIP
```

As well I am attaching config dump.

[config_dump.txt](https://github.com/istio/istio/files/4303257/config_dump.txt)

**Comment by howardjohn** [comment]
We are creating a listener on 0.0.0.0_6379 with filter chain for HTTP and TCP. The TCP one routes to another redis service on the same port. @hzxuzhonghu @yxue I thought we fixed this so there were no conflicts now?

@cober are there and instances of redis-cluster-player? Check `kubectl get endpoints -n redis`

**Comment by cober** [comment]
@howardjohn 

```
NAME                   ENDPOINTS                                                       AGE
redis-cluster-player   10.16.10.10:6379,10.16.11.10:6379,10.16.3.29:6379 + 9 more...   243d
redis-cluster-xiam     10.16.10.16:6379,10.16.11.11:6379,10.16.3.28:6379 + 9 more...   243d
```

**Comment by howardjohn** [comment]
For now a workaround is to rename the port name on both of those services to `tcp` or disable auto detection: https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection

I am pretty sure this will fix this issue, not sure yet what the root cause is.

**Comment by cober** [comment]
@howardjohn is there by any chance an issue where we can't set both values `values.pilot.enableProtocolSniffingForOutbound=false` and `values.pilot.enableProtocolSniffingForInbound=false` at the same time?

I tried with `istioctl apply manifest --set...` and as well to generate the yaml prior that and put it to false there, but `istioctl profile dump` shows

```
    pilot:
      appNamespaces: []
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      configNamespace: istio-config
      cpu:
        targetAverageUtilization: 80
      enableProtocolSniffingForInbound: false
      enableProtocolSniffingForOutbound: true
```

I tried as well to rename both svc name to `tcp` and `tcp2` (K8s doesn't allow to have the same name)

As a result, some of our services were able to connect to redis, however few of them are still failing. Not sure if I want to restart those working ones, since I am not sure if they will be able to connect back.

**Comment by howardjohn** [comment]
> I tried as well to rename both svc name to tcp and tcp2 (K8s doesn't allow to have the same name)

Sorry I meant the port name. Like
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-other
  namespace: redis
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: gossip
    port: 16379
    protocol: TCP
    targetPort: 16379
  selector:
    app: httpbin
  sessionAffinity: None
  type: ClusterIP
```

youll specifically want `enableProtocolSniffingForOutbound` to be false. Either that or the service port rename - you need one or the other (both works as well)

**Comment by cober** [comment]
@howardjohn I have tried with renaming svc name, but no success for us.

Can you confirm that `istioctl manifest apply --set values.pilot.enableProtocolSniffingForOutbound=false` works as intended from your side?

After few attempts it seems I just can't change this value.

```
      enableProtocolSniffingForInbound: false
      enableProtocolSniffingForOutbound: true
```

**Comment by howardjohn** [comment]
`profile dump` doesn't show what you have applied in the cluster, it just shows what the defaults are. 

> @howardjohn I have tried with renaming svc name, but no success for us.

Are you reaming the service name or the port name? Can you paste the new Service?

Can you also paste the pilot deloyment, and I can check ifthe sniffing was set correctly. It should impact a pilot environment variable

**Comment by cober** [comment]
@howardjohn 

```
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-player
  namespace: redis
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: gossip
    port: 16379
    protocol: TCP
    targetPort: 16379
  selector:
    app: redis-cluster-player
  sessionAffinity: None
  type: ClusterIP
```

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"istiod","istio":"pilot","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.5.0","release":"istio"},"name":"istiod","namespace":"istio-system"},"spec":{"selector":{"matchLabels":{"istio":"pilot"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":"25%"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"labels":{"app":"istiod","istio":"pilot"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["ppc64le"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["s390x"]}]},"weight":2}],"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64","ppc64le","s390x"]}]}]}}},"containers":[{"args":["discovery","--monitoringAddr=:15014","--log_output_level=default:info","--domain","cluster.local","--secureGrpcAddr=:15011","--trust-domain=cluster.local","--keepaliveMaxServerConnectionAge","30m","--disable-install-crds=true"],"env":[{"name":"JWT_POLICY","value":"third-party-jwt"},{"name":"PILOT_CERT_PROVIDER","value":"istiod"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"SERVICE_ACCOUNT","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.serviceAccountName"}}},{"name":"PILOT_TRACE_SAMPLING","value":"1"},{"name":"CONFIG_NAMESPACE","value":"istio-config"},{"name":"PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND","value":"false"},{"name":"PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND","value":"false"},{"name":"INJECTION_WEBHOOK_CONFIG_NAME","value":"istio-sidecar-injector"},{"name":"ISTIOD_ADDR","value":"istiod.istio-system.svc:15012"},{"name":"PILOT_EXTERNAL_GALLEY","value":"false"}],"envFrom":[{"configMapRef":{"name":"istiod","optional":true}}],"image":"docker.io/istio/pilot:1.5.0","imagePullPolicy":"IfNotPresent","name":"discovery","ports":[{"containerPort":8080},{"containerPort":15010},{"containerPort":15017}],"readinessProbe":{"httpGet":{"path":"/ready","port":8080},"initialDelaySeconds":5,"periodSeconds":5,"timeoutSeconds":5},"resources":{"requests":{"cpu":"500m","memory":"2048Mi"}},"securityContext":{"capabilities":{"drop":["ALL"]},"runAsGroup":1337,"runAsNonRoot":true,"runAsUser":1337},"volumeMounts":[{"mountPath":"/etc/istio/config","name":"config-volume"},{"mountPath":"/var/run/secrets/tokens","name":"istio-token","readOnly":true},{"mountPath":"/var/run/secrets/istio-dns","name":"local-certs"},{"mountPath":"/etc/cacerts","name":"cacerts","readOnly":true},{"mountPath":"/var/lib/istio/inject","name":"inject","readOnly":true},{"mountPath":"/var/lib/istio/local","name":"istiod","readOnly":true}]}],"securityContext":{"fsGroup":1337},"serviceAccountName":"istiod-service-account","volumes":[{"emptyDir":{"medium":"Memory"},"name":"local-certs"},{"name":"istio-token","projected":{"sources":[{"serviceAccountToken":{"audience":"istio-ca","expirationSeconds":43200,"path":"istio-token"}}]}},{"configMap":{"name":"istiod","optional":true},"name":"istiod"},{"name":"cacerts","secret":{"optional":true,"secretName":"cacerts"}},{"configMap":{"name":"istio-sidecar-injector","optional":true},"name":"inject"},{"configMap":{"name":"istio"},"name":"config-volume"},{"configMap":{"name":"pilot-envoy-config"},"name":"pilot-envoy-config"}]}}}}
  creationTimestamp: "2020-03-08T17:53:24Z"
  generation: 15
  labels:
    app: istiod
    istio: pilot
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.5.0
    release: istio
  name: istiod
  namespace: istio-system
  resourceVersion: "231522118"
  selfLink: /apis/extensions/v1beta1/namespaces/istio-system/deployments/istiod
  uid: 3940eaf7-0e13-45ed-bc87-644ba43ac0e9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      istio: pilot
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: istiod
        istio: pilot
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - discovery
        - --monitoringAddr=:15014
        - --log_output_level=default:info
        - --domain
        - cluster.local
        - --secureGrpcAddr=:15011
        - --trust-domain=cluster.local
        - --keepaliveMaxServerConnectionAge
        - 30m
        - --disable-install-crds=true
        env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: PILOT_TRACE_SAMPLING
          value: "1"
        - name: CONFIG_NAMESPACE
          value: istio-config
        - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND
          value: "false"
        - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
          value: "false"
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: istio-sidecar-injector
        - name: ISTIOD_ADDR
          value: istiod.istio-system.svc:15012
        - name: PILOT_EXTERNAL_GALLEY
          value: "false"
        envFrom:
        - configMapRef:
            name: istiod
            optional: true
        image: docker.io/istio/pilot:1.5.0
        imagePullPolicy: IfNotPresent
        name: discovery
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 15010
          protocol: TCP
        - containerPort: 15017
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio/config
          name: config-volume
        - mountPath: /var/run/secrets/tokens
          name: istio-token
          readOnly: true
        - mountPath: /var/run/secrets/istio-dns
          name: local-certs
        - mountPath: /etc/cacerts
          name: cacerts
          readOnly: true
        - mountPath: /var/lib/istio/inject
          name: inject
          readOnly: true
        - mountPath: /var/lib/istio/local
          name: istiod
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1337
      serviceAccount: istiod-service-account
      serviceAccountName: istiod-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: local-certs
      - name: istio-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - configMap:
          defaultMode: 420
          name: istiod
          optional: true
        name: istiod
      - name: cacerts
        secret:
          defaultMode: 420
          optional: true
          secretName: cacerts
      - configMap:
          defaultMode: 420
          name: istio-sidecar-injector
          optional: true
        name: inject
      - configMap:
          defaultMode: 420
          name: istio
        name: config-volume
      - configMap:
          defaultMode: 420
          name: pilot-envoy-config
        name: pilot-envoy-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-08T18:21:48Z"
    lastUpdateTime: "2020-03-08T18:21:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-08T17:53:24Z"
    lastUpdateTime: "2020-03-08T18:29:07Z"
    message: ReplicaSet "istiod-57555858" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by howardjohn** [comment]
Hm that looks right, maybe it's another issue. Mind attaching another
config dump with the new changes you have done so far?

**Comment by cober** [comment]
@howardjohn sure, there you go.

[config_dump2.txt](https://github.com/istio/istio/files/4303794/config_dump2.txt)

**Comment by hzxuzhonghu** [comment]
Can you also dump the configs of redis instance？

**Comment by hzxuzhonghu** [comment]
Another point, i can see you have more than 10 endpoints for redis-cluster-player service, but i can only see only 6 outbound listeners for it.

**Comment by howardjohn** [comment]
I think redis does not have a sidecar

**Comment by hzxuzhonghu** [comment]
```
     "cluster": {
      "@type": "type.googleapis.com/envoy.api.v2.Cluster",
      "name": "outbound|6379||redis-cluster-player.redis.svc.cluster.local",
      "type": "ORIGINAL_DST",
      "connect_timeout": "1s",
      "lb_policy": "CLUSTER_PROVIDED",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295
        }
       ]
      },
      "transport_socket": {
       "name": "envoy.transport_sockets.tls",
       "typed_config": {
        "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
        "common_tls_context": {
         "alpn_protocols": [
          "istio-peer-exchange",
          "istio"
         ],
         "tls_certificate_sds_secret_configs": [
          {
           "name": "default",
           "sds_config": {
            "api_config_source": {
             "api_type": "GRPC",
             "grpc_services": [
              {
               "envoy_grpc": {
                "cluster_name": "sds-grpc"
               }
              }
             ]
            }
           }
          }
         ],
         "combined_validation_context": {
          "default_validation_context": {
           "verify_subject_alt_name": [
            "spiffe://cluster.local/ns/redis/sa/default"
           ]
          },
          "validation_context_sds_secret_config": {
           "name": "ROOTCA",
           "sds_config": {
            "api_config_source": {
             "api_type": "GRPC",
             "grpc_services": [
              {
               "envoy_grpc": {
                "cluster_name": "sds-grpc"
               }
              }
             ]
            }
           }
          }
         }
        },
        "sni": "outbound_.6379_._.redis-cluster-player.redis.svc.cluster.local"
       }
      },
      "filters": [
       {
        "name": "envoy.filters.network.upstream.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
         "type_url": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "value": {
          "protocol": "istio-peer-exchange"
         }
        }
       }
      ]
     },
```

Here pilot generates cluster with tls initiated, definitely can not work with redis without sidecar injected

**Comment by hzxuzhonghu** [comment]
@diemtvu @incfly   I think this is introduced since autoMTLS.

**Comment by hzxuzhonghu** [comment]
We should disable tls for headless service by default when mtlsCtx is `autoDetected`, as we donot know whether there is sidecar injected for its instances.

**Comment by howardjohn** [comment]
why don't we know if it has sidecar? we should be able to since we create
listener per instance right? We would just need to change the
implementation to set this up right?

Or is this using original dst?

**Comment by hzxuzhonghu** [comment]
It is original dst

**Comment by incfly** [comment]
>  We should disable tls for headless service by default when mtlsCtx is autoDetected, as we donot know whether there is sidecar injected for its instances.

to be clear, I though you already made the change on the client side to no set transport socket match in case of a headless service? or based on the above config dump, it seems like

`when headless && auto mtls enabled, set transport_socket, rather than transport_socket_match`? we need to check.

if so, we have two choices really for headless

- default to plaintext, users manually explicit use DestinationRule for headless. document in auto mtls clearly this is not encrypted by default to prevent false illusion
- default to mtls on client side (transport_socket), and user need to do more work to disable.

a matter of which situation we are in favor of.

**Comment by incfly** [comment]
@cober would you mind quickly try using DestinationRule.trafficPolicy.Tls == DISABLE against Redis service see if fix the issue?

**Comment by hzxuzhonghu** [comment]
>default to plaintext, users manually explicit use DestinationRule for headless. document in auto mtls clearly this is not encrypted by default to prevent false illusion

+1, we should not influence normal connection even when sidecar injected.

**Comment by cober** [comment]
@hzxuzhonghu we don't have any istio sidecar injected into redis cluster, on other side 12 endpoints could be consisted of 6 pod instances (statefulset) and each one consists of 2 endpoints (client & gossip protocol)

@incfly 

Are you suggesting to try something like this?

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-disable-mtls
spec:
  host: redis-cluster-player-0.redis-cluster-player.redis.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

**Comment by hzxuzhonghu** [comment]
@cober I am clear about your access model now. Can you try #21987? I believe it can solve your problem as well

**Comment by cober** [comment]
@hzxuzhonghu Actually this one worked for us! I am leaving a comment on PR as well.

**Comment by suvl** [comment]
@cober 's solution also worked for my, but in this case for Kafka behind a headless service.

**Comment by hzxuzhonghu** [comment]
As the pr reverted

**Comment by rajsenthil** [comment]
> redis-cluster-player.redis.svc.cluster.local
>   trafficPolicy:

@cober I am also in the same situation. How did you solve it? I tried to look into  [#21987](https://github.com/istio/istio/pull/21987) but could not understand complete.

I have the redis-cluster running on port 6379(under namespace core-service) and could connect to it inside kubenetes cluster from Service A(under namespace `app-service`). 
redis-cluster and Service A are under different namespaces. 
This works as it is. Now when istio-injuection=enable for Service A(under namespace `app-service`), the connection problem occurs with execption `Connection reset by peer`. 

Following this thread, I applied 
`apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-all-ports
  namespace: app-service
spec:
  host: redis-redis-cluster.divvet-dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
`
and still the problem exsists.

**Comment by rajsenthil** [comment]
For now, I downgraded to 1.5.0 and currently working as expected.

**Comment by cober** [comment]
@rajsenthil you can use something like that:
`apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "mtls-disable"
  namespace: "redis"
spec:
  mtls:
    mode: DISABLE`

**Comment by lucbas** [comment]
Just saw at the bottom of the 1.6.6 release notes that this is fixed, is it working for you?

[https://istio.io/latest/news/releases/1.6.x/announcing-1.6.6/](https://istio.io/latest/news/releases/1.6.x/announcing-1.6.6/))

**Comment by rajsenthil** [comment]
> For now, I downgraded to 1.5.0 and currently working as expected.

An update, I am now using 1.7 version and it works as expected without any workaround.
