### ISSUE TITLE
"make push" sometimes fail on istio-presubmit

### ISSUE THREAD

**Issue by jmuk** [istio/istio#2219]
istio-presubmit seems to fail randomly on "make push", and the test log reports to say `no such package "@libssl1.0.0//file"`. More detailed error from https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/2191/istio-presubmit/1460/:

```
W1217 02:55:19.617] ERROR: /home/bootstrap/go/src/istio.io/istio/mixer/docker/BUILD:30:1: no such package '@libssl1.0.0//file': dpkg_parser command failed: Traceback (most recent call last):
W1217 02:55:19.617]   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
W1217 02:55:19.618]     "__main__", fname, loader, pkg_name)
W1217 02:55:19.619]   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
W1217 02:55:19.619]     exec code in run_globals
W1217 02:55:19.620]   File "/home/bootstrap/.cache/bazel/_bazel_bootstrap/4b9f6c50a056554ffa68683f64a2c905/external/dpkg_parser/file/dpkg_parser.par/__main__.py", line 114, in <module>
W1217 02:55:19.621]   File "/home/bootstrap/.cache/bazel/_bazel_bootstrap/4b9f6c50a056554ffa68683f64a2c905/external/dpkg_parser/file/dpkg_parser.par/__main__.py", line 55, in main
W1217 02:55:19.622]   File "/home/bootstrap/.cache/bazel/_bazel_bootstrap/4b9f6c50a056554ffa68683f64a2c905/external/dpkg_parser/file/dpkg_parser.par/__main__.py", line 67, in download_dpkg
W1217 02:55:19.622]   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
W1217 02:55:19.622]     return opener.open(url, data, timeout)
W1217 02:55:19.622]   File "/usr/lib/python2.7/urllib2.py", line 435, in open
W1217 02:55:19.623]     response = meth(req, response)
W1217 02:55:19.623]   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
W1217 02:55:19.624]     'http', request, response, code, msg, hdrs)
W1217 02:55:19.624]   File "/usr/lib/python2.7/urllib2.py", line 467, in error
W1217 02:55:19.625]     result = self._call_chain(*args)
W1217 02:55:19.625]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
W1217 02:55:19.625]     result = func(*args)
W1217 02:55:19.626]   File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
W1217 02:55:19.626]     return self.parent.open(new, timeout=req.timeout)
W1217 02:55:19.626]   File "/usr/lib/python2.7/urllib2.py", line 435, in open
W1217 02:55:19.626]     response = meth(req, response)
W1217 02:55:19.627]   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
W1217 02:55:19.627]     'http', request, response, code, msg, hdrs)
W1217 02:55:19.627]   File "/usr/lib/python2.7/urllib2.py", line 473, in error
W1217 02:55:19.627]     return self._call_chain(*args)
W1217 02:55:19.628]   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
W1217 02:55:19.628]     result = func(*args)
W1217 02:55:19.628]   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
W1217 02:55:19.629]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
W1217 02:55:19.629] urllib2.HTTPError: HTTP Error 404: Not Found
W1217 02:55:19.629]  (/home/bootstrap/.cache/bazel/_bazel_bootstrap/4b9f6c50a056554ffa68683f64a2c905/external/dpkg_parser/file/dpkg_parser.par --packages-file /home/bootstrap/.cache/bazel/_bazel_bootstrap/4b9f6c50a056554ffa68683f64a2c905/external/debian_jessie/file/Packages.json --package-name libssl1.0.0) and referenced by '//mixer/docker:mixer'.
W1217 02:55:19.764] ERROR: Analysis of target '//mixer/docker:mixer' failed; build aborted.
```

It's still unclear to me why this happens randomly.

**Comment by christian-posta** [comment]
Seeing the same thing building locally against 0.4.0 release

**Comment by mandarjog** [comment]
This bazel target is no longer in use.
It has been replaced by plain docker file build.
