### ISSUE TITLE
istio-pilot panic when adding a serviceentry

### ISSUE THREAD

**Issue by btoonk** [istio/istio#22393]
**Bug description**

When adding a specific serviceentry the discovery container in istio-pilot stops with a panic

[ x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
istio-pilots discovery container keeps running.

**Steps to reproduce the bug**
Currently this only happens in one of our setups.
I'm unable to reproduce this issue in our test setup

Adding the following service entry:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-se
spec:
  hosts:
  - test.host.com
  ports:
  - name: tcp
    number: 6379
    protocol: tcp
  resolution: DNS
  location: MESH_EXTERNAL
```

This results in the following log message in the istio-pilot discover container:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x184a244]

goroutine 462 [running]:
istio.io/istio/pilot/pkg/networking/core/v1alpha3.isFallthroughFilterChain(...)
	istio.io/istio@/pilot/pkg/networking/core/v1alpha3/listener.go:2247
istio.io/istio/pilot/pkg/networking/core/v1alpha3.mergeTCPFilterChains(0xc0003f7d90, 0x2, 0x2, 0xc000f542a0, 0xc000e70980, 0xc, 0xc000ea5308, 0xc000618000, 0x1, 0x1, ...)
	istio.io/istio@/pilot/pkg/networking/core/v1alpha3/listener.go:2083 +0x634
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarOutboundListenerForPortOrUDS(0xc000254b20, 0xc000618000, 0xc000682b40, 0xc000618000, 0x3398ee0, 0x0, 0x0, 0xc0009d8060, 0x1, 0x1, ...)
	istio.io/istio@/pilot/pkg/networking/core/v1alpha3/listener.go:1427 +0x1475
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarOutboundListeners(0xc000254b20, 0xc000682b40, 0xc000618000, 0xc000e427e0, 0x0, 0x0, 0x0)
	istio.io/istio@/pilot/pkg/networking/core/v1alpha3/listener.go:909 +0x96f
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ListenerBuilder).buildSidecarOutboundListeners(...)
	istio.io/istio@/pilot/pkg/networking/core/v1alpha3/listener_builder.go:201
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarListeners(0xc000254b20, 0xc000682b40, 0xc000618000, 0xc000e427e0, 0xc000ea5650, 0xc000874580)
	istio.io/istio@/pilot/pkg/networking/core/v1alpha3/listener.go:304 +0xc6
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildListeners(0xc000254b20, 0xc000682b40, 0xc000618000, 0xc000e427e0, 0xc000ea5810, 0x4407d6, 0xc0006fe120)
	istio.io/istio@/pilot/pkg/networking/core/v1alpha3/listener.go:284 +0x16e
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawListeners(0xc0004c0750, 0xc00028a180, 0xc000e427e0, 0xc0008ab660, 0x1fff760, 0x339a1e0)
	istio.io/istio@/pilot/pkg/proxy/envoy/v2/lds.go:49 +0x6f
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushLds(0xc0004c0750, 0xc00028a180, 0xc000e427e0, 0xc000693600, 0x16, 0x2, 0x0)
	istio.io/istio@/pilot/pkg/proxy/envoy/v2/lds.go:29 +0x7c
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc0004c0750, 0x227ee80, 0xc0002da090, 0x0, 0x0)
	istio.io/istio@/pilot/pkg/proxy/envoy/v2/ads.go:270 +0xbfb
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1ef7b80, 0xc0004c0750, 0x22730c0, 0xc00068da40, 0x3398ee0, 0xc000712600)
	github.com/envoyproxy/go-control-plane@v0.9.1-0.20191002184426-9d865299d2ff/envoy/service/discovery/v2/ads.pb.go:181 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0004a5080, 0x2283ec0, 0xc000554c00, 0xc000712600, 0xc000686b70, 0x3357ce0, 0xc000b94040, 0x0, 0x0)
	google.golang.org/grpc@v1.24.0/server.go:1199 +0xb2e
google.golang.org/grpc.(*Server).handleStream(0xc0004a5080, 0x2283ec0, 0xc000554c00, 0xc000712600, 0xc000b94040)
	google.golang.org/grpc@v1.24.0/server.go:1279 +0xd30
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000bc0070, 0xc0004a5080, 0x2283ec0, 0xc000554c00, 0xc000712600)
	google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.24.0/server.go:708 +0xa1
```

Maybe related:
We  do have other services running on this port (6379) also one specified as a http service.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.6

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by btoonk** [comment]
Ok that's great. We can then close this issue.
