### ISSUE TITLE
Pilot v1.5.2: SIGSEGV on startup when calling security/pkg/pki/ca.(*IstioCA).GetCAKeyCertBundle(...)

### ISSUE THREAD

**Issue by gnz00** [istio/istio#23278]
When trying to run docker-compose examples from the Consul integration, https://github.com/istio/istio/blob/master/install/consul/templates/istio.yaml.tmpl, Pilot crashes with the following stacktrace.

```
pilot_1                    | 2020-04-26T02:52:31.612350Z	info	FLAG: --appNamespace=""
pilot_1                    | 2020-04-26T02:52:31.612420Z	info	FLAG: --clusterRegistriesNamespace=""
pilot_1                    | 2020-04-26T02:52:31.612441Z	info	FLAG: --configDir=""
pilot_1                    | 2020-04-26T02:52:31.612462Z	info	FLAG: --consulserverURL="http://consul-agent-2:8500"
pilot_1                    | 2020-04-26T02:52:31.612478Z	info	FLAG: --ctrlz_address="localhost"
pilot_1                    | 2020-04-26T02:52:31.612501Z	info	FLAG: --ctrlz_port="9876"
pilot_1                    | 2020-04-26T02:52:31.612545Z	info	FLAG: --disable-install-crds="true"
pilot_1                    | 2020-04-26T02:52:31.612625Z	info	FLAG: --domain="cluster.local"
pilot_1                    | 2020-04-26T02:52:31.612648Z	info	FLAG: --grpcAddr=":15010"
pilot_1                    | 2020-04-26T02:52:31.612663Z	info	FLAG: --help="false"
pilot_1                    | 2020-04-26T02:52:31.612682Z	info	FLAG: --httpAddr=":15007"
pilot_1                    | 2020-04-26T02:52:31.612778Z	info	FLAG: --httpsAddr=":15017"
pilot_1                    | 2020-04-26T02:52:31.612823Z	info	FLAG: --keepaliveInterval="30s"
pilot_1                    | 2020-04-26T02:52:31.613015Z	info	FLAG: --keepaliveMaxServerConnectionAge="2562047h47m16.854775807s"
pilot_1                    | 2020-04-26T02:52:31.613038Z	info	FLAG: --keepaliveTimeout="10s"
pilot_1                    | 2020-04-26T02:52:31.613058Z	info	FLAG: --kubeconfig="/etc/istio/config/kubeconfig"
pilot_1                    | 2020-04-26T02:52:31.613148Z	info	FLAG: --log_as_json="false"
pilot_1                    | 2020-04-26T02:52:31.613194Z	info	FLAG: --log_caller=""
pilot_1                    | 2020-04-26T02:52:31.613292Z	info	FLAG: --log_output_level="default:info"
pilot_1                    | 2020-04-26T02:52:31.613318Z	info	FLAG: --log_rotate=""
pilot_1                    | 2020-04-26T02:52:31.613343Z	info	FLAG: --log_rotate_max_age="30"
pilot_1                    | 2020-04-26T02:52:31.613704Z	info	FLAG: --log_rotate_max_backups="1000"
pilot_1                    | 2020-04-26T02:52:31.613722Z	info	FLAG: --log_rotate_max_size="104857600"
pilot_1                    | 2020-04-26T02:52:31.614063Z	info	FLAG: --log_stacktrace_level="default:none"
pilot_1                    | 2020-04-26T02:52:31.614323Z	info	FLAG: --log_target="[stdout]"
pilot_1                    | 2020-04-26T02:52:31.614532Z	info	FLAG: --mcpInitialConnWindowSize="1048576"
pilot_1                    | 2020-04-26T02:52:31.614912Z	info	FLAG: --mcpInitialWindowSize="1048576"
pilot_1                    | 2020-04-26T02:52:31.615180Z	info	FLAG: --mcpMaxMsgSize="4194304"
pilot_1                    | 2020-04-26T02:52:31.615206Z	info	FLAG: --meshConfig="/etc/istio/config/mesh"
pilot_1                    | 2020-04-26T02:52:31.615294Z	info	FLAG: --monitoringAddr=":15014"
pilot_1                    | 2020-04-26T02:52:31.615512Z	info	FLAG: --namespace=""
pilot_1                    | 2020-04-26T02:52:31.615543Z	info	FLAG: --networksConfig="/etc/istio/config/meshNetworks"
pilot_1                    | 2020-04-26T02:52:31.615705Z	info	FLAG: --plugins="[authn,authz,health,mixer]"
pilot_1                    | 2020-04-26T02:52:31.615765Z	info	FLAG: --profile="true"
pilot_1                    | 2020-04-26T02:52:31.616084Z	info	FLAG: --registries="[Consul]"
pilot_1                    | 2020-04-26T02:52:31.616117Z	info	FLAG: --resync="1m0s"
pilot_1                    | 2020-04-26T02:52:31.616204Z	info	FLAG: --secureGrpcAddr=":15011"
pilot_1                    | 2020-04-26T02:52:31.616594Z	info	FLAG: --trust-domain=""
pilot_1                    | 2020-04-26T02:52:31.616688Z	info	Primary Cluster name:
pilot_1                    | 2020-04-26T02:52:31.620123Z	info	mesh configuration: {
pilot_1                    |     "disablePolicyChecks": true,
pilot_1                    |     "proxyListenPort": 15001,
pilot_1                    |     "connectTimeout": "1s",
pilot_1                    |     "protocolDetectionTimeout": "0.100s",
pilot_1                    |     "ingressService": "istio-ingressgateway",
pilot_1                    |     "enableTracing": true,
pilot_1                    |     "accessLogFile": "/dev/stdout",
pilot_1                    |     "defaultConfig": {
pilot_1                    |         "configPath": "/etc/istio/proxy",
pilot_1                    |         "binaryPath": "/usr/local/bin/envoy",
pilot_1                    |         "serviceCluster": "istio-proxy",
pilot_1                    |         "drainDuration": "45s",
pilot_1                    |         "parentShutdownDuration": "60s",
pilot_1                    |         "discoveryAddress": "istio-pilot:15010",
pilot_1                    |         "connectTimeout": "1s",
pilot_1                    |         "proxyAdminPort": 15000,
pilot_1                    |         "statNameLength": 189,
pilot_1                    |         "envoyAccessLogService": {
pilot_1                    |
pilot_1                    |         },
pilot_1                    |         "envoyMetricsService": {
pilot_1                    |
pilot_1                    |         }
pilot_1                    |     },
pilot_1                    |     "outboundTrafficPolicy": {
pilot_1                    |         "mode": "ALLOW_ANY"
pilot_1                    |     },
pilot_1                    |     "enableAutoMtls": false,
pilot_1                    |     "trustDomainAliases": [
pilot_1                    |     ],
pilot_1                    |     "defaultServiceExportTo": [
pilot_1                    |         "*"
pilot_1                    |     ],
pilot_1                    |     "defaultVirtualServiceExportTo": [
pilot_1                    |         "*"
pilot_1                    |     ],
pilot_1                    |     "defaultDestinationRuleExportTo": [
pilot_1                    |         "*"
pilot_1                    |     ],
pilot_1                    |     "rootNamespace": "istio-system",
pilot_1                    |     "dnsRefreshRate": "5s"
pilot_1                    | }
pilot_1                    | 2020-04-26T02:52:31.620269Z	info	version: 1.5.2-68d381dde45b34f82a7247f20840829f1ee56fc1-Clean
pilot_1                    | 2020-04-26T02:52:31.624830Z	info	flags: {
pilot_1                    |    "DiscoveryOptions": {
pilot_1                    |       "HTTPAddr": ":15007",
pilot_1                    |       "HTTPSAddr": ":15017",
pilot_1                    |       "GrpcAddr": ":15010",
pilot_1                    |       "SecureGrpcAddr": ":15011",
pilot_1                    |       "SecureGrpcDNSAddr": "",
pilot_1                    |       "MonitoringAddr": ":15014",
pilot_1                    |       "EnableProfiling": true
pilot_1                    |    },
pilot_1                    |    "InjectionOptions": {
pilot_1                    |       "InjectionDirectory": "./var/lib/istio/inject"
pilot_1                    |    },
pilot_1                    |    "PodName": "",
pilot_1                    |    "Namespace": "",
pilot_1                    |    "Revision": "",
pilot_1                    |    "ServiceAccountName": "",
pilot_1                    |    "Mesh": {
pilot_1                    |       "ConfigFile": "/etc/istio/config/mesh",
pilot_1                    |       "MixerAddress": ""
pilot_1                    |    },
pilot_1                    |    "Config": {
pilot_1                    |       "ControllerOptions": {
pilot_1                    |          "WatchedNamespace": "",
pilot_1                    |          "ResyncPeriod": 60000000000,
pilot_1                    |          "DomainSuffix": "cluster.local",
pilot_1                    |          "ClusterID": "",
pilot_1                    |          "Metrics": null,
pilot_1                    |          "XDSUpdater": null,
pilot_1                    |          "TrustDomain": "",
pilot_1                    |          "NetworksWatcher": null,
pilot_1                    |          "EndpointMode": 0
pilot_1                    |       },
pilot_1                    |       "ClusterRegistriesNamespace": "istio-system",
pilot_1                    |       "KubeConfig": "/etc/istio/config/kubeconfig",
pilot_1                    |       "FileDir": "",
pilot_1                    |       "DistributionCacheRetention": 60000000000,
pilot_1                    |       "DisableInstallCRDs": true,
pilot_1                    |       "DistributionTrackingEnabled": true
pilot_1                    |    },
pilot_1                    |    "Service": {
pilot_1                    |       "Registries": [
pilot_1                    |          "Consul"
pilot_1                    |       ],
pilot_1                    |       "Consul": {
pilot_1                    |          "ServerURL": "http://consul-agent-2:8500"
pilot_1                    |       }
pilot_1                    |    },
pilot_1                    |    "MeshConfig": null,
pilot_1                    |    "NetworksConfigFile": "/etc/istio/config/meshNetworks",
pilot_1                    |    "CtrlZOptions": {
pilot_1                    |       "Port": 9876,
pilot_1                    |       "Address": "localhost"
pilot_1                    |    },
pilot_1                    |    "Plugins": [
pilot_1                    |       "authn",
pilot_1                    |       "authz",
pilot_1                    |       "health",
pilot_1                    |       "mixer"
pilot_1                    |    ],
pilot_1                    |    "MCPMaxMessageSize": 4194304,
pilot_1                    |    "MCPInitialWindowSize": 1048576,
pilot_1                    |    "MCPInitialConnWindowSize": 1048576,
pilot_1                    |    "KeepaliveOptions": {
pilot_1                    |       "Time": 30000000000,
pilot_1                    |       "Timeout": 10000000000,
pilot_1                    |       "MaxServerConnectionAge": 9223372036854775807,
pilot_1                    |       "MaxServerConnectionAgeGrace": 10000000000
pilot_1                    |    },
pilot_1                    |    "ForceStop": false,
pilot_1                    |    "BasePort": 15000
pilot_1                    | }
pilot_1                    | 2020-04-26T02:52:31.625026Z	info	failed to read mesh networks configuration from "/etc/istio/config/meshNetworks": cannot read networks config file open /etc/istio/config/meshNetworks: no such file or directory
pilot_1                    | 2020-04-26T02:52:31.625068Z	info	mesh networks configuration not provided
pilot_1                    | 2020-04-26T02:52:31.625088Z	info	No certificates specified, skipping DNS certificate controller
pilot_1                    | 2020-04-26T02:52:31.651724Z	info	CRD controller watching namespaces ""
pilot_1                    | 2020-04-26T02:52:31.653313Z	info	Adding Consul registry adapter
pilot_1                    | 2020-04-26T02:52:31.653372Z	info	Consul url: http://consul-agent-2:8500
pilot_1                    | 2020-04-26T02:52:31.653418Z	info	JWT policy is third-party-jwt
pilot_1                    | 2020-04-26T02:52:31.653561Z	warn	kubeclient is nil; disable the K8S CA functionality
pilot_1                    | 2020-04-26T02:52:31.655226Z	info	Generating a certificate for secure gRPC (/)
pilot_1                    | panic: runtime error: invalid memory address or nil pointer dereference
pilot_1                    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1f929ec]
pilot_1                    |
pilot_1                    | goroutine 1 [running]:
pilot_1                    | istio.io/istio/security/pkg/pki/ca.(*IstioCA).GetCAKeyCertBundle(...)
pilot_1                    | 	istio.io/istio@/security/pkg/pki/ca/ca.go:320
pilot_1                    | istio.io/istio/pilot/pkg/bootstrap.(*Server).generateKeyAndCert(0xc000107860, 0x0, 0x0, 0x0, 0x0, 0x203000, 0x80, 0x0, 0x203000, 0x203000, ...)
pilot_1                    | 	istio.io/istio@/pilot/pkg/bootstrap/server.go:583 +0x13c
pilot_1                    | istio.io/istio/pilot/pkg/bootstrap.(*Server).getSpiffeeCert(0xc000107860, 0x0, 0x0, 0x0, 0x0, 0x40c1b6, 0xc000204a20, 0xe0, 0xd8, 0x0, ...)
pilot_1                    | 	istio.io/istio@/pilot/pkg/bootstrap/server.go:619 +0x75d
pilot_1                    | istio.io/istio/pilot/pkg/bootstrap.(*Server).initSecureGrpcServer(0xc000107860, 0xc0005a39e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
pilot_1                    | 	istio.io/istio@/pilot/pkg/bootstrap/server.go:634 +0x74
pilot_1                    | istio.io/istio/pilot/pkg/bootstrap.(*Server).initDiscoveryService(0xc000107860, 0x40ed8c0, 0x0, 0x0)
pilot_1                    | 	istio.io/istio@/pilot/pkg/bootstrap/server.go:487 +0x43c
pilot_1                    | istio.io/istio/pilot/pkg/bootstrap.NewServer(0x40ed8c0, 0x0, 0xc0006283c0, 0x4)
pilot_1                    | 	istio.io/istio@/pilot/pkg/bootstrap/server.go:259 +0xe6d
pilot_1                    | main.glob..func1(0x40ee240, 0xc000648c00, 0x0, 0x8, 0x0, 0x0)
pilot_1                    | 	istio.io/istio@/pilot/cmd/pilot-discovery/main.go:83 +0xef
pilot_1                    | github.com/spf13/cobra.(*Command).execute(0x40ee240, 0xc000648a80, 0x8, 0x8, 0x40ee240, 0xc000648a80)
pilot_1                    | 	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
pilot_1                    | github.com/spf13/cobra.(*Command).ExecuteC(0x40edfc0, 0x0, 0x0, 0x0)
pilot_1                    | 	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
pilot_1                    | github.com/spf13/cobra.(*Command).Execute(...)
pilot_1                    | 	github.com/spf13/cobra@v0.0.5/command.go:864
pilot_1                    | main.main()
pilot_1                    | 	istio.io/istio@/pilot/cmd/pilot-discovery/main.go:194 +0x2d
```

**Expected behavior**
It generates the CA and starts up correctly.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.2-68d381dde45b34f82a7247f20840829f1ee56fc1-Clean

**How was Istio installed?**
docker-compose from the Consul examples

**Environment where bug was observed (cloud vendor, OS, etc)**
Docker on OSX.
Image: istio/pilot:1.5.2

**Comment by lei-tang** [comment]
@gnz00 Can you share detailed steps to reproduce the problem? Have you tried the steps on other Istio versions and do the steps work for other Istio versions?

Meanwhile, the history of consul template https://github.com/istio/istio/commits/master/install/consul/templates/istio.yaml.tmpl shows that there is only one commit from 4-10-2019 to 4-21-2020. Thus, it is unclear whether the Consul integration is supported/up to date for 1.5.2. Add owners of Consul integration @rshriram @erdun @harryge00 to comment on the status of Consul integration.

**Comment by gnz00** [comment]
Seems to be a 1.5.x issue, as it works as expected on 1.4.5.

`docker-compose.yml`:
```
version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"
    command: ["/usr/local/bin/etcd", "-advertise-client-urls=http://0.0.0.0:2379", "-listen-client-urls=http://0.0.0.0:2379"]

  kube-api:
    image: k8s.gcr.io/kube-apiserver:v1.18.0
    ports:
      - "8080:8080"
    privileged: true
    command: ["kube-apiserver", "--etcd-servers", "http://etcd:2379", "--service-cluster-ip-range", "10.99.0.0/16", "--insecure-port", "8080", "-v", "2", "--insecure-bind-address", "0.0.0.0"]

  pilot:
    image: istio/pilot:1.5.2
    expose:
      - "15007"
      - "15010"
      - "15012"
    ports:
      - "8081:15007"
    command: ["discovery",
              "--httpAddr", ":15007",
              "--registries", "Consul",
              "--consulserverURL", "http://consul:8500",
              "--kubeconfig", "/etc/istio/config/kubeconfig",
              ]
    volumes:
      - ./kubeconfig:/etc/istio/config/kubeconfig
```
`kubeconfig`:
```
apiVersion: v1
clusters:
- cluster:
    server: http://kube-api:8080
  name: istio
contexts:
- context:
    cluster: istio
    user: ""
  name: istio
current-context: istio
```

Start etcd, kube-api first. Then Pilot.

**Comment by shenkonghui** [comment]
i alse encounter this quest. use istio 1.5.2 and i am in kubernetes
