### ISSUE TITLE
Install istio latest release/master 1.7-alpha via istioctl got runtime error

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#23562]
May-05
Following is the error log:

```
istio-1.7-alpha.8dfdb00c9ef491c5df220780c96802efdc483d40/bin/istioctl
+ install_istioctl /home/prow/go/src/istio.io/tools/perf/istio-install/tmp/istio-1.7-alpha.8dfdb00c9ef491c5df220780c96802efdc483d40 -f istioctl_profiles/default.yaml
+ release=/home/prow/go/src/istio.io/tools/perf/istio-install/tmp/istio-1.7-alpha.8dfdb00c9ef491c5df220780c96802efdc483d40
+ shift
+ /home/prow/go/src/istio.io/tools/perf/istio-install/tmp/istio-1.7-alpha.8dfdb00c9ef491c5df220780c96802efdc483d40/bin/istioctl manifest apply --skip-confirmation --wait -d /home/prow/go/src/istio.io/tools/perf/istio-install/tmp/istio-1.7-alpha.8dfdb00c9ef491c5df220780c96802efdc483d40/manifests -f istioctl_profiles/default.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2278321]

goroutine 1 [running]:
istio.io/istio/operator/pkg/apis/istio/v1alpha1/validation.validateFeatures(0xc0002467e0, 0xc000b91a40, 0x0, 0x0, 0x0)
	istio.io/istio/operator/pkg/apis/istio/v1alpha1/validation/validation.go:111 +0x51
istio.io/istio/operator/pkg/apis/istio/v1alpha1/validation.ValidateConfig(0x2a7f600, 0xc0001fa030, 0xc000b91a40, 0xb5e, 0xc0001d85a0, 0x97, 0x2f57400, 0xc00055f600)
	istio.io/istio/operator/pkg/apis/istio/v1alpha1/validation/validation.go:45 +0x201
istio.io/istio/operator/cmd/mesh.GenerateConfig(0xc000abbbe0, 0x1, 0x1, 0xc0001d85a0, 0x97, 0xc00036c000, 0xc00055f600, 0x2f574a0, 0xc0008923c0, 0x0, ...)
	istio.io/istio/operator/cmd/mesh/profile-common.go:63 +0x187
istio.io/istio/operator/cmd/mesh.ApplyManifests(0xc0009416d0, 0x1, 0x1, 0xc000abbbe0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	istio.io/istio/operator/cmd/mesh/manifest-apply.go:173 +0x196
istio.io/istio/operator/cmd/mesh.runApplyCmd(0xc0008c9080, 0xc000129cc8, 0xc000d10300, 0xc00006e630, 0x0, 0x0)
	istio.io/istio/operator/cmd/mesh/manifest-apply.go:149 +0x279
istio.io/istio/operator/cmd/mesh.manifestApplyCmd.func1(0xc0008c9080, 0xc0008aecc0, 0x0, 0x6, 0x0, 0x0)
	istio.io/istio/operator/cmd/mesh/manifest-apply.go:101 +0x46
github.com/spf13/cobra.(*Command).execute(0xc0008c9080, 0xc0008aec60, 0x6, 0x6, 0xc0008c9080, 0xc0008aec60)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d6000, 0x8, 0x8, 0xc0002d6000)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	istio.io/istio/istioctl/cmd/istioctl/main.go:29 +0x76
```

**Comment by carolynhu** [comment]
More info: May-04 job run is success for this release: istio-1.7-alpha.da59ac7292e0600845ed2c0c5df8f8ea47739e5e

**Comment by esnible** [comment]
While investigating this I found another panic:

```
cat > /tmp/issue23562.yaml <<EOF 
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
EOF
istioctl manifest generate --charts manifests -f /tmp/issue23562.yaml 
```
