### ISSUE TITLE
New test, TestExtractCACertExpiryTimestamp, is flaky

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23616]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2361

Trivial to reproduce locally, including a crash:

```
--- FAIL: TestExtractCACertExpiryTimestamp (9.41s)
    keycertbundle_test.go:402: failed to create key cert bundle cannot verify the cert with the provided root chain and cert pool with error: x509: certificate has expired or is not yet valid: current time 2020-05-07T12:43:00-07:00 is after 2020-05-07T19:42:58Z
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0245f]

goroutine 6 [running]:
testing.tRunner.func1.1(0xa8a7c0, 0xf48100)
        /usr/local/go/src/testing/testing.go:941 +0x5d0
testing.tRunner.func1(0xc0000ba7e0)
        /usr/local/go/src/testing/testing.go:944 +0x600
panic(0xa8a7c0, 0xf48100)
        /usr/local/go/src/runtime/panic.go:973 +0x396
istio.io/istio/security/pkg/pki/util.(*KeyCertBundleImpl).GetCertChainPem(0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/security/pkg/pki/util/keycertbundle.go:153 +0x5f
istio.io/istio/security/pkg/pki/util.(*KeyCertBundleImpl).ExtractCACertExpiryTimestamp(0x0, 0x30, 0x23, 0xc0003bfc98)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/security/pkg/pki/util/keycertbundle.go:217 +0x3d
istio.io/istio/security/pkg/pki/util.TestExtractCACertExpiryTimestamp(0xc0000ba7e0)
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/security/pkg/pki/util/keycertbundle_test.go:422 +0x7f8
testing.tRunner(0xc0000ba7e0, 0xb2cfa0)
        /usr/local/go/src/testing/testing.go:992 +0x1ec
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1043 +0x661

```

With https://godoc.org/golang.org/x/tools/cmd/stress: `162 runs so far, 86 failures`

**Comment by howardjohn** [comment]
@lucasvmiguel

**Comment by lucasvmiguel** [comment]
I'm happy to look this issue, but I was not able to reproduce so far,

command that I'm running:
```
➜  istio git:(master) ✗ stress go test -race ./security/pkg/pki/util/... -test.cpu=10 
15 runs so far, 0 failures
31 runs so far, 0 failures
48 runs so far, 0 failures
62 runs so far, 0 failures
78 runs so far, 0 failures
95 runs so far, 0 failures
111 runs so far, 0 failures
128 runs so far, 0 failures
145 runs so far, 0 failures
161 runs so far, 0 failures
177 runs so far, 0 failures
194 runs so far, 0 failures
211 runs so far, 0 failures
.
.
.
```
(in case CPU and memory is important for this test)
<img width="308" alt="Screenshot 2020-05-08 at 10 57 57" src="https://user-images.githubusercontent.com/7236505/81395018-d19b1400-911a-11ea-962c-f95d19d69e38.png">

**Comment by howardjohn** [comment]
Interesting.. I find its much easier to debug things you can reproduce so I gave it a shot in https://github.com/istio/istio/pull/23650
