### ISSUE TITLE
mixer/pkg/server/server_test.go hangs intermittently

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#2379]
server test hangs from time to time.

The following stack trace shows that
`monitor.Close()` is waiting on `channel receive` **after**  `server.Close()`
However `TCPListener.Accept()` is waiting for 9 minutes for a connection. The expectation is that `accept` call fails with `use of closed network connection` after `server.Close()` is called.

```
I0102 20:21:18.118] *** Test killed with quit: ran too long (10m0s).
I0102 20:21:18.118] FAIL    istio.io/istio/mixer/pkg/server    600.335s

I0102 20:21:16.957] SIGQUIT: quit
I0102 20:21:16.957] PC=0x45f541 m=0 sigcode=0
I0102 20:21:16.958] 
I0102 20:21:16.958] goroutine 0 [idle]:
I0102 20:21:16.958] runtime.futex(0x20e02b0, 0x0, 0x0, 0x0, 0x0, 0x7f3600000000, 0x0, 0x0, 0x7ffea7fea168, 0x4112fb, ...)
I0102 20:21:16.958]     /usr/local/go/src/runtime/sys_linux_amd64.s:438 +0x21
I0102 20:21:16.958] runtime.futexsleep(0x20e02b0, 0x0, 0xffffffffffffffff)
I0102 20:21:16.958]     /usr/local/go/src/runtime/os_linux.go:45 +0x62
I0102 20:21:16.958] runtime.notesleep(0x20e02b0)
I0102 20:21:16.959]     /usr/local/go/src/runtime/lock_futex.go:151 +0x9b
I0102 20:21:16.960] runtime.stopm()
I0102 20:21:16.960]     /usr/local/go/src/runtime/proc.go:1670 +0xe5
I0102 20:21:16.960] runtime.findrunnable(0xc420020000, 0x0)
I0102 20:21:16.960]     /usr/local/go/src/runtime/proc.go:2125 +0x4d2
I0102 20:21:16.960] runtime.schedule()
I0102 20:21:16.961]     /usr/local/go/src/runtime/proc.go:2245 +0x12c
I0102 20:21:16.961] runtime.park_m(0xc4209cc000)
I0102 20:21:16.961]     /usr/local/go/src/runtime/proc.go:2308 +0xb6
I0102 20:21:16.961] runtime.mcall(0x7ffea7fea300)
I0102 20:21:16.961]     /usr/local/go/src/runtime/asm_amd64.s:286 +0x5b
I0102 20:21:16.961] 
I0102 20:21:16.961] goroutine 1 [chan receive, 9 minutes]:
I0102 20:21:16.961] testing.(*T).Run(0xc420177a40, 0x171a7a9, 0x9, 0x179b1b0, 0x481b01)
I0102 20:21:16.962]     /usr/local/go/src/testing/testing.go:790 +0x2fc
I0102 20:21:16.962] testing.runTests.func1(0xc420177a40)
I0102 20:21:16.962]     /usr/local/go/src/testing/testing.go:1004 +0x64
I0102 20:21:16.962] testing.tRunner(0xc420177a40, 0xc4201d1de0)
I0102 20:21:16.962]     /usr/local/go/src/testing/testing.go:746 +0xd0
I0102 20:21:16.962] testing.runTests(0xc420345700, 0x20d15a0, 0x6, 0x6, 0x20)
I0102 20:21:16.962]     /usr/local/go/src/testing/testing.go:1002 +0x2d8
I0102 20:21:16.962] testing.(*M).Run(0xc4204d3f18, 0xc4201d1f70)
I0102 20:21:16.963]     /usr/local/go/src/testing/testing.go:921 +0x111
I0102 20:21:16.963] main.main()
I0102 20:21:16.963]     istio.io/istio/mixer/pkg/server/_test/_testmain.go:54 +0xdb
I0102 20:21:16.963] 
I0102 20:21:16.963] goroutine 50 [chan receive]:
I0102 20:21:16.963] istio.io/istio/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x20df640)
I0102 20:21:16.963]     /home/bootstrap/go/src/istio.io/istio/vendor/github.com/golang/glog/glog.go:882 +0x9f
I0102 20:21:16.963] created by istio.io/istio/vendor/github.com/golang/glog.init.0
I0102 20:21:16.963]     /home/bootstrap/go/src/istio.io/istio/vendor/github.com/golang/glog/glog.go:410 +0x203
I0102 20:21:16.963] 
I0102 20:21:16.963] goroutine 55 [chan receive, 9 minutes]:
I0102 20:21:16.963] istio.io/istio/mixer/pkg/server.(*monitor).Close(0xc4203d7d60, 0x0, 0x0)
I0102 20:21:16.964]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/server/monitoring.go:82 +0x5d
I0102 20:21:16.964] istio.io/istio/mixer/pkg/server.(*Server).Close(0xc420307ce0, 0xc42098e0a0, 0xc42098e0a0)
I0102 20:21:16.964]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/server/server.go:241 +0xcd
I0102 20:21:16.964] istio.io/istio/mixer/pkg/server.TestBasic(0xc420177e00)
I0102 20:21:16.964]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/server/server_test.go:126 +0x38c
I0102 20:21:16.964] testing.tRunner(0xc420177e00, 0x179b1b0)
I0102 20:21:16.964]     /usr/local/go/src/testing/testing.go:746 +0xd0
I0102 20:21:16.964] created by testing.(*T).Run
I0102 20:21:16.964]     /usr/local/go/src/testing/testing.go:789 +0x2de
I0102 20:21:16.964] 

I0102 20:21:18.112] goroutine 2107 [IO wait, 9 minutes]:
I0102 20:21:18.113] internal/poll.runtime_pollWait(0x7f369d68af70, 0x72, 0xffffffffffffffff)
I0102 20:21:18.113]     /usr/local/go/src/runtime/netpoll.go:173 +0x57
I0102 20:21:18.113] internal/poll.(*pollDesc).wait(0xc420334a18, 0x72, 0xc42003dd00, 0x0, 0x0)
I0102 20:21:18.113]     /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
I0102 20:21:18.113] internal/poll.(*pollDesc).waitRead(0xc420334a18, 0xffffffffffffff00, 0x0, 0x0)
I0102 20:21:18.113]     /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
I0102 20:21:18.113] internal/poll.(*FD).Accept(0xc420334a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
I0102 20:21:18.113]     /usr/local/go/src/internal/poll/fd_unix.go:334 +0x1e2
I0102 20:21:18.113] net.(*netFD).accept(0xc420334a00, 0x412b48, 0x30, 0x1621a40)
I0102 20:21:18.113]     /usr/local/go/src/net/fd_unix.go:238 +0x42
I0102 20:21:18.113] net.(*TCPListener).accept(0xc4201ae920, 0x52a0ba, 0x1621a40, 0xc420288d80)
I0102 20:21:18.114]     /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
I0102 20:21:18.114] net.(*TCPListener).Accept(0xc4201ae920, 0xc420016108, 0x15380e0, 0x20c6890, 0x16dc100)
I0102 20:21:18.114]     /usr/local/go/src/net/tcpsock.go:247 +0x49
I0102 20:21:18.114] net/http.(*Server).Serve(0xc4202f35f0, 0x2079e20, 0xc4201ae920, 0x0, 0x0)
I0102 20:21:18.114]     /usr/local/go/src/net/http/server.go:2695 +0x1b2
I0102 20:21:18.114] istio.io/istio/mixer/pkg/server.startMonitor.func2(0xc4203d7d60, 0x2079e20, 0xc4201ae920)
I0102 20:21:18.114]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/server/monitoring.go:68 +0x5e
I0102 20:21:18.114] created by istio.io/istio/mixer/pkg/server.startMonitor
I0102 20:21:18.114]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/server/monitoring.go:66 +0x313
I0102 20:21:18.114] 
I0102 20:21:18.114] goroutine 2114 [select]:
I0102 20:21:18.115] istio.io/istio/mixer/pkg/config/store.(*fsStore2).Init.func1(0xc420426300, 0x207b3e0, 0xc420016108)
I0102 20:21:18.115]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/config/store/fsstore2.go:204 +0x12e
I0102 20:21:18.115] created by istio.io/istio/mixer/pkg/config/store.(*fsStore2).Init
I0102 20:21:18.115]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/config/store/fsstore2.go:201 +0xca
I0102 20:21:18.115] 
I0102 20:21:18.115] goroutine 2115 [select, 9 minutes]:
I0102 20:21:18.115] istio.io/istio/mixer/pkg/config/store.(*eventQueue).run(0xc4202cbef0)
I0102 20:21:18.115]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/config/store/queue.go:66 +0x673
I0102 20:21:18.115] created by istio.io/istio/mixer/pkg/config/store.newQueue
I0102 20:21:18.115]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/config/store/queue.go:42 +0xd1
I0102 20:21:18.115] 
I0102 20:21:18.116] goroutine 2116 [chan receive (nil chan), 9 minutes]:
I0102 20:21:18.116] istio.io/istio/mixer/pkg/config/store.(*store2).Watch.func1(0x207b3e0, 0xc420016108, 0xc4202ca120)
I0102 20:21:18.116]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/config/store/store2.go:176 +0x4c
I0102 20:21:18.116] created by istio.io/istio/mixer/pkg/config/store.(*store2).Watch
I0102 20:21:18.116]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/config/store/store2.go:175 +0x153
I0102 20:21:18.116] 
I0102 20:21:18.116] goroutine 2117 [select, 9 minutes]:
I0102 20:21:18.116] istio.io/istio/mixer/pkg/runtime.watchChanges(0xc4209c7920, 0xc42039dfc0)
I0102 20:21:18.116]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/runtime/controller.go:199 +0x164
I0102 20:21:18.116] created by istio.io/istio/mixer/pkg/runtime.startController
I0102 20:21:18.116]     /home/bootstrap/go/src/istio.io/istio/mixer/pkg/runtime/init.go:116 +0x399
```

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/2331/istio-presubmit/1880/

**Comment by jmuk** [comment]
cc: @geeknoid 
This is interesting, monitoring server's `Close()` is called (hence ongoing `Accept` is unblocked), but `Accept` is still blocking. It's not reproducing on my environment, I guess it's a rare case that `Close` is called before `Serve` takes the effect.
