### ISSUE TITLE
Build issues with istio/proxy on Power architecture

### ISSUE THREAD

**Issue by junawaneshivani** [istio/istio#24257]
Hi All 

I am trying to build istio/proxy on power architecture. I made below changes to the Makefile.
```
diff --git a/Makefile b/Makefile
index c8754ad..c6a0202 100644
--- a/Makefile
+++ b/Makefile
@@ -45,6 +45,8 @@ else ifeq ($(LOCAL_ARCH),aarch64)
     TARGET_ARCH ?= arm64
 else ifeq ($(shell echo $(LOCAL_ARCH) | head -c 4),armv)
     TARGET_ARCH ?= arm
+else ifeq ($(LOCAL_ARCH),ppc64le)
+    TARGET_ARCH ?= ppc64le
```

And then tried to proceed with non-containerized build which is failing for me..

`make BUILD_WITH_CONTAINER=0 build` 
```
ang_libcxx", "gcc"]}
INFO: Call stack for the definition of repository 'emscripten_toolchain' which is a http_archive (rule definition at /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/envoy_api/bazel/envoy_http_archive.bzl:17:5
 - /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/envoy/bazel/repositories.bzl:16:5
 - /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/envoy/bazel/repositories.bzl:766:5
 - /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/envoy/bazel/repositories.bzl:153:5
 - /home/user4/Shivani/istio/proxy/WORKSPACE:68:1
ERROR: An error occurred during the fetch of repository 'emscripten_toolchain':
   Traceback (most recent call last):
        File "/home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 83
                patch(ctx)
        File "/home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 165, in patch
                fail(<1 more arguments>)
Error applying patch command ./emsdk install 1.39.6-upstream:
Warning: unknown machine architecture ppc64le
```

Any pointers/suggestions would be of great help.

**Comment by howardjohn** [comment]
Lets consolidate into https://github.com/istio/istio/issues/20836, it is hard to track so many split issues. Thanks!

Please note we do not official support/test power PC. From this it looks like emscripten, a dependency, may not support powerpc
