### ISSUE TITLE
Connection to external service with istio 1.6.1 is not working

### ISSUE THREAD

**Issue by nataraj24** [istio/istio#24575]
We use external service mechanism to connect to database.  Below is the full stack trace from application pod and outbound logs of istio-proxy side car. Request your help and resolution on this.  The issue is observed in istio 1.6.1 and 1.6.0.  As suggested in different thread i had tried deleting EnvoyFilters but invain.  The same image works fine in istio 1.5.2 without any changes.

2020-06-09T03:45:28.975361Z info Epoch 0 starting
2020-06-09T03:45:28.997182Z info Subchannel Connectivity change to READY
2020-06-09T03:45:29.002770Z info pickfirstBalancer: HandleSubConnStateChange: 0xc000b1eec0, {READY }
2020-06-09T03:45:29.003084Z info Channel Connectivity change to READY

[2020-06-09T03:46:49.878Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52588 - -
[2020-06-09T03:46:58.378Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52636 - -
[2020-06-09T03:46:58.681Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52640 - -
[2020-06-09T03:46:58.779Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52642 - -
[2020-06-09T03:46:59.172Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52648 - -
[2020-06-09T03:46:59.175Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52650 - -
[2020-06-09T03:46:59.177Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52652 - -
[2020-06-09T03:46:59.179Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52654 - -
[2020-06-09T03:46:59.181Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52656 - -
[2020-06-09T03:46:59.271Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52658 - -
[2020-06-09T03:46:59.273Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.99.132.118:6501 10.244.1.19:52660 - -

java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_232]
at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_232]
at com.edb.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:144) ~[edb-jdbc17.jar:?]
at com.edb.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113) ~[edb-jdbc17.jar:?]
at com.edb.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:72) ~[edb-jdbc17.jar:?]
at com.edb.core.PGStream.ReceiveChar(PGStream.java:307) ~[edb-jdbc17.jar:?]
at com.edb.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:437) ~[edb-jdbc17.jar:?]
at com.edb.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197) ~[edb-jdbc17.jar:?]
at com.edb.core.ConnectionFactory.openConnection(ConnectionFactory.java:67) ~[edb-jdbc17.jar:?]
at com.edb.jdbc2.AbstractJdbc2Connection.(AbstractJdbc2Connection.java:132) ~[edb-jdbc17.jar:?]
at com.edb.jdbc3.AbstractJdbc3Connection.(AbstractJdbc3Connection.java:30) ~[edb-jdbc17.jar:?]
at com.edb.jdbc3g.AbstractJdbc3gConnection.(AbstractJdbc3gConnection.java:22) ~[edb-jdbc17.jar:?]
at com.edb.jdbc4.AbstractJdbc4Connection.(AbstractJdbc4Connection.java:47) ~[edb-jdbc17.jar:?]
at com.edb.jdbc4.Jdbc4Connection.(Jdbc4Connection.java:25) ~[edb-jdbc17.jar:?]
at com.edb.Driver.makeConnection(Driver.java:413) ~[edb-jdbc17.jar:?]
at com.edb.Driver.connect(Driver.java:285) ~[edb-jdbc17.jar:?]
at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[tomcat-dbcp.jar:9.0.34]
at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[tomcat-dbcp.jar:9.0.34]
at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115) ~[tomcat-dbcp.jar:9.0.34]
at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665) ~[tomcat-dbcp.jar:9.0.34]
... 5 more
Wrapped by: com.edb.util.PSQLException: The connection attempt failed.
at com.edb.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:288) ~[edb-jdbc17.jar:?]
at com.edb.core.ConnectionFactory.openConnection(ConnectionFactory.java:67) ~[edb-jdbc17.jar:?]
at com.edb.jdbc2.AbstractJdbc2Connection.(AbstractJdbc2Connection.java:132) ~[edb-jdbc17.jar:?]
at com.edb.jdbc3.AbstractJdbc3Connection.(AbstractJdbc3Connection.java:30) ~[edb-jdbc17.jar:?]
at com.edb.jdbc3g.AbstractJdbc3gConnection.(AbstractJdbc3gConnection.java:22) ~[edb-jdbc17.jar:?]
at com.edb.jdbc4.AbstractJdbc4Connection.(AbstractJdbc4Connection.java:47) ~[edb-jdbc17.jar:?]
at com.edb.jdbc4.Jdbc4Connection.(Jdbc4Connection.java:25) ~[edb-jdbc17.jar:?]
at com.edb.Driver.makeConnection(Driver.java:413) ~[edb-jdbc17.jar:?]
at com.edb.Driver.connect(Driver.java:285) ~[edb-jdbc17.jar:?]
at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55) ~[tomcat-dbcp.jar:9.0.34]
at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355) ~[tomcat-dbcp.jar:9.0.34]
at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115) ~[tomcat-dbcp.jar:9.0.34]
at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665) ~[tomcat-dbcp.jar:9.0.34]
... 5 more
Wrapped by: java.sql.SQLException: Cannot create PoolableConnectionFactory (The connection attempt failed.)
at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669) ~[tomcat-dbcp.jar:9.0.34]
at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544) ~[tomcat-dbcp.jar:9.0.34]
at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753) ~[tomcat-dbcp.jar:9.0.34]

**Comment by uncycler** [comment]
I confirm I have the same issue. Reverting to 1.5.4 go back to normal.

I specified outboundTrafficPolicy in configuration, but no luck.
```
meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
```

**Comment by AlexandreRoba** [comment]
I reported the same issue [here](https://github.com/istio/istio/issues/24461)

**Comment by nataraj24** [comment]
team any resoultion on this would be helpful
