### ISSUE TITLE
DeepCopyInto of IstioOperatorSpec causes panic when patch value set

### ISSUE THREAD

**Issue by liamawhite** [istio/istio#24829]
**Bug description**

DeepCopyInto causes a panic when using any type in the patch value. This makes it impossible to use any patch in the operator CR here. I have created a [unit test reproducing it](https://github.com/liamawhite/api/blob/deep-copy-into-panic/operator/v1alpha1/deepcopy_test.go).

This function isn't used by the operator so I dont think it impacts users. I'm not sure what it is used for though! Maybe it should follow the DeepCopyInto in istio/istio and use json marshal?

```
--- FAIL: TestIstioOperatorSpec_DeepCopyInto (0.00s)
panic: reflect: call of reflect.Value.Elem on int Value [recovered]
	panic: reflect: call of reflect.Value.Elem on int Value

goroutine 7 [running]:
testing.tRunner.func1.1(0x15ec7c0, 0xc00000fd00)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0001986c0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:943 +0x3f9
panic(0x15ec7c0, 0xc00000fd00)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
reflect.Value.Elem(0x15c61a0, 0x1757378, 0x82, 0x15c61a0, 0x1757378, 0x82)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/reflect/value.go:820 +0x1a4
github.com/gogo/protobuf/proto.mergeAny(0x15e5da0, 0xc000035790, 0x194, 0x15e5da0, 0xc000035390, 0x194, 0x100, 0xc0001d2500)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:166 +0x471
github.com/gogo/protobuf/proto.mergeStruct(0x1650260, 0xc000035780, 0x199, 0x1650260, 0xc000035380, 0x199)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:108 +0x280
github.com/gogo/protobuf/proto.mergeAny(0x1650260, 0xc000035780, 0x199, 0x1650260, 0xc000035380, 0x199, 0x1625601, 0x0)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:236 +0x1724
github.com/gogo/protobuf/proto.mergeAny(0x1654de0, 0xc000010328, 0x196, 0x1654de0, 0xc0000102f0, 0x196, 0x100, 0x0)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:199 +0x70e
github.com/gogo/protobuf/proto.mergeAny(0x15b7d60, 0xc0001c6a40, 0x197, 0x15b7d60, 0xc000189290, 0x197, 0x100, 0xc0001d2300)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:231 +0x112c
github.com/gogo/protobuf/proto.mergeStruct(0x165e160, 0xc0001c6a10, 0x199, 0x165e160, 0xc000189260, 0x199)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:108 +0x280
github.com/gogo/protobuf/proto.mergeAny(0x165e160, 0xc0001c6a10, 0x199, 0x165e160, 0xc000189260, 0x199, 0x1625601, 0x0)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:236 +0x1724
github.com/gogo/protobuf/proto.mergeAny(0x1660320, 0xc000010308, 0x196, 0x1660320, 0xc0000102e8, 0x196, 0x100, 0x0)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:199 +0x70e
github.com/gogo/protobuf/proto.mergeAny(0x15b7d20, 0xc00016e348, 0x197, 0x15b7d20, 0xc00016e268, 0x197, 0x100, 0xc0001d1f00)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:231 +0x112c
github.com/gogo/protobuf/proto.mergeStruct(0x1685820, 0xc00016e2a0, 0x199, 0x1685820, 0xc00016e1c0, 0x199)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:108 +0x280
github.com/gogo/protobuf/proto.mergeAny(0x1685820, 0xc00016e2a0, 0x199, 0x1685820, 0xc00016e1c0, 0x199, 0x1, 0x0)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:236 +0x1724
github.com/gogo/protobuf/proto.mergeAny(0x167fee0, 0xc0001c69e8, 0x196, 0x167fee0, 0xc000189238, 0x196, 0x100, 0xc0001d3800)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:199 +0x70e
github.com/gogo/protobuf/proto.mergeStruct(0x1668240, 0xc0001c69a0, 0x199, 0x1668240, 0xc0001891f0, 0x199)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:108 +0x280
github.com/gogo/protobuf/proto.mergeAny(0x1668240, 0xc0001c69a0, 0x199, 0x1668240, 0xc0001891f0, 0x199, 0x15c7101, 0x0)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:236 +0x1724
github.com/gogo/protobuf/proto.mergeAny(0x165c660, 0xc00014c588, 0x196, 0x165c660, 0xc00014c408, 0x196, 0x100, 0xc0001d3200)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:199 +0x70e
github.com/gogo/protobuf/proto.mergeStruct(0x1670400, 0xc00014c580, 0x199, 0x1670400, 0xc00014c400, 0x199)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:108 +0x280
github.com/gogo/protobuf/proto.mergeAny(0x1670400, 0xc00014c580, 0x199, 0x1670400, 0xc00014c400, 0x199, 0x5a09901, 0x0)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:236 +0x1724
github.com/gogo/protobuf/proto.mergeAny(0x166d260, 0xc0001ac138, 0x196, 0x166d260, 0xc0001ac078, 0x196, 0x100, 0xc0001aea00)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:199 +0x70e
github.com/gogo/protobuf/proto.mergeStruct(0x167f1c0, 0xc0001ac0c0, 0x199, 0x167f1c0, 0xc0001ac000, 0x199)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:108 +0x280
github.com/gogo/protobuf/proto.Merge(0x1771540, 0xc0001ac0c0, 0x1771540, 0xc0001ac000)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:98 +0x3c1
github.com/gogo/protobuf/proto.Clone(0x1771540, 0xc0001ac000, 0x0, 0x0)
	/Users/liam/dev/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/clone.go:52 +0x18f
istio.io/api/operator/v1alpha1.(*IstioOperatorSpec).DeepCopyInto(...)
	/Users/liam/dev/src/istio.io/api/operator/v1alpha1/deepcopy.go:33
istio.io/api/operator/v1alpha1.TestIstioOperatorSpec_DeepCopyInto(0xc0001986c0)
	/Users/liam/dev/src/istio.io/api/operator/v1alpha1/deepcopy_test.go:40 +0x218
testing.tRunner(0xc0001986c0, 0x16c7718)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:1042 +0x357
FAIL	istio.io/api/operator/v1alpha1	0.205s
FAIL
```

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by sdake** [comment]
segfault is bad. Thank you so much for the unit test.

**Comment by jasonwzm** [comment]
Does json marshal correctly copy IstioOperator? The other Istio APIs all rely on gogo's proto clone for DeepCopy. This could be an issue for protos that use Struct.

**Comment by liamawhite** [comment]
I think the json marshal does work otherwise the operator wouldn't be able to use patches at all?

**Comment by jasonwzm** [comment]
Where is DeepCopy used in Operator?

**Comment by liamawhite** [comment]
[This](https://github.com/istio/istio/blob/master/operator/pkg/apis/istio/v1alpha1/deepcopy.go#L41 ) is used under the covers by the controller-runtime I believe. It calls `json.Marshal` of the kube wrapper for spec which presumably calls `json.Marshal` of the spec.

**Comment by jasonwzm** [comment]
Okay, so it seems that IstioOperator in istio/istio is a kubernetes type with spec being istio/api's IstioOperator. The DeepCopy in istio/istio does not rely on the DeepCopy in istio/api. @ostromart What do you think if IstioOperator uses json Marshal instead of proto Clone for its DeepCopy in istio/api?

**Comment by knight42** [comment]
@jasonwzm now that `gogo/protobuf` is no longer active, could we maintain our fork of `gogo/protobuf` and fix this bug?

**Comment by liamawhite** [comment]
@knight42 I believe the long term plan is to migrate away from `gogo/protobuf`. 

Tagging @howardjohn as he knows more.

**Comment by jasonwzm** [comment]
@howardjohn What is our current plan on gogo/protobuf migration? User in https://github.com/istio/istio/issues/25584 is affected by this.

**Comment by howardjohn** [comment]
@jasonwzm I think it is a good idea still but no one has invested in it. I did some efforts to it a while back but largely it was thousands of lines of boilerplate that I was scared would never get merged after tons of work...

**Comment by jasonwzm** [comment]
Gotcha. We can see if the workaround mentioned above that uses json marshal will solve this issue.
