### ISSUE TITLE
bookinfo, productpage.py error: Address family not supported by protocol

### ISSUE THREAD

**Issue by ggjjlldd** [istio/istio#25640]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I use bookinfo guide install it. but productpage pod is CrashLoopBackOff
```
NAME                             READY   STATUS             RESTARTS   AGE
details-v1-678494797d-s6k2w      2/2     Running            0          29m
productpage-v1-674ff6b6d-6zfvv   1/2     CrashLoopBackOff   10         29m
ratings-v1-6cbb579994-f2qf5      2/2     Running            0          29m
reviews-v1-776675fc96-srp47      2/2     Running            0          29m
reviews-v2-7988474c4d-fktgm      2/2     Running            0          29m
reviews-v3-59ffd9c848-7qt8f      2/2     Running            0          29m

```
here is log error:
```
[root@linuxtest58b5 istio-1.6.5]# kubectl logs -p productpage-v1-674ff6b6d-6zfvv -c productpage
INFO:root:start at port 9080
 * Serving Flask app "productpage" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "productpage.py", line 385, in <module>
    app.run(host='::', port=p, debug=True, threaded=True)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 985, in run_simple
    s = socket.socket(address_family, socket.SOCK_STREAM)
  File "/usr/local/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
run ok

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/istio/pull/25645
