### ISSUE TITLE
Panic in Multicluster-test setup: Concurrent Map

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#25684]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25589/integ-multicluster-k8s-tests_istio/7128

```
✔ Installation complete2020-07-21T02:16:33.247106Z	info	tf	Creating dummy rule to check for validation webhook readiness
2020-07-21T02:16:33.461320Z	debug	tf	Adding resource for tracking: [suite(multicluster_centralistio)]/[*istioctl.kubeComponent-0]
2020-07-21T02:16:33.461366Z	debug	tf	Adding resource for tracking: [suite(multicluster_centralistio)]/[*istioctl.kubeComponent-1]
fatal error: concurrent map writes
goroutine 1858 [running]:
runtime.throw(0x328cd85, 0x15)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc002ff3210 sp=0xc002ff31e0 pc=0x436a62
runtime.mapassign_faststr(0x2c93700, 0xc0016d39e0, 0x326d52d, 0x8, 0xc0016d39e0)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc002ff3278 sp=0xc002ff3210 pc=0x4152a7
github.com/spf13/viper.(*Viper).SetDefault(0xc001698800, 0x326d52d, 0x8, 0x2b75640, 0x37b9a90)
	/home/prow/go/pkg/mod/github.com/istio/viper@v1.3.3-0.20190515210538-2789fed3109c/viper.go:1214 +0x1bf fp=0xc002ff3308 sp=0xc002ff3278 pc=0x233784f
github.com/spf13/viper.SetDefault(...)
	/home/prow/go/pkg/mod/github.com/istio/viper@v1.3.3-0.20190515210538-2789fed3109c/viper.go:1203
istio.io/istio/istioctl/pkg/clioptions.(*CentralControlPlaneOptions).AttachControlPlaneFlags(0xc002f8ec00, 0xc002fad600)
	/home/prow/go/src/istio.io/istio/istioctl/pkg/clioptions/central.go:54 +0x5e fp=0xc002ff3370 sp=0xc002ff3308 pc=0x2342f5e
istio.io/istio/istioctl/cmd.xdsVersionCommand(0x2bacf60)
	/home/prow/go/src/istio.io/istio/istioctl/cmd/version.go:105 +0xe7 fp=0xc002ff33c8 sp=0xc002ff3370 pc=0x28dc527
istio.io/istio/istioctl/cmd.GetRootCmd(0xc00169e500, 0x26, 0x28, 0x26)
	/home/prow/go/src/istio.io/istio/istioctl/cmd/root.go:174 +0x640 fp=0xc002ff3638 sp=0xc002ff33c8 pc=0x28d6280
istio.io/istio/pkg/test/framework/components/istioctl.(*kubeComponent).Invoke(0xc002f8e900, 0xc0010226c0, 0x24, 0x24, 0xc000732000, 0x22, 0x40, 0x22, 0xc002ff3780, 0x1)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istioctl/kube.go:58 +0x1ae fp=0xc002ff3718 sp=0xc002ff3638 pc=0x28fa54e
istio.io/istio/pkg/test/framework/components/istio.applyManifest(0xc001733680, 0xc000732000, 0x22, 0x40, 0x384f820, 0xc002f8e900, 0xc00214b110, 0x9, 0x0, 0x0)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/operator.go:489 +0x124 fp=0xc002ff37d8 sp=0xc002ff3718 pc=0x29080b4
istio.io/istio/pkg/test/framework/components/istio.deployControlPlane(0xc001733680, 0x3275d34, 0xc, 0x3275d34, 0xc, 0x3275d34, 0xc, 0x3275d34, 0xc, 0x3275d34, ...)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/operator.go:465 +0x128a fp=0xc002ff3ca8 sp=0xc002ff37d8 pc=0x290752a
istio.io/istio/pkg/test/framework/components/istio.deploy.func3(0x33b1d18, 0x33b2060)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/operator.go:236 +0x128 fp=0xc002ff3f58 sp=0xc002ff3ca8 pc=0x290b998
github.com/hashicorp/go-multierror.(*Group).Go.func1(0xc001591520, 0xc002f8e8a0)
	/home/prow/go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/group.go:23 +0x5c fp=0xc002ff3fd0 sp=0xc002ff3f58 pc=0xc813cc
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc002ff3fd8 sp=0xc002ff3fd0 pc=0x469851
created by github.com/hashicorp/go-multierror.(*Group).Go
	/home/prow/go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/group.go:20 +0x66
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc001591538)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc001591530)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/hashicorp/go-multierror.(*Group).Wait(0xc001591520, 0x0)
	/home/prow/go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/group.go:34 +0x4b
istio.io/istio/pkg/test/framework/components/istio.deploy(0x38f4a00, 0xc0017e62d0, 0xc000bec980, 0x3275d34, 0xc, 0x3275d34, 0xc, 0x3275d34, 0xc, 0x3275d34, ...)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/operator.go:243 +0x7a3
istio.io/istio/pkg/test/framework/components/istio.Deploy(0x38f4a00, 0xc0017e62d0, 0xc0016e2000, 0x0, 0x0, 0x0, 0x0)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/istio.go:87 +0x1eb
istio.io/istio/pkg/test/framework/components/istio.Setup.func1(0x38f4a00, 0xc0017e62d0, 0xc0017e62d0, 0x38f4a00)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/istio.go:56 +0x2c9
istio.io/istio/pkg/test/framework.(*suiteImpl).runSetupFn(0xc001200100, 0xc0004f6a80, 0x38f4980, 0xc0017e62d0, 0x0, 0x0)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/suite.go:256 +0xa7
istio.io/istio/pkg/test/framework.(*suiteImpl).runSetupFns(0xc001200100, 0x38f4980, 0xc0017e62d0, 0x5a87dc0, 0x7f8b70b25e98)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/suite.go:418 +0x253
istio.io/istio/pkg/test/framework.(*suiteImpl).run(0xc001200100, 0x0)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/suite.go:322 +0x2c1
istio.io/istio/pkg/test/framework.(*suiteImpl).Run(0xc001200100)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/suite.go:261 +0x2b
istio.io/istio/tests/integration/multicluster/centralistio.TestMain(0xc001200000)
	/home/prow/go/src/istio.io/istio/tests/integration/multicluster/centralistio/main_test.go:99 +0x1d7
main.main()
	_testmain.go:44 +0x135
goroutine 10 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0007262d0)
	/home/prow/go/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/home/prow/go/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:32 +0x57
goroutine 66 [IO wait]:
internal/poll.runtime_pollWait(0x7f8b709adf18, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000c74098, 0x72, 0xc800, 0xc877, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000c74080, 0xc0008ee000, 0xc877, 0xc877, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000c74080, 0xc0008ee000, 0xc877, 0xc877, 0x203000, 0xc, 0xc0008ef01b)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000136f60, 0xc0008ee000, 0xc877, 0xc877, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc002f8b400, 0xc0008ee000, 0xc877, 0xc877, 0x400, 0x7f8b49aa6c00, 0xc001b399a8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc00061acd8, 0x37fe7e0, 0xc002f8b400, 0x40c225, 0x2d0c200, 0x31960e0)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00061aa80, 0x3816ac0, 0xc000136f60, 0x5, 0xc000136f60, 0x8)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00061aa80, 0x0, 0x0, 0xc001b39d18)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00061aa80, 0xc001bb1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc001b8b260, 0xc000246738, 0x9, 0x9, 0xc001b39d18, 0x33b2000, 0xabee35)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x37fe5a0, 0xc001b8b260, 0xc000246738, 0x9, 0x9, 0x9, 0xc000118050, 0x0, 0x37fea40)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc000246738, 0x9, 0x9, 0x37fe5a0, 0xc001b8b260, 0x0, 0x0, 0xc002137440, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000246700, 0xc002137440, 0x0, 0x0, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc001b39fa8, 0x0, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:1794 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0016cad80)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:1716 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:695 +0x64a
goroutine 70 [IO wait]:
internal/poll.runtime_pollWait(0x7f8b709ade38, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc001b5da18, 0x72, 0x4600, 0x4634, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001b5da00, 0xc000e62000, 0x4634, 0x4634, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc001b5da00, 0xc000e62000, 0x4634, 0x4634, 0x203000, 0x685d90, 0xc00061af38)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000136f88, 0xc000e62000, 0x4634, 0x4634, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000c6a740, 0xc000e62000, 0x4634, 0x4634, 0x1a, 0xae2, 0xc0000e19a8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc00061b058, 0x37fe7e0, 0xc000c6a740, 0x40c225, 0x2d0c200, 0x31960e0)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00061ae00, 0x3816ac0, 0xc000136f88, 0x5, 0xc000136f88, 0x9)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00061ae00, 0x0, 0x0, 0xc0000e1d18)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00061ae00, 0xc001bcb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc001bb94a0, 0xc0002468f8, 0x9, 0x9, 0xc0000e1d18, 0x33b2000, 0xabee35)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x37fe5a0, 0xc001bb94a0, 0xc0002468f8, 0x9, 0x9, 0x9, 0xc000118050, 0x0, 0x37fea40)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc0002468f8, 0x9, 0x9, 0x37fe5a0, 0xc001bb94a0, 0x0, 0x0, 0xc0016e4d80, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0002468c0, 0xc0016e4d80, 0x0, 0x0, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0000e1fa8, 0x0, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:1794 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0016cbe00)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:1716 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:695 +0x64a
goroutine 44 [IO wait]:
internal/poll.runtime_pollWait(0x7f8b709add58, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc001576598, 0x72, 0x4600, 0x462c, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001576580, 0xc001766000, 0x462c, 0x462c, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc001576580, 0xc001766000, 0x462c, 0x462c, 0x203000, 0x685d90, 0xc0017bf638)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000cc1df8, 0xc001766000, 0x462c, 0x462c, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0004fd000, 0xc001766000, 0x462c, 0x462c, 0x1a, 0x4627, 0xc001b829a8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc0017bf758, 0x37fe7e0, 0xc0004fd000, 0x40c225, 0x2d0c200, 0x31960e0)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc0017bf500, 0x3816ac0, 0xc000cc1df8, 0x5, 0xc000cc1df8, 0x9)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc0017bf500, 0x0, 0x0, 0xc001b82d18)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc0017bf500, 0xc001c06000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc001b76d20, 0xc001b242d8, 0x9, 0x9, 0xc001b82d18, 0x33b2000, 0xabee35)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x37fe5a0, 0xc001b76d20, 0xc001b242d8, 0x9, 0x9, 0x9, 0xc000118050, 0x0, 0x37fea40)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc001b242d8, 0x9, 0x9, 0x37fe5a0, 0xc001b76d20, 0x0, 0x0, 0xc0015fec00, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc001b242a0, 0xc0015fec00, 0x0, 0x0, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc001b82fa8, 0x0, 0x0)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:1794 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000c7af00)
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:1716 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/home/prow/go/pkg/mod/golang.org/x/net@v0.0.0-20200602114024-627f9648deb9/http2/transport.go:695 +0x64a
goroutine 1857 [runnable]:
github.com/spf13/cobra.(*Command).PersistentFlags(0xc003203600, 0x2e32360)
	/home/prow/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:1490 +0x12d
istio.io/istio/operator/cmd/mesh.addFlags(0xc003203600, 0xc0031a7e90)
	/home/prow/go/src/istio.io/istio/operator/cmd/mesh/root.go:52 +0x2b
istio.io/istio/operator/cmd/mesh.ProfileCmd(0x3262900)
	/home/prow/go/src/istio.io/istio/operator/cmd/mesh/profile.go:40 +0x167
istio.io/istio/istioctl/cmd.newVersionCommand(0xc003203340)
	/home/prow/go/src/istio.io/istio/istioctl/cmd/version.go:40 +0x40
istio.io/istio/istioctl/cmd.GetRootCmd(0xc001652a00, 0x26, 0x28, 0x26)
	/home/prow/go/src/istio.io/istio/istioctl/cmd/root.go:178 +0x67d
istio.io/istio/pkg/test/framework/components/istioctl.(*kubeComponent).Invoke(0xc002c21e60, 0xc00101f440, 0x24, 0x24, 0xc00055f800, 0x22, 0x40, 0x22, 0xc002fef780, 0x1)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istioctl/kube.go:58 +0x1ae
istio.io/istio/pkg/test/framework/components/istio.applyManifest(0xc001733680, 0xc00055f800, 0x22, 0x40, 0x384f820, 0xc002c21e60, 0xc0031a7de0, 0x9, 0x3d, 0x5ffb)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/operator.go:489 +0x124
istio.io/istio/pkg/test/framework/components/istio.deployControlPlane(0xc001733680, 0x3275d34, 0xc, 0x3275d34, 0xc, 0x3275d34, 0xc, 0x3275d34, 0xc, 0x3275d34, ...)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/operator.go:465 +0x128a
istio.io/istio/pkg/test/framework/components/istio.deploy.func3(0x33b1d18, 0x33b2060)
	/home/prow/go/src/istio.io/istio/pkg/test/framework/components/istio/operator.go:236 +0x128
github.com/hashicorp/go-multierror.(*Group).Go.func1(0xc001591520, 0xc002f8e840)
	/home/prow/go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/group.go:23 +0x5c
created by github.com/hashicorp/go-multierror.(*Group).Go
	/home/prow/go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/group.go:20 +0x66
FAIL	istio.io/istio/tests/integration/multicluster/centralistio	39.294s
```

**Comment by stevenctl** [comment]
fixed by https://github.com/istio/istio/pull/25664
