### ISSUE TITLE
istio-init(v1.6.3) fails to be recreated because of iptables rules restoring panic

### ISSUE THREAD

**Issue by bydeath** [istio/istio#25792]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

I'm using Seldon Core with istio as ingress. I deployed a model with istio sidecar auto injected and it works fine. But hours later, the container istio-init's readiness probe checking failed, when istio-init is created, it failed and never to be created. The log of the container istio-init show below:
```
iptables-restore --noflush /tmp/iptables-rules-xxxxxxxxxxxxxxxxxxxxx.txt670681543
iptables-restore: line 2 failed
...
...
COMMIT
# Completed on The Jul 23...
panic: exit status 1goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
...
...
main.main()
       istio.io/istio/pilot/cmd/pilot-agent/main.go:504 +0x2d
```
The first 3 lines of the iptables rules txt file is below:
```
* nat
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
recreate the container istio-init successfully
**Steps to reproduce the bug**
1. find the docker id of the container istio-init and which node the pod is on.
2. login the node and remove the container istio-init with `docker rm` command.
3. wait 1 minute, the issue will occur.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
I'm using bare metal kubernetes with version v1.16.4.
My istio version is v1.6.3
**How was Istio installed?**
`istioctl install --set profile=demo`
**Environment where bug was observed (cloud vendor, OS, etc)**
OS: Red Hat Enterprise Linux Server 7.6 (mAIPO) kernel version: 4.14.67
docker runtime: 19.3
k8s cni: flannel
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by bydeath** [comment]
Now I can reproduce the issue by removing the container istio-init.
`docker rm (docker id of istio-init)`
