### ISSUE TITLE
[distroless] [istio-init] [tproxy] libmnl.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by srinathhs** [istio/istio#25849]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

istio-init container is crashing with the following error

`libmnl.so.0: cannot open shared object file: No such file or directory`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
istio-init container should complete.

**Steps to reproduce the bug**
1. Set `interceptionMode: TPROXY` 
2. [Re]Start any workload with istio enabled

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (4 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.8", GitCommit:"35dc4cdc26cfcb6614059c4c6e836e5f0dc61dee", GitTreeState:"clean", BuildDate:"2020-06-26T03:36:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using istioctl install -f manifest.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: default-istiocontrolplane
spec:
  profile: default
  tag: 1.6.5-distroless
  meshConfig:
    defaultConfig:
      interceptionMode: TPROXY
      tracing:
        sampling: 1.0
        zipkin:
          address: svc-jager-collector.observability:9411 
  values:
    pilot: 
      traceSampling: 1.0
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    global:
      controlPlaneSecurityEnabled: true
    gateways:
      istio-ingressgateway:
        type: LoadBalancer
    kiali:
      enabled: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Baremetal kubernetes 1.17.x installed over Fedora Coreos and CRI-O with Cilium CNI (kube-proxy -less)

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
Complete istio-init output

```
 Environment:                                                                                                                         │
│ ------------                                                                                                                         │
│ ENVOY_PORT=                                                                                                                          │
│ INBOUND_CAPTURE_PORT=                                                                                                                │
│ ISTIO_INBOUND_INTERCEPTION_MODE=                                                                                                     │
│ ISTIO_INBOUND_TPROXY_MARK=                                                                                                           │
│ ISTIO_INBOUND_TPROXY_ROUTE_TABLE=                                                                                                    │
│ ISTIO_INBOUND_PORTS=                                                                                                                 │
│ ISTIO_LOCAL_EXCLUDE_PORTS=                                                                                                           │
│ ISTIO_SERVICE_CIDR=                                                                                                                  │
│ ISTIO_SERVICE_EXCLUDE_CIDR=                                                                                                          │
│ Variables:                                                                                                                           │
│ ----------                                                                                                                           │
│ PROXY_PORT=15001                                                                                                                     │
│ PROXY_INBOUND_CAPTURE_PORT=15006                                                                                                     │
│ PROXY_UID=1337                                                                                                                       │
│ PROXY_GID=1337                                                                                                                       │
│ INBOUND_INTERCEPTION_MODE=TPROXY                                                                                                     │
│ INBOUND_TPROXY_MARK=1337                                                                                                             │
│ INBOUND_TPROXY_ROUTE_TABLE=133                                                                                                       │
│ INBOUND_PORTS_INCLUDE=*                                                                                                              │
│ INBOUND_PORTS_EXCLUDE=15090,15021,15020                                                                                              │
│ OUTBOUND_IP_RANGES_INCLUDE=*                                                                                                         │
│ OUTBOUND_IP_RANGES_EXCLUDE=                                                                                                          │
│ OUTBOUND_PORTS_EXCLUDE=                                                                                                              │
│ KUBEVIRT_INTERFACES=                                                                                                                 │
│ ENABLE_INBOUND_IPV6=false                                                                                                            │
│ ip -f inet rule add fwmark 1337 lookup 133                                                                                           │
│ ip: error while loading shared libraries: libmnl.so.0: cannot open shared object file: No such file or directory                     │
│ iptables-save                                                                                                                        │
│ panic: exit status 127                                                                                                               │
│ goroutine 1 [running]:                                                                                                               │
│ istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail2020-07-25T01:08:10.215296418+05:30 (0x3baee68, 0x │
│     istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96                                                  │
│ istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).handleInboundPortsInclude2020-07-25T01:08:10.215316881+05:30 (0x │
│     istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:128 +0x216f                                                                   │
│ istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc000a3fd68)                                                │
│     istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:3652020-07-25T01:08:10.215352225+05:30  +0x68d                                │
│ istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x3b5c460, 0xc0000571002020-07-25T01:08:10.215369648+05:30 , 0x0, 0x10)      │
│     istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:642020-07-25T01:08:10.215387031+05:30  +0x148                                │
│ github.com/spf13/cobra.(*Command).execute2020-07-25T01:08:10.215404338+05:30 (0x3b5c460, 0xc000057000, 0x10, 0x10, 2020-07-25T01:08: │
│     github.com/spf13/cobra@v1.0.0/command.go:846 +2020-07-25T01:08:10.215438958+05:30 0x29d                                          │
│ github.com/spf13/cobra.(*Command).ExecuteC(0x3b5c700, 0x02020-07-25T01:08:10.215486035+05:30 , 0x0, 0x0)                             │
│     github.com/spf13/cobra@v1.0.0/command.go:950 +0x349                                                                              │
│ github.com/spf13/cobra.(*Command).Execute(...)                                                                                       │
│     github.com/spf13/cobra@v1.0.0/command.go:887                                                                                     │
│ main.main()                                                                                                                          │
│     istio.io/istio/pilot/cmd/pilot-agent/main.go2020-07-25T01:08:10.215507312+05:30 :504 +0x2d                                       │
│ stream closed 
```

**Comment by srinathhs** [comment]
This error does not occur with base 1.6.5 docker images. Only distroless has this issue.
