### ISSUE TITLE
Pods are entering CrashLoopBackOff after upgrade to Istio v1.6.6

### ISSUE THREAD

**Issue by oranje42** [istio/istio#25974]
**Bug description**

After upgrading from Istio v1.6.5 to Istio v1.6.6 some (not all) pods having an Istio sidecar automatically injected are entering CrashLoopBackOff state after restart. In particular, the following pods are showing that behavior:

* kubernetes-dashboard, see log excerpt below:

```
2020/07/30 11:54:21 Starting overwatch
2020/07/30 11:54:21 Using namespace: fdlgate-system
2020/07/30 11:54:21 Using in-cluster config to connect to apiserver
2020/07/30 11:54:21 Using secret token for csrf signing
2020/07/30 11:54:21 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: an error on the server ("") has prevented the request from succeeding (get secrets kubernetes-dashboard-csrf)

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc0001810a0)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:41 +0x446
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc000152080)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:501 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc000152080)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:469 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:550
main.main()
	/home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:105 +0x20d
```

* nginx-ingress-controller, see log-excerpt below:

```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v0.34.1
  Build:         v20200715-ingress-nginx-2.11.0-8-gda5fa45e2
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.1

-------------------------------------------------------------------------------

I0730 12:43:51.917976       6 flags.go:205] Watching for Ingress class: nginx
W0730 12:43:51.918263       6 flags.go:250] SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)
W0730 12:43:51.918308       6 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0730 12:43:51.918476       6 main.go:231] Creating API client for https://172.20.0.1:443
I0730 12:43:51.919187       6 main.go:251] Trying to discover Kubernetes version
I0730 12:43:51.919448       6 main.go:260] Unexpected error discovering Kubernetes version (attempt 0): Get "https://172.20.0.1:443/version?timeout=32s": dial tcp 172.20.0.1:443: connect: connection refused
I0730 12:43:52.956326       6 main.go:260] Unexpected error discovering Kubernetes version (attempt 1): Get "https://172.20.0.1:443/version?timeout=32s": dial tcp 172.20.0.1:443: connect: connection refused
I0730 12:43:54.548717       6 request.go:907] Got a Retry-After 1s response for attempt 1 to https://172.20.0.1:443/version?timeout=32s
I0730 12:43:55.549380       6 request.go:907] Got a Retry-After 1s response for attempt 2 to https://172.20.0.1:443/version?timeout=32s
I0730 12:43:56.550125       6 request.go:907] Got a Retry-After 1s response for attempt 3 to https://172.20.0.1:443/version?timeout=32s
I0730 12:43:57.550655       6 request.go:907] Got a Retry-After 1s response for attempt 4 to https://172.20.0.1:443/version?timeout=32s
I0730 12:43:58.551391       6 request.go:907] Got a Retry-After 1s response for attempt 5 to https://172.20.0.1:443/version?timeout=32s
I0730 12:43:59.551990       6 request.go:907] Got a Retry-After 1s response for attempt 6 to https://172.20.0.1:443/version?timeout=32s
I0730 12:44:00.552540       6 request.go:907] Got a Retry-After 1s response for attempt 7 to https://172.20.0.1:443/version?timeout=32s
I0730 12:44:01.553339       6 request.go:907] Got a Retry-After 1s response for attempt 8 to https://172.20.0.1:443/version?timeout=32s
I0730 12:44:02.553863       6 request.go:907] Got a Retry-After 1s response for attempt 9 to https://172.20.0.1:443/version?timeout=32s
I0730 12:44:03.554563       6 main.go:260] Unexpected error discovering Kubernetes version (attempt 2): an error on the server ("") has prevented the request from succeeding
```

Downgrading to Istio v1.6.5 fixes the issue so that all pods are running normally as expected again. Additionally, that behavior is reproducible, so that another upgrade to Istio v1.6.6 causes the same pods to enter CrashLoopBackOff again after restart.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Upgrading to Istio v1.6.6 should not break existing pods.

**Steps to reproduce the bug**

1) Setup a Kubernetes cluster (v1.17.7)
2) Install Istio v1.6.5
3) Install Kubernetes-Dashboard (I'm using this [Helm Chart](https://hub.helm.sh/charts/k8s-dashboard/kubernetes-dashboard), v2.3.0) with Istio sidecar enabled
4) Access Kubernetes-Dashboard, should be working
5) Upgrade Istio to v1.6.6
6) Restart Kubernetes-Dashboard pod
7) Kubernetes-Dashboard pod enters CrashLoopBackoff

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version

client version: 1.6.6
control plane version: 1.6.6
data plane version: 1.6.6 (4 proxies), 1.6.5 (8 proxies)
```

```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-eks-4e7f64", GitCommit:"4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c", GitTreeState:"clean", BuildDate:"2020-06-11T13:55:35Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ helm version

version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**How was Istio installed?**

```
istioctl manifest apply -f myvalues.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS (1.17)

**Comment by howardjohn** [comment]
Can you see these issues in a more simple environment? It's hard for us to figure out what's going on from the description as none of us are experts on nginx or kube dashboard. Ideally we would have simple curl commands that fail, as well as access logs and config dump from the failed traffic. Otherwise this may be challenging to debug

**Comment by oranje42** [comment]
Sure. I did some further investigation and to me it looks like that the containers are not able to access the Kubernetes API server any longer (running at https://172.20.0.1:443). The two pods mentioned in the bug description both try to access the API server during their startup phase. Since this is failing now (for Istio v.1.6.6), the pods are entering CrashLoopBackOff.

To verify this behavior, I just run another test:
1) Exec into a container (kubectl exec) that has curl installed and that is proxied by an Istio sidecar
2) Run `curl -k https://172.20.0.1:443/version?timeout=32s`

For Istio v1.6.5 I'm getting the following response:
```
{
  "major": "1",
  "minor": "17+",
  "gitVersion": "v1.17.6-eks-4e7f64",
  "gitCommit": "4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c",
  "gitTreeState": "clean",
  "buildDate": "2020-06-11T13:55:35Z",
  "goVersion": "go1.13.9",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

After upgrading to Istio v1.6.6 and following exactly the same procedure, I'm getting this one:
```
curl: (35) Unknown SSL protocol error in connection to 172.20.0.1:443
```

**Comment by howardjohn** [comment]
@oranje42 I tried this and it works for me. Can you add config dump and access logs from the fail request? https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by cober** [comment]
@howardjohn we are observing very same issue as well, running istio 1.6.6 on GKE 1.16.13-gke.1, some services are failing but not all and happened after update to 1.6.6

**Comment by tcondeixa** [comment]
We are having the same problem also with EKS 1.17 and Istio 1.6.6, so we went back to 1.6.5. We have a PodSecurityPolicy to k8s api, but all pods trying to reach the k8s api are failing.

**Comment by howardjohn** [comment]
And anymore info about install setup would help to (strict mtls enabled, etc)

**Comment by cober** [comment]
@howardjohn we are seeing failures only to the api-server.

What I spotted is that if you call straight away public IP (api-master) everything works fine, but if it goes through kubernetes.default.svc.cluster.local or kubernetes.default.svc, it might or might not fail. Public IP works all the time, even a simple curl command can be run in order to check that. Something like that:

```
 export CA_CERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
 export TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
 export NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

curl --cacert $CA_CERT -H "Authorization: Bearer $TOKEN" "https://kubernetes.default.svc/api/v1/namespaces/$NAMESPACE/services/"
```


kube-state-metrics is crashing constantly for example, while totally different pod is up and running but all calls to the api-server are failing. What is weird is that issue is not happening on another cluster, while the same apps and istio version is running.

```
k logs metrics-kube-state-metrics-699cdbfd79-9ztcg  kube-state-metrics
I0730 16:50:26.978169       1 main.go:89] Using collectors certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses
I0730 16:50:26.978222       1 main.go:98] Using all namespace
I0730 16:50:26.978238       1 main.go:139] metric white-blacklisting: blacklisting the following items:
W0730 16:50:26.978269       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0730 16:50:26.980061       1 main.go:184] Testing communication with server
F0730 16:50:26.980971       1 main.go:147] Failed to create client: error while trying to communicate with apiserver: Get https://10.51.240.1:443/version?timeout=32s: EOF
```

```
Exec Failure\njavax.net.ssl.SSLHandshakeException: Remote host terminated the handshake\n\tat java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1320)\n\tat java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1159)\n\tat java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)\n\tat java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)\n\tat okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)\n\tat okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)\n\tat okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)\n\tat okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)\n\tat okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)\n\tat okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:134)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:112)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)\n\tat okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)\n\tat okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.io.EOFException: SSL peer shut down incorrectly
```

We do have some PeerAuthentication policies set in order to disable mTLS, but didn't help in this case.

```
r>kubectl get peerauthentication -A
NAMESPACE                 NAME           AGE
default                   mtls-disable   168m
kafka                     mtls-disable   58d
production-task-manager   mtls-disable   5h26m
redis                     mtls-disable   58d
```

**Comment by tcondeixa** [comment]
I'm not sure what was affected because the apps are using the api to get configMaps, so they were not able to start.
We are setting mtls as PERMISSIVE for the namespaces and I also added a DestinationRule to disable tls for host '*.NAMESPACE.svc.cluster.local'.

**Comment by howardjohn** [comment]
I can reproduce the original kube dashboard error on 1.6.5 actually:
```
2020/07/30 17:26:05 Starting overwatch
2020/07/30 17:26:05 Using namespace: dashboard
2020/07/30 17:26:05 Using in-cluster config to connect to apiserver
2020/07/30 17:26:05 Using secret token for csrf signing
2020/07/30 17:26:05 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: Get "https://10.0.0.1:443/api/v1/namespaces/dashboard/secrets/kubernetes-dashboard-csrf": dial tcp 10.0.0.1:443: connect: connection refused

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc0000a65c0)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:41 +0x446
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc00050c100)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:501 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc00050c100)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:469 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
        /home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:550
main.main()
        /home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:105 +0x20d
```

Seems like https://github.com/istio/istio/issues/11130

**Comment by howardjohn** [comment]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - args:
        - bash
        - -c
        - |
          export CA_CERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          export TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          export NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          for i in {0..1000}; do
            echo attempt $i
            curl --cacert $CA_CERT -H "Authorization: Bearer $TOKEN" "https://kubernetes.default.svc/api/v1/namespaces/$NAMESPACE/services/" && break
            sleep .1
          done
          sleep 100000
        image: howardjohn/alpine-shell
        imagePullPolicy: Always
        name: shell

```

Gets ~10 failures at startup then succeeds in 1.6.5

**Comment by howardjohn** [comment]
Ok actually I think I reproduced it on 1.6.6. will update with my findings

**Comment by howardjohn** [comment]
```
2020-07-30T17:43:26.137861Z     debug   envoy filter    [external/envoy/source/extensions/filters/listener/original_dst/original_dst.cc:18] original_dst: New connection accepted
2020-07-30T17:43:26.137930Z     debug   envoy filter    [external/envoy/source/common/tcp_proxy/tcp_proxy.cc:251] [C143] new tcp proxy session
2020-07-30T17:43:26.137948Z     debug   envoy filter    [external/envoy/source/common/tcp_proxy/tcp_proxy.cc:395] [C143] Creating connection to cluster outbound|443||kubernetes.default.svc.cluster.local
2020-07-30T17:43:26.137968Z     debug   envoy upstream  [external/envoy/source/common/upstream/cluster_manager_impl.cc:1288] no healthy host for TCP connection pool
2020-07-30T17:43:26.137974Z     debug   envoy connection        [external/envoy/source/common/network/connection_impl.cc:109] [C143] closing data_to_write=0 type=1
2020-07-30T17:43:26.137979Z     debug   envoy connection        [external/envoy/source/common/network/connection_impl.cc:200] [C143] closing socket: 1
```

debug logs

If I add a Sidecar to not import the kubernetes.default.svc it works fine, so something in the cluster/listener is likely breaking. https://github.com/istio/envoy/pull/235 is only envoy change

**Comment by howardjohn** [comment]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-shell
spec:
  selector:
    matchLabels:
      app: old-shell
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyImage: istio/proxyv2:1.6.5
      labels:
        app: old-shell
    spec:
      containers:
      - args:
        - bash
        - -c
        - |
          export CA_CERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          export TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          export NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          for i in {0..1000}; do
            echo attempt $i
            curl --cacert $CA_CERT -H "Authorization: Bearer $TOKEN" "https://kubernetes.default.svc/api/v1/namespaces/$NAMESPACE/services/" && break
            sleep .1
          done
          sleep 100000
        image: howardjohn/alpine-shell
        imagePullPolicy: Always
        name: shell
```

is also broken (1.6.5 image), suggesting pilot regression?

**Comment by howardjohn** [comment]
Likely https://github.com/istio/istio/commit/fd8dda96249046c020b6f6a204ed8c4b0696e4e1 root cause

**Comment by howardjohn** [comment]
Confirmed broken in master and 1.6.6 by bae28dde42

**Comment by howardjohn** [comment]
View impacted endpoints: `kubectl get endpoints -A -ojson | jq -r '.items[] | select(.subsets[]?.addresses[]?.targetRef == null) | .metadata.namespace + "/" + .metadata.name'`

**Comment by brian-avery** [comment]
Fixed in https://github.com/istio/istio/pull/25978

**Comment by oranje42** [comment]
@howardjohn @brian-avery: After upgrading to v1.6.7 everything works again as expected, thank you very much!

**Comment by howardjohn** [comment]
No problem, thanks for all the info to help track this down
