### ISSUE TITLE
Can not regenerate mixer fiels - mixer_codegen.sh panics

### ISSUE THREAD

**Issue by dpacierpnik** [istio/istio#2644]
I would like to regenerate mixer files, but mixer_codegen.sh script does not work - ends with panic.

Istio from master branch (commit eb443d3a429622b5e600664ebe48ab0133f069c6)
OS: Ubuntu 17.10
Steps to reproduce:
`cd bin; ./mixer_codegen.sh`
Output:
```Building protoc-gen-gogoslick...
~/Programming/go/src/istio.io/istio ~/Programming/go/src/istio.io/istio/bin
~/Programming/go/src/istio.io/istio/bin
Done.
Building protoc-min-version...
~/Programming/go/src/istio.io/istio ~/Programming/go/src/istio.io/istio/bin
~/Programming/go/src/istio.io/istio/bin
Done.
Pull down source protos from googleapis...
panic: version string returned from protoc is seperated with a space: 

goroutine 1 [running]:
istio.io/istio/vendor/github.com/gogo/protobuf/version.Get(0x90, 0x7fff7978edc3)
	/home/gorilla/Programming/go/src/istio.io/istio/vendor/github.com/gogo/protobuf/version/version.go:43 +0x1a1
istio.io/istio/vendor/github.com/gogo/protobuf/version.AtLeast(0x7fff7978edc3, 0x5, 0xa)
	/home/gorilla/Programming/go/src/istio.io/istio/vendor/github.com/gogo/protobuf/version/version.go:77 +0x22
main.main()
	/home/gorilla/Programming/go/src/istio.io/istio/vendor/github.com/gogo/protobuf/protoc-min-version/minversion.go:55 +0xc3
```

**Comment by douglas-reid** [comment]
Sorry. To regenerate mixer files, please run: `go generate ./mixer/...` the `mixer_codegen.sh` script is not meant to be run directly.
