### ISSUE TITLE
Process to setup customized build pipeline for istio

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [istio/istio#26595]
We currently use istio service mesh with some customizations on our end. We are planning on setting up an automated build pipeline using our internal build tools. Can you please point me to any documentation that will help me understand the internal istio build process better and give me a starting point for setting up the build pipeline?

**Comment by fpesce** [comment]
Have you considered cloning and looking into github.com/istio/release-builder ?
Specifically https://github.com/istio/release-builder/blob/master/release/build.sh

**Comment by psikka1** [comment]
the `build.sh` looks for  `GOOGLE_APPLICATION_CREDENTIALS`
```
./release/build.sh: line 22: GOOGLE_APPLICATION_CREDENTIALS: unbound variable
```
I was able to follow the instructions in the readme and run 
```
./common/scripts/run.sh /bin/bash -c "mkdir -p /tmp/istio-release; go run main.go build --manifest example/manifest-1.yaml; go run main.go validate --release /tmp/istio-release/out"
```

Had to set `ignoreVulnerability: true` in the manifest.

Now my build is failing with the below error:

```
Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
/usr/local/lib/ruby/gems/2.6.0/gems/fpm-1.11.0/lib/fpm/util.rb:29: warning: Insecure world writable dir /gobin in PATH, mode 040777
Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag {:level=>:warn}
Created package {:path=>"/work/out/linux_amd64/release/istio-sidecar.deb"}
2020-09-16T19:01:11.800143Z     info    Copying /tmp/istio-release/work/src/istio.io/istio/out/linux_amd64/release/istio-sidecar.deb -> /tmp/istio-release/out/deb/istio-sidecar.deb
Error: failed to build: failed to build Debian: failed to package istio-sidecar.deb: failed to open file /tmp/istio-release/work/src/istio.io/istio/out/linux_amd64/release/istio-sidecar.deb to copy: open /tmp/istio-release/work/src/istio.io/istio/out/linux_amd64/release/istio-sidecar.deb: no such file or directory
exit status 1
2020-09-16T19:01:15.059514Z     info    test temporary dir at /tmp/release-test273445767
panic: failed to read manifest file: open /tmp/istio-release/out/manifest.yaml: no such file or directory

goroutine 1 [running]:
istio.io/release-builder/pkg/validate.NewReleaseInfo(0x7ffd6ccac85e, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /work/pkg/validate/validate.go:47 +0x57c
istio.io/release-builder/pkg/validate.CheckRelease(0x7ffd6ccac85e, 0x16, 0xc00028cf50, 0xc00027fd98, 0x5b3f87, 0xc000118b00, 0xc00027fd70, 0xc00027fd98, 0xc00027fd98, 0x559024)
        /work/pkg/validate/validate.go:74 +0x59
istio.io/release-builder/pkg/validate.glob..func1(0x11a2fe0, 0xc00000f0e0, 0x0, 0x2, 0x0, 0x0)
        /work/pkg/validate/cmd.go:36 +0x4b
github.com/spf13/cobra.(*Command).execute(0x11a2fe0, 0xc00000f0a0, 0x2, 0x2, 0x11a2fe0, 0xc00000f0a0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:762 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002bef00, 0x3, 0x3, 0xc0002bef00)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
main.main()
        /work/main.go:25 +0x76
exit status 2
```

@fpesce - can you give any clue to what needs to be done here?
