### ISSUE TITLE
istio-cni fails iptables-restore on Azure AKS with Azure networking after node update (Istio 1.7.2)

### ISSUE THREAD

**Issue by anyname2** [istio/istio#27771]
**Bug description**
When istio is installed with `cni` enabled on **Azure AKS** cluster with **Azure (Advanced)** networking, pod creation fails with:
```log
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "<long id>" network for pod "<pod name>": networkPlugin cni failed to set up pod "<pod name>" network: exit status 2
```

Below is the relevant log from the kubelet (`journalctl -xu kubelet`):
```log
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15020,15021,15090
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=15020
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

Writing following contents to rules file:  /tmp/iptables-rules-1601906285021420100.txt166544859
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1601906285021420100.txt166544859
iptables-restore: line 2 failed
iptables-save 
# Generated by iptables-save v1.6.1 on Mon Oct  5 13:58:05 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Mon Oct  5 13:58:05 2020
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0xd81528, 0x95642a, 0x10, 0xc00000c3e0, 0x2, 0x2)
    istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc000115d58, 0x7fba0b062101, 0x0, 0x0)
    istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:544 +0x387
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc000115d58)
    istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:551 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc000115d58)
    istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:489 +0x2d78
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0xd4e080, 0xc0000daea0, 0x0, 0x12)
    istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:66 +0x148
github.com/spf13/cobra.(*Command).execute(0xd4e080, 0xc0000be010, 0x12, 0x13, 0xd4e080, 0xc0000be010)
    github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xd4e080, 0x405b4f, 0xc000094058, 0x0)
    github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
    github.com/spf13/cobra@v1.0.0/command.go:887
istio.io/istio/tools/istio-iptables/pkg/cmd.Execute()
    istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:315 +0x2d
main.main()
    istio.io/istio/tools/istio-iptables/main.go:22 +0x20
",
"error": "exit status 2"
```

This starts to fails after updating & rebooting the node (automatic update, or can be forced with the command). The following packages are updated:
```bash
blobfuse/bionic 1.3.4 amd64 [upgradable from: 1.1.1]
cifs-utils/bionic-updates 2:6.8-1ubuntu1.1 amd64 [upgradable from: 2:6.8-1ubuntu1]
libwbclient0/bionic-updates,bionic-security 2:4.7.6+dfsg~ubuntu-0ubuntu2.20 amd64 [upgradable from: 2:4.7.6+dfsg~ubuntu-0ubuntu2.19]
moby-cli/bionic 19.03.13+azure-1 amd64 [upgradable from: 19.03.12+azure-1]
moby-engine/bionic 19.03.13+azure-1 amd64 [upgradable from: 19.03.12+azure-2]
moby-runc/bionic 1.0.0~rc92+azure-2 amd64 [upgradable from: 1.0.0~rc92+azure-1]
ntp/bionic-updates,bionic-security 1:4.2.8p10+dfsg-5ubuntu7.3 amd64 [upgradable from: 1:4.2.8p10+dfsg-5ubuntu7.2]
python-samba/bionic-updates,bionic-security 2:4.7.6+dfsg~ubuntu-0ubuntu2.20 amd64 [upgradable from: 2:4.7.6+dfsg~ubuntu-0ubuntu2.19]
samba-common/bionic-updates,bionic-security 2:4.7.6+dfsg~ubuntu-0ubuntu2.20 all [upgradable from: 2:4.7.6+dfsg~ubuntu-0ubuntu2.19]
samba-common-bin/bionic-updates,bionic-security 2:4.7.6+dfsg~ubuntu-0ubuntu2.20 amd64 [upgradable from: 2:4.7.6+dfsg~ubuntu-0ubuntu2.19]
samba-libs/bionic-updates,bionic-security 2:4.7.6+dfsg~ubuntu-0ubuntu2.20 amd64 [upgradable from: 2:4.7.6+dfsg~ubuntu-0ubuntu2.19]
shim/bionic-updates 15+1552672080.a4a1fbe-0ubuntu2 amd64 [upgradable from: 15+1533136590.3beb971-0ubuntu1]
shim-signed/bionic-updates 1.37~18.04.8+15+1552672080.a4a1fbe-0ubuntu2 amd64 [upgradable from: 1.37~18.04.6+15+1533136590.3beb971-0ubuntu1]
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Pod with injected istio container successfully starts on Azure AKS with Azure networking.

**Steps to reproduce the bug**
1. Create Azure AKS cluster with Kubenet (basic) networking
2. Install istio using `istioctl install -f` with the following config:
    ```yaml
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    spec:
      profile: default
      tag: 1.7.2-distroless
      components:
        cni:
          enabled: true
        ingressGateways:
          - enabled: false
            name: istio-ingressgateway
      values:
        cni:
          excludeNamespaces:
          - istio-system
          - kube-system
          - kube-public
          - kube-node-lease
    ```
3. Add `istio-injection: enabled` label to a namespace
4. Create a deployment in the namespace (pod will start successfully)
5. SSH into the node: https://docs.microsoft.com/en-us/azure/aks/ssh
6. Update the node and reboot:
    ```bash
    sudo apt-get update && sudo apt-get upgrade && sudo reboot
    ```
7. Delete the pod or create a new deployment (the pod will fail to be created)

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
* `istioctl version --remote`
    ```bash
    client version: 1.7.2
    control plane version: 1.7.2
    data plane version: 1.7.2 (43 proxies)
    ```
* `kubectl version --short`
    ```bash
    Client Version: v1.18.9
    Server Version: v1.18.8
    ```

**How was Istio installed?**
`istioctl install` (see reproduction step 2 for details)

**Environment where bug was observed (cloud vendor, OS, etc)**
* Cloud: Azure AKS
* Networking: Azure (advanced)
* OS: `Ubuntu 18.04.5 LTS`
* Kernel: `5.4.0-1026-azure`
* Container Runtime: `docker://19.3.13` (after update, before update `docker://19.3.12`)

**Comment by anyname2** [comment]
`/var/log/azure-vnet.log` seems to suggest there is no available IP addesses

```log
2020/10/17 19:32:54 [22187] Connected to telemetry service
2020/10/17 19:32:54 [22187] [cni-net] Plugin azure-vnet version v1.1.6.
2020/10/17 19:32:54 [22187] [cni-net] Running on Linux version 5.4.0-1026-azure (buildd@lcy01-amd64-004) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #26~18.04.1-Ubuntu SMP Thu Sep 10 16:19:25 UTC 2020
2020/10/17 19:32:54 [22187] [Azure-Utils] iptables --version
2020/10/17 19:32:54 [22187] [cni-net] iptable version:iptables v1.6.1, err:<nil>
2020/10/17 19:32:54 [22187] [Azure-Utils] ebtables --version
2020/10/17 19:32:54 [22187] [cni-net] ebtable version ebtables v2.0.10-4 (December 2011), err:<nil>
2020/10/17 19:32:54 [22187] [net] Network interface: {Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback} with IP: [127.0.0.1/8 ::1/128]
2020/10/17 19:32:54 [22187] [net] Network interface: {Index:2 MTU:1500 Name:eth0 HardwareAddr:00:22:48:3f:44:28 Flags:up|broadcast} with IP: [fe80::222:48ff:fe3f:4428/64]
2020/10/17 19:32:54 [22187] [net] Network interface: {Index:3 MTU:1500 Name:enP1s1 HardwareAddr:00:22:48:3f:44:28 Flags:up|broadcast|multicast} with IP: []
2020/10/17 19:32:54 [22187] [net] Network interface: {Index:4 MTU:1500 Name:azure0 HardwareAddr:00:22:48:3f:44:28 Flags:up|broadcast|multicast} with IP: [10.240.0.4/16 fe80::222:48ff:fe3f:4428/64]
2020/10/17 19:32:54 [22187] [net] Network interface: {Index:7 MTU:1500 Name:docker0 HardwareAddr:02:42:41:e2:b2:48 Flags:up|broadcast|multicast} with IP: [172.17.0.1/16]
2020/10/17 19:32:54 [22187] [net] reboot time 2020-10-17 18:15:52 +0000 UTC store mod time 2020-10-17 18:41:16.163619246 +0000 UTC
2020/10/17 19:32:54 [22187] [net] Restored state, &{Version:v1.1.6 TimeStamp:2020-10-17 18:41:16.162999111 +0000 UTC ExternalInterfaces:map[eth0:0xc000158b00] store:0xc00006f230 Mutex:{state:1 sema:0}}
2020/10/17 19:32:54 [22187] External Interface &{Name:eth0 Networks:map[azure:0xc000167c70] Subnets:[10.240.0.0/16] BridgeName:azure0 DNSInfo:{Suffix:cqt0ytf1diperaoh4zizd3xqmf.zx.internal.cloudapp.net Servers:[168.63.129.16] Options:[]} MacAddress:00:22:48:3f:44:28 IPAddresses:[10.240.0.4/16] Routes:[0xc0004b0ab0] IPv4Gateway:10.240.0.1 IPv6Gateway:::}
2020/10/17 19:32:54 [22187] Number of endpoints: 110
2020/10/17 19:32:54 [22187] [cni-net] Plugin started.
2020/10/17 19:32:54 [22187] [cni-net] Processing ADD command with args {ContainerID:71dcf3b46d7841c8e905cd02e848cfef3aaa448ea13105034fff35c80d060492 Netns:/var/run/netns/cni-b9525dcd-e7da-b7a0-e092-4edd96542ae2 IfName:eth0 Args:K8S_POD_NAMESPACE=dri-dev;K8S_POD_NAME=nginx-6f5f6fd799-cjwr9;K8S_POD_INFRA_CONTAINER_ID=71dcf3b46d7841c8e905cd02e848cfef3aaa448ea13105034fff35c80d060492;IgnoreUnknown=1 Path:/opt/cni/bin StdinData:{"bridge":"azure0","cniVersion":"0.3.0","ipam":{"type":"azure-vnet-ipam"},"ipsToRouteViaHost":["169.254.20.10"],"mode":"bridge","name":"azure","type":"azure-vnet"}}.
2020/10/17 19:32:54 [22187] [cni-net] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: InfraVnetAddressSpace: IPV6Mode: ServiceCidrs: VnetCidrs: PodNamespaceForDualNetwork:[] IPsToRouteViaHost:[169.254.20.10] MultiTenancy:false EnableSnatOnHost:false EnableExactMatchForPodName:false DisableHairpinOnHostInterface:false DisableIPTableLock:false CNSUrl: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RuntimeConfig:{PortMappings:[] DNS:{Servers:[] Searches:[] Options:[]}} AdditionalArgs:[]}.
2020/10/17 19:32:54 [22187] Get number of endpoints for ifname eth0 network azure
2020/10/17 19:32:54 [22187] Result from multitenancy <nil>
2020/10/17 19:32:54 [22187] Trying to retrieve endpoint id 71dcf3b4-eth0
2020/10/17 19:32:54 [22187] [cni-net] Found network azure with subnet 10.240.0.0/16.
2020/10/17 19:32:54 [22187] [cni] Calling plugin azure-vnet-ipam ADD nwCfg:&{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: InfraVnetAddressSpace: IPV6Mode: ServiceCidrs: VnetCidrs: PodNamespaceForDualNetwork:[] IPsToRouteViaHost:[169.254.20.10] MultiTenancy:false EnableSnatOnHost:false EnableExactMatchForPodName:false DisableHairpinOnHostInterface:false DisableIPTableLock:false CNSUrl: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.240.0.0/16 Address: QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RuntimeConfig:{PortMappings:[] DNS:{Servers:[] Searches:[] Options:[]}} AdditionalArgs:[]}.
2020/10/17 19:32:54 [22187] [cni] Plugin azure-vnet-ipam returned result:<nil>, err:Failed to allocate address: No available addresses.
2020/10/17 19:32:54 [22187] [azure-vnet] Failed to allocate pool: Failed to delegate: Failed to allocate address: No available addresses.
2020/10/17 19:32:54 [22187] [cni-net] ADD command completed with result:Interfaces:[{Name:eth0 Mac: Sandbox:}], DNS:{Nameservers:[] Domain: Search:[] Options:[]} err:Failed to allocate pool: Failed to delegate: Failed to allocate address: No available addresses.
2020/10/17 19:32:54 [22187] Failed to execute network plugin, err:Failed to allocate pool: Failed to delegate: Failed to allocate address: No available addresses.
2020/10/17 19:32:54 [22187] [cni-net] Plugin stopped.
2020/10/17 19:32:54 [22187] Report plugin error
```

**Comment by anyname2** [comment]
Istio CNI plugin config (` /etc/cni/net.d/10-azure.conflist`) gets duplicated every time node reboots.
The following gets added to the config at each reboot. After rebooting the node 3 times the file contains `istio-cni` config 4 times. 
```json
    {
      "kubernetes": {
        "cni_bin_dir": "/opt/cni/bin",
        "exclude_namespaces": [
          "istio-system",
          "kube-system",
          "kube-public",
          "kube-node-lease"
        ],
        "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig"
      },
      "log_level": "debug",
      "name": "istio-cni",
      "type": "istio-cni"
    }
```

<details>
<summary>Full Config:</summary>
<p>

```json
{
  "cniVersion": "0.3.0",
  "name": "azure",
  "plugins": [
    {
      "bridge": "azure0",
      "ipam": {
        "type": "azure-vnet-ipam"
      },
      "ipsToRouteViaHost": [
        "169.254.20.10"
      ],
      "mode": "bridge",
      "type": "azure-vnet"
    },
    {
      "capabilities": {
        "portMappings": true
      },
      "snat": true,
      "type": "portmap"
    },
    {
      "kubernetes": {
        "cni_bin_dir": "/opt/cni/bin",
        "exclude_namespaces": [
          "istio-system",
          "kube-system",
          "kube-public",
          "kube-node-lease"
        ],
        "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig"
      },
      "log_level": "debug",
      "name": "istio-cni",
      "type": "istio-cni"
    },
    {
      "kubernetes": {
        "cni_bin_dir": "/opt/cni/bin",
        "exclude_namespaces": [
          "istio-system",
          "kube-system",
          "kube-public",
          "kube-node-lease"
        ],
        "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig"
      },
      "log_level": "debug",
      "name": "istio-cni",
      "type": "istio-cni"
    },
    {
      "kubernetes": {
        "cni_bin_dir": "/opt/cni/bin",
        "exclude_namespaces": [
          "istio-system",
          "kube-system",
          "kube-public",
          "kube-node-lease"
        ],
        "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig"
      },
      "log_level": "debug",
      "name": "istio-cni",
      "type": "istio-cni"
    },
    {
      "kubernetes": {
        "cni_bin_dir": "/opt/cni/bin",
        "exclude_namespaces": [
          "istio-system",
          "kube-system",
          "kube-public",
          "kube-node-lease"
        ],
        "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig"
      },
      "log_level": "debug",
      "name": "istio-cni",
      "type": "istio-cni"
    }
  ]
}
```

</p>
</details>

**Comment by anyname2** [comment]
Fixing the issue with configs allows the pod to be created, but now istio-proxy fails.

```diff
diff --git a/cni/pkg/install-cni/pkg/install/cniconfig.go b/cni/pkg/install-cni/pkg/install/cniconfig.go
index 4b4abe943e..ac37ffa9aa 100644
--- a/cni/pkg/install-cni/pkg/install/cniconfig.go
+++ b/cni/pkg/install-cni/pkg/install/cniconfig.go
@@ -306,6 +306,18 @@ func insertCNIConfig(newCNIConfig, existingCNIConfig []byte) ([]byte, error) {
                if err != nil {
                        return nil, fmt.Errorf("existing CNI config: %v", err)
                }
+
+               for i, rawPlugin := range plugins {
+                       plugin, err := util.GetPlugin(rawPlugin)
+                       if err != nil {
+                               return nil, fmt.Errorf("existing CNI plugin: %v", err)
+                       }
+                       if plugin["type"] == "istio-cni" {
+                               plugins = append(plugins[:i], plugins[i+1:]...)
+                               break
+                       }
+               }
+
                newMap["plugins"] = append(plugins, istioMap)
        }
```


Here is the log from `istio-proxy`:
```log
error	cache	resource:default request:5bf7dc5f-4ff7-4069-9b85-1fe959cf1368 CSR retrial timed out: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.0.0.10:53: read udp 10.240.0.18:48737->10.0.0.10:53: i/o timeout"
error	cache	resource:default failed to generate secret for proxy: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.0.0.10:53: read udp 10.240.0.18:48737->10.0.0.10:53: i/o timeout"
error	sds	resource:default Close connection. Failed to get secret for proxy "sidecar~10.240.0.18~nginx-6f5f6fd799-lfdk9.test~test.svc.cluster.local" from secret cache: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.0.0.10:53: read udp 10.240.0.18:48737->10.0.0.10:53: i/o timeout"
info	sds	resource:default connection is terminated: rpc error: code = Canceled desc = context canceled
warning	envoy config	StreamSecrets gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.0.0.10:53: read udp 10.240.0.18:48737->10.0.0.10:53: i/o timeout"
warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, no healthy upstream
warning	envoy config	Unable to establish new stream

```
