### ISSUE TITLE
Istiod crash on namespace controller

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27944]
```
2020-10-14T16:20:10.883777Z     info    ads     ADS: new connection for node:sidecar~10.88.5.161~svc00-0-8-0-645d6c7dcb-q7h24.service-graph00~service-graph00.svc.cluster.local-509
2020-10-14T16:20:10.885382Z     info    ads     CDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:38
2020-10-14T16:20:10.885630Z     info    ads     NDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:1
2020-10-14T16:20:10.885779Z     info    ads     EDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:34 empty:0 cached:34/34
2020-10-14T16:20:10.887008Z     info    ads     LDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:18
2020-10-14T16:20:10.887791Z     info    ads     RDS: PUSH for node:svc00-0-8-0-645d6c7dcb-q7h24.service-graph00 resources:7
2020-10-14T16:20:10.930942Z     info    ads     ADS: "10.88.2.135:51136"  terminated rpc error: code = Canceled desc = context canceled
2020-10-14T16:20:10.981982Z     info    ads     ADS: "10.88.9.214:44208"  terminated rpc error: code = Canceled desc = context canceled
2020-10-14T16:20:11.031681Z     info    ads     ADS: "10.88.9.151:40838"  terminated rpc error: code = Canceled desc = context canceled
2020-10-14T16:20:11.082305Z     info    klog    successfully acquired lease istio-system/istio-leader
2020-10-14T16:20:11.082436Z     info    Starting ingress controller
2020-10-14T16:20:11.132149Z     info    ads     ADS: new connection for node:sidecar~10.88.2.116~svc14-0-1-668fc64696-qms9r.service-graph14~service-graph14.svc.cluster.local-510
2020-10-14T16:20:11.133761Z     info    ads     CDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:38
2020-10-14T16:20:11.133982Z     info    ads     NDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:1
2020-10-14T16:20:11.134138Z     info    ads     EDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:34 empty:0 cached:34/34
2020-10-14T16:20:11.135637Z     info    ads     LDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:18
2020-10-14T16:20:11.136513Z     info    ads     RDS: PUSH for node:svc14-0-1-668fc64696-qms9r.service-graph14 resources:7
2020-10-14T16:20:11.183144Z     info    klog    successfully acquired lease istio-system/istio-validation-controller-election
2020-10-14T16:20:11.183292Z     info    Starting validation controller
2020-10-14T16:20:11.183364Z     info    validationController    Reconcile(enter): initial request to kickstart reconciliation
2020-10-14T16:20:11.183957Z     info    validationController    validatingwebhookconfiguration istiod-istio-system (failurePolicy=Fail, resourceVersion=11245206) is up-to-date. No change required.
2020-10-14T16:20:11.233728Z     info    ads     ADS: new connection for node:sidecar~10.88.6.224~svc03-0-4-658d4c6ffd-nslxc.service-graph03~service-graph03.svc.cluster.local-511
2020-10-14T16:20:11.235321Z     info    ads     CDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:38
2020-10-14T16:20:11.235467Z     info    ads     EDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:34 empty:0 cached:34/34
2020-10-14T16:20:11.235827Z     info    ads     NDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:1
2020-10-14T16:20:11.237191Z     info    ads     LDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:18
2020-10-14T16:20:11.237997Z     info    ads     RDS: PUSH for node:svc03-0-4-658d4c6ffd-nslxc.service-graph03 resources:7
2020-10-14T16:20:11.282211Z     info    klog    successfully acquired lease istio-system/istio-namespace-controller-election
2020-10-14T16:20:11.282345Z     info    Namespace controller started
panic: queue can not be run twice

goroutine 19400 [running]:
istio.io/istio/pkg/queue.(*queueImpl).Run(0xc001e0efa0, 0xc008fb9080)
        istio.io/istio/pkg/queue/instance.go:76 +0x36a
created by istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*NamespaceController).Run
        istio.io/istio/pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go:125 +0x14c

```

**Comment by howardjohn** [comment]
this was from https://github.com/istio/istio/pull/27823 - it could be just from that PR but I don't see how

**Comment by bianpengyuan** [comment]
Without #27823, it does not crash?

**Comment by tbarrella** [comment]
It seems due to [this](https://github.com/istio/istio/pull/25965/files#diff-91e0a18a58ea36d2c656d7b2706c52917a74103820c07fc843f48a110c847678R1009) opening up a possibility for a situation where after leader election stops, the queue isn't closed by the time leader election starts again. I haven't spent enough time to figure out how to ensure the queue is closed first

**Comment by howardjohn** [comment]
I think this was happening only on startup and in a large cluster, so I am not sure it was losing leader election than gaining it again. Unless, it was under heavy load and throttling so it lost leader election? That is pretty likely actually, I noticed I was having up to 30s of throttling to api-server

**Comment by hzxuzhonghu** [comment]
As seen from the log "Namespace controller started", only start the controller and run the queue once.

**Comment by tbarrella** [comment]
(I concluded this because there are only two places where NewNamespaceController is called, and this is the only place where Run can possibly be called more than once for the same controller, which is necessary for triggering the panic)

**Comment by hzxuzhonghu** [comment]
>Unless, it was under heavy load and throttling so it lost leader election? That is pretty likely actually, I noticed I was having up to 30s of throttling to api-server

According to this, i guess the queue is still running. And the tasks have not been empty. So when new calling will cause panic
