### ISSUE TITLE
Istiod data race

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28878]
fixed in https://github.com/istio/istio/pull/28882

<details>

```
==================
WARNING: DATA RACE
Read at 0x00c038c9c670 by goroutine 48:
  istio.io/istio/pilot/pkg/xds.recordPushTriggers()
      istio.io/istio/pilot/pkg/xds/monitoring.go:184 +0x7e
  istio.io/istio/pilot/pkg/xds.doSendPushes()
      istio.io/istio/pilot/pkg/xds/discovery.go:424 +0x1cd
  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).sendPushes()
      istio.io/istio/pilot/pkg/xds/discovery.go:473 +0x83

Previous write at 0x00c038c9c670 by goroutine 3753:
  runtime.slicecopy()
      runtime/slice.go:197 +0x0
  istio.io/istio/pilot/pkg/model.(*PushRequest).Merge()
      istio.io/istio/pilot/pkg/model/push_context.go:349 +0x162
  istio.io/istio/pilot/pkg/xds.(*PushQueue).Enqueue()
      istio.io/istio/pilot/pkg/xds/pushqueue.go:66 +0x301
  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).startPush()
      istio.io/istio/pilot/pkg/xds/ads.go:809 +0x405
  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).AdsPushAll()
      istio.io/istio/pilot/pkg/xds/ads.go:784 +0x2bd

Goroutine 48 (running) created at:
  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Start()
      istio.io/istio/pilot/pkg/xds/discovery.go:218 +0xdc
  istio.io/istio/pilot/pkg/bootstrap.(*Server).initDiscoveryService.func1()
      istio.io/istio/pilot/pkg/bootstrap/server.go:568 +0xcd
  istio.io/istio/pilot/pkg/bootstrap.(*Server).Start()
      istio.io/istio/pilot/pkg/bootstrap/server.go:365 +0x17a
  main.glob..func2()
      istio.io/istio/pilot/cmd/pilot-discovery/main.go:76 +0x18e
  encoding/json.ptrEncoder.encode()
      encoding/json/encode.go:914 +0x1b8
  encoding/json.ptrEncoder.encode-fm()
      encoding/json/encode.go:899 +0x7b
  encoding/json.(*encodeState).reflectValue()
      encoding/json/encode.go:358 +0x93
  encoding/json.(*encodeState).marshal()
      encoding/json/encode.go:330 +0xcc
  encoding/json.Marshal()
      encoding/json/encode.go:161 +0x73
  encoding/json.MarshalIndent()
      encoding/json/encode.go:176 +0x5d
  istio.io/istio/pilot/pkg/bootstrap.(*Server).initMeshConfiguration.func1()
      istio.io/istio/pilot/pkg/bootstrap/mesh.go:44 +0x3b3
  istio.io/istio/pilot/pkg/bootstrap.(*Server).initMeshConfiguration()
      istio.io/istio/pilot/pkg/bootstrap/mesh.go:53 +0x8a2
  istio.io/istio/pilot/pkg/bootstrap.NewServer()
      istio.io/istio/pilot/pkg/bootstrap/server.go:231 +0xde3
  main.glob..func2()
      istio.io/istio/pilot/cmd/pilot-discovery/main.go:70 +0xa1
  github.com/spf13/cobra.(*Command).execute()
      github.com/spf13/cobra@v1.0.0/command.go:842 +0x523
  github.com/spf13/cobra.(*Command).ExecuteC()
      github.com/spf13/cobra@v1.0.0/command.go:950 +0x499
  github.com/spf13/cobra.(*Command).Execute()
      github.com/spf13/cobra@v1.0.0/command.go:887 +0x4e
  main.main()
      istio.io/istio/pilot/cmd/pilot-discovery/main.go:190 +0x2f

Goroutine 3753 (running) created at:
  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Push()
      istio.io/istio/pilot/pkg/xds/discovery.go:270 +0x4d0
  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Push-fm()
      istio.io/istio/pilot/pkg/xds/discovery.go:267 +0x4b
  istio.io/istio/pilot/pkg/xds.debounce.func1()
      istio.io/istio/pilot/pkg/xds/discovery.go:349 +0x4f
==================
```
</details>

**Comment by howardjohn** [comment]
from 177f38187c

**Comment by howardjohn** [comment]
```
==================
WARNING: DATA RACE
Read at 0x00c03716c670 by goroutine 2822:
  istio.io/istio/pkg/kube/inject.(*Webhook).inject()
      istio.io/istio/pkg/kube/inject/webhook.go:627 +0xa59
  istio.io/istio/pkg/kube/inject.(*Webhook).serveInject()
      istio.io/istio/pkg/kube/inject/webhook.go:693 +0xcac
  istio.io/istio/pkg/kube/inject.(*Webhook).serveInject-fm()
      istio.io/istio/pkg/kube/inject/webhook.go:654 +0x5f
  net/http.HandlerFunc.ServeHTTP()
      net/http/server.go:2012 +0x51
  net/http.(*ServeMux).ServeHTTP()
      net/http/server.go:2387 +0x288
  net/http.serverHandler.ServeHTTP()
      net/http/server.go:2807 +0xce
  net/http.(*conn).serve()
      net/http/server.go:1895 +0x837

Previous write at 0x00c03716c670 by goroutine 304:
  [failed to restore the stack]

Goroutine 2822 (running) created at:
  net/http.(*Server).Serve()
      net/http/server.go:2933 +0x5b6
  net/http.(*Server).ServeTLS()
      net/http/server.go:2973 +0x3b3
  net/http.(*Server).ListenAndServeTLS()
      net/http/server.go:3130 +0x17d
  istio.io/istio/pilot/pkg/bootstrap.(*Server).Start.func4()
      istio.io/istio/pilot/pkg/bootstrap/server.go:415 +0x137

Goroutine 304 (running) created at:
  istio.io/istio/pkg/kube/inject.(*Webhook).Run()
      istio.io/istio/pkg/kube/inject/webhook.go:200 +0x92
==================
```

```
==================
WARNING: DATA RACE
Read at 0x00c03716c660 by goroutine 2822:
  istio.io/istio/pkg/kube/inject.injectRequired()
      istio.io/istio/pkg/kube/inject/inject.go:191 +0x167
  istio.io/istio/pkg/kube/inject.(*Webhook).inject()
      istio.io/istio/pkg/kube/inject/webhook.go:614 +0x96f
  istio.io/istio/pkg/kube/inject.(*Webhook).serveInject()
      istio.io/istio/pkg/kube/inject/webhook.go:693 +0xcac
  istio.io/istio/pkg/kube/inject.(*Webhook).serveInject-fm()
      istio.io/istio/pkg/kube/inject/webhook.go:654 +0x5f
  net/http.HandlerFunc.ServeHTTP()
      net/http/server.go:2012 +0x51
  net/http.(*ServeMux).ServeHTTP()
      net/http/server.go:2387 +0x288
  net/http.serverHandler.ServeHTTP()
      net/http/server.go:2807 +0xce
  net/http.(*conn).serve()
      net/http/server.go:1895 +0x837

Previous write at 0x00c03716c660 by goroutine 304:
  [failed to restore the stack]

Goroutine 2822 (running) created at:
  net/http.(*Server).Serve()
      net/http/server.go:2933 +0x5b6
  net/http.(*Server).ServeTLS()
      net/http/server.go:2973 +0x3b3
  net/http.(*Server).ListenAndServeTLS()
      net/http/server.go:3130 +0x17d
  istio.io/istio/pilot/pkg/bootstrap.(*Server).Start.func4()
      istio.io/istio/pilot/pkg/bootstrap/server.go:415 +0x137

Goroutine 304 (running) created at:
  istio.io/istio/pkg/kube/inject.(*Webhook).Run()
      istio.io/istio/pkg/kube/inject/webhook.go:200 +0x92
==================
```

**Comment by howardjohn** [comment]
```
fatal error: concurrent map read and map write

goroutine 1784 [running]:
runtime.throw(0x4148da7, 0x21)
        runtime/panic.go:1116 +0x72 fp=0xc008eea1a8 sp=0xc008eea178 pc=0x463842
runtime.mapaccess1_fast64(0x3b99a60, 0xc00107ca20, 0xc005d88c60, 0xa)
        runtime/map_fast64.go:21 +0x1d1 fp=0xc008eea1d0 sp=0xc008eea1a8 pc=0x440031
istio.io/istio/pilot/pkg/model.(*Service).GetServiceAddressForProxy(...)
        istio.io/istio/pilot/pkg/model/service.go:608
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarOutboundTCPListenerOptsForPortOrUDS(0xc0013b2c30, 0xc008eea860, 0xc008eea850, 0xc008eea698, 0xc008eeab48, 0xc008eeadf8, 0x68e4038, 0x0, 0x0, 0x410d798, ...)eneratorImpl).buildSidecarOutboundListenerForPortOrUDS(0xc0013b2c30, 0xc004d45590, 0xc000fb49a0, 0xc004d45590, 0x0, 0x0, 0x
c0062b3d40, 0x0, 0x0, 0x0, ...)g/networking/core/v1alpha3/listener.go:1386 +0x3352 fp=0xc008eeab38 sp=0xc008eea520 pc=0x36d4222
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarOutboundListeners(0xc0013b2c30, 0xc004d45590, 0xc000fb49a0, 0xc0007daf10, 0x1, 0x1)
        istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:960 +0x12ec fp=0xc008eeb178 sp=0xc008eeab38 pc=0x36cbf7c
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ListenerBuilder).buildSidecarOutboundListeners(...)
        istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener_builder.go:307
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarListeners(0xc0013b2c30, 0xc008eeb248, 0x36)
        istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:311 +0x1e2 fp=0xc008eeb208 sp=0xc008eeb178 pc=0x36c4a12
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildListeners(0xc0013b2c30, 0xc004d45590, 0xc000fb49a0, 0x36, 0xc008eeb388, 0x480843)
        istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:297 +0x1c8 fp=0xc008eeb2d0 sp=0xc008eeb208 pc=0x36c4818
istio.io/istio/pilot/pkg/xds.LdsGenerator.Generate(0xc00037c5a0, 0xc004d45590, 0xc000fb49a0, 0xc00aa2fe40, 0xc003205130, 0x3a0ca714, 0xea15e71a40ea, 0x3a0ca71408eeb3e0)
        istio.io/istio/pilot/pkg/xds/lds.go:61 +0xa7 fp=0xc008eeb368 sp=0xc008eeb2d0 pc=0x3760037
istio.io/istio/pilot/pkg/xds.(*LdsGenerator).Generate(0xc0001b6b30, 0xc004d45590, 0xc000fb49a0, 0xc00aa2fe40, 0xc003205130, 0xc007161601, 0x35, 0xc00597a340)
        <autogenerated>:1 +0x9a fp=0xc008eeb3d8 sp=0xc008eeb368 pc=0x37722ba
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).pushXds(0xc00037c5a0, 0xc004a4fd40, 0xc000fb49a0, 0x4109177, 0x1, 0xc00aa2fe40, 0xc003205130, 0x0, 0x0)
        istio.io/istio/pilot/pkg/xds/gen.go:104 +0x29d fp=0xc008eeb640 sp=0xc008eeb3d8 pc=0x375c43d
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).processRequest(0xc00037c5a0, 0xc003786f80, 0xc004a4fd40, 0x0, 0x1)
        istio.io/istio/pilot/pkg/xds/ads.go:214 +0x4cb fp=0xc008eeb760 sp=0xc008eeb640 pc=0x3733c5b
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).StreamAggregatedResources(0xc00037c5a0, 0x477f5a0, 0xc00059b090, 0x46ceb80, 0xc00037c5a0)
        istio.io/istio/pilot/pkg/xds/ads.go:286 +0x8e6 fp=0xc008eeb9c0 sp=0xc008eeb760 pc=0x3734936
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x4100600, 0xc00037c5a0, 0x476a180, 0xc0075dc6c0, 0x68e4038, 0xc005cfa000)
        github.com/envoyproxy/go-control-plane@v0.9.8-0.20201019204000-12785f608982/envoy/service/discovery/v3/ads.pb.go:298 +0xce fp=0xc008eeba10 sp=0xc008eeb9c0 pc=0x2baa50e
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0010108c0, 0x4788900, 0xc0035ef080, 0xc005cfa000, 0xc0010b7dd0, 0x68779e0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.33.1/server.go:1457 +0x15c4 fp=0xc008eebda8 sp=0xc008eeba10 pc=0x2252a14
google.golang.org/grpc.(*Server).handleStream(0xc0010108c0, 0x4788900, 0xc0035ef080, 0xc005cfa000, 0x0)
        google.golang.org/grpc@v1.33.1/server.go:1537 +0x1302 fp=0xc008eebf30 sp=0xc008eebda8 pc=0x2254cb2
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000f19d80, 0xc0010108c0, 0x4788900, 0xc0035ef080, 0xc005cfa000)
        google.golang.org/grpc@v1.33.1/server.go:871 +0xd9 fp=0xc008eebfb8 sp=0xc008eebf30 pc=0x226a779
runtime.goexit()
        runtime/asm_amd64.s:1373 +0x1 fp=0xc008eebfc0 sp=0xc008eebfb8 pc=0x498101
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.33.1/server.go:869 +0x342
```

**Comment by howardjohn** [comment]
```
==================
WARNING: DATA RACE
Write at 0x00c000fb4ab8 by goroutine 273:
  istio.io/istio/pilot/pkg/model.(*PushContext).InitContext()
      istio.io/istio/pilot/pkg/model/push_context.go:871 +0x13b
  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).StreamAggregatedResources()
      istio.io/istio/pilot/pkg/xds/ads.go:248 +0x29f
  github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler()
      github.com/envoyproxy/go-control-plane@v0.9.8-0.20201019204000-12785f608982/envoy/service/discovery/v3/ads.pb.go:298 +0xcd
  google.golang.org/grpc.(*Server).processStreamingRPC()
      google.golang.org/grpc@v1.33.1/server.go:1457 +0x15c3
  google.golang.org/grpc.(*Server).handleStream()
      google.golang.org/grpc@v1.33.1/server.go:1537 +0x1301
  google.golang.org/grpc.(*Server).serveStreams.func1.2()
      google.golang.org/grpc@v1.33.1/server.go:871 +0xd8

Previous read at 0x00c000fb4ab8 by goroutine 251:
  istio.io/istio/pilot/pkg/model.(*PushContext).initServiceRegistry()
      istio.io/istio/pilot/pkg/model/push_context.go:1069 +0x374
  istio.io/istio/pilot/pkg/model.(*PushContext).createNewContext()
      istio.io/istio/pilot/pkg/model/push_context.go:901 +0x5d
  istio.io/istio/pilot/pkg/model.(*PushContext).InitContext()
      istio.io/istio/pilot/pkg/model/push_context.go:882 +0x292
  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).StreamAggregatedResources()
      istio.io/istio/pilot/pkg/xds/ads.go:248 +0x29f
  github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler()
      github.com/envoyproxy/go-control-plane@v0.9.8-0.20201019204000-12785f608982/envoy/service/discovery/v3/ads.pb.go:298 +0xcd
  google.golang.org/grpc.(*Server).processStreamingRPC()
      google.golang.org/grpc@v1.33.1/server.go:1457 +0x15c3
  google.golang.org/grpc.(*Server).handleStream()
      google.golang.org/grpc@v1.33.1/server.go:1537 +0x1301
  google.golang.org/grpc.(*Server).serveStreams.func1.2()
      google.golang.org/grpc@v1.33.1/server.go:871 +0xd8

Goroutine 273 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      google.golang.org/grpc@v1.33.1/server.go:869 +0x341
  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      google.golang.org/grpc@v1.33.1/internal/transport/http2_server.go:448 +0x1627
  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      google.golang.org/grpc@v1.33.1/internal/transport/http2_server.go:493 +0x439
  google.golang.org/grpc.(*Server).serveStreams()
      google.golang.org/grpc@v1.33.1/server.go:855 +0x22f
  google.golang.org/grpc.(*Server).handleRawConn.func1()
      google.golang.org/grpc@v1.33.1/server.go:814 +0x4c

Goroutine 251 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      google.golang.org/grpc@v1.33.1/server.go:869 +0x341
  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      google.golang.org/grpc@v1.33.1/internal/transport/http2_server.go:448 +0x1627
  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      google.golang.org/grpc@v1.33.1/internal/transport/http2_server.go:493 +0x439
  google.golang.org/grpc.(*Server).serveStreams()
      google.golang.org/grpc@v1.33.1/server.go:855 +0x22f
  google.golang.org/grpc.(*Server).handleRawConn.func1()
      google.golang.org/grpc@v1.33.1/server.go:814 +0x4c
==================
```

**Comment by howardjohn** [comment]
I think these are all fixed. The only one I am not certain is https://github.com/istio/istio/issues/28878#issuecomment-727063637 but I don't see how it can happen. I think its fixed by the push context fix as well
