### ISSUE TITLE
status: panic in CRD discovery

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30133]
```
2021-01-15T22:38:58.559225Z     info    source  Beginning CRD Discovery, to figure out resources that are available...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x251ee41]

goroutine 3413639 [running]:
istio.io/istio/galley/pkg/config/source/kube/apiserver/status.(*state).applyMessages(0x0, 0xc01d173b08)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/status/state.go:123 +0x41
istio.io/istio/galley/pkg/config/source/kube/apiserver/status.(*ControllerImpl).Report(0xc02e2636b0, 0xc022000000, 0x11, 0x20)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/status/controller.go:144 +0x388
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*Source).Update(0xc02d4c9b80, 0xc022000000, 0x11, 0x20)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/source.go:251 +0x5d
istio.io/istio/galley/pkg/config/processing/snapshotter.(*AnalyzingDistributor).analyzeAndDistribute(0xc007c14600, 0xc029c56e40, 0xc02db52910, 0x7, 0xc01368e2a0, 0xc0212ec5d0)
        istio.io/istio/galley/pkg/config/processing/snapshotter/analyzingdistributor.go:166 +0x2ca
created by istio.io/istio/galley/pkg/config/processing/snapshotter.(*AnalyzingDistributor).Distribute
        istio.io/istio/galley/pkg/config/processing/snapshotter/analyzingdistributor.go:139 +0x23c
```

Not sure what triggered it, just left my cluster alone for a while

**Comment by howardjohn** [comment]
This has crashed 24x over 2 days

**Comment by howardjohn** [comment]
Another one, different stack trace:
```
2021-01-18T18:04:40.761227Z     info    source  Detected a CRD change while processing configuration events. Sending Reset event.
2021-01-18T18:04:40.761270Z     info    processing      session[9] "processing" => "terminating"
2021-01-18T18:04:40.779756Z     info    ads     Push debounce stable[218] 1: 100.997308ms since last change, 100.997133ms since last push, full=true
2021-01-18T18:04:40.784164Z     info    ads     XDS: Pushing:2021-01-18T18:04:40Z/216 Services:13 ConnectedEndpoints:1
2021-01-18T18:04:40.786012Z     info    ads     CDS: PUSH for node:istio-ingressgateway-5c6c4cb7c9-rc2tf.istio-system resources:29 size:27.0kB
2021-01-18T18:04:40.786127Z     info    ads     LDS: PUSH for node:istio-ingressgateway-5c6c4cb7c9-rc2tf.istio-system resources:0 size:0B
2021-01-18T18:04:41.121019Z     info    processing      session[9] "terminating" => "inactive"
2021-01-18T18:04:41.121093Z     info    processing      Runtime.run: Completing session: id:9
2021-01-18T18:04:41.121108Z     info    processing      Runtime.run: Starting new session id:10
2021-01-18T18:04:41.121118Z     info    processing      session[10] "inactive" => "starting"
2021-01-18T18:04:41.121229Z     info    processing      session.handleMeshEvent: Received initial mesh event, applying it: [Event](Added: istio/mesh/v1alpha1/MeshConfig/istio-system/meshconfig)
2021-01-18T18:04:41.121249Z     info    processing      session.handleMeshEvent: received an add/update mesh config event: [Event](Added: istio/mesh/v1alpha1/MeshConfig/istio-system/meshconfig)
2021-01-18T18:04:41.121277Z     info    processing      session.handleMeshEvent: Received initial mesh event, applying it: [Event](FullSync: istio/mesh/v1alpha1/MeshConfig)
2021-01-18T18:04:41.121292Z     info    processing      session.applyMeshEvent meshSynced: false => true
2021-01-18T18:04:41.121325Z     info    source  Beginning CRD Discovery, to figure out resources that are available...
2021-01-18T18:04:41.121323Z     error   klog    Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 23813 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x29b2f60, 0x4e08e20)
        k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:48 +0x86
panic(0x29b2f60, 0x4e08e20)
        runtime/panic.go:965 +0x1b9
istio.io/istio/galley/pkg/config/source/kube/apiserver/status.(*state).setObserved(0x0, 0xc0022bd260, 0x30, 0xc003ecd588, 0x7, 0xc003ecd590, 0xa, 0xc003ecd5c0, 0x8, 0x27fdaa0, ...)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/status/state.go:88 +0x3e
istio.io/istio/galley/pkg/config/source/kube/apiserver/status.(*ControllerImpl).UpdateResourceStatus(0xc0027f9080, 0xc0022bd260, 0x30, 0xc003ecd588, 0x7, 0xc003ecd590, 0xa, 0xc003ecd5c0, 0x8, 0x297fd00, ...)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/status/controller.go:111 +0xf8
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*watcher).handleEvent(0xc00393e820, 0x2, 0x2ecedc0, 0xc003c48d70)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/watcher.go:130 +0x414
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*watcher).start.func2(0x2ecedc0, 0xc003bb68d8, 0x2ecedc0, 0xc003c48d70)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/watcher.go:80 +0x9a
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        k8s.io/client-go@v0.20.1/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        k8s.io/client-go@v0.20.1/tools/cache/shared_informer.go:775 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0032b6760)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc004c6ff60, 0x3291a20, 0xc002106c00, 0x2920601, 0xc003eaade0)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0032b6760, 0x3b9aca00, 0x0, 0xc0032b6701, 0xc003eaade0)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc001e2e680)
        k8s.io/client-go@v0.20.1/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000be6df0, 0xc0031501a0)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:71 +0x65[]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x251e8be]

goroutine 23813 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.20.1/pkg/util/runtime/runtime.go:55 +0x109
panic(0x29b2f60, 0x4e08e20)
        runtime/panic.go:965 +0x1b9
istio.io/istio/galley/pkg/config/source/kube/apiserver/status.(*state).setObserved(0x0, 0xc0022bd260, 0x30, 0xc003ecd588, 0x7, 0xc003ecd590, 0xa, 0xc003ecd5c0, 0x8, 0x27fdaa0, ...)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/status/state.go:88 +0x3e
istio.io/istio/galley/pkg/config/source/kube/apiserver/status.(*ControllerImpl).UpdateResourceStatus(0xc0027f9080, 0xc0022bd260, 0x30, 0xc003ecd588, 0x7, 0xc003ecd590, 0xa, 0xc003ecd5c0, 0x8, 0x297fd00, ...)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/status/controller.go:111 +0xf8
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*watcher).handleEvent(0xc00393e820, 0x2, 0x2ecedc0, 0xc003c48d70)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/watcher.go:130 +0x414
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*watcher).start.func2(0x2ecedc0, 0xc003bb68d8, 0x2ecedc0, 0xc003c48d70)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/watcher.go:80 +0x9a
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        k8s.io/client-go@v0.20.1/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        k8s.io/client-go@v0.20.1/tools/cache/shared_informer.go:775 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0032b6760)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc004c6ff60, 0x3291a20, 0xc002106c00, 0x2920601, 0xc003eaade0)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0032b6760, 0x3b9aca00, 0x0, 0xc0032b6701, 0xc003eaade0)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc001e2e680)
        k8s.io/client-go@v0.20.1/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000be6df0, 0xc0031501a0)
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:71 +0x65

```

**Comment by howardjohn** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x23833b1]

goroutine 257437 [running]:
istio.io/istio/galley/pkg/config/source/kube/rt.(*Provider).GetAdapter(0x0, 0x333b548, 0xc0026bf340, 0x1)
        istio.io/istio/galley/pkg/config/source/kube/rt/provider.go:70 +0x91
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*Source).startWatchers(0xc002750840)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/source.go:196 +0x356
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*Source).onCrdEvent(0xc002750840, 0x4, 0x3325e58, 0xc00031b880, 0x0)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/source.go:167 +0x4a8
istio.io/istio/pkg/config/event.(*fnHandler).Handle(0xc006894078, 0x4, 0x3325e58, 0xc00031b880, 0x0)
        istio.io/istio/pkg/config/event/handler.go:53 +0x51
created by istio.io/istio/galley/pkg/config/source/kube/apiserver.(*watcher).start
        istio.io/istio/galley/pkg/config/source/kube/apiserver/watcher.go:92 +0x685
```
