### ISSUE TITLE
ISTIO_META_DNS_CAPTURE: "true" cannot resolve hostnames in another namespace for some applications

### ISSUE THREAD

**Issue by samene** [istio/istio#30531]
When the `ISTIO_META_DNS_CAPTURE` feature is enabled certain applications are not able to resolve service names in another namespace. For example, java 11 apps, netcat etc. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**

Install istio using ```istioctl install --profile=preview```

Create two namespaces, sample and test. Install an application like PostgreSQL Server in namespace sample and install a Postgres Client in test namespace. Deploy helloworld too in the same namespace as the postgres server namespace.

From test namespace try to reach the sample namespace service. The helloworld service is reachable over curl, but the postgres service is not and give name resolution error.

Surprisingly, if you append an extra dot at the end of the FQDN, it is resolved properly.

Disable the `ISTIO_META_DNS` and try again. It works fine.

sample tests output

```
root@ubuntu:/# kdig @127.0.0.1 -p 15053 postgres-stolon-proxy.sample.svc
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 11760
;; Flags: qr rd; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; postgres-stolon-proxy.sample.svc.  IN A

;; ANSWER SECTION:
postgres-stolon-proxy.sample.svc. 30 IN  A      10.43.137.211

;; Received 96 B
;; Time 2021-01-30 09:11:48 UTC
;; From 127.0.0.1@15053(UDP) in 0.1 ms


root@ubuntu:/# nc -zv postgres-stolon-proxy.sample.svc 5432
postgres-stolon-proxy.sample.svc: forward host lookup failed: Unknown server error : Resource temporarily unavailable
root@ubuntu:/# nc -zv postgres-stolon-proxy.sample 5432
postgres-stolon-proxy.sample: forward host lookup failed: Unknown server error : Resource temporarily unavailable

root@ubuntu:/# nc -zv postgres-stolon-proxy.sample. 5432
DNS fwd/rev mismatch: postgres-stolon-proxy.sample != postgres-stolon-proxy.sample.svc.cluster.local
postgres-stolon-proxy.sample [10.43.137.211] 5432 (?) open

root@ubuntu:/# nc -zv postgres-stolon-proxy.sample.svc.cluster.local 5432
postgres-stolon-proxy.sample.svc.cluster.local: forward host lookup failed: Unknown server error : Resource temporarily unavailable

root@ubuntu:/# nc -zv postgres-stolon-proxy.sample.svc.cluster.local. 5432
postgres-stolon-proxy.sample.svc.cluster.local [10.43.137.211] 5432 (?) open

```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

istioctl version
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (1 proxies)

kubectl version
Client Version: v1.18.12
Server Version: v1.18.10

How was Istio installed?
IstioOperator

**Comment by howardjohn** [comment]
can you add the output of `curl localhost:8080/debug/nsdz?proxyID=<POD-NAME>`?

replace pod name with the client

**Comment by howardjohn** [comment]
Run that in istiod pod

**Comment by samene** [comment]
got a 404. Do I need to put namespace too somewhere in the query

``` 
exec -it istiod-6c9bb964bc-8s7lw -n istio-system -- curl localhost:8080/debug/nsdz?proxyID=ers-mdm-schema-manager-7b5dc4844f-j2gtx
404 page not found
```

**Comment by samene** [comment]
```
[{
  "@type": "type.googleapis.com/istio.networking.nds.v1.NameTable",
  "table": {
    "cert-manager-webhook.cert-manager.svc.cluster.local": {
      "ips": [
        "10.43.149.56"
      ],
      "registry": "Kubernetes",
      "shortname": "cert-manager-webhook",
      "namespace": "cert-manager"
    },
    "cert-manager.cert-manager.svc.cluster.local": {
      "ips": [
        "10.43.27.190"
      ],
      "registry": "Kubernetes",
      "shortname": "cert-manager",
      "namespace": "cert-manager"
    },
    "elasticsearch-master-headless.elasticsearch.svc.cluster.local": {
      "ips": [
        "10.42.89.73"
      ],
      "registry": "Kubernetes",
      "shortname": "elasticsearch-master-headless",
      "namespace": "elasticsearch"
    },
    "elasticsearch-master.elasticsearch.svc.cluster.local": {
      "ips": [
        "10.43.196.99"
      ],
      "registry": "Kubernetes",
      "shortname": "elasticsearch-master",
      "namespace": "elasticsearch"
    },
    "istio-ingressgateway.istio-system.svc.cluster.local": {
      "ips": [
        "10.43.6.22"
      ],
      "registry": "Kubernetes",
      "shortname": "istio-ingressgateway",
      "namespace": "istio-system"
    },
    "istiod.istio-system.svc.cluster.local": {
      "ips": [
        "10.43.181.35"
      ],
      "registry": "Kubernetes",
      "shortname": "istiod",
      "namespace": "istio-system"
    },
    "kube-dns.kube-system.svc.cluster.local": {
      "ips": [
        "10.43.0.10"
      ],
      "registry": "Kubernetes",
      "shortname": "kube-dns",
      "namespace": "kube-system"
    },
    "kubernetes.default.svc.cluster.local": {
      "ips": [
        "10.43.0.1"
      ],
      "registry": "Kubernetes",
      "shortname": "kubernetes",
      "namespace": "default"
    },
    "metrics-server.kube-system.svc.cluster.local": {
      "ips": [
        "10.43.101.139"
      ],
      "registry": "Kubernetes",
      "shortname": "metrics-server",
      "namespace": "kube-system"
    },
    "postgres-stolon-keeper-headless.sample.svc.cluster.local": {
      "ips": [
        "10.42.89.93",
        "10.42.89.94"
      ],
      "registry": "Kubernetes",
      "shortname": "postgres-stolon-keeper-headless",
      "namespace": "sample"
    },
    "postgres-stolon-node-port.sample.svc.cluster.local": {
      "ips": [
        "10.43.14.178"
      ],
      "registry": "Kubernetes",
      "shortname": "postgres-stolon-node-port",
      "namespace": "sample"
    },
    "postgres-stolon-proxy.sample.svc.cluster.local": {
      "ips": [
        "10.43.40.67"
      ],
      "registry": "Kubernetes",
      "shortname": "postgres-stolon-proxy",
      "namespace": "sample"
    }
  }
}
```

**Comment by howardjohn** [comment]
> `dig @localhost -p 15053 postgres-stolon-proxy.sample.svc`

Is not what you want, Istio will automatically redirect queries to localhost:15053. You can just do `dig postgres-stolon-proxy.sample.svc`

Are you on a VM with system-resolved? You may be hitting https://github.com/istio/istio/issues/30309

**Comment by samene** [comment]
Same result 

```
root@ubuntu:/# dig  postgres-stolon-proxy.sample.svc

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> postgres-stolon-proxy.sample.svc
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40845
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;postgres-stolon-proxy.sample.svc. IN A

;; ANSWER SECTION:
postgres-stolon-proxy.sample.svc. 30 IN A      10.43.40.67

;; Query time: 0 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Mon Feb 01 16:55:51 UTC 2021
;; MSG SIZE  rcvd: 98

root@ubuntu:/# nslookup postgres-stolon-proxy.sample.svc
;; Warning: Message parser reports malformed message packet.
Server:  10.43.0.10
Address: 10.43.0.10#53

Non-authoritative answer:
postgres-stolon-proxy.sample.svc.test.svc.cluster.local canonical name = postgres-stolon-proxy.sample.svc.
Name:  postgres-stolon-proxy.sample.svc
Address: 10.43.40.67
** server can't find postgres-stolon-proxy.sample.svc: NXDOMAIN

root@ubuntu:/# cat /etc/resolv.conf
nameserver 10.43.0.10
search test.svc.cluster.local svc.cluster.local cluster.local devops.empirix.com openstacklocal
options ndots:5
```

Problem is that nslookup works, netcat does not.
curl to helloworld works.

I have a Java client (jdk11) using postgresql JDBC which is not able to resolve which is my main issue here.

```
org.postgresql.util.PSQLException: The connection attempt failed.
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:315)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
    at org.postgresql.Driver.makeConnection(Driver.java:465)
    at org.postgresql.Driver.connect(Driver.java:264)
    at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
    at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
    at com.postgres.redbox.core.MDMDatabaseConnection.createDBConnection(MDMDatabaseConnection.java:72)
    at com.postgres.redbox.core.MDMDatabaseConnection$1$1.getConnection(MDMDatabaseConnection.java:39)
    at com.postgres.redbox.core.MDMDbService.open(MDMDbService.java:59)
    at com.postgres.redbox.mdm.schemaUpgrade.MDMSchemaUpgradeDao.openConnection(MDMSchemaUpgradeDao.java:49)
    at com.postgres.redbox.mdm.MDMSchemaUpgradeModule.run(MDMSchemaUpgradeModule.java:78)
    at com.postgres.redbox.mdm.RbMDMConfig.performOperation(RbMDMConfig.java:202)
    at com.postgres.redbox.mdm.RbMDMConfig.run(RbMDMConfig.java:98)
    at com.postgres.redbox.mdm.RbMDMConfig.main(RbMDMConfig.java:42)
Caused by: java.net.UnknownHostException: postgres-stolon-proxy.sample.svc
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
    at org.postgresql.core.PGStream.<init>(PGStream.java:95)
    at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
    ... 14 more
```

**Comment by howardjohn** [comment]
Can you add `--log_output_level=dns:debug` to the istio-agent flags? it will show all the dns requests.

If its a vm it can be controlled by `ISTIO_AGENT_FLAGS="--log_output_level=dns:debug"`

**Comment by samene** [comment]
2021-02-01T17:16:24.663004Z     error   invalid output level '"dns:debug"'
Error: invalid output level '"dns:debug"'

**Comment by howardjohn** [comment]
I think its a quoting issue, it seems to be parsing `"dns:debug"` instead of `dns:debug`

**Comment by samene** [comment]
now this

```
2021-02-01T17:22:53.763316Z error unknown scope 'dns' specified
Error: unknown scope 'dns' specified
```

this is my version

```
  istio-proxy:
    Container ID:  docker://11c40685e4909fdc22f37914a4530dad14449f14d79b4d69979f81bac2526f56
    Image:         docker.io/istio/proxyv2:1.8.1
    Image ID:      docker-pullable://istio/proxyv2@sha256:0a407ecee363d8d31957162b82738ae3dd09690668a0168d660044ac8fc728f0
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --log_output_level=dns:debug
      --serviceCluster
      ubuntu.$(POD_NAMESPACE)
      --proxyComponentLogLevel=misc:error
      --concurrency
      2
    State:          Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 01 Feb 2021 22:53:24 +0530
      Finished:     Mon, 01 Feb 2021 22:53:24 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 01 Feb 2021 22:52:53 +0530
      Finished:     Mon, 01 Feb 2021 22:52:53 +0530
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=3s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    first-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      ubuntu (v1:metadata.name)
      POD_NAMESPACE:                 test (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"proxyMetadata":{"DNS_AGENT":"","ISTIO_META_DNS_CAPTURE":"true"}}

      ISTIO_META_POD_PORTS:          [
                                     ]
      ISTIO_META_APP_CONTAINERS:     ubuntu
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_ANNOTATIONS:    {"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{\"sidecar.istio.io/inject\":\"true\"},\"labels\":{\"app\":\"ubuntu\"},\"name\":\"ubuntu\",\"namespace\":\"test\"},\"spec\":{\"containers\":[{\"args\":[\"sleep\",\"1000000\"],\"image\":\"ubuntu:18.04\",\"name\":\"ubuntu\"}]}}\n","sidecar.istio.io/inject":"true"}

      ISTIO_META_WORKLOAD_NAME:      ubuntu
      ISTIO_META_OWNER:              kubernetes://apis/v1/namespaces/test/pods/ubuntu
      ISTIO_META_MESH_ID:            cluster.local
      TRUST_DOMAIN:                  cluster.local
      DNS_AGENT:
      ISTIO_META_DNS_CAPTURE:        true
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lkx7z (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-lkx7z:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lkx7z
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istiod-ca-cert:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        istio-ca-root-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  51s                default-scheduler  Successfully assigned test/ubuntu to server16
  Normal   Pulling    51s                kubelet            Pulling image "docker.io/istio/proxyv2:1.8.1"
  Normal   Pulled     51s                kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.8.1"
  Normal   Created    51s                kubelet            Created container istio-init
  Normal   Started    51s                kubelet            Started container istio-init
  Normal   Pulled     50s                kubelet            Container image "ubuntu:18.04" already present on machine
  Normal   Started    50s                kubelet            Started container ubuntu
  Normal   Created    50s                kubelet            Created container ubuntu
  Normal   Created    36s (x3 over 49s)  kubelet            Created container istio-proxy
  Normal   Started    36s (x3 over 49s)  kubelet            Started container istio-proxy
  Warning  BackOff    20s (x4 over 48s)  kubelet            Back-off restarting failed container
  Normal   Pulling    5s (x4 over 50s)   kubelet            Pulling image "docker.io/istio/proxyv2:1.8.1"
  Normal   Pulled     5s (x4 over 49s)   kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.8.1"
```
