### ISSUE TITLE
Unable to build on MacOS

### ISSUE THREAD

**Issue by theganyo** [istio/istio#3074]
There are still errors building on MacOS. From latest commit [a957c379a9cce5e38109b9ff4e73cb8872870d43] on master, the following error occurs during `make` on MacOS High Sierra.

```
go test -p 1  ./pilot/...
?   	istio.io/istio/pilot/cmd	[no test files]
?   	istio.io/istio/pilot/cmd/istioctl	[no test files]
ok  	istio.io/istio/pilot/cmd/istioctl/gendeployment	0.034s
?   	istio.io/istio/pilot/cmd/pilot-agent	[no test files]
?   	istio.io/istio/pilot/cmd/pilot-discovery	[no test files]
?   	istio.io/istio/pilot/cmd/sidecar-injector	[no test files]
ok  	istio.io/istio/pilot/pkg/bootstrap	1.180s
ok  	istio.io/istio/pilot/pkg/config/aggregate	0.154s
ok  	istio.io/istio/pilot/pkg/config/kube/crd	27.626s
ok  	istio.io/istio/pilot/pkg/config/kube/crd/file	13.703s
ok  	istio.io/istio/pilot/pkg/config/kube/ingress	30.720s
ok  	istio.io/istio/pilot/pkg/config/memory	0.287s
ok  	istio.io/istio/pilot/pkg/kube/admit	0.220s
?   	istio.io/istio/pilot/pkg/kube/admit/testcerts	[no test files]
ok  	istio.io/istio/pilot/pkg/kube/inject	0.227s
ok  	istio.io/istio/pilot/pkg/model	0.174s
?   	istio.io/istio/pilot/pkg/model/test	[no test files]
ok  	istio.io/istio/pilot/pkg/proxy	0.446s
ok  	istio.io/istio/pilot/pkg/proxy/envoy/v1	4.428s
ok  	istio.io/istio/pilot/pkg/proxy/envoy/v1/mock	0.058s
?   	istio.io/istio/pilot/pkg/serviceregistry	[no test files]
ok  	istio.io/istio/pilot/pkg/serviceregistry/aggregate	0.057s
ok  	istio.io/istio/pilot/pkg/serviceregistry/cloudfoundry	3.426s
ok  	istio.io/istio/pilot/pkg/serviceregistry/consul	0.069s
ok  	istio.io/istio/pilot/pkg/serviceregistry/eureka	0.266s
ok  	istio.io/istio/pilot/pkg/serviceregistry/kube	0.227s
?   	istio.io/istio/pilot/test/client	[no test files]
?   	istio.io/istio/pilot/test/eurekamirror	[no test files]
?   	istio.io/istio/pilot/test/grpcecho	[no test files]
?   	istio.io/istio/pilot/test/integration	[no test files]
[2018-02-01 13:35:45.953][4660943][critical][main] external/envoy/source/server/server.cc:72] error initializing configuration 'tmp/envoy-rev0.json': unable to open file '/dev/stdout': Permission denied
panic: running envoy: exit status 1

goroutine 72 [running]:
istio.io/istio/pilot/test/integration/cloudfoundry_test.(*testState).runEnvoy.func2(0x1b8a920, 0xc4201c0000, 0xc42009d5e0, 0xc420214600, 0x1b7c4a0, 0xc4201f8490)
	/Users/theganyo/dev/istio/src/istio.io/istio/pilot/test/integration/cloudfoundry/copilot_test.go:188 +0x16c
created by istio.io/istio/pilot/test/integration/cloudfoundry_test.(*testState).runEnvoy
	/Users/theganyo/dev/istio/src/istio.io/istio/pilot/test/integration/cloudfoundry/copilot_test.go:185 +0x6bc
FAIL	istio.io/istio/pilot/test/integration/cloudfoundry	23.087s
?   	istio.io/istio/pilot/test/integration/cloudfoundry/mock	[no test files]
?   	istio.io/istio/pilot/test/mock	[no test files]
?   	istio.io/istio/pilot/test/server	[no test files]
```

**Comment by mattdelco** [comment]
Some related work going on in https://github.com/istio/istio/pull/3080.

**Comment by robcresswell** [comment]
Is it intended that the tests run as part of the build? I'd have thought running `make build` might get around these issues, if its during the tests its failing. Might not be a genuine failure, but a test infrastructure issue on MacOS.

**Comment by theganyo** [comment]
You're right... it's not the build itself... I'll update the title to say "tests" fail. (FWIW, the default target of make runs the tests.)

**Comment by mattdelco** [comment]
The following change in the Makefile might help to skip the tests that are only expected to pass on Linux:

<pre>- test: pilot-test mixer-test security-test broker-test galley-test common-test
+ # pilot tests have dependencies on proxy, which is only available for Linux
+ ifeq ($(GOOS),linux)
+   test: pilot-test 
+ endif
+ test: mixer-test security-test broker-test galley-test common-test
</pre>
