### ISSUE TITLE
prow/istio-unit-tests.sh — Job failed.

### ISSUE THREAD

**Issue by mangchiandjjoe** [istio/istio#3245]
I0206 23:08:17.791] Bootstrap istio-unit-tests...
I0206 23:08:17.791] Gubernator results at https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3169/istio-unit-tests/18
I0206 23:08:17.791] Root: /home/bootstrap/go/src
I0206 23:08:17.791] Checkout: /home/bootstrap/go/src/github.com/istio/istio master:fb701b66453951138cb2710e932a9ef0d5a02d9a,3169:36fd4a6a5371a1965d7114542fb57ac53c6b05d2
I0206 23:08:17.791] Call:  git init github.com/istio/istio
I0206 23:08:17.795] Initialized empty Git repository in /home/bootstrap/go/src/github.com/istio/istio/.git/
I0206 23:08:17.795] process 72 exited with code 0 after 0.0m
I0206 23:08:17.795] Call:  git clean -dfx
I0206 23:08:17.797] process 73 exited with code 0 after 0.0m
I0206 23:08:17.797] Call:  git reset --hard
I0206 23:08:17.799] process 74 exited with code 0 after 0.0m
I0206 23:08:17.799] Call:  git config --local user.name 'K8S Bootstrap'
I0206 23:08:17.801] process 75 exited with code 0 after 0.0m
I0206 23:08:17.801] Call:  git config --local user.email k8s_bootstrap@localhost
I0206 23:08:17.803] process 76 exited with code 0 after 0.0m
I0206 23:08:17.803] Call:  git fetch --quiet --tags https://github.com/istio/istio master +refs/pull/3169/head:refs/pr/3169
I0206 23:08:18.975] process 77 exited with code 0 after 0.0m
I0206 23:08:18.976] Call:  git checkout -B test fb701b66453951138cb2710e932a9ef0d5a02d9a
W0206 23:08:19.117] Switched to a new branch 'test'
I0206 23:08:19.118] process 132 exited with code 0 after 0.0m
I0206 23:08:19.118] Call:  git merge --no-ff -m 'Merge +refs/pull/3169/head:refs/pr/3169' 36fd4a6a5371a1965d7114542fb57ac53c6b05d2
I0206 23:08:19.305] Auto-merging security/pkg/server/grpc/server_test.go
I0206 23:08:19.305] Auto-merging security/pkg/server/grpc/server.go
I0206 23:08:19.305] Auto-merging security/cmd/istio_ca/main.go
I0206 23:08:19.306] Merge made by the 'recursive' strategy.
I0206 23:08:19.308]  security/cmd/istio_ca/main.go                 | 154 ++++++++++++++++++++++++++
I0206 23:08:19.308]  security/pkg/pki/ca/ca.go                     |  14 +--
I0206 23:08:19.308]  security/pkg/pki/ca/controller/secret_test.go |   4 +
I0206 23:08:19.309]  security/pkg/server/grpc/server.go            |   2 +-
I0206 23:08:19.309]  security/pkg/server/grpc/server_test.go       |   4 +
I0206 23:08:19.309]  5 files changed, 170 insertions(+), 8 deletions(-)
I0206 23:08:19.309] process 141 exited with code 0 after 0.0m
I0206 23:08:19.309] Configure environment...
I0206 23:08:19.309] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0206 23:08:19.796] Activated service account credentials for: [istio-prow-test-job@istio-testing.iam.gserviceaccount.com]
I0206 23:08:20.287] process 143 exited with code 0 after 0.0m
I0206 23:08:20.287] Call:  gcloud config get-value account
I0206 23:08:20.920] process 158 exited with code 0 after 0.0m
I0206 23:08:20.920] Will upload results to gs://istio-prow/ using istio-prow-test-job@istio-testing.iam.gserviceaccount.com
I0206 23:08:20.920] Start 18 at unknown...
I0206 23:08:20.920] Call:  gsutil -q -h Content-Type:application/json cp - gs://istio-prow/pull/istio_istio/3169/istio-unit-tests/18/started.json
I0206 23:08:22.425] process 173 exited with code 0 after 0.0m
I0206 23:08:22.425] Call:  gsutil -q -h Content-Type:text/plain cp - gs://istio-prow/directory/istio-unit-tests/18.txt
I0206 23:08:23.951] process 347 exited with code 0 after 0.0m
I0206 23:08:23.951] Call:  prow/istio-unit-tests.sh
E0206 23:08:23.955] unexpected error
Traceback (most recent call last):
  File "./bootstrap.py", line 893, in bootstrap
    call(job_script(job, use_json, args.jobs_dir))
  File "./bootstrap.py", line 860, in <lambda>
    call = lambda *a, **kw: _call(end, *a, **kw)
  File "./bootstrap.py", line 109, in _call
    preexec_fn=os.setsid,
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
I0206 23:08:23.956] Upload result and artifacts...
I0206 23:08:23.956] Gubernator results at https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3169/istio-unit-tests/18
I0206 23:08:23.956] Call:  git rev-parse HEAD
I0206 23:08:23.959] process 522 exited with code 0 after 0.0m
I0206 23:08:23.959] Call:  gsutil stat gs://istio-prow/directory/istio-unit-tests/jobResultsCache.json
I0206 23:08:25.005] process 523 exited with code 0 after 0.0m
I0206 23:08:25.005] Call:  gsutil -q cat 'gs://istio-prow/directory/istio-unit-tests/jobResultsCache.json#1517958481963685'
I0206 23:08:26.169] process 664 exited with code 0 after 0.0m
I0206 23:08:26.170] Call:  gsutil -q -h Content-Type:application/json -h x-goog-if-generation-match:1517958481963685 cp - gs://istio-prow/directory/istio-unit-tests/jobResultsCache.json
I0206 23:08:27.682] process 807 exited with code 0 after 0.0m
I0206 23:08:27.682] Call:  gsutil stat gs://istio-prow/pull/istio_istio/3169/istio-unit-tests/jobResultsCache.json
I0206 23:08:28.742] process 981 exited with code 0 after 0.0m
I0206 23:08:28.742] Call:  gsutil -q cat 'gs://istio-prow/pull/istio_istio/3169/istio-unit-tests/jobResultsCache.json#1517956474245635'
I0206 23:08:29.996] process 1122 exited with code 0 after 0.0m
I0206 23:08:29.996] Call:  gsutil -q -h Content-Type:application/json -h x-goog-if-generation-match:1517956474245635 cp - gs://istio-prow/pull/istio_istio/3169/istio-unit-tests/jobResultsCache.json
I0206 23:08:31.392] process 1265 exited with code 0 after 0.0m
I0206 23:08:31.392] Call:  gsutil -q -h Content-Type:application/json cp - gs://istio-prow/pull/istio_istio/3169/istio-unit-tests/18/finished.json
I0206 23:08:32.838] process 1439 exited with code 0 after 0.0m
I0206 23:08:32.839] Call:  gsutil -q -h Content-Type:text/plain -h 'Cache-Control:private, max-age=0, no-transform' cp - gs://istio-prow/pull/istio_istio/3169/istio-unit-tests/latest-build.txt
I0206 23:08:34.219] process 1613 exited with code 0 after 0.0m
I0206 23:08:34.220] Call:  gsutil -q -h Content-Type:text/plain -h 'Cache-Control:private, max-age=0, no-transform' cp - gs://istio-prow/directory/istio-unit-tests/latest-build.txt
I0206 23:08:35.648] process 1787 exited with code 0 after 0.0m

**Comment by mangchiandjjoe** [comment]
The issue has been fixed.
