### ISSUE TITLE
Readiness probe failed after injection

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#32963]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
In our private AKS on azure, we have installed istio

The pod was running, however:
After istio injection, the pod is down
kubectl label namespace xxx istio-injection=enabled

NAME                              READY   STATUS             RESTARTS   AGE
xxx-6774fc499d-zplxq   0/2     CrashLoopBackOff   70         5h37m

PS C:\Users\swu> kubectl.exe logs xxx-6774fc499d-zplxq -n thebase -c thebasetestapi
Unhandled exception. System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at TheBaseAPI.Program.Main(String[] args) in /src/API/Program.cs:line 16

kubectl.exe **describe** pods xxx-6774fc499d-zplxq -n thebase
Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
  Warning  BackOff    14m (x1445 over 5h29m)    kubelet, aks-pool1-13468513-vmss00001t  Back-off restarting failed container
  Warning  Unhealthy  4m47s (x9745 over 5h29m)  kubelet, aks-pool1-13468513-vmss00001t  Readiness probe failed: Get http://10.123.17.60:15021/healthz/ready: dial tcp 10.123.17.60:15021: connect: connection refused

.\kubectl.exe logs xxx-6774fc499d-zplxq -n thebase -c istio-proxy
tion error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.80.0.204:53: no such host"
2021-05-19T21:28:46.167001Z     warn    cache   resource:default request:88110626-5daf-404a-899e-7fbf1250ab42 CSR failed with error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.80.0.204:53: no such host", retry in 200 millisec
2021-05-19T21:28:58.570071Z     error   sds     resource:default Close connection. Failed to get secret for proxy "sidecar~10.123.17.60~thebasetestapi-6774fc499d-zplxq.thebase~thebase.svc.cluster.local" from secret cache: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.80.0.204:53: no such host"

The error is about the connection to keyvault to get the secrets
here is the code:

                       
 var azureServiceTokenProvider = new AzureServiceTokenProvider();
                        var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));

if (!double.TryParse(builtConfig["KeyVault:ReloadIntervalInMinutes"], out var minutes)) minutes = 10;
                        config.AddAzureKeyVault(new AzureKeyVaultConfigurationOptions
                        {
                            Vault = builtConfig["KeyVault:KeyVaultUrlCache"],
                            ReloadInterval = TimeSpan.FromMinutes(minutes),
                            Client = keyVaultClient
                        });

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
aks : 1.19.7
istioctl.exe version
client version: 1.10.0-rc.1
control plane version: 1.7.3
data plane version: 1.7.3 (1 proxies)

**How was Istio installed?**

ISTIO_VERSION=1.7.3

curl -sL "https://github.com/istio/istio/releases/download/$ISTIO_VERSION/istioctl-$ISTIO_VERSION-linux-amd64.tar.gz" | tar xz

**Comment by howardjohn** [comment]
`connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.80.0.204:53: no such host"`

Sounds like there is no access to DNS, or the `istiod` service does not exist anyhow..

Is it there if you do `kubectl get svc -n istio-system`? 

PS: https://istio.io/latest/news/support/announcing-1.7-eol-final/

**Comment by calvinShan** [comment]
> `connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.80.0.204:53: no such host"`
> 
> Sounds like there is no access to DNS, or the `istiod` service does not exist anyhow..
> 
> Is it there if you do `kubectl get svc -n istio-system`?
> 
> PS: https://istio.io/latest/news/support/announcing-1.7-eol-final/

hello, 
kubectl get svc -n istio-system
NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                      AGE
grafana                     ClusterIP      172.16.218.75    <none>        3000/TCP                                                     8d
istio-ingressgateway        LoadBalancer   172.16.235.111   20.74.17.34   15021:31844/TCP,80:31896/TCP,443:32065/TCP,15443:32597/TCP   8d
istiod                      ClusterIP      172.16.36.55     <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP,853/TCP                8d
jaeger-agent                ClusterIP      None             <none>        5775/UDP,6831/UDP,6832/UDP                                   8d
jaeger-collector            ClusterIP      172.16.134.157   <none>        14267/TCP,14268/TCP,14250/TCP                                8d
jaeger-collector-headless   ClusterIP      None             <none>        14250/TCP                                                    8d
jaeger-query                ClusterIP      172.16.57.84     <none>        16686/TCP                                                    8d
kiali                       ClusterIP      172.16.254.166   <none>        20001/TCP                                                    8d
prometheus                  ClusterIP      172.16.97.9      <none>        9090/TCP                                                     8d
tracing                     ClusterIP      172.16.193.125   <none>        80/TCP                                                       8d
zipkin                      ClusterIP      172.16.233.60    <none>        9411/TCP                                                     8d

so we need to setup istiod ro resolve this problem?
Why we have the error about connection refused in the application?
System.Net.Sockets.SocketException (111): Connection refused
Thanks

**Comment by howardjohn** [comment]
The `Connection refused` refused is a side effect of not being able to connect to Istiod, which is a result of DNS not working, which is a result of `DNSPolicy is not "ClusterFirst". The Envoy sidecar may not able to connect to Istio Pilot`.

Configure the pod to have a DNSPolicy that will allow it to connect to Istiod. In-cluster DNS is required for Istio to work.
