### ISSUE TITLE
Panic in istioctl wait

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33088]
https://prow.istio.io/view/gs/istio-prow/logs/integ-distroless-k8s-tests_istio_postsubmit/1397275225019650048

```
panic: interface conversion: *v1.Status is not v1.Object: missing method GetAnnotations
goroutine 13187 [running]:
istio.io/istio/istioctl/cmd.getAndWatchResource.func1(0xc00379d260, 0x53c6448, 0xc0059eacb0)
	/home/prow/go/src/istio.io/istio/istioctl/cmd/wait.go:258 +0x49d
istio.io/istio/istioctl/cmd.(*watcher).Go.func1(0xc003872ed0, 0xc003abeda0)
	/home/prow/go/src/istio.io/istio/istioctl/cmd/wait.go:291 +0x33
created by istio.io/istio/istioctl/cmd.(*watcher).Go
	/home/prow/go/src/istio.io/istio/istioctl/cmd/wait.go:290 +0x49
FAIL	istio.io/istio/tests/integration/security	185.888s
```

**Comment by zhlsunshine** [comment]
Added protection for such interface conversion.
