### ISSUE TITLE
Istio gatways proxy agent runtime error when upgrading from 1.6.11 to 1.7.8

### ISSUE THREAD

**Issue by dilipgb6594** [istio/istio#33224]
**Bug description**
We are trying to upgrade istio is one of the cluster from 1.6.11 to 1.7.8 which is hosted in Azure AKS. Upgrade was performed but istio-ingressgateway and istio-egressgateway controllers are going into the crashloopbcakoff state. When checked for logs on both controllers below is the error we are seeing.

Istio-egress-gateway
```
2021-06-02T11:17:18.703945Z     info    FLAG: --concurrency="0"
2021-06-02T11:17:18.703984Z     info    FLAG: --disableInternalTelemetry="false"
2021-06-02T11:17:18.703992Z     info    FLAG: --domain="istio-system.svc.cluster.local"
2021-06-02T11:17:18.703996Z     info    FLAG: --help="false"
2021-06-02T11:17:18.704001Z     info    FLAG: --id=""
2021-06-02T11:17:18.704005Z     info    FLAG: --ip=""
2021-06-02T11:17:18.704010Z     info    FLAG: --log_as_json="false"
2021-06-02T11:17:18.704014Z     info    FLAG: --log_caller=""
2021-06-02T11:17:18.704019Z     info    FLAG: --log_output_level="default:info"
2021-06-02T11:17:18.704029Z     info    FLAG: --log_rotate=""
2021-06-02T11:17:18.704033Z     info    FLAG: --log_rotate_max_age="30"
2021-06-02T11:17:18.704038Z     info    FLAG: --log_rotate_max_backups="1000"
2021-06-02T11:17:18.704043Z     info    FLAG: --log_rotate_max_size="104857600"
2021-06-02T11:17:18.704048Z     info    FLAG: --log_stacktrace_level="default:none"
2021-06-02T11:17:18.704057Z     info    FLAG: --log_target="[stdout]"
2021-06-02T11:17:18.704063Z     info    FLAG: --meshConfig="./etc/istio/config/mesh"
2021-06-02T11:17:18.704068Z     info    FLAG: --mixerIdentity=""
2021-06-02T11:17:18.704072Z     info    FLAG: --outlierLogPath=""
2021-06-02T11:17:18.704077Z     info    FLAG: --proxyComponentLogLevel="misc:error"
2021-06-02T11:17:18.704081Z     info    FLAG: --proxyLogLevel="warning"
2021-06-02T11:17:18.704086Z     info    FLAG: --serviceCluster="istio-egressgateway"
2021-06-02T11:17:18.704091Z     info    FLAG: --serviceregistry="Kubernetes"
2021-06-02T11:17:18.704096Z     info    FLAG: --stsPort="0"
2021-06-02T11:17:18.704100Z     info    FLAG: --templateFile=""
2021-06-02T11:17:18.704105Z     info    FLAG: --tokenManagerPlugin="GoogleTokenExchange"
2021-06-02T11:17:18.704111Z     info    FLAG: --trust-domain="cluster.local"
2021-06-02T11:17:18.704148Z     info    Version 1.7.8-30e54dcb8a1c6196e48394f79fed1399e2562ed3-Clean
2021-06-02T11:17:18.704339Z     info    Obtained private IP [10.99.129.37]
2021-06-02T11:17:18.704460Z     info    Apply mesh config from file accessLogFile: /dev/stdout
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata:
    DNS_AGENT: ""
    TERMINATION_DRAIN_DURATION_SECONDS: "30"
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
disableMixerHttpReports: true
disablePolicyChecks: false
enablePrometheusMerge: true
mixerCheckServer: istio-policy.istio-system.svc.cluster.local:9091
outboundTrafficPolicy:
  mode: REGISTRY_ONLY
rootNamespace: istio-system
trustDomain: cluster.local
2021-06-02T11:17:18.706579Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 0
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
envoyAccessLogService: {}
envoyMetricsService: {}
parentShutdownDuration: 60s
proxyAdminPort: 15000
proxyMetadata:
  DNS_AGENT: ""
  TERMINATION_DRAIN_DURATION_SECONDS: "30"
serviceCluster: istio-egressgateway
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411

2021-06-02T11:17:18.706640Z     info    Proxy role: &model.Proxy{Type:"router", IPAddresses:[]string{"10.99.129.37"}, ID:"istio-egressgateway-696678487-5mmhv.istio-system", Locality:(*envoy_config_core_v3.Locality)(nil), DNSDomain:"istio-system.svc.cluster.local", ConfigNamespace:"", Metadata:(*model.NodeMetadata)(nil), SidecarScope:(*model.SidecarScope)(nil), PrevSidecarScope:(*model.SidecarScope)(nil), MergedGateway:(*model.MergedGateway)(nil), ServiceInstances:[]*model.ServiceInstance(nil), IstioVersion:(*model.IstioVersion)(nil), ipv6Support:false, ipv4Support:false, GlobalUnicastIP:"", XdsResourceGenerator:model.XdsResourceGenerator(nil), Active:map[string]*model.WatchedResource(nil), ActiveExperimental:map[string]*model.WatchedResource(nil), RequestedTypes:struct { CDS string; EDS string; RDS string; LDS string }{CDS:"", EDS:"", RDS:"", LDS:""}}
2021-06-02T11:17:18.706647Z     info    JWT policy is third-party-jwt
2021-06-02T11:17:18.706697Z     info    PilotSAN []string{"istiod.istio-system.svc"}
2021-06-02T11:17:18.706712Z     info    MixerSAN []string{"spiffe://cluster.local/ns/istio-system/sa/istio-mixer-service-account"}
2021-06-02T11:17:18.706760Z     info    sa.serverOptions.CAEndpoint == istiod.istio-system.svc:15012
2021-06-02T11:17:18.706772Z     info    Using user-configured CA istiod.istio-system.svc:15012
2021-06-02T11:17:18.706776Z     info    istiod uses self-issued certificate
2021-06-02T11:17:18.706820Z     info    the CA cert of istiod is: -----BEGIN CERTIFICATE-----
MIIC3TCCAcWgAwIBAgIQOmAbHjjMP7ocFc2iv8f9jjANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIwMTEyNTE1MTEwNloXDTMwMTEy
MzE1MTEwNlowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAKNMU8xHoCaXl96sdhQcSCdG5Lg6fLcMGHI9qE4D
U22TRxu+aDxNnnXrpq03d2dRjZOJndCPAHCCgkquW38BqaxDJcnUoe0s0Ea6DwOS
LEhWhRv8puFTCuqCZk2GYkP3TjZzWYunxWAY8o/JwuFKy6TRVZ34XEFgldoP5MT3
DIEa5J8HqJATZqQL2LPlRngke7usRa8E8PwOgiFZw3c7syk+S4oYHibPSTh+UTNR
NNCNlMTjRK8qNAtmrHr5Nb+xWqlg7UgdVsUSRhhAiyzKEu8VTHqrMVsyJso/7yYe
afbLAwZfvIwKFJs1ftaxG0KYlewR/YK4jPd2Pfn/nb9b4NsCAwEAAaMjMCEwDgYD
VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AEdLQvji3Q8glSLago9cWNObRg8lwOyGIBZ+2Y5ReY/c3ROLh37/x5m61W1R96mg
ozoDuTuesALFWqSqwCnNKcEY0JqF9KYxDwInFtBAig/FUmMUSE8+x3gg45K/GziC
coVjmXeygmheNdCAeE6FKsDZJ07Q3QurJIGinUS5R8v5OPGjsmhgljZ+4E9t/8Ct
6nERFWnRAZZQ6V2BAjN+/5Lu5nla7j0G3cO04ZnFfImtsZR1YkeBlnVKXXJlMlmX
R8s6bgstmEjZp9redtgrz79ruzSPJ+QIGuYhhSEFqEoil4929vua4Nc66Igj8r+U
ll6ntip2YvBG6eNrPAfGbOQ=
-----END CERTIFICATE-----

2021-06-02T11:17:18.756611Z     info    Skipping gateway SDS
2021-06-02T11:17:18.756888Z     info    sds     SDS gRPC server for workload UDS starts, listening on "./etc/istio/proxy/SDS"

2021-06-02T11:17:18.756938Z     info    Starting proxy agent
2021-06-02T11:17:18.757017Z     info    Opening status port 15020

2021-06-02T11:17:18.757018Z     info    sds     Start SDS grpc server
2021-06-02T11:17:18.757220Z     info    Received new config, creating new Envoy epoch 0
2021-06-02T11:17:18.757296Z     info    Epoch 0 starting
panic: runtime error: index out of range [1] with length 1

goroutine 113 [running]:
istio.io/istio/pkg/bootstrap/platform.(*azureEnv).azureTags(0xc0008a0180, 0xc000e98240)
        istio.io/istio/pkg/bootstrap/platform/azure.go:185 +0x22c
istio.io/istio/pkg/bootstrap/platform.(*azureEnv).Metadata(0xc0008a0180, 0xa)
        istio.io/istio/pkg/bootstrap/platform/azure.go:146 +0x195
istio.io/istio/pkg/bootstrap.extractAttributesMetadata(0xc000f3e000, 0xc1, 0xc1, 0x2b34b60, 0xc0008a0180, 0xc000d5e000)
        istio.io/istio/pkg/bootstrap/config.go:461 +0x44d
istio.io/istio/pkg/bootstrap.getNodeMetaData(0xc000f3e000, 0xc1, 0xc1, 0x2b34b60, 0xc0008a0180, 0xc000de15f0, 0x1, 0x1, 0x0, 0xc00046e000, ...)
        istio.io/istio/pkg/bootstrap/config.go:498 +0x1c5
istio.io/istio/pkg/bootstrap.Config.toTemplateParams(0xc00005b730, 0x63, 0xc00046e000, 0x2b34b60, 0xc0008a0180, 0xc000c4be20, 0x1, 0x1, 0xc000c4be10, 0x1, ...)
        istio.io/istio/pkg/bootstrap/config.go:140 +0x765
istio.io/istio/pkg/bootstrap.(*instance).WriteTo(0xc000730a20, 0x26d69c8, 0x2f, 0x2abeb20, 0xc000118000, 0x0, 0x0)
        istio.io/istio/pkg/bootstrap/instance.go:72 +0xb8
istio.io/istio/pkg/bootstrap.(*instance).CreateFileForEpoch(0xc000730a20, 0x0, 0x0, 0x0, 0x0, 0x0)
        istio.io/istio/pkg/bootstrap/instance.go:129 +0x18e
istio.io/istio/pkg/envoy.(*envoy).Run(0xc00046e000, 0x2173120, 0xc000664000, 0x0, 0xc000714780, 0xc000662000, 0x20)
        istio.io/istio/pkg/envoy/proxy.go:176 +0x860
istio.io/istio/pkg/envoy.(*agent).runWait(0xc000747630, 0x2173120, 0xc000664000, 0x0, 0xc000714780)
        istio.io/istio/pkg/envoy/agent.go:260 +0xd2
created by istio.io/istio/pkg/envoy.(*agent).Restart
        istio.io/istio/pkg/envoy/agent.go:160 +0x2ba
```
Istio Ingressgateway:
```
2021-06-02T11:21:49.767381Z     info    FLAG: --concurrency="0"
2021-06-02T11:21:49.767416Z     info    FLAG: --disableInternalTelemetry="false"
2021-06-02T11:21:49.767424Z     info    FLAG: --domain="istio-system.svc.cluster.local"
2021-06-02T11:21:49.767429Z     info    FLAG: --help="false"
2021-06-02T11:21:49.767434Z     info    FLAG: --id=""
2021-06-02T11:21:49.767438Z     info    FLAG: --ip=""
2021-06-02T11:21:49.767442Z     info    FLAG: --log_as_json="false"
2021-06-02T11:21:49.767446Z     info    FLAG: --log_caller=""
2021-06-02T11:21:49.767451Z     info    FLAG: --log_output_level="default:info"
2021-06-02T11:21:49.767455Z     info    FLAG: --log_rotate=""
2021-06-02T11:21:49.767459Z     info    FLAG: --log_rotate_max_age="30"
2021-06-02T11:21:49.767464Z     info    FLAG: --log_rotate_max_backups="1000"
2021-06-02T11:21:49.767469Z     info    FLAG: --log_rotate_max_size="104857600"
2021-06-02T11:21:49.767475Z     info    FLAG: --log_stacktrace_level="default:none"
2021-06-02T11:21:49.767484Z     info    FLAG: --log_target="[stdout]"
2021-06-02T11:21:49.767490Z     info    FLAG: --meshConfig="./etc/istio/config/mesh"
2021-06-02T11:21:49.767495Z     info    FLAG: --mixerIdentity=""
2021-06-02T11:21:49.767500Z     info    FLAG: --outlierLogPath=""
2021-06-02T11:21:49.767505Z     info    FLAG: --proxyComponentLogLevel="misc:error"
2021-06-02T11:21:49.767510Z     info    FLAG: --proxyLogLevel="warning"
2021-06-02T11:21:49.767516Z     info    FLAG: --serviceCluster="istio-ingressgateway"
2021-06-02T11:21:49.767522Z     info    FLAG: --serviceregistry="Kubernetes"
2021-06-02T11:21:49.767527Z     info    FLAG: --stsPort="0"
2021-06-02T11:21:49.767532Z     info    FLAG: --templateFile=""
2021-06-02T11:21:49.767538Z     info    FLAG: --tokenManagerPlugin="GoogleTokenExchange"
2021-06-02T11:21:49.767543Z     info    FLAG: --trust-domain="cluster.local"
2021-06-02T11:21:49.767581Z     info    Version 1.7.8-30e54dcb8a1c6196e48394f79fed1399e2562ed3-Clean
2021-06-02T11:21:49.767797Z     info    Obtained private IP [10.99.128.229]
2021-06-02T11:21:49.767911Z     info    Apply mesh config from file accessLogFile: /dev/stdout
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata:
    DNS_AGENT: ""
    TERMINATION_DRAIN_DURATION_SECONDS: "30"
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
disableMixerHttpReports: true
disablePolicyChecks: false
enablePrometheusMerge: true
mixerCheckServer: istio-policy.istio-system.svc.cluster.local:9091
outboundTrafficPolicy:
  mode: REGISTRY_ONLY
rootNamespace: istio-system
trustDomain: cluster.local
2021-06-02T11:21:49.769752Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 0
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
envoyAccessLogService: {}
envoyMetricsService: {}
parentShutdownDuration: 60s
proxyAdminPort: 15000
proxyMetadata:
  DNS_AGENT: ""
  TERMINATION_DRAIN_DURATION_SECONDS: "30"
serviceCluster: istio-ingressgateway
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411

2021-06-02T11:21:49.769798Z     info    Proxy role: &model.Proxy{Type:"router", IPAddresses:[]string{"10.99.128.229"}, ID:"istio-ingressgateway-c96bf8589-b622j.istio-system", Locality:(*envoy_config_core_v3.Locality)(nil), DNSDomain:"istio-system.svc.cluster.local", ConfigNamespace:"", Metadata:(*model.NodeMetadata)(nil), SidecarScope:(*model.SidecarScope)(nil), PrevSidecarScope:(*model.SidecarScope)(nil), MergedGateway:(*model.MergedGateway)(nil), ServiceInstances:[]*model.ServiceInstance(nil), IstioVersion:(*model.IstioVersion)(nil), ipv6Support:false, ipv4Support:false, GlobalUnicastIP:"", XdsResourceGenerator:model.XdsResourceGenerator(nil), Active:map[string]*model.WatchedResource(nil), ActiveExperimental:map[string]*model.WatchedResource(nil), RequestedTypes:struct { CDS string; EDS string; RDS string; LDS string }{CDS:"", EDS:"", RDS:"", LDS:""}}
2021-06-02T11:21:49.769803Z     info    JWT policy is third-party-jwt
2021-06-02T11:21:49.769855Z     info    PilotSAN []string{"istiod.istio-system.svc"}
2021-06-02T11:21:49.769869Z     info    MixerSAN []string{"spiffe://cluster.local/ns/istio-system/sa/istio-mixer-service-account"}
2021-06-02T11:21:49.769915Z     info    sa.serverOptions.CAEndpoint == istiod.istio-system.svc:15012
2021-06-02T11:21:49.769921Z     info    Using user-configured CA istiod.istio-system.svc:15012
2021-06-02T11:21:49.769925Z     info    istiod uses self-issued certificate
2021-06-02T11:21:49.769980Z     info    the CA cert of istiod is: -----BEGIN CERTIFICATE-----
MIIC3TCCAcWgAwIBAgIQOmAbHjjMP7ocFc2iv8f9jjANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIwMTEyNTE1MTEwNloXDTMwMTEy
MzE1MTEwNlowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAKNMU8xHoCaXl96sdhQcSCdG5Lg6fLcMGHI9qE4D
U22TRxu+aDxNnnXrpq03d2dRjZOJndCPAHCCgkquW38BqaxDJcnUoe0s0Ea6DwOS
LEhWhRv8puFTCuqCZk2GYkP3TjZzWYunxWAY8o/JwuFKy6TRVZ34XEFgldoP5MT3
DIEa5J8HqJATZqQL2LPlRngke7usRa8E8PwOgiFZw3c7syk+S4oYHibPSTh+UTNR
NNCNlMTjRK8qNAtmrHr5Nb+xWqlg7UgdVsUSRhhAiyzKEu8VTHqrMVsyJso/7yYe
afbLAwZfvIwKFJs1ftaxG0KYlewR/YK4jPd2Pfn/nb9b4NsCAwEAAaMjMCEwDgYD
VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AEdLQvji3Q8glSLago9cWNObRg8lwOyGIBZ+2Y5ReY/c3ROLh37/x5m61W1R96mg
ozoDuTuesALFWqSqwCnNKcEY0JqF9KYxDwInFtBAig/FUmMUSE8+x3gg45K/GziC
coVjmXeygmheNdCAeE6FKsDZJ07Q3QurJIGinUS5R8v5OPGjsmhgljZ+4E9t/8Ct
6nERFWnRAZZQ6V2BAjN+/5Lu5nla7j0G3cO04ZnFfImtsZR1YkeBlnVKXXJlMlmX
R8s6bgstmEjZp9redtgrz79ruzSPJ+QIGuYhhSEFqEoil4929vua4Nc66Igj8r+U
ll6ntip2YvBG6eNrPAfGbOQ=
-----END CERTIFICATE-----

2021-06-02T11:21:49.824225Z     info    Starting gateway SDS
2021-06-02T11:21:49.862146Z     warn    secretfetcher   failed load server cert/key pair from secret kiali-admin: server cert or private key is empty
2021-06-02T11:21:49.926175Z     info    sds     SDS gRPC server for workload UDS starts, listening on "./etc/istio/proxy/SDS"

2021-06-02T11:21:49.926262Z     info    sds     Start SDS grpc server
2021-06-02T11:21:49.926326Z     info    sds     SDS gRPC server for gateway controller starts, listening on "./var/run/ingress_gateway/sds"

2021-06-02T11:21:49.926394Z     info    Starting proxy agent
2021-06-02T11:21:49.926390Z     info    sds     Start SDS grpc server for ingress gateway proxy
2021-06-02T11:21:49.926423Z     info    Opening status port 15020

2021-06-02T11:21:49.926544Z     info    Received new config, creating new Envoy epoch 0
2021-06-02T11:21:49.926585Z     info    Epoch 0 starting
panic: runtime error: index out of range [1] with length 1

goroutine 29 [running]:
istio.io/istio/pkg/bootstrap/platform.(*azureEnv).azureTags(0xc0012c4620, 0xc000ad26f0)
        istio.io/istio/pkg/bootstrap/platform/azure.go:185 +0x22c
istio.io/istio/pkg/bootstrap/platform.(*azureEnv).Metadata(0xc0012c4620, 0x16)
        istio.io/istio/pkg/bootstrap/platform/azure.go:146 +0x195
istio.io/istio/pkg/bootstrap.extractAttributesMetadata(0xc00004f900, 0xc1, 0xc1, 0x2b34b60, 0xc0012c4620, 0xc0003d0c80)
        istio.io/istio/pkg/bootstrap/config.go:461 +0x44d
istio.io/istio/pkg/bootstrap.getNodeMetaData(0xc00004f900, 0xc1, 0xc1, 0x2b34b60, 0xc0012c4620, 0xc0009e0b00, 0x1, 0x1, 0x0, 0xc000ed4000, ...)
        istio.io/istio/pkg/bootstrap/config.go:498 +0x1c5
istio.io/istio/pkg/bootstrap.Config.toTemplateParams(0xc0001ac5b0, 0x65, 0xc000ed4000, 0x2b34b60, 0xc0012c4620, 0xc000b66820, 0x1, 0x1, 0xc000b66810, 0x1, ...)
        istio.io/istio/pkg/bootstrap/config.go:140 +0x765
istio.io/istio/pkg/bootstrap.(*instance).WriteTo(0xc0006b8480, 0x26d69c8, 0x2f, 0x2abeb20, 0xc000534030, 0x0, 0x0)
        istio.io/istio/pkg/bootstrap/instance.go:72 +0xb8
istio.io/istio/pkg/bootstrap.(*instance).CreateFileForEpoch(0xc0006b8480, 0x0, 0x0, 0x0, 0x0, 0x0)
        istio.io/istio/pkg/bootstrap/instance.go:129 +0x18e
istio.io/istio/pkg/envoy.(*envoy).Run(0xc000ed4000, 0x2173120, 0xc000414020, 0x0, 0xc0010f6000, 0xc0010be000, 0x20)
        istio.io/istio/pkg/envoy/proxy.go:176 +0x860
istio.io/istio/pkg/envoy.(*agent).runWait(0xc000b32cd0, 0x2173120, 0xc000414020, 0x0, 0xc0010f6000)
        istio.io/istio/pkg/envoy/agent.go:260 +0xd2
created by istio.io/istio/pkg/envoy.(*agent).Restart
        istio.io/istio/pkg/envoy/agent.go:160 +0x2ba
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X ] Upgrade

**Expected behavior**
Istio ingressgateway and istio egressgateway should start proxy agent and should load configurations form istiod.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.10.0
control plane version: 1.7.8
data plane version: 1.6.11 (16 proxies)

Client Version: v1.20.2
Server Version: v1.18.17

**How was Istio installed?**
Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

Azure AKS.

**Comment by howardjohn** [comment]
Can you try on a newer version? 1.7 is no longer supported and thus will not be fixed. It looks like this may have been fixed in #31209?

cc @douglas-reid

**Comment by douglas-reid** [comment]
@dilipgb6594 iirc, the earlier issue was having a `;` in the tag values. if you have any tags like that, you could potentially work around this issue by using a different delimiter.

**Comment by kalyanteja19** [comment]
@douglas-reid , Thank you. We could see that one of the tags value has ";" delimiter , we will remove it and try.

**Comment by kalyanteja19** [comment]
@douglas-reid , This worked. We upgraded istio to 1.7.8. Thank you so much for your help :)

**Comment by dilipgb6594** [comment]
@douglas-reid thanks for quick response and help. We see controllers are stable now. I will be closing the issue.

 To summarize, Resource tags for the Node Pool VMSS should not have any semicolon in its value.
