### ISSUE TITLE
 istioctl crashed on retrieveListenerAddress 

### ISSUE THREAD

**Issue by KfreeZ** [istio/istio#33432]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
  istioctl crashed when retrieving the listener config which is listening on an unix domain socket
  100% percent re-produciable
```
$ istioctl pc listeners python-6db574dd4d-6trft.uds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2608c0f]

goroutine 1 [running]:
istio.io/istio/istioctl/pkg/writer/envoy/configdump.retrieveListenerAddress(...)
        istio.io/istio/istioctl/pkg/writer/envoy/configdump/listener.go:107
istio.io/istio/istioctl/pkg/writer/envoy/configdump.(*ConfigWriter).PrintListenerSummary(0xc0004e9830, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        istio.io/istio/istioctl/pkg/writer/envoy/configdump/listener.go:151 +0x32f
istio.io/istio/istioctl/cmd.listenerConfigCmd.func2(0xc0013b8780, 0xc00041b300, 0x1, 0x1, 0x0, 0x0)
        istio.io/istio/istioctl/cmd/proxyconfig.go:526 +0x333
github.com/spf13/cobra.(*Command).execute(0xc0013b8780, 0xc00041b2a0, 0x1, 0x1, 0xc0013b8780, 0xc00041b2a0)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d3f900, 0x3, 0x3, 0xc000d3f900)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        istio.io/istio/istioctl/cmd/istioctl/main.go:36 +0x12b

```

while the listener can be retrieved from envoy's RESTful API correctly
```
$ kubectl -n uds exec -it python-6db574dd4d-6trft -c istio-proxy -- curl http://127.0.0.1:15000/listeners
9e2f08b9-b5ed-4f2b-9918-e3e7ffe9f8fa::0.0.0.0:15090
c6fea90f-6c79-4aef-afea-0e92c159fb90::0.0.0.0:15021
**unix:///dev/shm/out.socket_0::/dev/shm/out.socket**
virtualOutbound::0.0.0.0:15001
virtualInbound::0.0.0.0:15006
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
the istioctl should get the correct listener config as the evnoy's RESTful API

**Steps to reproduce the bug**

1. add a sidecar configuration which is an istio CRD, to the istio-proxy, the yaml file as below
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: modify-sidecar
  namespace: uds
spec:
  ingress:
  - port:
      number: 9999
      protocol: HTTP
      name: udsin
    defaultEndpoint: unix:///dev/shm/in.socket
  egress:
  - port:
      number: 0
      protocol: HTTP
      name: udsout
    captureMode: NONE
    bind: unix:///dev/shm/out.socket
    hosts:
    - "default/*"
    - "./*"
```
2. start the POD with the istio-proxy injected
```
$ kubectl get pods -n uds
NAME                      READY   STATUS    RESTARTS   AGE
ngx-7d6c6767b9-kfc5l      2/2     Running   10         21d
python-6db574dd4d-6trft   2/2     Running   10         21d
```
3. the istio-proxy can work with the added sidecar
```
$ kubectl -n uds exec -it python-6db574dd4d-6trft -c istio-proxy -- curl http://127.0.0.1:15000/listeners
9e2f08b9-b5ed-4f2b-9918-e3e7ffe9f8fa::0.0.0.0:15090
c6fea90f-6c79-4aef-afea-0e92c159fb90::0.0.0.0:15021
unix:///dev/shm/out.socket_0::/dev/shm/out.socket
virtualOutbound::0.0.0.0:15001
virtualInbound::0.0.0.0:15006
```
4. istioctl crashed when retrieving the listeners
```
$ istioctl pc listeners python-6db574dd4d-6trft.uds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2608c0f]

goroutine 1 [running]:
istio.io/istio/istioctl/pkg/writer/envoy/configdump.retrieveListenerAddress(...)
        istio.io/istio/istioctl/pkg/writer/envoy/configdump/listener.go:107
istio.io/istio/istioctl/pkg/writer/envoy/configdump.(*ConfigWriter).PrintListenerSummary(0xc0004e9830, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        istio.io/istio/istioctl/pkg/writer/envoy/configdump/listener.go:151 +0x32f
istio.io/istio/istioctl/cmd.listenerConfigCmd.func2(0xc0013b8780, 0xc00041b300, 0x1, 0x1, 0x0, 0x0)
        istio.io/istio/istioctl/cmd/proxyconfig.go:526 +0x333
github.com/spf13/cobra.(*Command).execute(0xc0013b8780, 0xc00041b2a0, 0x1, 0x1, 0xc0013b8780, 0xc00041b2a0)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d3f900, 0x3, 0x3, 0xc000d3f900)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        istio.io/istio/istioctl/cmd/istioctl/main.go:36 +0x12b
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (10 proxies)

$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.20.2
```

**How was Istio installed?**

istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

centos7/centos8/ubuntu/20.10

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by KfreeZ** [comment]
raised a PR https://github.com/istio/istio/pull/33433 to fix this issue

**Comment by KfreeZ** [comment]
PR merged
