### ISSUE TITLE
iptables-restore v1.6.1: iptables-restore: unable to initialize table 'nat'

### ISSUE THREAD

**Issue by zhangzerui20** [istio/istio#33498]
**Bug description**

When istio starts it fails with `iptables-restore v1.6.1: iptables-restore: unable to initialize table 'nat'`

`istio-init`  startup log:

```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
DNS_SERVERS=[],[]

Writing following contents to rules file:  /tmp/iptables-rules-1623946433799282628.txt194580685
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1623946433799282628.txt194580685
iptables-restore v1.6.1: iptables-restore: unable to initialize table 'nat'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-save 
panic: exit status 2

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x2912700, 0x1a23936, 0x10, 0xc00011dec0, 0x2, 0x2)
	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:42 +0x9c
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc0007c5d78, 0x4000803f01, 0x0, 0x0)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:672 +0x386
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc0007c5d78)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:679 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc0007c5d78)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:557 +0x23e5
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x28caf60, 0xc00088aa00, 0x0, 0x10)
	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:60 +0x165
github.com/spf13/cobra.(*Command).execute(0x28caf60, 0xc00088a900, 0x10, 0x10, 0x28caf60, 0xc00088a900)
	github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x28cb1e0, 0x41af01, 0x0, 0x0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	istio.io/istio/pilot/cmd/pilot-agent/main.go:338 +0x31
```

**Expected behavior**
istio-init should start properly and setup network.

**Steps to reproduce the bug**
```
# install istio (description of installation provided below)
kubectl create -f samples/bookinfo/platform/kube/bookinfo.yaml
# deployment will fail to start on init
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
# istio
client version: 1.10.1
control plane version: 1.10.1
data plane version: none

# kubectl
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}
```

**How was Istio installed?**
```
curl -L https://istio.io/downloadIstio | sh -
cd istio-1.10.1
export PATH=$PWD/bin:$PATH
istioctl install --set profile=demo -y
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

```
Docker Desktop for Mac
```
<img width="760" alt="image" src="https://user-images.githubusercontent.com/13730670/122437174-0a6b1500-cfcc-11eb-9bcd-6a9ac2f03343.png">

Thanks in advance.

**Comment by howardjohn** [comment]
Is this on an ARM cluster? Istio does not currently support arm

**Comment by zhangzerui20** [comment]
Yes, I am using Apple m1 chip

**Comment by zhangzerui20** [comment]
It may be due to the arm structure, close issue.
