### ISSUE TITLE
istio-init start failed (panic in executeIptablesRestoreCommand)

### ISSUE THREAD

**Issue by zhengzepeng** [istio/istio#33566]
I use istio1.9.1 , my k8s env is v1.18.0. I found all pods(sidecar) status is  `Init:CrashLoopBackOff`.

```
[root@k8smaster ~]# k get pods -n lan
NAME                           READY   STATUS                  RESTARTS   AGE
mytomcat-v1-7fbcc8b595-nmjjf   2/2     Running                 0          38m
mytomcat-v2-585c784f79-f2kxj   0/2     Init:CrashLoopBackOff   604        3d22h
mytomcat-v3-f5d58d9d8-vnxtl    0/2     Init:Error              605        3d22h
test-0                         0/2     Init:CrashLoopBackOff   607        3d22h
```
I delete pod mytomcat-v1, and it restart, status is Running.

I found istio-init start failed. The log:

```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337,1338
PROXY_GID=1337,1338
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_SERVERS=[],[]

Writing following contents to rules file:  /tmp/iptables-rules-1624302302470899943.txt609775029
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1624302302470899943.txt609775029
iptables-restore: line 2 failed
iptables-save 
# Generated by iptables-save v1.6.1 on Mon Jun 21 19:05:02 2021
*mangle
:PREROUTING ACCEPT [1467429:949737148]
:INPUT ACCEPT [1467429:949737148]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1435004:12778316560]
:POSTROUTING ACCEPT [1435004:12778316560]
COMMIT
# Completed on Mon Jun 21 19:05:02 2021
# Generated by iptables-save v1.6.1 on Mon Jun 21 19:05:02 2021
*nat
:PREROUTING ACCEPT [33916:2034960]
:INPUT ACCEPT [33916:2034960]
:OUTPUT ACCEPT [26697:2015234]
:POSTROUTING ACCEPT [26697:2015234]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Mon Jun 21 19:05:02 2021
# Generated by iptables-save v1.6.1 on Mon Jun 21 19:05:02 2021
*filter
:INPUT ACCEPT [1467429:949737148]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1435004:12778316560]
COMMIT
# Completed on Mon Jun 21 19:05:02 2021
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x27f6650, 0x1999655, 0x10, 0xc00050f220, 0x2, 0x2)
        istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc0008d1d68, 0x27c5601, 0x0, 0x0)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:618 +0x38a
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc0008d1d68)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:625 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc0008d1d68)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:563 +0x2dbb
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x27ade80, 0xc000783300, 0x0, 0x10)
        istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:59 +0x150
github.com/spf13/cobra.(*Command).execute(0x27ade80, 0xc000783200, 0x10, 0x10, 0x27ade80, 0xc000783200)
        github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x27ae120, 0x0, 0x0, 0x0)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        istio.io/istio/pilot/cmd/pilot-agent/main.go:457 +0x31

```

If i delete the pod and restart it again, everything is ok! I don't know why?

**Comment by devincd** [comment]
You can check the pods under `Init:CrashLoopBackOff` status whether in same node.

**Comment by zhengzepeng** [comment]
> You can check the pods under `Init:CrashLoopBackOff` status whether in same node.

No! They are different node!

**Comment by esnible** [comment]
The backtrace shows `executeIptablesRestoreCommand()` is failing on `iptConfigurator.ext.RunOrFail(cmd, "--noflush", rulesFile.Name())`.

Anything different in the logs between these crashes and when it works?

**Comment by zhengzepeng** [comment]
> The backtrace shows `executeIptablesRestoreCommand()` is failing on `iptConfigurator.ext.RunOrFail(cmd, "--noflush", rulesFile.Name())`.
> 
> Anything different in the logs between these crashes and when it works?

So It happend again!
```
[root@k8smaster ~]# k get pods
NAME                              READY   STATUS                  RESTARTS   AGE
details-v1-66b6955995-sstf5       0/2     Init:CrashLoopBackOff   398        4d18h
productpage-v1-5d9b4c9849-dsjhv   0/2     Init:CrashLoopBackOff   398        3d22h
ratings-v1-fd78f799f-zdnwv        0/2     Init:CrashLoopBackOff   398        4d18h
reviews-v1-6549ddccc5-qblk8       0/2     Init:CrashLoopBackOff   398        4d18h
reviews-v2-76c4865449-wd454       0/2     Init:CrashLoopBackOff   398        4d18h
reviews-v3-6b554c875-hlqtg        0/2     Init:CrashLoopBackOff   398        4d18h
```

Below are the crash logs and the normal logs:
[proxy-init-crash.log](https://github.com/istio/istio/files/6722780/proxy-init-crash.log) 
[proxy-init.log](https://github.com/istio/istio/files/6722782/proxy-init.log)

**Comment by zhengzepeng** [comment]
> The backtrace shows `executeIptablesRestoreCommand()` is failing on `iptConfigurator.ext.RunOrFail(cmd, "--noflush", rulesFile.Name())`.
> 
> Anything different in the logs between these crashes and when it works?

I found a situation, i noticed the pod status maybe `Init:CrashLoopBackOff`, but i saw the container inside, i found nothing wrong with the istio-proxy container. So i delete the pod, and edit the pod, make the istio-proxy container run with root(can exeute the iptables). Last i run the pod, and go inside the istio-proxy container, execute pilot-agent istio-iptables command, like that :

```
root@productpage-v1-58dd78b776-8zh4j:/usr/local/bin# /usr/local/bin/pilot-agent istio-iptables -p "15001" -z "15006" -u 1337,1338 -m REDIRECT -i '*' -x "" -b '*' -d 15090,15021,15020   
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337,1338
PROXY_GID=1337,1338
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_SERVERS=[],[]

Writing following contents to rules file:  /tmp/iptables-rules-1624847719551105474.txt239527509
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1624847719551105474.txt239527509
iptables-restore: line 2 failed
iptables-save 
# Generated by iptables-save v1.6.1 on Mon Jun 28 02:35:19 2021
*nat
:PREROUTING ACCEPT [61:6524]
:INPUT ACCEPT [29:1740]
:OUTPUT ACCEPT [336:26274]
:POSTROUTING ACCEPT [376:28674]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1338 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1338 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1338 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Mon Jun 28 02:35:19 2021
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x27f6650, 0x1999655, 0x10, 0xc0008ec780, 0x2, 0x2)
        istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc00083dd68, 0x27c5601, 0x0, 0x0)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:618 +0x38a
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc00083dd68)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:625 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc00083dd68)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:563 +0x2dbb
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x27ade80, 0xc00012f900, 0x0, 0x10)
        istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:59 +0x150
github.com/spf13/cobra.(*Command).execute(0x27ade80, 0xc00012f800, 0x10, 0x10, 0x27ade80, 0xc00012f800)
        github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x27ae120, 0x0, 0x0, 0x0)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        istio.io/istio/pilot/cmd/pilot-agent/main.go:457 +0x31
```

So the question should be why did my init container restart? This shouldn't be Istio's problem. I will try to find it out!

**Comment by zhengzepeng** [comment]
> The backtrace shows `executeIptablesRestoreCommand()` is failing on `iptConfigurator.ext.RunOrFail(cmd, "--noflush", rulesFile.Name())`.
> 
> Anything different in the logs between these crashes and when it works?

If kubelet gc delete the init container, and the init container will restart. So the probleam happend.(You can delete the init container by yourself)

**Comment by zhengzepeng** [comment]
I change the istio init container command , like that:
```
#!/bin/sh
# first to clean all exist rules
/usr/local/bin/pilot-agent istio-clean-iptables
/usr/local/bin/pilot-agent "$@"
```
Now if the init container restart, probleam never happend again.
