### ISSUE TITLE
Istiod crashes when external authz provider config does not provide port value.

### ISSUE THREAD

**Issue by incfly** [istio/istio#34693]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

A invalid MeshConfig, without port, can make Istiod crash looping.
Istio version: master (but should exist since 1.9)

```yaml
    extensionProviders:
      - name: "authservice-grpc"
        envoyExtAuthzGrpc:
        service: authservice.default.svc.cluster.local
        port: "10003"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
spec:
  selector:
    matchLabels:
      app: sleep
  action: CUSTOM
  provider:
    # The provider name must match the extension provider defined in the mesh config.
    name: authz-foo
  rules:
  - to:
    - operation:
        notPaths: ["/public"] # enable all except /public paths.
```

```
2021-08-14T06:35:25.351027Z	info	ads	EDS: PUSH request for node:sleep-854565cb79-v95gk.default resources:12 size:2.2kB empty:1 cached:0/12
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2ad07d7]

goroutine 679 [running]:
istio.io/istio/pilot/pkg/security/authz/builder.buildExtAuthzGRPC(0xc002138c78, 0x0, 0xc0010de590, 0x10, 0x597de80)
	istio.io/istio/pilot/pkg/security/authz/builder/extauthz.go:187 +0x37
istio.io/istio/pilot/pkg/security/authz/builder.processExtensionProvider(0xc002138c78, 0x0)
	istio.io/istio/pilot/pkg/security/authz/builder/extauthz.go:89 +0x1d6
istio.io/istio/pilot/pkg/security/authz/builder.New(0xc001f1f0e0, 0x1, 0x1, 0xc002138c78, 0x1, 0xc00212a840, 0x203000)
	istio.io/istio/pilot/pkg/security/authz/builder/builder.go:79 +0x1cf
istio.io/istio/pilot/pkg/networking/plugin/authz.Plugin.buildFilter(0x1, 0xc002138c78, 0xc00212a820)
	istio.io/istio/pilot/pkg/networking/plugin/authz/authorization.go:88 +0x1fd
istio.io/istio/pilot/pkg/networking/plugin/authz.Plugin.OnInboundListener(...)
	istio.io/istio/pilot/pkg/networking/plugin/authz/authorization.go:71
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildInboundFilterchains(0xc001033ec0, 0xc002138c78, 0xc0014b1600, 0xc0014b8f00, 0x35fd2fd, 0x7, 0xc002283650, 0x0, 0x0, 0x0, ...)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener_builder.go:623 +0xa26
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarInboundListenerForPortOrUDS(0xc001033ec0, 0xc0014b1600, 0xc0014b8f00, 0x35fd2fd, 0x7, 0xc002283650, 0x0, 0x0, 0x0, 0x0, ...)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:340 +0x518
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarInboundListeners(0xc001033ec0, 0xc0014b8f00, 0xc0014b1600, 0x0, 0xc0002572d8, 0x40dc9b)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:200 +0x38f
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ListenerBuilder).buildSidecarInboundListeners(...)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener_builder.go:349
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildSidecarListeners(0xc001033ec0, 0xc0015c94b0, 0xc0015c94f8)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:120 +0x65
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildListeners(0xc001033ec0, 0xc0014b8f00, 0xc0014b1600, 0x36, 0x36, 0xc0015c95f8)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:107 +0x157
istio.io/istio/pilot/pkg/xds.LdsGenerator.Generate(0xc000cd83c0, 0xc0014b8f00, 0xc0014b1600, 0xc001f07ce0, 0xc001f176d0, 0x5b0000c014ee9bb0, 0x14ee9bb000455127, 0x6117642d, 0xc0015c9638, 0x498046, ...)
	istio.io/istio/pilot/pkg/xds/lds.go:64 +0x84
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).pushXds(0xc000cd83c0, 0xc001dda0c0, 0xc0014b1600, 0xc001f07ce0, 0xc001f176d0, 0x0, 0x0)
	istio.io/istio/pilot/pkg/xds/xdsgen.go:101 +0x1d6
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).processRequest(0xc000cd83c0, 0xc00154ae00, 0xc001dda0c0, 0x0, 0x3)
	istio.io/istio/pilot/pkg/xds/ads.go:243 +0x24f
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Stream(0xc000cd83c0, 0x3b6ddb8, 0xc0015d0000, 0x40e301, 0xc0015d0000)
	istio.io/istio/pilot/pkg/xds/ads.go:318 +0x5ac
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).StreamAggregatedResources(0xc000cd83c0, 0x3b6ddb8, 0xc0015d0000, 0x3b03f38, 0xc000cd83c0)
	istio.io/istio/pilot/pkg/xds/ads.go:248 +0x3f
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x35f4300, 0xc000cd83c0, 0x3b628f8, 0xc00157fa40, 0x2d63600, 0xc0016d7ff0)
	github.com/envoyproxy/go-control-plane@v0.9.10-0.20210804155723-c55ac1656905/envoy/service/discovery/v3/ads.pb.go:298 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000023dc0, 0x3b71b98, 0xc0013d9500, 0xc0016c39e0, 0xc001115950, 0x58f7260, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.39.1/server.go:1542 +0xe73
google.golang.org/grpc.(*Server).handleStream(0xc000023dc0, 0x3b71b98, 0xc0013d9500, 0xc0016c39e0, 0x0)
	google.golang.org/grpc@v1.39.1/server.go:1622 +0xca5
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001d831b0, 0xc000023dc0, 0x3b71b98, 0xc0013d9500, 0xc0016c39e0)
	google.golang.org/grpc@v1.39.1/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.39.1/server.go:939 +0x1fd

```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Istiod log the error of invalid config for CUSTOM provider instead of crashing.

**Comment by hzxuzhonghu** [comment]
`port, err := parsePort(config.Port)` how does this panic lack of port?

**Comment by su225** [comment]
@hzxuzhonghu - It is possible only when `config` is `nil`. Somewhere in the call stack it could be passing nil resulting in blowing up like this

**Comment by incfly** [comment]
@su225 that's due to vim indent's credit :). yeah but my point is that crashing due to invalid config is an issue.

**Comment by su225** [comment]
@incfly - See "edit" section. That is the root cause. We do catch the error when configs are nil, but it is logged as warning at the moment.

**Comment by yangminzhu** [comment]
can we instead fix this directly in pilot/pkg/security/authz/builder/extauthz.go? We intentionally didn't want to block the user from a config that might not be actively used in the MeshConfig.

**Comment by yangminzhu** [comment]
closing, the issue has been fixed.
