### ISSUE TITLE
BenchmarkAnalyzersArtificialBlankData100 crashes

### ISSUE THREAD

**Issue by cuonglm** [istio/istio#35093]
### Bug Description

Coming here from [bencher](https://bencher.orijtech.com/), a continuous benchmarking infrastructure for Go language, which shows a crash when running istio benchmark suite:

```
BenchmarkAnalyzersArtificialBlankData100/deprecation.DeprecationAnalyzer-bench-8                                       	panic: interface conversion: proto.Message is *v1.CustomResourceDefinition, not *v1.CustomResourceDefinitionSpec

goroutine 15172 [running]:
istio.io/istio/galley/pkg/config/analysis/analyzers/deprecation.(*FieldAnalyzer).analyzeCRD(0xc00076b5a8, 0x18358f6, {0x42e8398, 0xc000cf7b00})
	/home/cuong/go/src/github.com/orijtech/istio/galley/pkg/config/analysis/analyzers/deprecation/deprecation.go:97 +0x411
istio.io/istio/galley/pkg/config/analysis/analyzers/deprecation.(*FieldAnalyzer).Analyze.func3(0xc00076b5e8)
	/home/cuong/go/src/github.com/orijtech/istio/galley/pkg/config/analysis/analyzers/deprecation/deprecation.go:84 +0x2b
istio.io/istio/galley/pkg/config/collection.(*Instance).ForEach(0x39447c0, 0xc000d66080)
	/home/cuong/go/src/github.com/orijtech/istio/galley/pkg/config/collection/instance.go:77 +0xf7
istio.io/istio/galley/pkg/config/analysis/analyzers.(*context).ForEach(0xc00076b6c8, {0x3f36e4b, 0x3fdcbd8}, 0x0)
	/home/cuong/go/src/github.com/orijtech/istio/galley/pkg/config/analysis/analyzers/analyzers_bench_test.go:66 +0x51
istio.io/istio/galley/pkg/config/analysis/analyzers/deprecation.(*FieldAnalyzer).Analyze(0x63bc7d0, {0x42e8398, 0xc000cf7b00})
	/home/cuong/go/src/github.com/orijtech/istio/galley/pkg/config/analysis/analyzers/deprecation/deprecation.go:83 +0x1f5
istio.io/istio/galley/pkg/config/analysis/analyzers.benchmarkAnalyzersArtificialBlankData.func2(0xc0009dad80)
	/home/cuong/go/src/github.com/orijtech/istio/galley/pkg/config/analysis/analyzers/analyzers_bench_test.go:176 +0x30
testing.(*B).runN(0xc0009dad80, 0x1)
	/home/cuong/sdk/go1.17/src/testing/benchmark.go:192 +0x126
testing.(*B).run1.func1()
	/home/cuong/sdk/go1.17/src/testing/benchmark.go:232 +0x59
created by testing.(*B).run1
	/home/cuong/sdk/go1.17/src/testing/benchmark.go:225 +0xa5
exit status 2
FAIL	istio.io/istio/galley/pkg/config/analysis/analyzers	29.681s
```

You can see more details [here](https://dashboard.github.orijtech.com/benchmark/59ab0a32f1c14733983170ce8216660a)

### Version

```prose
Commit: de3a8fc852b4ea2b420f083d74e533899f982c7c
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [X] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by cuonglm** [comment]
cc @odeke-em

**Comment by odeke-em** [comment]
Thank you for the report @cuonglm! For quick clarity the crash is here per https://dashboard.github.orijtech.com/benchmark/59ab0a32f1c14733983170ce8216660a
"panic: interface conversion: proto.Message is *v1.CustomResourceDefinition, not *v1.CustomResourceDefinitionSpec"
![image](https://user-images.githubusercontent.com/4898263/132643734-a5096d1f-a72d-43fa-8b24-24e68d9531fe.png)
