### ISSUE TITLE
fatal error: concurrent map iteration and map write in /debug/registryz

### ISSUE THREAD

**Issue by maxbischoff** [istio/istio#36448]
### Bug Description

Since upgrading to istio 1.12.0 our istiod instances crash regularly with following error:

```
fatal error: concurrent map iteration and map write

goroutine 13767 [running]:
runtime.throw({0x2e0daff, 0x462999})
	runtime/panic.go:1198 +0x71 fp=0xc021c32ee8 sp=0xc021c32eb8 pc=0x435891
runtime.mapiternext(0x17)
	runtime/map.go:858 +0x4eb fp=0xc021c32f58 sp=0xc021c32ee8 pc=0x40f90b
reflect.mapiternext(0x195)
	runtime/map.go:1346 +0x19 fp=0xc021c32f70 sp=0xc021c32f58 pc=0x4628d9
reflect.(*MapIter).Next(0xc01805d420)
	reflect/value.go:1618 +0x99 fp=0xc021c32f90 sp=0xc021c32f70 pc=0x4d4399
encoding/json.mapEncoder.encode({0x0}, 0xc00adcc100, {0x28462e0, 0xc00947cfc8, 0xc021c33208}, {0xc, 0x0})
	encoding/json/encode.go:799 +0x305 fp=0xc021c33150 sp=0xc021c32f90 pc=0x74aec5
encoding/json.mapEncoder.encode-fm(0x29c0380, {0x28462e0, 0xc00947cfc8, 0x27}, {0xf8, 0x31})
	encoding/json/encode.go:779 +0x45 fp=0xc021c33190 sp=0xc021c33150 pc=0x7556e5
encoding/json.structEncoder.encode({{{0xc009e2de60, 0x2f06798, 0x2974500}, 0xc01d43b680}}, 0xc00adcc100, {0x29c0380, 0xc00947cfc8, 0xe}, {0x0, 0x1})
	encoding/json/encode.go:761 +0x1f4 fp=0xc021c33240 sp=0xc021c33190 pc=0x74a914
encoding/json.structEncoder.encode-fm(0x29c0380, {0x29c0380, 0xc00947cfc8, 0xf3}, {0xc0, 0xc0})
	encoding/json/encode.go:732 +0x69 fp=0xc021c33298 sp=0xc021c33240 pc=0x755629
encoding/json.structEncoder.encode({{{0xc00ffc2d00, 0x400, 0x10}, 0xc01d43b830}}, 0xc00adcc100, {0x2cdf9e0, 0xc00947cf00, 0x41782b}, {0x0, 0x1})
	encoding/json/encode.go:761 +0x1f4 fp=0xc021c33348 sp=0xc021c33298 pc=0x74a914
encoding/json.structEncoder.encode-fm(0x29e2100, {0x2cdf9e0, 0xc00947cf00, 0x10}, {0x1, 0x0})
	encoding/json/encode.go:732 +0x69 fp=0xc021c333a0 sp=0xc021c33348 pc=0x755629
encoding/json.ptrEncoder.encode({0x91}, 0xc00adcc100, {0x29e2100, 0xc0259b9580, 0xc021c334d8}, {0x17, 0x0})
	encoding/json/encode.go:945 +0x27e fp=0xc021c33470 sp=0xc021c333a0 pc=0x74c61e
encoding/json.ptrEncoder.encode-fm(0x267c020, {0x29e2100, 0xc0259b9580, 0x4037e9}, {0x4, 0x0})
	encoding/json/encode.go:930 +0x45 fp=0xc021c334b0 sp=0xc021c33470 pc=0x755925
encoding/json.arrayEncoder.encode({0x10}, 0xc00adcc100, {0x267c020, 0xc025a2a1b0, 0x4035b2}, {0x70, 0x35})
	encoding/json/encode.go:916 +0xb5 fp=0xc021c33520 sp=0xc021c334b0 pc=0x74c255
encoding/json.arrayEncoder.encode-fm(0x44d374, {0x267c020, 0xc025a2a1b0, 0x40e5d0}, {0x5b, 0x10})
	encoding/json/encode.go:909 +0x45 fp=0xc021c33560 sp=0xc021c33520 pc=0x755865
encoding/json.sliceEncoder.encode({0xf}, 0xc00adcc100, {0x267c020, 0xc025a2a1b0, 0x267c020}, {0x8, 0x0})
	encoding/json/encode.go:889 +0x2e6 fp=0xc021c33668 sp=0xc021c33560 pc=0x74bd86
encoding/json.sliceEncoder.encode-fm(0x267c020, {0x267c020, 0xc025a2a1b0, 0x0}, {0xa8, 0xc0})
	encoding/json/encode.go:869 +0x45 fp=0xc021c336a8 sp=0xc021c33668 pc=0x7557a5
encoding/json.(*encodeState).reflectValue(0xc021c33740, {0x267c020, 0xc025a2a1b0, 0x330}, {0xc0, 0x94})
	encoding/json/encode.go:360 +0x78 fp=0xc021c33708 sp=0xc021c336a8 pc=0x7484b8
encoding/json.(*encodeState).marshal(0x30, {0x267c020, 0xc025a2a1b0}, {0x0, 0x0})
	encoding/json/encode.go:332 +0xfa fp=0xc021c33780 sp=0xc021c33708 pc=0x7480da
encoding/json.Marshal({0x267c020, 0xc025a2a1b0})
	encoding/json/encode.go:161 +0x45 fp=0xc021c337e0 sp=0xc021c33780 pc=0x747745
istio.io/istio/pkg/config.ToJSON({0x267c020, 0xc025a2a1b0})
	istio.io/istio/pkg/config/model.go:178 +0x128 fp=0xc021c33840 sp=0xc021c337e0 pc=0x156aa28
istio.io/istio/pilot/pkg/xds.writeJSON({0x32bc680, 0xc014999260}, {0x267c020, 0xc025a2a1b0})
	istio.io/istio/pilot/pkg/xds/debug.go:939 +0xd6 fp=0xc021c338a0 sp=0xc021c33840 pc=0x24751f6
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).registryz(0xc0257868f0, {0x32bc680, 0xc014999260}, 0xc01bfd1ef0)
	istio.io/istio/pilot/pkg/xds/debug.go:290 +0x5e fp=0xc021c338d0 sp=0xc021c338a0 pc=0x246f99e
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).registryz-fm({0x32bc680, 0xc014999260}, 0xc025786900)
	istio.io/istio/pilot/pkg/xds/debug.go:285 +0x3c fp=0xc021c33900 sp=0xc021c338d0 pc=0x2496d5c
net/http.HandlerFunc.ServeHTTP(0xc0002697c0, {0x32bc680, 0xc014999260}, 0xc0250da024)
	net/http/server.go:2046 +0x2f fp=0xc021c33928 sp=0xc021c33900 pc=0x83f6cf
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).allowAuthenticatedOrLocalhost.func1({0x32bc680, 0xc014999260}, 0xc0239ec000)
	istio.io/istio/pilot/pkg/xds/debug.go:223 +0xdd fp=0xc021c33a48 sp=0xc021c33928 pc=0x246f0dd
net/http.HandlerFunc.ServeHTTP(0x0, {0x32bc680, 0xc014999260}, 0x0)
	net/http/server.go:2046 +0x2f fp=0xc021c33a70 sp=0xc021c33a48 pc=0x83f6cf
net/http.(*ServeMux).ServeHTTP(0x0, {0x32bc680, 0xc014999260}, 0xc0239ec000)
	net/http/server.go:2424 +0x149 fp=0xc021c33ac0 sp=0xc021c33a70 pc=0x840fc9
net/http.serverHandler.ServeHTTP({0xc023fa2810}, {0x32bc680, 0xc014999260}, 0xc0239ec000)
	net/http/server.go:2878 +0x43b fp=0xc021c33b80 sp=0xc021c33ac0 pc=0x842c3b
net/http.(*conn).serve(0xc02e7ee320, {0x32dbcd8, 0xc0030d6e40})
	net/http/server.go:1929 +0xb08 fp=0xc021c33fb8 sp=0xc021c33b80 pc=0x83e7a8
net/http.(*Server).Serve·dwrap·87()
	net/http/server.go:3033 +0x2e fp=0xc021c33fe0 sp=0xc021c33fb8 pc=0x84358e
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc021c33fe8 sp=0xc021c33fe0 pc=0x468b41
created by net/http.(*Server).Serve
	net/http/server.go:3033 +0x4e8
```

As far as I understand it from the stack trace, this happens when `/debug/registryz` is called

### Version

```prose
$ istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (16 proxies)
$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.21.7
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by zijianz** [comment]
Not only registryz, I am seeing `endpointsz` as well

```
fatal error: concurrent map iteration and map write


goroutine 70921 [running]:
runtime.throw({0x31d4354, 0x100000000000020})
        runtime/panic.go:1198 +0x71 fp=0xc0542547f8 sp=0xc0542547c8 pc=0x435af1
runtime.mapiternext(0x30e55a0)
        runtime/map.go:858 +0x4eb fp=0xc054254868 sp=0xc0542547f8 pc=0x40fb6b
runtime.mapiterinit(0x501, 0xc0542548d8, 0x4d472a)
        runtime/map.go:848 +0x236 fp=0xc054254888 sp=0xc054254868 pc=0x40f636
reflect.mapiterinit(0x2baec40, 0xc010999ec8)
        runtime/map.go:1340 +0x45 fp=0xc0542548c8 sp=0xc054254888 pc=0x462ae5
reflect.(*MapIter).Next(0xc0a3c65aa0)
        reflect/value.go:1626 +0x5a fp=0xc0542548e8 sp=0xc0542548c8 pc=0x4d463a
encoding/json.mapEncoder.encode({0x0}, 0xc0bee74f80, {0x2baec40, 0xc010999ec8, 0xc054254b60}, {0xc, 0x0})
        encoding/json/encode.go:799 +0x305 fp=0xc054254aa8 sp=0xc0542548e8 pc=0x74b425
encoding/json.mapEncoder.encode-fm(0x2d73640, {0x2baec40, 0xc010999ec8, 0x2c}, {0x50, 0x4b})
        encoding/json/encode.go:779 +0x45 fp=0xc054254ae8 sp=0xc054254aa8 pc=0x755c45
encoding/json.structEncoder.encode({{{0xc0f94b6480, 0x32cdc08, 0x2d27400}, 0xc0f94b43c0}}, 0xc0bee74f80, {0x2d73640, 0xc010999ec8, 0xe}, {0x0, 0x1})
        encoding/json/encode.go:761 +0x1f4 fp=0xc054254b98 sp=0xc054254ae8 pc=0x74ae74
encoding/json.structEncoder.encode-fm(0x2d73640, {0x2d73640, 0xc010999ec8, 0x181}, {0x0, 0x1})
        encoding/json/encode.go:732 +0x69 fp=0xc054254bf0 sp=0xc054254b98 pc=0x755b89
encoding/json.structEncoder.encode({{{0xc0c5bc7600, 0x0, 0xc054254d38}, 0xc0f94b4540}}, 0xc0bee74f80, {0x30a3000, 0xc010999e00, 0x7}, {0x0, 0x1})
        encoding/json/encode.go:761 +0x1f4 fp=0xc054254ca0 sp=0xc054254bf0 pc=0x74ae74
encoding/json.structEncoder.encode-fm(0x2d957c0, {0x30a3000, 0xc010999e00, 0x10}, {0x0, 0x20})
        encoding/json/encode.go:732 +0x69 fp=0xc054254cf8 sp=0xc054254ca0 pc=0x755b89
encoding/json.ptrEncoder.encode({0x0}, 0xc0bee74f80, {0x2d957c0, 0xc0da599350, 0xc075776520}, {0xa, 0x0})
        encoding/json/encode.go:945 +0x27e fp=0xc054254dc8 sp=0xc054254cf8 pc=0x74cb7e
encoding/json.ptrEncoder.encode-fm(0x2d957c0, {0x2d957c0, 0xc0da599350, 0x2}, {0x19, 0x0})
        encoding/json/encode.go:930 +0x45 fp=0xc054254e08 sp=0xc054254dc8 pc=0x755e85
encoding/json.structEncoder.encode({{{0xc036eec240, 0xc075776520, 0x31a7394}, 0xc036f14420}}, 0xc0bee74f80, {0x2e28b40, 0xc0da599350, 0x31}, {0x0, 0x1})
        encoding/json/encode.go:761 +0x1f4 fp=0xc054254eb8 sp=0xc054254e08 pc=0x74ae74
encoding/json.structEncoder.encode-fm(0x2c36660, {0x2e28b40, 0xc0da599350, 0xc06fa844e0}, {0x24, 0x0})
        encoding/json/encode.go:732 +0x69 fp=0xc054254f10 sp=0xc054254eb8 pc=0x755b89
encoding/json.ptrEncoder.encode({0xc077639dc8}, 0xc0bee74f80, {0x2c36660, 0xc0da654368, 0x30}, {0x17, 0x0})
        encoding/json/encode.go:945 +0x27e fp=0xc054254fe0 sp=0xc054254f10 pc=0x74cb7e
encoding/json.ptrEncoder.encode-fm(0x29d8ea0, {0x2c36660, 0xc0da654368, 0xc077dd61c0}, {0x0, 0x0})
        encoding/json/encode.go:930 +0x45 fp=0xc054255020 sp=0xc054254fe0 pc=0x755e85
encoding/json.arrayEncoder.encode({0xc06fa846c0}, 0xc0bee74f80, {0x29d8ea0, 0xc102a38078, 0xc06fb16440}, {0x4, 0x0})
        encoding/json/encode.go:916 +0xb5 fp=0xc054255090 sp=0xc054255020 pc=0x74c7b5
encoding/json.arrayEncoder.encode-fm(0xc06fa844e0, {0x29d8ea0, 0xc102a38078, 0x0}, {0x8, 0x0})
        encoding/json/encode.go:909 +0x45 fp=0xc0542550d0 sp=0xc054255090 pc=0x755dc5
encoding/json.sliceEncoder.encode({0x2a82600}, 0xc0bee74f80, {0x29d8ea0, 0xc102a38078, 0x7f21b0942ba1}, {0x5, 0x0})
        encoding/json/encode.go:889 +0x2e6 fp=0xc0542551d8 sp=0xc0542550d0 pc=0x74c2e6
encoding/json.sliceEncoder.encode-fm(0x2d754e0, {0x29d8ea0, 0xc102a38078, 0x4143c6}, {0x0, 0x7e})
        encoding/json/encode.go:869 +0x45 fp=0xc054255218 sp=0xc0542551d8 pc=0x755d05
encoding/json.structEncoder.encode({{{0xc036ebcb40, 0x7f21aeca7e00, 0x0}, 0xc036f14480}}, 0xc0bee74f80, {0x2d754e0, 0xc102a38068, 0x17}, {0x0, 0x1})
        encoding/json/encode.go:761 +0x1f4 fp=0xc0542552c8 sp=0xc054255218 pc=0x74ae74
encoding/json.structEncoder.encode-fm(0x29e79a0, {0x2d754e0, 0xc102a38068, 0x403a49}, {0x20, 0x1})
        encoding/json/encode.go:732 +0x69 fp=0xc054255320 sp=0xc0542552c8 pc=0x755b89
encoding/json.arrayEncoder.encode({0x8}, 0xc0bee74f80, {0x29e79a0, 0xc0cdb90810, 0x403812}, {0xe0, 0x53})
        encoding/json/encode.go:916 +0xb5 fp=0xc054255390 sp=0xc054255320 pc=0x74c7b5
encoding/json.arrayEncoder.encode-fm(0x203038, {0x29e79a0, 0xc0cdb90810, 0x40e830}, {0x66, 0x19})
        encoding/json/encode.go:909 +0x45 fp=0xc0542553d0 sp=0xc054255390 pc=0x755dc5
encoding/json.sliceEncoder.encode({0x473d89}, 0xc0bee74f80, {0x29e79a0, 0xc0cdb90810, 0x29e79a0}, {0x40, 0x55})
        encoding/json/encode.go:889 +0x2e6 fp=0xc0542554d8 sp=0xc0542553d0 pc=0x74c2e6
encoding/json.sliceEncoder.encode-fm(0x29e79a0, {0x29e79a0, 0xc0cdb90810, 0xc0b9b3f800}, {0x0, 0x0})
        encoding/json/encode.go:869 +0x45 fp=0xc054255518 sp=0xc0542554d8 pc=0x755d05
encoding/json.(*encodeState).reflectValue(0xc0542555b0, {0x29e79a0, 0xc0cdb90810, 0x5}, {0xe0, 0xec})
        encoding/json/encode.go:360 +0x78 fp=0xc054255578 sp=0xc054255518 pc=0x748a18
encoding/json.(*encodeState).marshal(0x30, {0x29e79a0, 0xc0cdb90810}, {0x20, 0x68})
        encoding/json/encode.go:332 +0xfa fp=0xc0542555f0 sp=0xc054255578 pc=0x74863a
encoding/json.Marshal({0x29e79a0, 0xc0cdb90810})
        encoding/json/encode.go:161 +0x45 fp=0xc054255650 sp=0xc0542555f0 pc=0x747ca5
istio.io/istio/pkg/config.ToJSON({0x29e79a0, 0xc0cdb90810})
        istio.io/istio/pkg/config/model.go:178 +0x128 fp=0xc0542556b0 sp=0xc054255650 pc=0x156b408
istio.io/istio/pilot/pkg/xds.writeJSON({0x36a2210, 0xc0d3622000}, {0x29e79a0, 0xc0cdb90810})
        istio.io/istio/pilot/pkg/xds/debug.go:939 +0xd6 fp=0xc054255710 sp=0xc0542556b0 pc=0x27c87b6
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).endpointz(0xc000c606e0, {0x36a2210, 0xc0d3622000}, 0xc0d3608ed0)
        istio.io/istio/pilot/pkg/xds/debug.go:377 +0x165 fp=0xc0542558d0 sp=0xc054255710 pc=0x27c3925
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).endpointz-fm({0x36a2210, 0xc0d3622000}, 0xc0c3df1900)
        istio.io/istio/pilot/pkg/xds/debug.go:350 +0x3c fp=0xc054255900 sp=0xc0542558d0 pc=0x27ea4fc
net/http.HandlerFunc.ServeHTTP(0xc000f9eec0, {0x36a2210, 0xc0d3622000}, 0xc0d5ad3484)
        net/http/server.go:2047 +0x2f fp=0xc054255928 sp=0xc054255900 pc=0x840d8f
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).allowAuthenticatedOrLocalhost.func1({0x36a2210, 0xc0d3622000}, 0xc0ce1a8900)
        istio.io/istio/pilot/pkg/xds/debug.go:223 +0xdd fp=0xc054255a48 sp=0xc054255928 pc=0x27c269d
net/http.HandlerFunc.ServeHTTP(0x0, {0x36a2210, 0xc0d3622000}, 0x0)
        net/http/server.go:2047 +0x2f fp=0xc054255a70 sp=0xc054255a48 pc=0x840d8f
net/http.(*ServeMux).ServeHTTP(0x0, {0x36a2210, 0xc0d3622000}, 0xc0ce1a8900)
        net/http/server.go:2425 +0x149 fp=0xc054255ac0 sp=0xc054255a70 pc=0x842689
net/http.serverHandler.ServeHTTP({0xc0be5b9200}, {0x36a2210, 0xc0d3622000}, 0xc0ce1a8900)
        net/http/server.go:2879 +0x43b fp=0xc054255b80 sp=0xc054255ac0 pc=0x8442fb
net/http.(*conn).serve(0xc0119a2460, {0x36c21b8, 0xc0013da6f0})
        net/http/server.go:1930 +0xb08 fp=0xc054255fb8 sp=0xc054255b80 pc=0x83fe68
net/http.(*Server).Serve·dwrap·87()
        net/http/server.go:3034 +0x2e fp=0xc054255fe0 sp=0xc054255fb8 pc=0x844c4e
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc054255fe8 sp=0xc054255fe0 pc=0x468da1
created by net/http.(*Server).Serve
        net/http/server.go:3034 +0x4e8
```

**Comment by ramaraochavali** [comment]
This seems to have been fixed. @hzxuzhonghu
