### ISSUE TITLE
kube-inject panic

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36899]
```
$ cat ~/kube/shell/shell.yaml| ik kube-inject -f -
2022-01-19T21:02:44.896317Z     warn    failed to get injection config from mutatingWebhookConfigurations "istio-sidecar-injector", will fall back to get injection from the injection configmap "istio-sidecar-injector" : could not find valid mutatingWebhookConfiguration "sidecar-injector.istio.io" from cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x3f11d24]

goroutine 1 [running]:
istio.io/istio/pkg/kube/inject.RunTemplate({0xc000500400, {{0xc00103b857, 0x5}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        /home/howardjohn/go/src/istio.io/istio/pkg/kube/inject/inject.go:412 +0x6e4
istio.io/istio/pkg/kube/inject.injectPod({0xc000500400, {{0xc00103b857, 0x5}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        /home/howardjohn/go/src/istio.io/istio/pkg/kube/inject/webhook.go:358 +0xc5
istio.io/istio/pkg/kube/inject.IntoObject({0x52d42e0, 0xc00103c600}, 0xc000d12d50, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x5316068, 0xc000dc5200}, ...)
        /home/howardjohn/go/src/istio.io/istio/pkg/kube/inject/inject.go:788 +0xdf8
istio.io/istio/pkg/kube/inject.IntoResourceFile({0x52d42e0, 0xc00103c600}, 0xc000b67210, {0x0, 0x0}, {0x0, 0x0}, 0xc000d135f0, {0x52d5980, 0xc000010010}, ...)
        /home/howardjohn/go/src/istio.io/istio/pkg/kube/inject/inject.go:576 +0x32a
istio.io/istio/istioctl/cmd.injectCommand.func1(0xc000be0780, {0xc000683a40, 0x0, 0x2})
        /home/howardjohn/go/src/istio.io/istio/istioctl/cmd/kubeinject.go:594 +0x3f7
github.com/spf13/cobra.(*Command).execute(0xc000be0780, {0xc000683a20, 0x2, 0x2})
        /home/howardjohn/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000be0500)
        /home/howardjohn/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/howardjohn/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        /home/howardjohn/go/src/istio.io/istio/istioctl/cmd/istioctl/main.go:39 +0xde
```

**Comment by howardjohn** [comment]
I don't have a MWH but do have Istiod running in cluster. I do have all the configmaps so it should be able to use those.

Also tried `--xds-address istiod.istio-system.svc` but seems to do nothing... maybe separate issue though

**Comment by therealmitchconnors** [comment]
not stale

**Comment by howardjohn** [comment]
Also this one:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"shell","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"shell"}},"template":{"metadata":{"annotations":{"proxy.istio.io/config":"proxyMetadata:\n  OUTPUT_CERTS: /etc/istio-output-certs\n","sidecar.istio.io/userVolumeMount":"[{\"name\": \"istio-certs\", \"mountPath\": \"/etc/istio-output-certs\"}]","traffic.sidecar.istio.io/includeInboundPorts":"","traffic.sidecar.istio.io/includeOutboundIPRanges":""},"labels":{"app":"shell"}},"spec":{"containers":[{"args":["/bin/sleep","infinity"],"image":"gcr.io/istio-testing/app:latest","imagePullPolicy":"IfNotPresent","name":"shell","resources":{"limits":{"cpu":"500m","memory":"500M"},"requests":{"cpu":"10m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/etc/istio-output-certs","name":"istio-certs"}]}],"terminationGracePeriodSeconds":0,"volumes":[{"emptyDir":{"medium":"Memory"},"name":"istio-certs"}]}}}}
  creationTimestamp: "2022-08-22T15:07:05Z"
  generation: 5
  name: shell
  namespace: default
  resourceVersion: "3705"
  uid: 80e99bb6-c9ac-4621-9b5b-9794ce60a9b1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shell
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-output-certs
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
        traffic.sidecar.istio.io/includeInboundPorts: ""
        traffic.sidecar.istio.io/includeOutboundIPRanges: ""
      creationTimestamp: null
      labels:
        app: shell
    spec:
      containers:
      - args:
        - /bin/sleep
        - infinity
        image: gcr.io/istio-testing/app:latest
        imagePullPolicy: IfNotPresent
        name: shell
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 10m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio-output-certs
          name: istio-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-certs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-22T15:22:07Z"
    lastUpdateTime: "2022-08-22T15:22:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-22T15:07:08Z"
    lastUpdateTime: "2022-08-22T15:31:01Z"
    message: ReplicaSet "shell-85f9ff4887" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

```
$ k get deployment shell -oyaml | ~/istio/istio-1.14.3/bin/istioctl kube-inject -f -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x22760c2]

goroutine 1 [running]:
istio.io/istio/pkg/config/mesh.ApplyProxyConfig({0xc0003bf9c0, 0x37}, 0x3123780?)
        istio.io/istio/pkg/config/mesh/mesh.go:144 +0x42
istio.io/istio/pkg/kube/inject.IntoObject({0x36d18a0, 0xc00124cc00}, 0xc00124cc30, {{0x0?, 0xc00124cd50?}, 0xc00064c480?, 0xc00124ccc0?}, {0x0, 0x0}, 0x0, ...)
        istio.io/istio/pkg/kube/inject/inject.go:747 +0xb2d
istio.io/istio/pkg/kube/inject.IntoResourceFile({0x36d18a0, 0xc00124cc00}, 0x15?, {{0x0?, 0xc000fffbe0?}, 0xc00064c480?, 0xc00124ccc0?}, {0x0, 0x0}, 0x0, ...)
        istio.io/istio/pkg/kube/inject/inject.go:560 +0x387
istio.io/istio/istioctl/cmd.injectCommand.func1(0xc000be6f00?, {0xc000caa5e0?, 0x0?, 0x2?})
        istio.io/istio/istioctl/cmd/kubeinject.go:618 +0x468
github.com/spf13/cobra.(*Command).execute(0xc000be6f00, {0xc000caa5c0, 0x2, 0x2})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000be6c80)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        istio.io/istio/istioctl/cmd/istioctl/main.go:39 +0xdd
```
