### ISSUE TITLE
Istio 1-10-6 ➡️ 1-11-6 Canary Upgrade Failed: Sidecar Injection Panic

### ISSUE THREAD

**Issue by rrpolanco** [istio/istio#37671]
### Bug Description

I attempted to do a canary upgrade from Istio `1-10-6` to `1-11-6`. 

The Istio `1-10-6` initial control plane was installed using the controller operator. 
Istio `1-11-6` was installed using the manifests generated from `istioctl manifest generate -r 1-11-6`.

After the upgrade, the `1-11-6` Istiod pods reported the following errors:
```
istiod-1-11-6-645bdf9d46-w6n9h discovery 2022-03-02T20:24:36.661176Z    info    Sidecar injection request for monitoring/armada-ops-blackbox-exporter-8b9797dd6-***** (actual name not yet known)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.632527Z    info    ads     EDS: PUSH for node:istio-ingressgateway-dal13-public-7547b9cd6b-69vfm.istio-system resources:175 size:145.8kB empty:0 cached:163/175
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.634686Z    info    ads     LDS: PUSH for node:istio-ingressgateway-dal10-public-5bbfddbcbf-cw7tx.istio-system resources:2 size:39.1kB
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.634865Z    info    ads     LDS: PUSH for node:istio-ingressgateway-dal13-public-7547b9cd6b-69vfm.istio-system resources:2 size:39.1kB
istiod-1-11-6-645bdf9d46-w6n9h discovery 2022-03-02T20:24:36.665055Z    info    http: panic serving 172.18.100.166:33318: runtime error: comparing uncomparable type []interface {}
istiod-1-11-6-645bdf9d46-w6n9h discovery goroutine 1023 [running]:
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.649293Z    info    ads     EDS: PUSH for node:istio-ingressgateway-dal13-private-5d78f577f-5625p.istio-system resources:175 size:145.8kB empty:0 cached:175/175
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.656051Z    info    ads     LDS: PUSH for node:istio-ingressgateway-dal13-private-5d78f577f-5625p.istio-system resources:2 size:39.1kB
istiod-1-11-6-645bdf9d46-w6n9h discovery net/http.(*conn).serve.func1(0xc00310c5a0)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.662403Z    info    ads     EDS: PUSH for node:istio-ingressgateway-dal12-private-7ff45c4487-lv8qp.istio-system resources:175 size:145.8kB empty:0 cached:172/175
istiod-1-11-6-645bdf9d46-w6n9h discovery        net/http/server.go:1805 +0x153
istiod-1-11-6-645bdf9d46-w6n9h discovery panic(0x2fbfa60, 0xc003bf4e80)
istiod-1-11-6-645bdf9d46-w6n9h discovery        runtime/panic.go:971 +0x499
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.665187Z    info    ads     LDS: PUSH for node:istio-ingressgateway-dal12-private-7ff45c4487-lv8qp.istio-system resources:2 size:39.1kB
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.680131Z    info    ads     EDS: PUSH for node:istio-ingressgateway-dal12-public-6dd588687d-vpzfc.istio-system resources:175 size:145.8kB empty:0 cached:175/175
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.findMapInSliceBasedOnKeyValue(0xc003bf4e70, 0x1, 0x1, 0x31024ef, 0x4, 0x2d875a0, 0xc005bdda10, 0x0, 0x0, 0x0, ...)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.682647Z    info    ads     LDS: PUSH for node:istio-ingressgateway-dal12-public-6dd588687d-vpzfc.istio-system resources:2 size:39.1kB
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:1577 +0x185
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.807549Z    info    ads     XDS: Pushing:2022-03-02T20:23:02Z/23 Services:143 ConnectedEndpoints:16  Version:2022-03-02T20:23:02Z/23
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:02.927973Z    info    ads     Push debounce stable[74] 8: 132.239686ms since last change, 237.618326ms since last push, full=true
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.partitionMapsByPresentInList(0xc006211020, 0x2, 0x2, 0xc003bf4e70, 0x1, 0x1, 0x31024ef, 0x4, 0x3b0e260, 0xc003bf4e60, ...)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.175393Z    info    ads     XDS: Pushing:2022-03-02T20:23:02Z/24 Services:143 ConnectedEndpoints:16  Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:1261 +0x1db
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.201724Z    info    ads     CDS: PUSH for node:istio-egressgateway-with-sni-proxy-dal12-7bc9884c86-n2x2v.istio-system resources:176 size:180.0kB
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.mergeSlice(0xc003bf4050, 0x1, 0x1, 0xc003bf4e70, 0x1, 0x1, 0x3b0e260, 0xc003bf4e60, 0x31024ef, 0x4, ...)
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:1454 +0x576
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.216079Z    info    ads     EDS: PUSH for node:istio-egressgateway-with-sni-proxy-dal12-7bc9884c86-n2x2v.istio-system resources:175 size:148.9kB empty:0 cached:156/175
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.216606Z    info    ads     LDS: PUSH for node:istio-egressgateway-with-sni-proxy-dal12-7bc9884c86-n2x2v.istio-system resources:1 size:5.3kB
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.mergeSliceHandler(0x2d875a0, 0xc005bdd8d8, 0x2d875a0, 0xc005bdda28, 0x3b0e260, 0xc003bf4e60, 0x31024d9, 0x5, 0x31024ef, 0x4, ...)
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:1401 +0x16c
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.240746Z    info    ads     CDS: PUSH for node:istio-egressgateway-with-sni-proxy-dal12-7bc9884c86-n2x2v.istio-system resources:176 size:180.0kB
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.mergeMap(0xc008249350, 0xc008249bc0, 0x3b0e260, 0xc003bf4dd0, 0xc008240101, 0xc008249bc0, 0x0, 0x0)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.272625Z    info    ads     EDS: PUSH for node:istio-egressgateway-with-sni-proxy-dal12-7bc9884c86-n2x2v.istio-system resources:175 size:148.9kB empty:0 cached:175/175
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.273521Z    info    ads     LDS: PUSH for node:istio-egressgateway-with-sni-proxy-dal12-7bc9884c86-n2x2v.istio-system resources:1 size:5.3kB
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:1364 +0x7c5
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.673490Z    info    ads     Push debounce stable[75] 16: 158.17799ms since last change, 280.988286ms since last push, full=false
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:03.673815Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.mergeMapHandler(0x2f7f8e0, 0xc008249350, 0x2f7f8e0, 0xc008249bc0, 0x3b0e260, 0xc003bf4dd0, 0x0, 0x0, 0x101, 0x0, ...)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:04.636883Z    info    ads     Push debounce stable[76] 5: 188.174711ms since last change, 232.496253ms since last push, full=false
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:04.636915Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:1385 +0xb5
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.mergeMap(0xc008249230, 0xc008249ad0, 0x3b0e260, 0xc003b99ac0, 0xc002a90101, 0x0, 0x0, 0xc002a9bbc0)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:05.327051Z    info    ads     Push debounce stable[77] 5: 154.444312ms since last change, 295.157174ms since last push, full=false
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:1354 +0xb26
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:05.327213Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.StrategicMergeMapPatchUsingLookupPatchMeta(0xc008249230, 0xc008249ad0, 0x3b0e260, 0xc003b99ac0, 0x0, 0x0, 0xc003b99ac0)
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:880 +0x50
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:05.582432Z    info    ads     Push debounce stable[78] 1: 100.026531ms since last change, 100.026531ms since last push, full=false
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.StrategicMergePatchUsingLookupPatchMeta(0xc000413c00, 0xab6, 0xc00, 0xc005fd1500, 0x14e6, 0x1500, 0x3b0e260, 0xc003b99ac0, 0xc0060b50f8, 0x40b4df, ...)
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:831 +0xd5
istiod-1-11-6-645bdf9d46-w6n9h discovery k8s.io/apimachinery/pkg/util/strategicpatch.StrategicMergePatch(0xc000413c00, 0xab6, 0xc00, 0xc005fd1500, 0x14e6, 0x1500, 0x32d48c0, 0xc005e07800, 0xc005e1b468, 0x7, ...)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:05.582558Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:06.097913Z    info    ads     Push debounce stable[79] 13: 107.920607ms since last change, 221.592701ms since last push, full=false
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:06.098150Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-w6n9h discovery        k8s.io/apimachinery@v0.21.2/pkg/util/strategicpatch/patch.go:818 +0x116
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:06.201528Z    info    ads     Push debounce stable[80] 2: 103.48854ms since last change, 103.500588ms since last push, full=false
istiod-1-11-6-645bdf9d46-w6n9h discovery istio.io/istio/pkg/kube/inject.applyOverlay(0xc0059cac00, 0xc005fd1500, 0x14e6, 0x1500, 0xc005fd1500, 0x14e6, 0x1500)
istiod-1-11-6-645bdf9d46-w6n9h discovery        istio.io/istio/pkg/kube/inject/webhook.go:701 +0x14d
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:06.390290Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:06.837543Z    info    ads     Push debounce stable[81] 14: 160.731855ms since last change, 345.117962ms since last push, full=false
istiod-1-11-6-645bdf9d46-w6n9h discovery istio.io/istio/pkg/kube/inject.RunTemplate(0xc0059cac00, 0xc00808e630, 0x1c, 0xc00808e570, 0x27, 0xc005b569e0, 0xa, 0x0, 0x0, 0x0, ...)
istiod-1-11-6-645bdf9d46-w6n9h discovery        istio.io/istio/pkg/kube/inject/inject.go:378 +0xd25
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:06.837687Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.233161Z    info    ads     RDS: PUSH for node:istio-ingressgateway-dal10-private-7788fd7cf9-rg8kd.istio-system resources:7 size:285.6kB
istiod-1-11-6-645bdf9d46-w6n9h discovery istio.io/istio/pkg/kube/inject.injectPod(0xc0059cac00, 0xc00808e630, 0x1c, 0xc00808e570, 0x27, 0xc005b569e0, 0xa, 0x0, 0x0, 0x0, ...)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.248068Z    info    ads     CDS: PUSH for node:istio-ingressgateway-dal10-private-7788fd7cf9-rg8kd.istio-system resources:176 size:180.0kB
istiod-1-11-6-645bdf9d46-w6n9h discovery        istio.io/istio/pkg/kube/inject/webhook.go:356 +0xd8
istiod-1-11-6-645bdf9d46-w6n9h discovery istio.io/istio/pkg/kube/inject.(*Webhook).inject(0xc000670480, 0xc009052330, 0xc008350785, 0x7, 0x0)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.258339Z    info    ads     EDS: PUSH for node:istio-ingressgateway-dal10-private-7788fd7cf9-rg8kd.istio-system resources:175 size:153.9kB empty:0 cached:156/175
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.259093Z    info    ads     Push debounce stable[82] 4: 143.598459ms since last change, 145.202548ms since last push, full=false
istiod-1-11-6-645bdf9d46-w6n9h discovery        istio.io/istio/pkg/kube/inject/webhook.go:759 +0x8f8
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.259194Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.278484Z    info    ads     LDS: PUSH for node:istio-ingressgateway-dal10-private-7788fd7cf9-rg8kd.istio-system resources:2 size:39.1kB
istiod-1-11-6-645bdf9d46-w6n9h discovery istio.io/istio/pkg/kube/inject.(*Webhook).serveInject(0xc000670480, 0x3b0d240, 0xc00838b260, 0xc001935300)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.529093Z    info    ads     Push debounce stable[83] 17: 101.972531ms since last change, 131.346973ms since last push, full=false
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.538955Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-w6n9h discovery        istio.io/istio/pkg/kube/inject/webhook.go:816 +0x932
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.610058Z    info    ads     RDS: PUSH for node:istio-ingressgateway-dal12-private-7ff45c4487-lv8qp.istio-system resources:7 size:285.6kB
istiod-1-11-6-645bdf9d46-pgrs5 discovery 2022-03-02T20:23:01.577262Z    info    ads     Push debounce stable[76] 49: 100.425315ms since last change, 554.777531ms since last push, full=false
istiod-1-11-6-645bdf9d46-w6n9h discovery net/http.HandlerFunc.ServeHTTP(0xc000dae870, 0x3b0d240, 0xc00838b260, 0xc001935300)
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.623768Z    info    ads     CDS: PUSH for node:istio-ingressgateway-dal12-private-7ff45c4487-lv8qp.istio-system resources:176 size:180.0kB
istiod-1-11-6-645bdf9d46-w6n9h discovery        net/http/server.go:2050 +0x44
istiod-1-11-6-645bdf9d46-pgrs5 discovery 2022-03-02T20:23:01.577417Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:22:38Z/21 ConnectedEndpoints:19 Version:2022-03-02T20:22:38Z/21
istiod-1-11-6-645bdf9d46-pgrs5 discovery 2022-03-02T20:23:02.065406Z    info    ads     Push debounce stable[77] 1: 100.428687ms since last change, 100.426279ms since last push, full=true
istiod-1-11-6-645bdf9d46-w6n9h discovery net/http.(*ServeMux).ServeHTTP(0xc001742ec0, 0x3b0d240, 0xc00838b260, 0xc001935300)
istiod-1-11-6-645bdf9d46-w6n9h discovery        net/http/server.go:2429 +0x1ad
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.632612Z    info    ads     EDS: PUSH for node:istio-ingressgateway-dal12-private-7ff45c4487-lv8qp.istio-system resources:175 size:153.9kB empty:0 cached:162/175
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.636382Z    info    ads     LDS: PUSH for node:istio-ingressgateway-dal12-private-7ff45c4487-lv8qp.istio-system resources:2 size:39.1kB
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.996030Z    info    ads     Push debounce stable[84] 21: 102.896806ms since last change, 391.30025ms since last push, full=false
istiod-1-11-6-645bdf9d46-pgrs5 discovery 2022-03-02T20:23:02.079573Z    info    ads     XDS: Pushing:2022-03-02T20:23:02Z/22 Services:143 ConnectedEndpoints:19  Version:2022-03-02T20:23:02Z/22
istiod-1-11-6-645bdf9d46-w6n9h discovery net/http.serverHandler.ServeHTTP(0xc0014b6700, 0x3b0d240, 0xc00838b260, 0xc001935300)
istiod-1-11-6-645bdf9d46-pgrs5 discovery 2022-03-02T20:23:02.089484Z    info    ads     CDS: PUSH for node:istio-egressgateway-dal13-79c8f5d78b-rvkth.istio-system resources:176 size:180.0kB
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:07.996173Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-w6n9h discovery        net/http/server.go:2868 +0xa3
istiod-1-11-6-645bdf9d46-pgrs5 discovery 2022-03-02T20:23:02.089568Z    info    ads     CDS: PUSH for node:istio-ingressgateway-dal12-public-6dd588687d-ml2mc.istio-system resources:176 size:180.0kB
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:08.148115Z    info    ads     Push debounce stable[85] 7: 126.431551ms since last change, 127.588464ms since last push, full=false
istiod-1-11-6-645bdf9d46-w6n9h discovery net/http.(*conn).serve(0xc00310c5a0, 0x3b128b8, 0xc00595a1c0)
istiod-1-11-6-645bdf9d46-pgrs5 discovery 2022-03-02T20:23:02.090388Z    info    ads     CDS: PUSH for node:istio-ingressgateway-dal12-public-6dd588687d-frfz4.istio-system resources:176 size:180.0kB
istiod-1-11-6-645bdf9d46-scsj9 discovery 2022-03-02T20:23:08.148408Z    info    ads     XDS: Incremental Pushing:2022-03-02T20:23:02Z/24 ConnectedEndpoints:16 Version:2022-03-02T20:23:02Z/24
istiod-1-11-6-645bdf9d46-w6n9h discovery        net/http/server.go:1933 +0x8cd
istiod-1-11-6-645bdf9d46-w6n9h discovery created by net/http.(*Server).Serve
```
It's panicking due to `istiod-1-11-6-645bdf9d46-w6n9h discovery 2022-03-02T20:24:36.665055Z    info    http: panic serving 172.18.100.166:33318: runtime error: comparing uncomparable type []interface {}`

I suspect this is where the panic originates from (?): https://github.com/kubernetes/apimachinery/blob/master/pkg/util/strategicpatch/patch.go#L1605

This prevents any new pods from being created.

### Version

```prose
istioctl version
client version: 1.13.1
istiod version: 1.10.6
istiod version: 1.10.6
istiod version: 1.10.6
istiod version: 1.11.6
istiod version: 1.11.6
istiod version: 1.11.6
istiod version: 1.11.6
istiod version: 1.11.6
data plane version: 1.11.6 (51 proxies), 1.10.6 (415 proxies)

kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.9+IKS
```

### Additional Information
[istiod_37671.txt](https://github.com/istio/istio/files/8173294/istiod_37671.txt)
[ingressgateway_37671.txt](https://github.com/istio/istio/files/8173296/ingressgateway_37671.txt)
[egressgateway_37671.txt](https://github.com/istio/istio/files/8173297/egressgateway_37671.txt)

**Comment by rrpolanco** [comment]
@howardjohn Any initial thoughts on this?

**Comment by howardjohn** [comment]
I cannot explain why this would happen. The closest idea I could have is the k8s library and your server do not align, and they had some API change which somehow made it behave unexpectedly. But even that doesn't work, since the go.mod file matches your server version almost exactly!

Does this happen for 100% of pods? if there is just one can you add the spec for it here?
