### ISSUE TITLE
Istiod 1.14.1 crashes when a VirtualService with a TLS block is added

### ISSUE THREAD

**Issue by bvandewalle** [istio/istio#39999]
### Bug Description

We discovered that all instances of Istiod were crashing and unable to successfully come up again whenever the following VirtualSevice is added:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: spire
  namespace: spire
spec:
  gateways:
  - istio-gateway/spire
  hosts:
  - '*'
  tls:
  - match:
    - port: 443
      sniHosts:
      - spire.myhost.io
  - route:
    - destination:
        host: spire-server.myhost.io
        port:
          number: 8081
```

The exact StackTrace is the following. Looking at the code it seem to indicate that `routes[0]` is empty here: https://github.com/istio/istio/blob/release-1.14.1-patch/pilot/pkg/networking/core/v1alpha3/networkfilter.go#L203

:
```
2022-07-18T15:27:52.953242Z	info	ads	EDS: PUSH request for node:istio-ingressgateway-default-6fc8bd6774-spmz6.istio-gateway resources:3820 size:1.3MB empty:1043 cached:1738/3820
panic: runtime error: index out of range [0] with length 0

goroutine 13504 [running]:
istio.io/istio/pilot/pkg/networking/core/v1alpha3.buildOutboundNetworkFilters(0x306fba0?, {0x0?, 0x2fdd480?, 0xc029b2e780?}, 0x1?, _, {{{0x31c3f04, 0x13}, {0x31a98b8, 0x8}, ...}, ...})
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/networkfilter.go:203 +0x34c
istio.io/istio/pilot/pkg/networking/core/v1alpha3.buildGatewayNetworkFiltersFromTLSRoutes(0xc0363fd2c0, 0xc025604340, 0xc00105ad00, {0xc005804f48, 0x13})
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/gateway.go:825 +0xe33
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).createGatewayTCPFilterChainOpts(0xc00105ad00?, 0xb?, 0xc00105ad00?, 0xc02290e8c0?, {0xc005804f48?, 0x100000000000b?})
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/gateway.go:707 +0x4e
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildGatewayTCPBasedFilterChains(0xc000196060?, 0xc00855b560, {0x319ee15, 0x3}, {0x1bb, {0xc0036108dc, 0x3}, {0x0, 0x0}}, 0xc027d70c00, ...)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/gateway.go:222 +0x5ff
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildGatewayListeners(0xc0363fd2c0?, 0xc00855b560)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/gateway.go:123 +0x1170
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildListeners(0x40?, 0xc0363fd2c0, 0xc0211a6380?)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/listener.go:118 +0x65
istio.io/istio/pilot/pkg/xds.LdsGenerator.Generate({0x0?}, 0x0?, 0xc02290f468?, 0x48da57?)
	istio.io/istio/pilot/pkg/xds/lds.go:74 +0xce
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).pushXds(0xc000cff680, 0xc03911bea0, 0xc02a5dff40, 0xc027d701e0)
	istio.io/istio/pilot/pkg/xds/xdsgen.go:117 +0x42f
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).processRequest(0xc000cff680, 0xc0300d1b00, 0xc03911bea0)
	istio.io/istio/pilot/pkg/xds/ads.go:229 +0x28a
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Stream(0xc000cff680, {0x365c7d8, 0xc025a67c80})
	istio.io/istio/pilot/pkg/xds/ads.go:308 +0x985
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).StreamAggregatedResources(0xc029c51b78?, {0x365c7d8?, 0xc025a67c80?})
	istio.io/istio/pilot/pkg/xds/ads.go:234 +0x25
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler({0x319c1a0?, 0xc000cff680}, {0x3659890?, 0xc0053bdbc0})
	github.com/envoyproxy/go-control-plane@v0.10.2-0.20220428052930-ec95b9f870a8/envoy/service/discovery/v3/ads.pb.go:298 +0x9f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000c016c0, {0x365eec0, 0xc038441040}, 0xc01172b9e0, 0xc002694330, 0x54dca80, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1541 +0xece
google.golang.org/grpc.(*Server).handleStream(0xc000c016c0, {0x365eec0, 0xc038441040}, 0xc01172b9e0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1623 +0x9d6
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x28a
```

### Version

```prose
istioctl version
control plane version: 1.14.1
```
```
kubectl version --short
Client Version: v1.22.2
Server Version: v1.18.20
```
```

**Comment by howardjohn** [comment]
```
$  cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: spire
  namespace: spire
spec:
  gateways:
  - istio-gateway/spire
  hosts:
  - '*'
  tls:
  - match:
    - port: 443
      sniHosts:
      - spire.myhost.io
  - route:
    - destination:
        host: spire-server.myhost.io
        port:
          number: 8081
EOF
Error from server: error when creating "STDIN": admission webhook "validation.istio.io" denied the request: configuration is invalid: 2 errors occurred:
        * TLS route is required
        * TLS route must have at least one match condition
```

I would consider this low priority since its expected that validation webhook is used to prevent invalid config. we should still have defense-in-depth, but there must be a misconfig in your environment disabling the webhook?

**Comment by frankbu** [comment]
@bvandewalle you need to pass `--set values.defaultRevision=<default revision>` to turn on the default validator when using `manifest generate`. Documentation is being updated here: https://github.com/istio/istio.io/pull/11653
