### ISSUE TITLE
virtualInbound: Didn't find a registered implementation for name: 'istio.metadata_exchange'

### ISSUE THREAD

**Issue by mgiessing** [istio/istio#40992]
### Bug Description

Hello, I'm using istio service mesh (istio pilot & istio proxyv2) which I built for ppc64le, but it seems something went wrong here, since the pods in the istio namespace are not getting ready:

```bash
NAME                                    READY   STATUS    RESTARTS   AGE
authservice-0                           1/1     Running   0          52m
cluster-local-gateway-69966db74-whfbh   0/1     Running   0          52m
istio-ingressgateway-7b69c4db6b-dbtn5   0/1     Running   0          52m
istiod-7f9c77b8fb-xlvf7                 1/1     Running   0          52m
```

It seems like something went wrong regarding the extensions:

Logs from istiod (pilot:1.14.1):

```bash
[...]
0.0.0.0_8008: Unable to create Wasm HTTP filter 
virtualInbound: Didn't find a registered implementation for name: 'istio.metadata_exchange'
```

Logs from ingress (proxyv2:1.14.1)

```bash
[...]
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange not found
```

Cluster gateway looks similar to ingress - anyone got an idea what is going wrong?

Thanks!

### Version

```prose
istio 1.14.1

$ kubectl version --short
Client Version: v1.21.11
Server Version: v1.21.11
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by zirain** [comment]
did you build you envoy for ppc64le from https://github.com/istio/proxy ?

**Comment by mgiessing** [comment]
Good catch @zirain ! I used the envoy binary from envoyproxy and was therefore missing the extensions!
Once I built everything using istio/proxy envoy it works like a charm - thanks a lot!

**Comment by RunlinXiao** [comment]
@mgiessing Hi, I'm facing the same problem using the envoy binary from envoyproxy. Could you provide the cmd line how you build the istio/proxy? Thanks!

**Comment by zirain** [comment]
https://github.com/istio/proxy/blob/ddbad6db45049b1cc83b446fb46a19beb69786c9/Makefile.core.mk#L81

**Comment by RunlinXiao** [comment]
awesome! Thank you so much! zirain

**Comment by RunlinXiao** [comment]
Hi! Not sure if I should ask here or open a new issue, but I encounter below problems:
OS: linux x64_64

1. Run `make-build` directly 

> ubuntu@ip-10-1-13-15:~/runlin/proxy$ sudo make build
/bin/bash: line 1: clang++: command not found
echo clang
clang
echo clang++
clang++
export PATH=/usr/lib/llvm-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CC=clang CXX=clang++ && \
bazel  build  --config=libc++ //...
INFO: Repository local_config_cc instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:509:13: in <toplevel>
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/cc_configure.bzl:183:16: in cc_configure
Repository rule cc_autoconf defined at:
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/cc_configure.bzl:143:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125, column 33, in cc_autoconf_impl
		configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 349, column 17, in configure_unix_toolchain
		cc = find_cc(repository_ctx, overriden_tools)
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 314, column 23, in find_cc
		cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 32, in _find_generic
		auto_configure_fail(msg)
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: /DEFAULT.WORKSPACE.SUFFIX:509:13: fetching cc_autoconf rule //external:local_config_cc: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125, column 33, in cc_autoconf_impl
		configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 349, column 17, in configure_unix_toolchain
		cc = find_cc(repository_ctx, overriden_tools)
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 314, column 23, in find_cc
		cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 32, in _find_generic
		auto_configure_fail(msg)
	File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
INFO: Repository com_google_absl instantiated at:
  /home/ubuntu/runlin/proxy/WORKSPACE:71:19: in <toplevel>
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:192:21: in envoy_dependencies
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:648:26: in _com_google_absl
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository com_google_protobuf_protoc_linux_x86_64 instantiated at:
  /home/ubuntu/runlin/proxy/WORKSPACE:71:19: in <toplevel>
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:194:25: in envoy_dependencies
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:768:30: in _com_google_protobuf
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/com_github_google_flatbuffers/BUILD.bazel:82:10: @com_github_google_flatbuffers//:flatc depends on @local_config_cc//:cc-compiler-k8 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//':
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: Analysis of target '//extensions/common:node_info_fbs' failed; build aborted:
INFO: Elapsed time: 0.257s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 7 targets configured)
    Fetching repository @go_sdk; starting
make: *** [Makefile.core.mk:84: build] Error 1
^^ echo $CC and echo $CXX is both empty


2. [when using Clang/LLVM 15.0.5 in Makefile (tags/1.16.2)](https://github.com/istio/proxy/blob/master/Makefile.core.mk#L35) (echo $CC is empty, echo $CXX is empty) will give same error ^^^ (either correct your path or set the CC environment variable)

3. when using Clang/LLVM 15.0.5 (echo $CC is /usr/bin/gcc-11, echo $CXX is /usr/bin/g++-11)

> echo /usr/bin/gcc-11
/usr/bin/gcc-11
echo /usr/bin/g++-11
/usr/bin/g++-11
export PATH=clang+llvm-15.0.5-x86_64-linux-gnu-ubuntu-18.04:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CC=/usr/bin/gcc-11 CXX=/usr/bin/g++-11 && \
bazel  build   //...
INFO: Build options --action_env, --define, and --linkopt have changed, discarding analysis cache.
INFO: Analyzed 180 targets (1012 packages loaded, 52935 targets configured).
INFO: Found 180 targets...
WARNING: cleared convenience symlink(s) bazel-bin, bazel-testlogs because their destinations would be ambiguous
ERROR: /home/ubuntu/runlin/proxy/extensions/access_log_policy/config/v1alpha1/BUILD:26:14: Generating proto_library //extensions/access_log_policy/config/v1alpha1:access_log_policy_config_proto failed: (Exit 1): protoc.exe failed: error executing command (from target //extensions/access_log_policy/config/v1alpha1:access_log_policy_config_proto) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf_protoc_linux_x86_64/protoc.exe '--cpp_out=bazel-out/k8-fastbuild/bin' ... (remaining 4 arguments skipped)

> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto: warning: directory does not exist.
> Could not make proto path relative: extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto: No such file or directory
> INFO: Elapsed time: 16.165s, Critical Path: 0.09s
> INFO: 11 processes: 9 internal, 2 linux-sandbox.
> FAILED: Build did NOT complete successfully
> make: *** [Makefile.core.mk:84: build] Error 1
> 

I also found [same issue here](https://github.com/bazelbuild/bazel/issues/1152) but this does not provide a solution. Would really appreciate any help!
