### ISSUE TITLE
Istio 1.15.0 Panic on empty hostname

### ISSUE THREAD

**Issue by Minh-Ng** [istio/istio#41014]
### Bug Description

Applying a VirtualService with an empty host causes Istiod 1.15.0 to panic.

To reproduce, apply:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: empty-host
  namespace: istio-system
spec:
  hosts:
  - ""
  http:
  - route:
    - destination:
        host: productpage.prod.svc.cluster.local
```

### Version

```prose
panic: runtime error: index out of range [0] with length 0

goroutine 7658 [running]:
istio.io/istio/pkg/config/host.Names.Less(...)
	istio.io/istio/pkg/config/host/names.go:41
sort.partition({0x39307f0, 0xc09b07e720}, 0x0, 0xf6, 0xc06a73e3b8?)
	sort/zsortinterface.go:157 +0x1bb
sort.pdqsort({0x39307f0, 0xc09b07e720}, 0x18?, 0x2d29820?, 0xc09b1caf01?)
	sort/zsortinterface.go:114 +0x24b
sort.Sort({0x39307f0, 0xc09b07e720})
	sort/sort.go:48 +0x5d
istio.io/istio/pilot/pkg/networking/core/v1alpha3.collapseDuplicateRoutes(0xc06a73ea98)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/gateway.go:520 +0x25d
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildGatewayHTTPRouteConfig(0x32d29c0?, 0xc08bd64dc0, 0xc0d52a5520, {0xc08d1e8d80, 0x31})
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/gateway.go:460 +0x9c7
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildHTTPRoutes(0xc06a73f270?, 0xc08bd64dc0, 0xc09b0a9200, {0xc0da75a700, 0x9, 0x45599c?})
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/httproute.go:87 +0x5ce
istio.io/istio/pilot/pkg/xds.RdsGenerator.Generate({0x0?}, 0x0?, 0xc06a73f348?, 0x48fc37?)
	istio.io/istio/pilot/pkg/xds/rds.go:65 +0xcb
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).pushXds(0xc00147f180, 0xc075ffc640, 0xc09b075a40, 0xc09b0a9200)
	istio.io/istio/pilot/pkg/xds/xdsgen.go:116 +0x432
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).processRequest(0xc00147f180, 0xc08d15bcc0, 0xc075ffc640)
	istio.io/istio/pilot/pkg/xds/ads.go:232 +0x6c5
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Stream(0xc00147f180, {0x393c7b8, 0xc0886560d0})
	istio.io/istio/pilot/pkg/xds/ads.go:314 +0x950
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).StreamAggregatedResources(0xc05684bb80?, {0x393c7b8?, 0xc0886560d0?})
	istio.io/istio/pilot/pkg/xds/ads.go:237 +0x25
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler({0x3420660?, 0xc00147f180}, {0x39384e0?, 0xc085e635f0})
	github.com/envoyproxy/go-control-plane@v0.10.3-0.20220719090109-b024c36d9935/envoy/service/discovery/v3/ads.pb.go:298 +0x9f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00148ec40, {0x393f480, 0xc04861f1e0}, 0xc08645b0e0, 0xc002e7f500, 0x58eb2e0, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1542 +0xf5c
google.golang.org/grpc.(*Server).handleStream(0xc00148ec40, {0x393f480, 0xc04861f1e0}, 0xc08645b0e0, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1624 +0x9ea
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x28a
```

### Additional Information

istio 1.15.0

**Comment by zirain** [comment]
this should be rejected by webhook?

**Comment by Minh-Ng** [comment]
Our webhook failurePolicy is set to Fail, so it appears to have made it through

**Comment by zirain** [comment]
I can not reproduce this
```
root@ecs-zirain:~/go/src/playground# k apply -f istio/test.yaml 
Error from server: error when creating "istio/test.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: empty domain name not allowed
```

**Comment by Minh-Ng** [comment]
If thats the case we can consider this closed, I'll check into the deployment's validating webhook configuration and reopen if it appears to be completely correct
