### ISSUE TITLE
istiod Pod panic and restart when scaling new Pods due to nil pointer dereference

### ISSUE THREAD

**Issue by able8** [istio/istio#41162]
### Bug Description

We enabled HPA for `Deployment/istiod`, but last week we got 3 istiod panic and restart alerts when scaling new Pods.
The panic logs are as the followings:

```
...
2022-09-24T11:57:28.282074Z    info    FLAG: --vklog="0"
2022-09-24T11:57:28.297095Z    info    klog    Config not found: /var/run/secrets/remote/config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2743f20]

goroutine 1 [running]:
[istio.io/istio/pkg/kube.IsAtLeastVersion({0x3b1a3f0](http://istio.io/istio/pkg/kube.IsAtLeastVersion(%7B0x3b1a3f0), 0xc000ade2c0}, 0xc0005c6188)
    [istio.io/istio/pkg/kube/version.go:30](http://istio.io/istio/pkg/kube/version.go:30) +0x60
[istio.io/istio/pilot/pkg/serviceregistry/kube/controller.DetectEndpointMode(](http://istio.io/istio/pilot/pkg/serviceregistry/kube/controller.DetectEndpointMode(){0x3b1a3f0, 0xc000ade2c0})
    [istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:168](http://istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:168) +0x48
[istio.io/istio/pilot/pkg/bootstrap.NewServer(0xc000afa500](http://istio.io/istio/pilot/pkg/bootstrap.NewServer(0xc000afa500), {0x0, 0x0, 0x0})
    [istio.io/istio/pilot/pkg/bootstrap/server.go:233](http://istio.io/istio/pilot/pkg/bootstrap/server.go:233) +0xafc
[istio.io/istio/pilot/cmd/pilot-discovery/app.newDiscoveryCommand.func2(0xc000afa280](http://istio.io/istio/pilot/cmd/pilot-discovery/app.newDiscoveryCommand.func2(0xc000afa280), {0xc0005d53e0, 0x6, 0x6})
    [istio.io/istio/pilot/cmd/pilot-discovery/app/cmd.go:92](http://istio.io/istio/pilot/cmd/pilot-discovery/app/cmd.go:92) +0x4e
[github.com/spf13/cobra.(*Command).execute(0xc000afa280](http://github.com/spf13/cobra.(*Command).execute(0xc000afa280), {0xc0005d5380, 0x6, 0x6})
    [github.com/spf13/cobra@v1.3.0/command.go:856](http://github.com/spf13/cobra@v1.3.0/command.go:856) +0x60e
[github.com/spf13/cobra.(*Command).ExecuteC(0xc000afa000)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc000afa000))
    [github.com/spf13/cobra@v1.3.0/command.go:974](http://github.com/spf13/cobra@v1.3.0/command.go:974) +0x3bc
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
    [github.com/spf13/cobra@v1.3.0/command.go:902](http://github.com/spf13/cobra@v1.3.0/command.go:902)
main.main()
    [istio.io/istio/pilot/cmd/pilot-discovery/main.go:27](http://istio.io/istio/pilot/cmd/pilot-discovery/main.go:27) +0x25
```

The code `istio/pkg/kube/version.go:30` is https://github.com/istio/istio/blob/1.13.2/pkg/kube/version.go#L30

```
func IsAtLeastVersion(client Client, minorVersion uint) bool {
	clusterVersion, err := client.GetKubernetesVersion()
	if err != nil {
		return true
	}
	cv, err := version.ParseGeneric(fmt.Sprintf("v%s.%s.0", clusterVersion.Major, clusterVersion.Minor))
	if err != nil {
		return true
	}
	ev, err := version.ParseGeneric(fmt.Sprintf("v1.%d.0", minorVersion))
	if err != nil {
		return true
	}
	return cv.AtLeast(ev)
}
```

### Version

```prose
client version: 1.13.2
control plane version: 1.13.1
data plane version: 1.13.1 (265 proxies)

➜  ~ kubectl version --short
Client Version: v1.21.0
Server Version: v1.22.12-gke.500
```

### Additional Information

The panic code line is `istio/pkg/kube/version.go:30`, do we need to check `if clusterVersion != nil` before calling `clusterVersion.Major`
```
cv, err := version.ParseGeneric(fmt.Sprintf("v%s.%s.0", clusterVersion.Major, clusterVersion.Minor))
```

It seems a bug on the following code `if err != nil`, should be `if err == nil` ?:
```
v, err := clientWithTimeout.Discovery().ServerVersion()
	if err != nil {
		c.version = v
	}
```

https://github.com/istio/istio/blob/91533d04e894ff86b80acd6d7a4517b144f9e19a/pkg/kube/client.go#L521

```
func (c *client) GetKubernetesVersion() (*kubeVersion.Info, error) {
	c.versionOnce.Do(func() {
		v, err := c.Discovery().ServerVersion()
		if err == nil {
			c.version = v
		}
	})
	if c.version != nil {
		return c.version, nil
	}
	// Initial attempt failed, retry on each call to this function
	v, err := c.Discovery().ServerVersion()
	if err != nil {
		c.version = v
	}
	return c.version, err
}
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [x] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by zirain** [comment]
1.13 is EOL, can you test with the latest version of 1.13 or newer major version(1.14 1.15 etc)?

**Comment by hzxuzhonghu** [comment]
is that because of non existing kubeconfig? If that's true, the panic can be reproduced in master

**Comment by able8** [comment]
> is that because of non existing kubeconfig? If that's true, the panic can be reproduced in master

Hi, do you mean the secret `istio-kubeconfig`?  
The logs shows that `Config not found: /var/run/secrets/remote/config`, and secrets "istio-kubeconfig" not found. 
But some new pods can work with the above log.

```
➜  ~ k get secret istio-kubeconfig
Error from server (NotFound): secrets "istio-kubeconfig" not found

istio-system          istiod-f988c999-v9brk                                            1/1     Running             0                  7d21h  
istio-system          istiod-f988c999-xhlcp                                            1/1     Running             0                  7d21h
istio-system          istiod-f988c999-vbp7p                                            1/1     Running             0                  3m16s 
```

**Comment by able8** [comment]
It seems a bug on the following code `if err !=nil`, should be `if err == nil`:
```
v, err := clientWithTimeout.Discovery().ServerVersion()
	if err != nil {
		c.version = v
	}
```

https://github.com/istio/istio/blob/79559c87b3ab3dd899690f9e2ab5ddd72afe489f/pkg/kube/client.go#L594

**Comment by able8** [comment]
Confirmed and fixed  https://github.com/istio/istio/pull/41175
