### ISSUE TITLE
Error "panic: runtime error: invalid memory address or nil pointer dereference" when using istio networking HTTPRoute struct

### ISSUE THREAD

**Issue by elraoustih** [istio/istio#41939]
**Bug description**
Hi,
I'm creating a custom operator in Go (using Kubebuilder). So in my CR i want to include istio [HTTPRoute](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute) type. Here my CR def :
```
package v1

import (
	networkingv1alpha3 "istio.io/api/networking/v1alpha3"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type VirtualServiceFragmentSpec struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
	HandledRevision string `json:"handledRevision,omitempty"`

	// +kubebuilder:validation:Required
	Target string `json:"name"`

	// +kubebuilder:validation:Required
	Gateways []string `json:"gateways"`

	// +kubebuilder:validation:Required
	Hosts []string `json:"hosts"`

	// +kubebuilder:validation:Optional
	Http *networkingv1alpha3.HTTPRoute `json:"http,omitempty"`
}
```
When i'm generating ther CRD using **istio.io/api v0.0.0-20221107183313-6f1164d46553** (with kubebuilder command "make manifest") i have an error :
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10493ff5c]

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedPackage(0x1400033c840, 0x0)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:237 +0x4c
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0x1400033c840, {0x0?, {0x14000e87bc8?, 0x31?}})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:170 +0x48
sigs.k8s.io/controller-tools/pkg/crd.(*schemaContext).requestSchema(0x14002d41050?, {0x14000236940?, 0x1049cfd18?}, {0x14000e87bc8?, 0x8?})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:107 +0xd8
sigs.k8s.io/controller-tools/pkg/crd.namedToSchema(0x14002d41050, 0x140005b9ab8)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:254 +0x1b4
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0x14002d41050, {0x104c4f858?, 0x140005b9ab8})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:173 +0x68
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0x14002d41050, {0x104c4f8e8?, 0x140005b9cc8})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:179 +0xc8
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0x14000a2ce48, 0x14000915188)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:401 +0x750
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0x14000a2ce48, {0x104c4f918?, 0x14000915188})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:181 +0x94
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(0x14000a2ce48)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:124 +0x114
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0x1400033c840, {0x14000c40220?, {0x14000138da0?, 0x20?}})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:193 +0x204
sigs.k8s.io/controller-tools/pkg/crd.(*schemaContext).requestSchema(0x14001867b30?, {0x14000485220?, 0x1049cfd18?}, {0x14000138da0?, 0x9?})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:107 +0xd8
sigs.k8s.io/controller-tools/pkg/crd.namedToSchema(0x14001867b30, 0x140002bf878)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:254 +0x1b4
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0x14001867b30, {0x104c4f858?, 0x140002bf878})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:173 +0x68
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0x14001867b30, {0x104c4f8e8?, 0x140002bf890})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:179 +0xc8
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0x14000a2d908, 0x140002bf8a8)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:401 +0x750
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0x14000a2d908, {0x104c4f918?, 0x140002bf8a8})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:181 +0x94
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(0x14000a2d908)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:124 +0x114
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0x1400033c840, {0x14001313060?, {0x14000c0d1c0?, 0x0?}})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:193 +0x204
sigs.k8s.io/controller-tools/pkg/crd.(*schemaContext).requestSchema(0x1400059f0e0?, {0x0?, 0x1049cfd18?}, {0x14000c0d1c0?, 0x0?})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:107 +0xd8
sigs.k8s.io/controller-tools/pkg/crd.localNamedToSchema(0x14001866d20, 0x14000cbb360)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:237 +0x1e4
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0x14001866d20, {0x104c4f5b8?, 0x14000cbb360})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:171 +0x120
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0x14000a2e368, 0x140002bfb60)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:401 +0x750
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0x14000a2e368, {0x104c4f918?, 0x140002bfb60})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:181 +0x94
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(0x14000a2e368)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:124 +0x114
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0x1400033c840, {0x14001313060?, {0x14000c02de0?, 0x8?}})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:193 +0x204
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedFlattenedSchemaFor(0x1400033c840, {0x14001313060?, {0x14000c02de0?, 0x1049ce17a?}})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:205 +0x88
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedCRDFor(0x1400033c840, {{0x14000d0604e?, 0x0?}, {0x14000c02de0?, 0x0?}}, 0x0)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/spec.go:85 +0x400
sigs.k8s.io/controller-tools/pkg/crd.Generator.Generate({0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0}, 0x14000d12a50)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/gen.go:132 +0x228
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0x140003afd40)
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/genall/genall.go:261 +0x234
main.main.func1(0x140002fec80?, {0x140000a1db0?, 0x5?, 0x5?})
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/cmd/controller-gen/main.go:176 +0x68
github.com/spf13/cobra.(*Command).execute(0x140002fec80, {0x140000321f0, 0x5, 0x5})
        xxxxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x140002fec80)
        xxxxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        xxxxxxxx/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        xxxxxxxx/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/cmd/controller-gen/main.go:200 +0x27c
make: *** [manifests] Error 2
```

**But when i'm using an old version like istio.io/api v0.0.0-20211206163441-1a632586cbd4 i have no errors.**

So is it a known  issue ? is there a solution ?

Thanks for your help.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio.io/api v0.0.0-20221107183313-6f1164d46553

**Comment by wonderzerg** [comment]
same here

**Comment by zhifanggao** [comment]
Can anyone give any help on this issue? we are hit this problem too.

**Comment by ArenaSu** [comment]
@jwendell @howardjohn @linsun Can anyone solve the problem ? I'm confused that why not generate virtualservice deepcopy code as it is crd resource.

**Comment by zhifanggao** [comment]
paste the error here

```
[root@server kubearena-app-repository]# make manifests
/data/go/bin/controller-gen rbac:roleName=manager-role crd:generateEmbeddedObjectMeta=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa26112]

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedPackage(0xc0003b5620, 0x0)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:237 +0x52
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0xc0003b5620, {0x0, {0xc00594bb28, 0x31}})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:170 +0x67
sigs.k8s.io/controller-tools/pkg/crd.(*schemaContext).requestSchema(0xc0042f1b30, {0xc0007183c0, 0xbff178}, {0xc00594bb28, 0x8})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:107 +0xd5
sigs.k8s.io/controller-tools/pkg/crd.namedToSchema(0xc0042f1b30, 0xc0077359f8)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:254 +0x1ec
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc0042f1b30, {0xd05ae0, 0xc0077359f8})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:173 +0xdc
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc0042f1b30, {0xd05b70, 0xc007735a10})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:179 +0x119
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0xc00802c040, 0xc007735db8)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:401 +0x811
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc00802c040, {0xd05ba0, 0xc007735db8})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:181 +0x145
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(0xc00802c040)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:124 +0xed
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0xc0003b5620, {0xc001f6f0c0, {0xc007717bd0, 0x0}})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:193 +0x2d4
sigs.k8s.io/controller-tools/pkg/crd.(*schemaContext).requestSchema(0xc002db9340, {0x0, 0xbff178}, {0xc007717bd0, 0x0})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:107 +0xd5
sigs.k8s.io/controller-tools/pkg/crd.localNamedToSchema(0xc00802c4d0, 0xc007723380)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:237 +0x216
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc00802c4d0, {0xd05870, 0xc007723380})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:171 +0x7c
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc00802c4d0, {0xd05b70, 0xc007728ab0})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:179 +0x119
sigs.k8s.io/controller-tools/pkg/crd.arrayToSchema(0xc0042e9f20, 0xc0077217a0)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:275 +0x11f
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc0042e9f20, {0xd053c0, 0xc0077217a0})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:175 +0x173
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0xc00802cbd8, 0xc007728d80)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:401 +0x811
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc00802cbd8, {0xd05ba0, 0xc007728d80})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:181 +0x145
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(0xc00802cbd8)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:124 +0xed
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0xc0003b5620, {0xc001f6f0c0, {0xc007716d90, 0x1f}})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:193 +0x2d4
sigs.k8s.io/controller-tools/pkg/crd.(*schemaContext).requestSchema(0xc00808ec90, {0xc002db9340, 0xbff178}, {0xc007716d90, 0xe})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:107 +0xd5
sigs.k8s.io/controller-tools/pkg/crd.namedToSchema(0xc00808ec90, 0xc007547830)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:254 +0x1ec
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc00808ec90, {0xd05ae0, 0xc007547830})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:173 +0xdc
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0xc00802d600, 0xc007547860)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:401 +0x811
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc00802d600, {0xd05ba0, 0xc007547860})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:181 +0x145
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(0xc00802d600)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:124 +0xed
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0xc0003b5620, {0xc001f6f060, {0xc006a89780, 0x2e}})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:193 +0x2d4
sigs.k8s.io/controller-tools/pkg/crd.(*schemaContext).requestSchema(0xc009b603c0, {0xc002df91a0, 0xbff178}, {0xc006a89780, 0xe})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:107 +0xd5
sigs.k8s.io/controller-tools/pkg/crd.namedToSchema(0xc009b603c0, 0xc0034f8e58)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:254 +0x1ec
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc009b603c0, {0xd05ae0, 0xc0034f8e58})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:173 +0xdc
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc009b603c0, {0xd05b70, 0xc0034f8e70})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:179 +0x119
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0xc00802e0a0, 0xc0034f8e88)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:401 +0x811
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc00802e0a0, {0xd05ba0, 0xc0034f8e88})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:181 +0x145
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(0xc00802e0a0)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:124 +0xed
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0xc0003b5620, {0xc0010c9920, {0xc001e97e90, 0x0}})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:193 +0x2d4
sigs.k8s.io/controller-tools/pkg/crd.(*schemaContext).requestSchema(0xc002df9ef0, {0x0, 0xbff178}, {0xc001e97e90, 0x0})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:107 +0xd5
sigs.k8s.io/controller-tools/pkg/crd.localNamedToSchema(0xc009b60150, 0xc003b03ea0)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:237 +0x216
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc009b60150, {0xd05870, 0xc003b03ea0})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:171 +0x7c
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0xc00802eae0, 0xc0034f90c8)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:401 +0x811
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc00802eae0, {0xd05ba0, 0xc0034f90c8})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:181 +0x145
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(0xc00802eae0)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/schema.go:124 +0xed
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0xc0003b5620, {0xc0010c9920, {0xc0034d93d0, 0xc00802ee08}})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:193 +0x2d4
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedFlattenedSchemaFor(0xc0003b5620, {0xc0010c9920, {0xc0034d93d0, 0xbfd6af}})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/parser.go:205 +0xb7
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedCRDFor(0xc0003b5620, {{0xc0035a335d, 0xc00802f888}, {0xc0034d93d0, 0x1}}, 0x0)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/spec.go:85 +0x56e
sigs.k8s.io/controller-tools/pkg/crd.Generator.Generate({0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0xc00037a300}, 0xc001bfe280)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/crd/gen.go:132 +0x2c5
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc0023917a0)
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/genall/genall.go:261 +0x246
main.main.func1(0xc000368c80, {0xc00013ff40, 0x5, 0x5})
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/cmd/controller-gen/main.go:176 +0x6a
github.com/spf13/cobra.(*Command).execute(0xc000368c80, {0xc000132130, 0x5, 0x5})
	/data/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000368c80)
	/data/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/data/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/data/go/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/cmd/controller-gen/main.go:200 +0x2c6
make: *** [manifests] Error 2
```

My code likes this:

```
package v1

import (
	networkingv1beta1 "istio.io/client-go/pkg/apis/networking/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
type VirtualServiceSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// clustername
	ClusterName string `json:"clustername"`
	// virtualservicetmpl      spec field for istio virtual service
	Template *networkingv1beta1.VirtualService `json:"template,omitempty"`
}

```

**Comment by yangxggo** [comment]
istio client has a struct VirtualService( in istio/client-go/pkg/apis/networking/v1beta1/types.gen.go). The type of 'spec' in struct VirtualService is 'networkingv1beta1.VirtualService':
`type VirtualService struct {
	v1.TypeMeta `json:",inline"`
	// +optional
	v1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`

	// Spec defines the implementation of this definition.
	// +optional
	Spec networkingv1beta1.VirtualService `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`

	Status v1alpha1.IstioStatus `json:"status"`
}`

I create a cr (called VS for example ) by kubebuilder,  and the type of spec is also 'networkingv1beta1.VirtualService' (just for test):
`// VS is the Schema for the vs API
type VS struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   VirtualServiceSpec   `json:"spec,omitempty"`
	Status VirtualServiceStatus `json:"status,omitempty"`
}`

Same crash will happen when running 'make manifest'.

Any special operations need before 'make manifests'?

**Comment by yangxggo** [comment]
```
sdf
```

**Comment by yangxggo** [comment]
istio client has a struct VirtualService( in istio/client-go/pkg/apis/networking/v1beta1/types.gen.go). The type of 'spec' in struct VirtualService is 'networkingv1beta1.VirtualService':
```
type VirtualService struct {
    v1.TypeMeta `json:",inline"`
    // +optional
    v1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`

    // Spec defines the implementation of this definition.
    // +optional
    Spec networkingv1beta1.VirtualService `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`

    Status v1alpha1.IstioStatus `json:"status"`
}
```

I create a cr (called VS for example ) by kubebuilder, and the type of spec is also 'networkingv1beta1.VirtualService' (just for test):
```
// VS is the Schema for the vs API 
type VS struct { 
  metav1.TypeMeta json:",inline"
  metav1.ObjectMetajson:"metadata,omitempty"`

  Spec   VirtualServiceSpec   `json:"spec,omitempty"`
  Status VirtualServiceStatus `json:"status,omitempty"`
}
```

Same crash will happen when running 'make manifest'.

Any special operations need before 'make manifests'?

**Comment by yangxggo** [comment]
istio client has a struct VirtualService( in istio/client-go/pkg/apis/networking/v1beta1/types.gen.go). The type of 'spec' in struct VirtualService is 'networkingv1beta1.VirtualService':
```
type VirtualService struct {
    v1.TypeMeta `json:",inline"`
    // +optional
    v1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`

    // Spec defines the implementation of this definition.
    // +optional
    Spec networkingv1beta1.VirtualService `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`

    Status v1alpha1.IstioStatus `json:"status"`
}
```

I create a cr (called VS for example ) by kubebuilder, and the type of spec is also 'networkingv1beta1.VirtualService' (just for test):
```
// VS is the Schema for the vs API 
type VS struct { 
  metav1.TypeMeta json:",inline"
  metav1.ObjectMetajson:"metadata,omitempty"`

  Spec   networkingv1beta1.VirtualService   `json:"spec,omitempty"`
  Status VirtualServiceStatus `json:"status,omitempty"`
}
```

Same crash will happen when running 'make manifest'.
Any special operations need before 'make manifests'?

**Comment by ArenaSu** [comment]
@chaunceyjiang can you help solve the problem ? It is a critical problem for my project, thanks!

**Comment by chaunceyjiang** [comment]
> @chaunceyjiang can you help solve the problem ? It is a critical problem for my project, thanks!

Ok, let me have a look.

**Comment by chaunceyjiang** [comment]
hi @ArenaSu 
I think this issue was introduced by this  [commit](https://github.com/istio/api/commit/9d336787a432111e78266c4cd52dd90e086a1612
) , you can try using the version before this pr.

**Comment by zhifanggao** [comment]
@chaunceyjiang It looks like the commit is merged on Mar 23, but the version of  api is newer than that , please refer to 
https://pkg.go.dev/istio.io/api/networking@v0.0.0-20221121205957-417106f309c2 . Could you give a suggestion how to use the old version like v1.12.7  or  [1.14.0-beta.0](https://github.com/istio/api/releases/tag/1.14.0-beta.0) or [1.14.0-beta.1](https://github.com/istio/api/releases/tag/1.14.0-beta.1) ?
<img width="662" alt="截屏2022-11-22 10 04 07" src="https://user-images.githubusercontent.com/110591357/203199769-77ea093f-5e3d-4600-b689-f75f31c6802d.png">

<img width="456" alt="截屏2022-11-22 10 07 30" src="https://user-images.githubusercontent.com/110591357/203199789-c6b9fd78-5e03-4e12-b9d8-cbdf868245ea.png">

**Comment by dezmui** [comment]
> hi @ArenaSu I think this issue was introduced by this [commit](https://github.com/istio/api/commit/9d336787a432111e78266c4cd52dd90e086a1612) , you can try using the version before this pr.

Can confirm, using `v0.0.0-20220322234440-289bfe748e00` works (albeit has a bunch of warnings about certain structs not having JSON tags).

Using the version that's built off of that commit (`v0.0.0-20220323151137-9d336787a432`) gives me the panic error.

FYI to get the api version for these commits you should look at the `update_api_dep_client_go_api_postsubmit` build logs in the status check.

**Comment by elraoustih** [comment]
Thanks for your responses but do you know if it will be a fixed on future version of istio api?

**Comment by stevenkitter** [comment]
IstioStatus does not support

**Comment by davidxia** [comment]
Is there a fix for this?

**Comment by howardjohn** [comment]
No, this is working as intended. Istio Go structs use protobuf as the underlying types, which explicitly do not have json tags

**Comment by davidxia** [comment]
@howardjohn thanks, does that mean there's no way to import Istio Go structs into our own kubebuilder custom types and we just have to copy-paste the struct code?

**Comment by howardjohn** [comment]
I don't know there is no way to do it but I know it doesn't work out of the box at least.
