### ISSUE TITLE
trafficPolicyTLSModeForPort cause pilot push XDS panic:  invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by nicole-lihui** [istio/istio#42598]
### Bug Description

trafficPolicyTLSModeForPort cause pilot push XDS panic， then istiod restart

below logs：
```bash
2022-12-14Т13:44:12.023431Z info ads
XDS: Pushing: 2022-12-14T13:44: 12Z/6 Services: 76 ConnectedEndpoints: 0 Version: 2022-12-14T13:44:12Z/6
2022-12-14T13:44:13.191154Z info ads  ADS: new connection for node: helloworld-vc2-5d67bc48d8-2tpxd.sample-1
2022-12-1413:44:13.193835Z info ads   CDS: PUSH request for node: helloworld-vc2-5d67bc48d8-2tpxd.sample resources: 123 size: 122. 1kB cached: 0/119
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEG: segmentation violation code=0x1 addr=0×28 pc=0×29876cd]

goroutine 1099 [running]:
istio.io/istio/pilot/pkg/ds.trafficPolicyTLSModeForPort (...)
             istio.io/istio/pilot/pkq/ds/endpoint builder.qo:502
istio.io/istio/pilot/pkg/xds.mt lsModeForDefaultTrafficPolicy(OXffffffffffffffff?,Oxc003f76c80?)
             istio.io/istio/pilot/pkg/ds/endpoint_builder.go:489 +0×6d
istio.io/istio/pilot/pkg/ds.newMtlsChecker(Oxc002c2a680, Oxlbb, 0×342a877?)
             istio.io/istio/pilot/pkg/ds/endpoint_builder.go:401 +0×59
istio.io/istio/pilot/pkg/xds.NewEndpointBuilder ({oxc003f211c0, 0x3b}, Oxc0036b3900, oxc002c2a680)
             istio.io/istio/pilot/pkg/ds/endpoint_builder.go: 117 +0×45f
istio.io/istio/pilot/pkg/xds.(*EdsGenerator).buildEndpoints(Oxc00044a640,0xc0045d6e00?,Oxc0045e4840,0xc0045d6e70)
             istio.io/istio/pilot/pkg/ds/eds.go:507 +0×4db
istio.io/istio/pilot/pkg/xds. (*EdsGenerator).Generate(0x2dd1260?, Oxc000c1d260?, Oxc003f116802, 0×42?)
             istio.io/istio/pilot/pkg/ds/eds.go: 387 +0xa5
istio.io/istio/pilot/pkg/xds. (*DiscoveryServer)-pushXds(Oxc0002f9a40,0xc0041280a0,0xc0045d6e70,0xc0045e4840)
             istio.io/istio/pilot/pkq/xds/dsqen.qo: 116 +0×432
istio.io/istio/pilot/pkg/xds. (*DiscoveryServer).processRequest(Oxc0002f9a40,0xc004129040,0xc0041280a0)
             istio.io/istio/pilot/pkg/xds/ads.go:232 +0×6c5
istio.io/istio/pilot/pkg/ds. (*DiscoveryServer) .Stream (Oxc0002f9a40, {0×393eff8, Oxc003f084b0})
             istio.io/istio/pilot/pkg/ds/ads.go:332 +0xa37
istio.io/istio/pilot/pkg/ds. (*DiscoveryServer). StreamAggregatedResources (0xc003ce1b80?, {0x393eff8?, oxc003f084b0?})
             istio.io/istio/pilot/pkg/ds/ads.go:237 +0×25
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler ({0×3422980?, Oxc0002f9a40}, {0×393ad20?, OxcO 0107c5b07)
             github.com/envoyproxy/go-control-plane@vo.10.3-0.20220719090109-b024c36d9935/envoy/service/discovery/v3/ads.pb.go:298 +0×9f
google.golang.org/grpc. (*Server) -processStreamingRPC(Oxc000e64e00, {0×3941d20, Oxc002c2aea0}, Oxc003f186c0, Oxc0009904b0, 0×58f7c60, 0x0)
```

### Version

```prose
[root@controller-node-1 ~]# istioctl version
client version: 1.15.1
control plane version: 1.16.1
data plane version: 1.15.3(18 proxies), 1.16.1 (1 proxies)
```

**Comment by nicole-lihui** [comment]
Trace record:

Due to the misconfiguration of Istio installation parameters `values.global.configValidation: false`, there is a lack of ValidatingWebhookConfiguration resources. 

The chain reaction causes the creation of incorrect `DestinationRule` resources, causing Pilot to crash. However, I believe that optimization is necessary here.
