### ISSUE TITLE
istioctl analyze SIGSEGV while analyzing envoy filter

### ISSUE THREAD

**Issue by pawelbeza** [istio/istio#42831]
### Bug Description

Hey, we have an issue with istioctl analyze when I'm running it on envoy filter for the following envoy filter:

**Envoy Filter**
```json
{
   "apiVersion": "networking.istio.io/v1alpha3",
   "kind": "EnvoyFilter",
   "metadata": {
      "name": "app-inbound-tls",
      "namespace": "app-dev"
   },
   "spec": {
      "configPatches": [
         {
            "applyTo": "FILTER_CHAIN",
            "match": {
               "context": "SIDECAR_INBOUND",
               "listener": {
                  "filterChain": {
                     "transportProtocol": "tls"
                  }
               }
            },
            "patch": {
               "operation": "MERGE",
               "value": {
                    "comment": "some non relevant patch value"
               }
            }
         }
      ]
   }
}
```

**Error**
```bash
$ istioctl analyze --use-kube=false envoy_filter_bug.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x104473094]

goroutine 1 [running]:
istio.io/istio/pkg/config/analysis/analyzers/envoyfilter.(*EnvoyPatchAnalyzer).analyzeEnvoyFilterPatch(0x1400059fef0, 0x140010390e0, {0x1056632c0, 0x14001263a40?}, {0x107662e60?, 0x1400000e9d0?, 0x0?})
        istio.io/istio/pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go:108 +0x1e4
istio.io/istio/pkg/config/analysis/analyzers/envoyfilter.(*EnvoyPatchAnalyzer).Analyze.func1(0x1045ff3c9?)
        istio.io/istio/pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go:51 +0x44
istio.io/istio/pkg/config/analysis/local.(*istiodContext).ForEach(0x14001263a40, {0x10463cc0c, 0x26}, 0x1400104cf30)
        istio.io/istio/pkg/config/analysis/local/context.go:146 +0x4bc
istio.io/istio/pkg/config/analysis/analyzers/envoyfilter.(*EnvoyPatchAnalyzer).Analyze(0x107662e60, {0x1056632c0?, 0x14001263a40})
        istio.io/istio/pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go:50 +0x138
istio.io/istio/pkg/config/analysis.(*CombinedAnalyzer).Analyze(0x14000525230, {0x1056632c0, 0x14001263a40})
        istio.io/istio/pkg/config/analysis/analyzer.go:60 +0x148
istio.io/istio/pkg/config/analysis/local.(*IstiodAnalyzer).ReAnalyze(0x14001247930, 0x140008f26c0)
        istio.io/istio/pkg/config/analysis/local/istiod_analyze.go:136 +0x254
istio.io/istio/pkg/config/analysis/local.(*IstiodAnalyzer).Analyze(0x14001247930?, 0x1400101ef80?)
        istio.io/istio/pkg/config/analysis/local/istiod_analyze.go:155 +0xa0
istio.io/istio/istioctl/cmd.Analyze.func1(0x14001244280?, {0x1400101e540, 0x1, 0x2})
        istio.io/istio/istioctl/cmd/analyze.go:218 +0x7a0
github.com/spf13/cobra.(*Command).execute(0x14001244280, {0x1400101e520, 0x2, 0x2})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x140011c5400)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        istio.io/istio/istioctl/cmd/istioctl/main.go:39 +0xd0
```

I've debugged the issue and it seems that [this line](https://github.com/istio/istio/blob/7b24ef916be2375fcb4b599bdd96bb3058b813ac/pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go#L108) causes the problem because it assumes that field [filter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ListenerMatch:~:text=No-,filter,-FilterMatch) under EnvoyFilter.ListenerMatch.FilterChainMatch is always present which is not necessarily a case as this field is [non required ](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ListenerMatch:~:text=HTTP%20connection%20manager.-,No,-destinationPort). 

For example in our case we have envoy filter patch which should be applied to all "tls" listeners and we don't want to specify any filter. 

As an temporary fix we just updated our envoy filter in the following way:
**Envoy Filter**
```json
{
   "apiVersion": "networking.istio.io/v1alpha3",
   "kind": "EnvoyFilter",
   "metadata": {
      "name": "app-inbound-tls",
      "namespace": "app-dev"
   },
   "spec": {
      "configPatches": [
         {
            "applyTo": "FILTER_CHAIN",
            "match": {
               "context": "SIDECAR_INBOUND",
               "listener": {
                  "filterChain": {
                     "transportProtocol": "tls",
                      "filter": {} <------------ added line
                  }
               }
            },
            "patch": {
               "operation": "MERGE",
               "value": {
                    "comment": "some non relevant patch value"
               }
            }
         }
      ]
   }
}
```

But I think it's not intended behaviour so I've created small PR https://github.com/istio/istio/pull/42832 which fixes the issue

### Version

```prose
$ istioctl version
client version: 1.16.1

Since I'm running istioctl analyze in --use-kube=false mode istiod version doesn't matter as much.
```

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/42832
