### ISSUE TITLE
Follow up on #25640 - Bookinfo sample application does not run in IPV4 ONLY clusters

### ISSUE THREAD

**Issue by aek-arm** [istio/istio#43309]
### Bug Description

Issue #25640 stated that this should have been fixed by an update to the base image, nevertheless this is still not working.

Following the sample bookinfo installation the productpage pod goes into a crash loop as it can not bind to the IPV6 address ::9080 that is used in the app.run statement.

``` bash
INFO:root:start at port 9080
 * Serving Flask app "productpage" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "productpage.py", line 437, in <module>
    app.run(host='::', port=p, debug=True, threaded=True)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 985, in run_simple
    s = socket.socket(address_family, socket.SOCK_STREAM)
  File "/usr/local/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

The assumption made in productpage.py is that under linux always IPV6 is enabled, which isn't always true.

``` python
    # Make it compatible with IPv6 if Linux
    if sys.platform == "linux":
        app.run(host='::', port=p, debug=True, threaded=True)
    else:
        app.run(host='0.0.0.0', port=p, debug=True, threaded=True)
```

Looking at https://stackoverflow.com/a/66249915 a proper solution would be to test for IPV6:

``` python
def system_has_ipv6() -> bool:
    # On Windows, the E* constants will use the WSAE* values
    # So no need to hardcode an opaque integer in the sets.
    _ADDR_NOT_AVAIL = {errno.EADDRNOTAVAIL, errno.EAFNOSUPPORT}
    _ADDR_IN_USE = {errno.EADDRINUSE}

    if not has_ipv6:
        return False
    try:
        with socket.socket(socket.AF_INET6, socket.SOCK_STREAM) as sock:
            sock.bind(("::1", 0))
        return True
    except OSError as e:
        if e.errno in _ADDR_NOT_AVAIL:
            return False
        if e.errno in _ADDR_IN_USE:
            # This point shouldn't ever be reached. But just in case...
            return True
        # Other errors should be inspected
        raise

    # Make it compatible with IPv6 if Linux
    if sys.platform == "linux":
        app.run(host='::', port=p, debug=True, threaded=True)
    else:
        app.run(host='0.0.0.0', port=p, debug=True, threaded=True)
```

I would have created a PR to add, but the readme.md states that I would need to upload to dockerhub a test which isn't working as my M1 mac doesn't want to build with the scripts against amd64, without amending also the ibuild-services.sh

### Version

```prose
➜  bookinfo git:(bookinfo-ipv4) ✗ istioctl version                                                  
client version: 1.16.2
control plane version: 1.16.2
data plane version: 1.16.2 (3 proxies)

➜  bookinfo git:(bookinfo-ipv4) ✗ kubectl version --short
Client Version: v1.22.17
Server Version: v1.22.15+vmware.1
```

**Comment by aek-arm** [comment]
Hi @shamsher31 - Would this something you could look into or give advisory?

**Comment by alpha-baby** [comment]
I also encountered this issue, and the reason is that my Linux machine did not have the IPv6 module enabled, but the productpage Python program needs to listen on the IPv6 address "::".

**Comment by dminca** [comment]
FYI this is still not working with version

```
istio/examples-bookinfo-productpage-v1:1.20.3
```

Throwing the same

```
[2025-07-05 22:22:35 +0000] [1] [INFO] Starting gunicorn 23.0.0                                                                                                                                                                                                  
[2025-07-05 22:22:35 +0000] [1] [ERROR] connection to ('::', 9080) failed: [Errno 97] Address family not supported by protocol                                                                                                                                   
[2025-07-05 22:22:36 +0000] [1] [ERROR] connection to ('::', 9080) failed: [Errno 97] Address family not supported by protocol                                                                                                                                   
[2025-07-05 22:22:37 +0000] [1] [ERROR] connection to ('::', 9080) failed: [Errno 97] Address family not supported by protocol                                                                                                                                   
[2025-07-05 22:22:38 +0000] [1] [ERROR] connection to ('::', 9080) failed: [Errno 97] Address family not supported by protocol                                                                                                                                   
[2025-07-05 22:22:39 +0000] [1] [ERROR] connection to ('::', 9080) failed: [Errno 97] Address family not supported by protocol                                                                                                                                   
[2025-07-05 22:22:40 +0000] [1] [ERROR] Can't connect to ('::', 9080)
```
