### ISSUE TITLE
Failed to patch current policy

### ISSUE THREAD

**Issue by jekv2** [istio/istio#44361]
### Bug Description

I open latest eds installed from playstore and i recieve an error occurred.
i am unlocked and rooted with magisks.

### Version

```prose
version 2.0.0.245

<<< log_count = 3 >>>
[04-12 15:23:12.287 14929:14929 W/rks.eds.android]
type=1400 audit(0.0:367): avc: granted { execute } for name="eds-setup" dev="dm-12" ino=95372 scontext=u:r:untrusted_app:s0:c133,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c133,c257,c512,c768 tclass=file ppid=14900 pcomm="rks.eds.android" pgid=14900 pgcomm="rks.eds.android"

[04-12 15:23:12.287 14929:14929 W/rks.eds.android]
type=1400 audit(0.0:368): avc: denied { execute_no_trans } for path="/data/data/com.sovworks.eds.android/files/eds-setup" dev="dm-12" ino=95372 scontext=u:r:untrusted_app:s0:c133,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c133,c257,c512,c768 tclass=file permissive=0 ppid=14900 pcomm="rks.eds.android" pgid=14900 pgcomm="rks.eds.android"

[04-12 15:23:12.390 14900:14900 W/EDS]
com.sovworks.eds.exceptions.ApplicationException: Failed to patch current policy
	at e2.e.I(:6)
	at e2.e.w(Unknown Source:12)
	at e2.b.x(Unknown Source:15)
	at v1.f.c(:2)
	at io.reactivex.internal.operators.single.SingleCreate.g(Unknown Source:10)
	at n4.r.a(:2)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source:2)
	at n4.q$a.run(Unknown Source:9)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.IOException: Cannot run program "/data/user/0/com.sovworks.eds.android/files/eds-setup": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
	at g4.b.h(Unknown Source:24)
	at g4.b.b(Unknown Source:4)
	at e2.b.u(:3)
	at e2.b.v(:8)
	at e2.e.I(:4)
	... 14 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 19 more
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by jekv2** [comment]
![Screenshot_20230412-154610](https://user-images.githubusercontent.com/7735249/231580892-03e40155-f68a-4d8e-ba5e-cad1c690a5e2.png)

**Comment by howardjohn** [comment]
I think you may have come to the wrong place. This appears unrelated to istio
