### ISSUE TITLE
TestValidatorCacheDoubleEdits crashing in racetest

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4560]
blocking #4235 

=== RUN   TestValidatorCacheDoubleEdits/put-put-3
2018-03-23T02:40:03.204614Z	info	Publishing 1 events
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x175fd67]

goroutine 111 [running]:
istio.io/istio/mixer/pkg/runtime2/validator.(*validatorCache).applyChanges(0xc420ad4260, 0xc42045e000, 0x1, 0x32)
	/go/src/istio.io/istio/mixer/pkg/runtime2/validator/validatorcache.go:46 +0x147
istio.io/istio/mixer/pkg/runtime2/validator.(*validatorCacheTestController).applyChanges(0xc4207dea20, 0xc42045e000, 0x1, 0x32)
	/go/src/istio.io/istio/mixer/pkg/runtime2/validator/validatorcache_test.go:74 +0x6c
istio.io/istio/mixer/pkg/runtime2/validator.(*validatorCacheTestController).(istio.io/istio/mixer/pkg/runtime2/validator.applyChanges)-fm(0xc42045e000, 0x1, 0x32)
	/go/src/istio.io/istio/mixer/pkg/runtime2/validator/validatorcache_test.go:64 +0x60
istio.io/istio/mixer/pkg/config/store.WatchChanges(0xc42037e000, 0xc420924360, 0xf4240, 0xc4207460d0)
	/go/src/istio.io/istio/mixer/pkg/config/store/listener.go:67 +0x2a5
created by istio.io/istio/mixer/pkg/runtime2/validator.newValidatorCacheForTest
	/go/src/istio.io/istio/mixer/pkg/runtime2/validator/validatorcache_test.go:64 +0x727
FAIL	istio.io/istio/mixer/pkg/runtime2/validator	4.407s

**Comment by xiaolanz** [comment]
no longer be able to repo.
