### ISSUE TITLE
multicluster: Istiod crash when deleting cluster

### ISSUE THREAD

**Issue by sschepens** [istio/istio#45798]
### Bug Description

We've been experiencing this crash lately, happening on all Istiod instances simultaneously.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1efb158]
goroutine 420 [running]:
[istio.io/istio/pilot/pkg/model.(*EndpointIndex).DeleteShard(0x4000bd9cb0](http://istio.io/istio/pilot/pkg/model.(*EndpointIndex).DeleteShard(0x4000bd9cb0), {{0x4000f87680?, 0x0?}, {0x3184396?, 0x15?}})
[istio.io/istio/pilot/pkg/model/endpointshards.go:207](http://istio.io/istio/pilot/pkg/model/endpointshards.go:207) +0x108
[istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).RemoveShard(0x37f3960](http://istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).RemoveShard(0x37f3960)?, {{0x4000f87680?, 0x6fc23ac00?}, {0x3184396?, 0x40bc5b6540?}})
[istio.io/istio/pilot/pkg/xds/eds.go:199](http://istio.io/istio/pilot/pkg/xds/eds.go:199) +0x2c
[istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).Cleanup(0x4004e02600)](http://istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).Cleanup(0x4004e02600))
[istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:443](http://istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:443) +0x108
[istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Multicluster).deleteCluster(0x4000c0b200](http://istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Multicluster).deleteCluster(0x4000c0b200), {0x4000f87680, 0x15})
[istio.io/istio/pilot/pkg/serviceregistry/kube/controller/multicluster.go:395](http://istio.io/istio/pilot/pkg/serviceregistry/kube/controller/multicluster.go:395) +0xb0
[istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Multicluster).ClusterDeleted(0x4000c0b200](http://istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Multicluster).ClusterDeleted(0x4000c0b200), {0x4000f87680?, 0x406021bb38?})
[istio.io/istio/pilot/pkg/serviceregistry/kube/controller/multicluster.go:186](http://istio.io/istio/pilot/pkg/serviceregistry/kube/controller/multicluster.go:186) +0xa0
[istio.io/istio/pkg/kube/multicluster.(*Controller).handleDelete(0x40056a8540](http://istio.io/istio/pkg/kube/multicluster.(*Controller).handleDelete(0x40056a8540)?, {0x4000f87680, 0x15})
[istio.io/istio/pkg/kube/multicluster/secretcontroller.go:439](http://istio.io/istio/pkg/kube/multicluster/secretcontroller.go:439) +0x54
[istio.io/istio/pkg/kube/multicluster.(*Controller).deleteCluster(0x4000a5c6c0](http://istio.io/istio/pkg/kube/multicluster.(*Controller).deleteCluster(0x4000a5c6c0), {0x404f3c9340, 0x39}, 0x400a975bc0)
[istio.io/istio/pkg/kube/multicluster/secretcontroller.go:410](http://istio.io/istio/pkg/kube/multicluster/secretcontroller.go:410) +0xe0
[istio.io/istio/pkg/kube/multicluster.(*Controller).deleteSecret(0x4000a5c6c0](http://istio.io/istio/pkg/kube/multicluster.(*Controller).deleteSecret(0x4000a5c6c0), {0x404f3c9340, 0x39})
[istio.io/istio/pkg/kube/multicluster/secretcontroller.go:401](http://istio.io/istio/pkg/kube/multicluster/secretcontroller.go:401) +0xb0
[istio.io/istio/pkg/kube/multicluster.(*Controller).processItem(0x4000a5c6c0](http://istio.io/istio/pkg/kube/multicluster.(*Controller).processItem(0x4000a5c6c0), {{0x4066dbc990, 0xf}, {0x4082130e10, 0x29}})
[istio.io/istio/pkg/kube/multicluster/secretcontroller.go:225](http://istio.io/istio/pkg/kube/multicluster/secretcontroller.go:225) +0x290
[istio.io/istio/pkg/kube/controllers.WithReconciler.func1.1({0x2d7a1c0](http://istio.io/istio/pkg/kube/controllers.WithReconciler.func1.1(%7B0x2d7a1c0)?, 0x40d008bea0?})
[istio.io/istio/pkg/kube/controllers/queue.go:68](http://istio.io/istio/pkg/kube/controllers/queue.go:68) +0x50
[istio.io/istio/pkg/kube/controllers.Queue.processNextItem({{0x38286a8](http://istio.io/istio/pkg/kube/controllers.Queue.processNextItem(%7B%7B0x38286a8), 0x40000e5e00}, 0x4000e09190, {0x319dc01, 0x13}, 0xf, 0x4000a75070, 0x4000eb0540, 0x4000f63170})
[istio.io/istio/pkg/kube/controllers/queue.go:167](http://istio.io/istio/pkg/kube/controllers/queue.go:167) +0x138
[istio.io/istio/pkg/kube/controllers.Queue.Run.func1()](http://istio.io/istio/pkg/kube/controllers.Queue.Run.func1())
[istio.io/istio/pkg/kube/controllers/queue.go:116](http://istio.io/istio/pkg/kube/controllers/queue.go:116) +0x4c
created by [istio.io/istio/pkg/kube/controllers.Queue.Run](http://istio.io/istio/pkg/kube/controllers.Queue.Run)
[istio.io/istio/pkg/kube/controllers/queue.go:114](http://istio.io/istio/pkg/kube/controllers/queue.go:114) +0x144
```

This particular stack trace is from 1.18.0, but this is also happening on and 1.17.2.

I can provide more logs if necessary.

### Version

```Text
1.18.0
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hzxuzhonghu** [comment]
How can we reproduce
