### ISSUE TITLE
Install Istio ambient failed - kubernetes1.27.3 + Calico3.25

### ISSUE THREAD

**Issue by Snuger** [istio/istio#46054]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio-cni-node cannot start normally

istioctl install --set profile=ambient --set values.cni.ambient.redirectMode="ebpf" --set .values.global.hub="xxxxxxxx/istio"

istioctl install --set profile=ambient  --set .values.global.hub="xxxxxxxx/istio"

### Version

```Text
$ istioctl version
client version: 1.18.0
control plane version: 1.18.0
$ kubectl version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

### Additional Information

istioctl install --set profile=ambient --set values.cni.ambient.redirectMode="ebpf" --set .values.global.hub="xxxxxxxx/istio"
This will install the Istio 1.18.0 ambient profile with ["Istio core" "Istiod" "CNI" "Ztunnel"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ztunnel installed
✘ CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: context deadline exceeded

[root@k8s-master-01 istio-1.18.0]# kubectl get pod -n istio-system
NAME                      READY   STATUS             RESTARTS      AGE
istio-cni-node-mftkq      0/1     CrashLoopBackOff   4 (83s ago)   3m1s
istio-cni-node-nptmh      0/1     CrashLoopBackOff   5 (8s ago)    3m1s
istio-cni-node-nrh5p      0/1     CrashLoopBackOff   4 (79s ago)   3m1s
istio-cni-node-p2tdg      0/1     CrashLoopBackOff   4 (83s ago)   3m1s
istio-cni-node-tn2fv      0/1     Error              5 (94s ago)   3m1s
istiod-765ff6b944-98q9z   1/1     Running            0             3m7s
ztunnel-9wnrs             1/1     Running            0             3m12s
ztunnel-hkkwb             1/1     Running            0             3m12s
ztunnel-mpxb4             1/1     Running            0             3m12s
ztunnel-r7g4t             1/1     Running            0             3m12s
ztunnel-rz88f             1/1     Running            0             3m12s

[root@k8s-master-01 istio-1.18.0]# kubectl logs istio-cni-node-mftkq -n istio-system
2023-07-18T08:03:01.159989Z     info    FLAG: --ambient-enabled="false"
2023-07-18T08:03:01.160087Z     info    FLAG: --chained-cni-plugin="true"
2023-07-18T08:03:01.160103Z     info    FLAG: --cni-conf-name=""
2023-07-18T08:03:01.160111Z     info    FLAG: --cni-enable-install="true"
2023-07-18T08:03:01.160120Z     info    FLAG: --cni-enable-reinstall="true"
2023-07-18T08:03:01.160136Z     info    FLAG: --cni-net-dir="/etc/cni/net.d"
2023-07-18T08:03:01.160145Z     info    FLAG: --cni-network-config=""
2023-07-18T08:03:01.160151Z     info    FLAG: --cni-network-config-file=""
2023-07-18T08:03:01.160159Z     info    FLAG: --ctrlz_address="localhost"
2023-07-18T08:03:01.160179Z     info    FLAG: --ctrlz_port="9876"
2023-07-18T08:03:01.160189Z     info    FLAG: --ebpf-enabled="false"
2023-07-18T08:03:01.160200Z     info    FLAG: --help="false"
2023-07-18T08:03:01.160206Z     info    FLAG: --kube-ca-file=""
2023-07-18T08:03:01.160212Z     info    FLAG: --kubecfg-file-name="ZZZ-istio-cni-kubeconfig"
2023-07-18T08:03:01.160220Z     info    FLAG: --kubeconfig-mode="384"
2023-07-18T08:03:01.160228Z     info    FLAG: --log-level="warn"
2023-07-18T08:03:01.160234Z     info    FLAG: --log-uds-address="/var/run/istio-cni/log.sock"
2023-07-18T08:03:01.160242Z     info    FLAG: --log_as_json="false"
2023-07-18T08:03:01.160248Z     info    FLAG: --log_caller=""
2023-07-18T08:03:01.160255Z     info    FLAG: --log_output_level="default:info"
2023-07-18T08:03:01.160261Z     info    FLAG: --log_rotate=""
2023-07-18T08:03:01.160268Z     info    FLAG: --log_rotate_max_age="30"
2023-07-18T08:03:01.160276Z     info    FLAG: --log_rotate_max_backups="1000"
2023-07-18T08:03:01.160281Z     info    FLAG: --log_rotate_max_size="104857600"
2023-07-18T08:03:01.160288Z     info    FLAG: --log_stacktrace_level="default:none"
2023-07-18T08:03:01.160305Z     info    FLAG: --log_target="[stdout]"
2023-07-18T08:03:01.160313Z     info    FLAG: --monitoring-port="15014"
2023-07-18T08:03:01.160321Z     info    FLAG: --mounted-cni-net-dir="/host/etc/cni/net.d"
2023-07-18T08:03:01.160331Z     info    FLAG: --repair-broken-pod-label-key="cni.istio.io/uninitialized"
2023-07-18T08:03:01.160337Z     info    FLAG: --repair-broken-pod-label-value="true"
2023-07-18T08:03:01.160348Z     info    FLAG: --repair-delete-pods="false"
2023-07-18T08:03:01.160359Z     info    FLAG: --repair-enabled="true"
2023-07-18T08:03:01.160366Z     info    FLAG: --repair-field-selectors=""
2023-07-18T08:03:01.160373Z     info    FLAG: --repair-init-container-exit-code="126"
2023-07-18T08:03:01.160381Z     info    FLAG: --repair-init-container-name="istio-validation"
2023-07-18T08:03:01.160391Z     info    FLAG: --repair-init-container-termination-message=""
2023-07-18T08:03:01.160398Z     info    FLAG: --repair-label-pods="false"
2023-07-18T08:03:01.160405Z     info    FLAG: --repair-label-selectors=""
2023-07-18T08:03:01.160412Z     info    FLAG: --repair-node-name=""
2023-07-18T08:03:01.160418Z     info    FLAG: --repair-run-as-daemon="false"
2023-07-18T08:03:01.160424Z     info    FLAG: --repair-sidecar-annotation="sidecar.istio.io/status"
2023-07-18T08:03:01.160433Z     info    FLAG: --skip-cni-binaries="[]"
2023-07-18T08:03:01.160439Z     info    FLAG: --skip-tls-verify="false"
2023-07-18T08:03:01.160445Z     info    FLAG: --update-cni-binaries="true"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x21ed991]

goroutine 1 [running]:
github.com/cilium/ebpf.(*Program).FD(...)
2023-07-18T08:03:01.168486Z     info    CNI install configuration:
CNINetDir: /etc/cni/net.d
MountedCNINetDir: /host/etc/cni/net.d
CNIConfName:
ChainedCNIPlugin: true
CNINetworkConfigFile:
CNINetworkConfig: {
        github.com/cilium/ebpf@v0.10.0/prog.go:437
istio.io/istio/cni/pkg/ebpf/server.(*RedirectServer).initBpfObjects(0xc0001606e0)
        istio.io/istio/cni/pkg/ebpf/server/redirectionServer_linux.go:172 +0x131
istio.io/istio/cni/pkg/ebpf/server.NewRedirectServer()
        istio.io/istio/cni/pkg/ebpf/server/redirectionServer_linux.go:222 +0x135
istio.io/istio/cni/pkg/ambient.NewServer({0x2fc1c50, 0xc000158e60}, {{0x2a588fc, 0xc}, {0x0, 0x0}, {0x0, 0x0}, 0x1, {0xc00007e00a, ...}})
        istio.io/istio/cni/pkg/ambient/server.go:86 +0x1da
istio.io/istio/cni/pkg/cmd.glob..func2(0x4703200, {0x2a46d8b?, 0x1?, 0x1?})
        istio.io/istio/cni/pkg/cmd/root.go:89 +0x3cc
github.com/spf13/cobra.(*Command).execute(0x4703200, {0xc000072070, 0x1, 0x1})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x4703200)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(0xc0005821e0?, {0x2fc1c50?, 0xc000158e60?})
        github.com/spf13/cobra@v1.7.0/command.go:985 +0x4a
main.main()
        istio.io/istio/cni/cmd/install-cni/main.go:39 +0x113
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "info",
  "log_uds_address": "__LOG_UDS_ADDRESS__",
  "ambient_enabled": true,
  "kubernetes": {
      "kubeconfig": "__KUBECONFIG_FILEPATH__",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "kube-system" ]
  }
}
CNIEnableInstall: true
CNIEnableReinstall: true
LogLevel: info
KubeconfigFilename: ZZZ-istio-cni-kubeconfig
KubeconfigMode: 0600
KubeCAFile:
SkipTLSVerify: false
K8sServiceProtocol:
K8sServiceHost: 10.96.0.1
K8sServicePort: 443
K8sNodeName: k8s-master-03
UpdateCNIBinaries: true
SkipCNIBinaries: []
MonitoringPort: 15014
LogUDSAddress: /var/run/istio-cni/log.sock
HostNSEnterExec: false
AmbientEnabled: true

2023-07-18T08:03:01.168636Z     info    CNI race repair configuration:
Enabled: true
RunAsDaemon: true
NodeName: k8s-master-03
LabelKey: cni.istio.io/uninitialized
LabelValue: true
DeletePods: true
LabelPods: true
SidecarAnnotation: sidecar.istio.io/status
InitContainerName: istio-validation
InitTerminationMsg:
InitExitCode: 126
LabelSelectors:
FieldSelectors:

2023-07-18T08:03:01.168430Z     info    ControlZ available at 127.0.0.1:9876
2023-07-18T08:03:01.169295Z     info    Start a UDS server for CNI plugin logs
eBPF support is temporarily disabled pending CNCF establishing guidance around dual-licensed eBPF bytecodehttps://github.com/cncf/toc/pull/1000#issuecomment

kubectl get pod -n kube-system
NAME                                       READY   STATUS    RESTARTS      AGE
calico-kube-controllers-6558bc7bbf-rn9b5   1/1     Running   0             24m
calico-node-47rwx                          1/1     Running   0             24m
calico-node-blhdd                          1/1     Running   0             24m
calico-node-fxvcv                          1/1     Running   0             24m
calico-node-rmw7r                          1/1     Running   0             24m
calico-node-tn9qr                          1/1     Running   0             24m
coredns-7c8488c699-6hs24                   1/1     Running   0             5h45m
coredns-7c8488c699-cjjsg                   1/1     Running   5 (24m ago)   5h45m
kube-apiserver-k8s-master-01               1/1     Running   0             5h46m
kube-apiserver-k8s-master-02               1/1     Running   0             5h45m
kube-apiserver-k8s-master-03               1/1     Running   0             5h45m
kube-controller-manager-k8s-master-01      1/1     Running   0             5h46m
kube-controller-manager-k8s-master-02      1/1     Running   0             5h45m
kube-controller-manager-k8s-master-03      1/1     Running   0             5h45m
kube-proxy-72tnm                           1/1     Running   0             5m11s
kube-proxy-g97pz                           1/1     Running   0             4m57s
kube-proxy-trhc6                           1/1     Running   0             5m
kube-proxy-xwgrd                           1/1     Running   0             5m8s
kube-proxy-zc79s                           1/1     Running   0             5m4s
kube-scheduler-k8s-master-01               1/1     Running   0             5h46m
kube-scheduler-k8s-master-02               1/1     Running   0             5h45m
kube-scheduler-k8s-master-03               1/1     Running   0             5h45m

-----------------------------------------------------------------------------------------------------------------------------------------

$istioctl install --set profile=ambient --set values.global.hub="XXXXXXX:8000/istio"
This will install the Istio 1.18.0 ambient profile with ["Istio core" "Istiod" "CNI" "Ztunnel"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ztunnel installed
✘ CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: context deadline exceeded

- Pruning removed resources
Error: failed to install manifests: errors occurred during operation

$kubectl logs  istio-cni-node-b5gsg -n istio-system
2023-07-18T10:34:54.346071Z     info    FLAG: --ambient-enabled="false"
2023-07-18T10:34:54.346159Z     info    FLAG: --chained-cni-plugin="true"
2023-07-18T10:34:54.346174Z     info    FLAG: --cni-conf-name=""
2023-07-18T10:34:54.346182Z     info    FLAG: --cni-enable-install="true"
2023-07-18T10:34:54.346190Z     info    FLAG: --cni-enable-reinstall="true"
2023-07-18T10:34:54.346200Z     info    FLAG: --cni-net-dir="/etc/cni/net.d"
2023-07-18T10:34:54.346243Z     info    FLAG: --cni-network-config=""
2023-07-18T10:34:54.346253Z     info    FLAG: --cni-network-config-file=""
2023-07-18T10:34:54.346263Z     info    FLAG: --ctrlz_address="localhost"
2023-07-18T10:34:54.346275Z     info    FLAG: --ctrlz_port="9876"
2023-07-18T10:34:54.346284Z     info    FLAG: --ebpf-enabled="false"
2023-07-18T10:34:54.346293Z     info    FLAG: --help="false"
2023-07-18T10:34:54.346302Z     info    FLAG: --kube-ca-file=""
2023-07-18T10:34:54.346311Z     info    FLAG: --kubecfg-file-name="ZZZ-istio-cni-kubeconfig"
2023-07-18T10:34:54.346323Z     info    FLAG: --kubeconfig-mode="384"
2023-07-18T10:34:54.346518Z     info    FLAG: --log-level="warn"
2023-07-18T10:34:54.346531Z     info    FLAG: --log-uds-address="/var/run/istio-cni/log.sock"
2023-07-18T10:34:54.346538Z     info    FLAG: --log_as_json="false"
2023-07-18T10:34:54.346544Z     info    FLAG: --log_caller=""
2023-07-18T10:34:54.346549Z     info    FLAG: --log_output_level="default:info"
2023-07-18T10:34:54.346555Z     info    FLAG: --log_rotate=""
2023-07-18T10:34:54.346560Z     info    FLAG: --log_rotate_max_age="30"
2023-07-18T10:34:54.346567Z     info    FLAG: --log_rotate_max_backups="1000"
2023-07-18T10:34:54.346578Z     info    FLAG: --log_rotate_max_size="104857600"
2023-07-18T10:34:54.346584Z     info    FLAG: --log_stacktrace_level="default:none"
2023-07-18T10:34:54.346598Z     info    FLAG: --log_target="[stdout]"
2023-07-18T10:34:54.346605Z     info    FLAG: --monitoring-port="15014"
2023-07-18T10:34:54.346611Z     info    FLAG: --mounted-cni-net-dir="/host/etc/cni/net.d"
2023-07-18T10:34:54.346618Z     info    FLAG: --repair-broken-pod-label-key="cni.istio.io/uninitialized"
2023-07-18T10:34:54.346624Z     info    FLAG: --repair-broken-pod-label-value="true"
2023-07-18T10:34:54.346629Z     info    FLAG: --repair-delete-pods="false"
2023-07-18T10:34:54.346635Z     info    FLAG: --repair-enabled="true"
2023-07-18T10:34:54.346641Z     info    FLAG: --repair-field-selectors=""
2023-07-18T10:34:54.346647Z     info    FLAG: --repair-init-container-exit-code="126"
2023-07-18T10:34:54.346653Z     info    FLAG: --repair-init-container-name="istio-validation"
2023-07-18T10:34:54.346658Z     info    FLAG: --repair-init-container-termination-message=""
2023-07-18T10:34:54.346664Z     info    FLAG: --repair-label-pods="false"
2023-07-18T10:34:54.346669Z     info    FLAG: --repair-label-selectors=""
2023-07-18T10:34:54.346677Z     info    FLAG: --repair-node-name=""
2023-07-18T10:34:54.346685Z     info    FLAG: --repair-run-as-daemon="false"
2023-07-18T10:34:54.346696Z     info    FLAG: --repair-sidecar-annotation="sidecar.istio.io/status"
2023-07-18T10:34:54.346707Z     info    FLAG: --skip-cni-binaries="[]"
2023-07-18T10:34:54.346716Z     info    FLAG: --skip-tls-verify="false"
2023-07-18T10:34:54.346726Z     info    FLAG: --update-cni-binaries="true"
2023-07-18T10:34:54.352536Z     info    ControlZ available at 127.0.0.1:9876
2023-07-18T10:34:54.352619Z     info    CNI install configuration:
CNINetDir: /etc/cni/net.d
MountedCNINetDir: /host/etc/cni/net.d
CNIConfName:
ChainedCNIPlugin: true
CNINetworkConfigFile:
CNINetworkConfig: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "info",
  "log_uds_address": "__LOG_UDS_ADDRESS__",
  "ambient_enabled": true,
  "kubernetes": {
      "kubeconfig": "__KUBECONFIG_FILEPATH__",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "kube-system" ]
  }
}
CNIEnableInstall: true
CNIEnableReinstall: true
LogLevel: info
KubeconfigFilename: ZZZ-istio-cni-kubeconfig
KubeconfigMode: 0600
KubeCAFile:
SkipTLSVerify: false
K8sServiceProtocol:
K8sServiceHost: 10.96.0.1
K8sServicePort: 443
K8sNodeName: k8s-master-01
UpdateCNIBinaries: true
SkipCNIBinaries: []
MonitoringPort: 15014
LogUDSAddress: /var/run/istio-cni/log.sock
HostNSEnterExec: false
AmbientEnabled: true

2023-07-18T10:34:54.352754Z     info    CNI race repair configuration:
Enabled: true
RunAsDaemon: true
NodeName: k8s-master-01
LabelKey: cni.istio.io/uninitialized
LabelValue: true
DeletePods: true
LabelPods: true
SidecarAnnotation: sidecar.istio.io/status
InitContainerName: istio-validation
InitTerminationMsg:
InitExitCode: 126
LabelSelectors:
FieldSelectors:

2023-07-18T10:34:54.353325Z     info    Start a UDS server for CNI plugin logs
2023-07-18T10:34:54.381826Z     info    ambient HostIP=172.19.133.3
2023-07-18T10:34:54.382557Z     info    ambient Writing ambient config: {"ztunnelReady":false,"redirectMode":"iptables"}
2023-07-18T10:34:54.388480Z     info    ambient Namespace default is enabled in ambient mesh
2023-07-18T10:34:54.389783Z     info    ambient Namespace istio-system is disabled from ambient mesh
2023-07-18T10:34:54.389840Z     info    ambient Namespace kube-node-lease is disabled from ambient mesh
2023-07-18T10:34:54.389869Z     info    ambient Namespace kube-public is disabled from ambient mesh
2023-07-18T10:34:54.389888Z     info    ambient Namespace kube-system is disabled from ambient mesh
2023-07-18T10:34:54.484508Z     info    repair  Start CNI race condition repair.
2023-07-18T10:34:54.484549Z     info    controllers     starting        controller=ambient
2023-07-18T10:34:55.239880Z     info    install Copied istio-cni to /host/opt/cni/bin.
2023-07-18T10:34:55.239955Z     info    install Directory /host/secondary-bin-dir is not writable, skipping.
2023-07-18T10:34:55.240324Z     info    install write kubeconfig file /host/etc/cni/net.d/ZZZ-istio-cni-kubeconfig with:
# Kubeconfig file for Istio CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://[10.96.0.1]:443
    certificate-authority-data: <CA cert from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt>
users:
- name: istio-cni
  user:
    token: "<redacted>"
contexts:
- name: istio-cni-context
  context:
    cluster: local
    user: istio-cni
current-context: istio-cni-context

2023-07-18T10:34:55.240669Z     info    install Using CNI config template from CNI_NETWORK_CONFIG environment variable.
2023-07-18T10:34:55.240696Z     info    install CNI config: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "info",
  "log_uds_address": "/var/run/istio-cni/log.sock",
  "ambient_enabled": true,
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "kube-system" ]
  }
}
2023-07-18T10:34:55.241408Z     info    install CNI config file /host/etc/cni/net.d/10-calico.conflist exists. Proceeding.
2023-07-18T10:34:55.241872Z     info    install Created CNI config /host/etc/cni/net.d/10-calico.conflist
2023-07-18T10:34:55.241894Z     info    install Installation succeed, start watching for re-installation.
2023-07-18T10:35:10.246927Z     info    cni     Pod istio-system/ztunnel-nmhrd excluded because it only has 1 containers
2023-07-18T10:35:29.096849Z     info    ambient Writing ambient config: {"ztunnelReady":true,"redirectMode":"iptables"}
2023-07-18T10:35:29.097396Z     info    ambient active ztunnel updated to ztunnel-nmhrd
2023-07-18T10:35:29.097422Z     info    ambient Node-level network rule cleanup started
2023-07-18T10:35:29.097442Z     info    ambient Detecting iptables command
2023-07-18T10:35:29.155544Z     info    ambient Detected iptables-legacy
2023-07-18T10:35:29.161090Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.167416Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.172358Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.176368Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.180966Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.184483Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.189763Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.195407Z     warn    ambient Error running command iptables-legacy: iptables v1.8.7 (legacy): Couldn't load target `ztunnel-PREROUTING':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

2023-07-18T10:35:29.199852Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.203309Z     warn    ambient Error running command iptables-legacy: iptables v1.8.7 (legacy): Couldn't load target `ztunnel-POSTROUTING':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

2023-07-18T10:35:29.207644Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.210894Z     warn    ambient Error running command iptables-legacy: iptables v1.8.7 (legacy): Couldn't load target `ztunnel-PREROUTING':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

2023-07-18T10:35:29.213619Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.216719Z     warn    ambient Error running command iptables-legacy: iptables v1.8.7 (legacy): Couldn't load target `ztunnel-POSTROUTING':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

2023-07-18T10:35:29.219929Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.224141Z     warn    ambient Error running command iptables-legacy: iptables v1.8.7 (legacy): Couldn't load target `ztunnel-FORWARD':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

2023-07-18T10:35:29.227484Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.230446Z     warn    ambient Error running command iptables-legacy: iptables v1.8.7 (legacy): Couldn't load target `ztunnel-INPUT':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

2023-07-18T10:35:29.233409Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.235962Z     warn    ambient Error running command iptables-legacy: iptables v1.8.7 (legacy): Couldn't load target `ztunnel-OUTPUT':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

2023-07-18T10:35:29.238409Z     warn    ambient Error running command iptables-legacy: iptables: No chain/target/match by that name.

2023-07-18T10:35:29.244105Z     warn    ambient Error running command ip rule del priority 100: RTNETLINK answers: No such file or directory

2023-07-18T10:35:29.248067Z     warn    ambient Error running command ip rule del priority 101: RTNETLINK answers: No such file or directory

2023-07-18T10:35:29.251581Z     warn    ambient Error running command ip rule del priority 102: RTNETLINK answers: No such file or directory

2023-07-18T10:35:29.255318Z     warn    ambient Error running command ip rule del priority 103: RTNETLINK answers: No such file or directory

2023-07-18T10:35:29.255522Z     warn    ambient did not find existing inbound tunnel istioin to delete: Link not found
2023-07-18T10:35:29.255601Z     warn    ambient did not find existing outbound tunnel istioout to delete: Link not found
2023-07-18T10:35:29.259414Z     warn    ambient unable to delete IPSet: no such file or directory
2023-07-18T10:35:29.437475Z     error   controllers     error handling istio-system/ztunnel-nmhrd, retrying (retry count: 1): failed to get ns name: failed to get namespace for 1  controller=ambient

### Affected product area

- [X] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
There are conflicts when using Ambient and Calico. Originally, the eBPF solution worked, but it has been disabled for reasons explained in the provided logs. You might want to try using Ambient in different environments.
