### ISSUE TITLE
istiod panics when deploying a virtualservice with updated HTTPRedirect config

### ISSUE THREAD

**Issue by paragones92** [istio/istio#47963]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Context

A service accessed through an ingress for accessing a UI deployed with istio inject sidecar has the following virtualservice, gateway, sidecar and destinationrule yamls in place and performing correctly:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-tutorium
  namespace: tutorium
spec:
  selector:
    istio: ingressgateway-public
  servers:
    - hosts:
        - tutorium.status.platform.de
        - tutorium.deploy.platform.de
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: tutorium-cert
        mode: SIMPLE
    - hosts:
        - tutorium.status.platform.de
        - tutorium.deploy.platform.de
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destinationrule-tutorium-status
  namespace: tutorium
spec:
  host: tutorium.status.platform.de
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecar-tutorium
  namespace: tutorium
spec:
  egress:
    - hosts:
        - ./*
        - istio-system/*
        - core-public/*
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-tutorium-status
  namespace: tutorium
spec:
  gateways:
    - gateway-tutorium
  hosts:
    - tutorium.status.platform.de
  http:
    - route:
      - destination:
          port:
            number: 80
          host: "tutorium-argocd-server"
```
### Changes

We are now performing a migration of the platform that temporally we want to redirect all request accessing to this UI to another authority and we have now changed the virtualservice config to HTTPRoute to HTTPRedirect as follows:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-tutorium-status
  namespace: tutorium
spec:
  gateways:
    - gateway-tutorium
  hosts:
    - tutorium.status.platform.de
  http:
  - redirect:
      authority: argocd.platform.de
      uri: /applications?proj=tutorium
```

After immedietly applying this change to the virtualservice component, we see that no redirections is occurring and we see the istiod pods all entering in crashloop with the following logs:

```
2023-11-21T15:23:54.631704Z	info	FLAG: --log_rotate=""
2023-11-21T15:23:54.631709Z	info	FLAG: --log_rotate_max_age="30"
2023-11-21T15:23:54.631714Z	info	FLAG: --log_rotate_max_backups="1000"
2023-11-21T15:23:54.631719Z	info	FLAG: --log_rotate_max_size="104857600"
2023-11-21T15:23:54.631726Z	info	FLAG: --log_stacktrace_level="default:none"
2023-11-21T15:23:54.631742Z	info	FLAG: --log_target="[stdout]"
2023-11-21T15:23:54.631761Z	info	FLAG: --meshConfig="./etc/istio/config/mesh"
2023-11-21T15:23:54.631766Z	info	FLAG: --monitoringAddr=":15014"
2023-11-21T15:23:54.631771Z	info	FLAG: --namespace="istio-system"
2023-11-21T15:23:54.631777Z	info	FLAG: --networksConfig="./etc/istio/config/meshNetworks"
2023-11-21T15:23:54.631781Z	info	FLAG: --profile="true"
2023-11-21T15:23:54.631798Z	info	FLAG: --registries="[Kubernetes]"
2023-11-21T15:23:54.631822Z	info	FLAG: --secureGRPCAddr=":15012"
2023-11-21T15:23:54.631828Z	info	FLAG: --shutdownDuration="10s"
2023-11-21T15:23:54.631840Z	info	FLAG: --tls-cipher-suites="[]"
2023-11-21T15:23:54.631847Z	info	FLAG: --tlsCertFile="/etc/cert-manager/tls/tls.crt"
2023-11-21T15:23:54.631856Z	info	FLAG: --tlsKeyFile="/etc/cert-manager/tls/tls.key"
2023-11-21T15:23:54.631863Z	info	FLAG: --vklog="0"
2023-11-21T15:23:54.652109Z	info	multiplexing gRPC on http addr :8080
2023-11-21T15:23:54.652142Z	info	initializing Istiod admin server
2023-11-21T15:23:54.657762Z	info	starting HTTP service at 0.0.0.0:8080
2023-11-21T15:23:54.657837Z	info	klog	Config not found: /var/run/secrets/remote/config
2023-11-21T15:23:54.671075Z	info	initializing mesh configuration ./etc/istio/config/mesh
2023-11-21T15:23:54.678252Z	info	controllers	starting	controller=configmap istio
2023-11-21T15:23:54.678569Z	info	Loaded MeshNetworks config from Kubernetes API server.
2023-11-21T15:23:54.678600Z	info	mesh networks configuration updated to: {

}
2023-11-21T15:23:54.682092Z	info	Loaded MeshConfig config from Kubernetes API server.
2023-11-21T15:23:54.682662Z	info	mesh configuration updated to: {
    "proxyListenPort": 15001,
    "proxyInboundListenPort": 15006,
    "connectTimeout": "10s",
    "protocolDetectionTimeout": "0s",
    "ingressClass": "istio",
    "ingressService": "istio-ingressgateway",
    "ingressControllerMode": "STRICT",
    "enableTracing": true,
    "accessLogFile": "/dev/stdout",
    "defaultConfig": {
        "configPath": "./etc/istio/proxy",
        "binaryPath": "/usr/local/bin/envoy",
        "serviceCluster": "istio-proxy",
        "drainDuration": "45s",
        "discoveryAddress": "istiod.istio-system.svc:15012",
        "proxyAdminPort": 15000,
        "controlPlaneAuthPolicy": "MUTUAL_TLS",
        "statNameLength": 189,
        "tracing": {
            "datadog": {
                "address": "$(HOST_IP):8126"
            }
        },
        "proxyMetadata": {
            "ISTIO_META_DNS_AUTO_ALLOCATE": "true",
            "ISTIO_META_DNS_CAPTURE": "true",
            "SECRET_TTL": "48h"
        },
        "statusPort": 15020,
        "terminationDrainDuration": "5s",
        "meshId": "istio-mesh",
        "holdApplicationUntilProxyStarts": true
    },
    "outboundTrafficPolicy": {
        "mode": "ALLOW_ANY"
    },
    "enableAutoMtls": true,
    "trustDomain": "cluster.local",
    "defaultServiceExportTo": [
        "*"
    ],
    "defaultVirtualServiceExportTo": [
        "*"
    ],
    "defaultDestinationRuleExportTo": [
        "*"
    ],
    "rootNamespace": "istio-system",
    "localityLbSetting": {
        "enabled": true
    },
    "dnsRefreshRate": "60s",
    "serviceSettings": [
        {
            "settings": {
                "clusterLocal": true
            },
            "hosts": [
                "dex.core-public.svc.cluster.local",
                "oauth2-proxy.core-public.svc.cluster.local",
                "dashboard.core-public.svc.cluster.local"
            ]
        }
    ],
    "enablePrometheusMerge": true,
    "extensionProviders": [
        {
            "name": "prometheus",
            "prometheus": {

            }
        },
        {
            "name": "stackdriver",
            "stackdriver": {

            }
        },
        {
            "name": "envoy",
            "envoyFileAccessLog": {
                "path": "/dev/stdout"
            }
        },
        {
            "name": "oauth2-proxy",
            "envoyExtAuthzHttp": {
                "service": "oauth2-proxy.core-public.svc.cluster.local",
                "port": 80,
                "includeHeadersInCheck": [
                    "authorization",
                    "cookie"
                ],
                "includeAdditionalHeadersInCheck": {
                    "X-Auth-Request-Redirect": "%REQ(x-forwarded-proto)%://%REQ(:authority)%%REQ(:path)%"
                },
                "headersToUpstreamOnAllow": [
                    "authorization",
                    "cookie",
                    "path"
                ],
                "headersToDownstreamOnDeny": [
                    "content-type",
                    "set-cookie"
                ]
            }
        }
    ],
    "defaultProviders": {
        "metrics": [
            "prometheus"
        ]
    },
    "discoverySelectors": [
        {
            "matchExpressions": [
                {
                    "key": "name",
                    "operator": "NotIn",
                    "values": [
                        "baku"
                    ]
                }
            ]
        }
    ],
    "meshMTLS": {
        "minProtocolVersion": "TLSV1_3"
    }
}
2023-11-21T15:23:54.686386Z	info	initializing mesh networks from mesh config watcher
2023-11-21T15:23:54.686640Z	info	mesh configuration: {
    "proxyListenPort": 15001,
    "proxyInboundListenPort": 15006,
    "connectTimeout": "10s",
    "protocolDetectionTimeout": "0s",
    "ingressClass": "istio",
    "ingressService": "istio-ingressgateway",
    "ingressControllerMode": "STRICT",
    "enableTracing": true,
    "accessLogFile": "/dev/stdout",
    "defaultConfig": {
        "configPath": "./etc/istio/proxy",
        "binaryPath": "/usr/local/bin/envoy",
        "serviceCluster": "istio-proxy",
        "drainDuration": "45s",
        "discoveryAddress": "istiod.istio-system.svc:15012",
        "proxyAdminPort": 15000,
        "controlPlaneAuthPolicy": "MUTUAL_TLS",
        "statNameLength": 189,
        "tracing": {
            "datadog": {
                "address": "$(HOST_IP):8126"
            }
        },
        "proxyMetadata": {
            "ISTIO_META_DNS_AUTO_ALLOCATE": "true",
            "ISTIO_META_DNS_CAPTURE": "true",
            "SECRET_TTL": "48h"
        },
        "statusPort": 15020,
        "terminationDrainDuration": "5s",
        "meshId": "istio-mesh",
        "holdApplicationUntilProxyStarts": true
    },
    "outboundTrafficPolicy": {
        "mode": "ALLOW_ANY"
    },
    "enableAutoMtls": true,
    "trustDomain": "cluster.local",
    "defaultServiceExportTo": [
        "*"
    ],
    "defaultVirtualServiceExportTo": [
        "*"
    ],
    "defaultDestinationRuleExportTo": [
        "*"
    ],
    "rootNamespace": "istio-system",
    "localityLbSetting": {
        "enabled": true
    },
    "dnsRefreshRate": "60s",
    "serviceSettings": [
        {
            "settings": {
                "clusterLocal": true
            },
            "hosts": [
                "dex.core-public.svc.cluster.local",
                "oauth2-proxy.core-public.svc.cluster.local",
                "dashboard.core-public.svc.cluster.local"
            ]
        }
    ],
    "enablePrometheusMerge": true,
    "extensionProviders": [
        {
            "name": "prometheus",
            "prometheus": {

            }
        },
        {
            "name": "stackdriver",
            "stackdriver": {

            }
        },
        {
            "name": "envoy",
            "envoyFileAccessLog": {
                "path": "/dev/stdout"
            }
        },
        {
            "name": "oauth2-proxy",
            "envoyExtAuthzHttp": {
                "service": "oauth2-proxy.core-public.svc.cluster.local",
                "port": 80,
                "includeHeadersInCheck": [
                    "authorization",
                    "cookie"
                ],
                "includeAdditionalHeadersInCheck": {
                    "X-Auth-Request-Redirect": "%REQ(x-forwarded-proto)%://%REQ(:authority)%%REQ(:path)%"
                },
                "headersToUpstreamOnAllow": [
                    "authorization",
                    "cookie",
                    "path"
                ],
                "headersToDownstreamOnDeny": [
                    "content-type",
                    "set-cookie"
                ]
            }
        }
    ],
    "defaultProviders": {
        "metrics": [
            "prometheus"
        ]
    },
    "discoverySelectors": [
        {
            "matchExpressions": [
                {
                    "key": "name",
                    "operator": "NotIn",
                    "values": [
                        "baku"
                    ]
                }
            ]
        }
    ],
    "meshMTLS": {
        "minProtocolVersion": "TLSV1_3"
    }
}
2023-11-21T15:23:54.686665Z	info	version: 1.18.2-0183f2886bc078e8df4d6bbd21fa452a3a23481d-Clean
2023-11-21T15:23:54.686991Z	info	flags: {
   "ServerOptions": {
      "HTTPAddr": ":8080",
      "HTTPSAddr": ":15017",
      "GRPCAddr": "",
      "MonitoringAddr": ":15014",
      "EnableProfiling": true,
      "TLSOptions": {
         "CaCertFile": "/etc/cert-manager/ca/root-cert.pem",
         "CertFile": "/etc/cert-manager/tls/tls.crt",
         "KeyFile": "/etc/cert-manager/tls/tls.key",
         "TLSCipherSuites": null,
         "CipherSuits": null
      },
      "SecureGRPCAddr": ":15012"
   },
   "InjectionOptions": {
      "InjectionDirectory": "./var/lib/istio/inject"
   },
   "PodName": "istiod-5b8795d4d9-24lg9",
   "Namespace": "istio-system",
   "Revision": "default",
   "MeshConfigFile": "./etc/istio/config/mesh",
   "NetworksConfigFile": "./etc/istio/config/meshNetworks",
   "RegistryOptions": {
      "FileDir": "",
      "Registries": [
         "Kubernetes"
      ],
      "KubeOptions": {
         "SystemNamespace": "",
         "MeshServiceController": null,
         "DomainSuffix": "cluster.local",
         "ClusterID": "cd-dev-fra-1698928345",
         "ClusterAliases": {},
         "Metrics": null,
         "XDSUpdater": null,
         "MeshNetworksWatcher": null,
         "MeshWatcher": null,
         "EndpointMode": 1,
         "KubernetesAPIQPS": 80,
         "KubernetesAPIBurst": 160,
         "SyncTimeout": 0,
         "DiscoveryNamespacesFilter": null,
         "ConfigController": null,
         "ConfigCluster": false
      },
      "ClusterRegistriesNamespace": "istio-system",
      "KubeConfig": "",
      "DistributionCacheRetention": 60000000000,
      "DistributionTrackingEnabled": false
   },
   "CtrlZOptions": {
      "Port": 9876,
      "Address": "localhost"
   },
   "KeepaliveOptions": {
      "Time": 30000000000,
      "Timeout": 10000000000,
      "MaxServerConnectionAge": 1800000000000,
      "MaxServerConnectionAgeGrace": 10000000000
   },
   "ShutdownDuration": 10000000000,
   "JwtRule": ""
}
2023-11-21T15:23:54.687017Z	info	initializing mesh handlers
2023-11-21T15:23:54.687090Z	info	model	reloading network gateways
2023-11-21T15:23:54.687118Z	info	initializing controllers
2023-11-21T15:23:54.921630Z	warn	kube	Skipping CRD gateway.networking.k8s.io/v1beta1/GatewayClass as it is not present	controller=crd-controller
2023-11-21T15:23:54.921681Z	warn	kube	Skipping CRD gateway.networking.k8s.io/v1beta1/HTTPRoute as it is not present	controller=crd-controller
2023-11-21T15:23:54.921687Z	warn	kube	Skipping CRD gateway.networking.k8s.io/v1beta1/Gateway as it is not present	controller=crd-controller
2023-11-21T15:23:54.921728Z	warn	kube	Skipping CRD gateway.networking.k8s.io/v1beta1/ReferenceGrant as it is not present	controller=crd-controller
2023-11-21T15:23:54.922197Z	info	Adding Kubernetes registry adapter
2023-11-21T15:23:54.922405Z	info	adding watcher for certificate /etc/cert-manager/tls/tls.crt
2023-11-21T15:23:54.922641Z	info	adding watcher for certificate /etc/cert-manager/tls/tls.key
2023-11-21T15:23:54.923501Z	info	Istiod certificates are reloaded
2023-11-21T15:23:54.924022Z	info	spiffe	Added 10 certs to trust domain cluster.local in peer cert verifier
2023-11-21T15:23:54.924046Z	info	initializing secure discovery service
2023-11-21T15:23:54.924084Z	info	initializing secure webhook server for istiod webhooks
2023-11-21T15:23:54.931030Z	info	initializing sidecar injector
2023-11-21T15:23:54.949974Z	info	initializing config validator
2023-11-21T15:23:54.950008Z	info	initializing registry event handlers
2023-11-21T15:23:54.950077Z	info	starting discovery service
2023-11-21T15:23:54.955005Z	info	Starting Istiod Server with primary cluster cd-dev-fra-1698928345
2023-11-21T15:23:54.955120Z	info	ControlZ available at 127.0.0.1:9876
2023-11-21T15:23:54.955235Z	info	initializing Kubernetes credential reader for cluster cd-dev-fra-1698928345
2023-11-21T15:23:54.955304Z	info	kube	Initializing Kubernetes service registry "cd-dev-fra-1698928345"
2023-11-21T15:23:54.955481Z	info	kube	should join leader-election for cluster cd-dev-fra-1698928345: false
2023-11-21T15:23:54.956273Z	info	status	Starting status manager
2023-11-21T15:23:54.956481Z	info	Starting multicluster remote secrets controller
2023-11-21T15:23:54.956608Z	info	Starting validation controller
2023-11-21T15:23:54.956717Z	info	Starting ADS server
2023-11-21T15:23:54.957092Z	info	klog	attempting to acquire leader lease istio-system/istio-gateway-status-leader...
2023-11-21T15:23:54.957679Z	info	klog	attempting to acquire leader lease istio-system/istio-gateway-deployment-default...
2023-11-21T15:23:54.957873Z	info	klog	attempting to acquire leader lease istio-system/istio-leader...
2023-11-21T15:23:54.958551Z	info	controllers	starting	controller=healthcheck
2023-11-21T15:23:54.960444Z	info	kube	Starting Pilot K8S CRD controller	controller=crd-controller
2023-11-21T15:23:54.960937Z	info	kube	controller "networking.istio.io/v1alpha3/DestinationRule" is syncing...	controller=crd-controller
2023-11-21T15:23:54.961161Z	info	controllers	starting	controller=unregister_workloadentry
2023-11-21T15:23:54.962892Z	info	multicluster remote secrets controller cache synced in 7.284183ms
2023-11-21T15:23:54.963098Z	info	controllers	starting	controller=multicluster secret
2023-11-21T15:23:54.963276Z	info	kube	controller "networking.istio.io/v1alpha3/EnvoyFilter" is syncing...	controller=crd-controller
2023-11-21T15:23:54.967816Z	info	kube	controller "security.istio.io/v1beta1/PeerAuthentication" is syncing...	controller=crd-controller
2023-11-21T15:23:54.976469Z	info	kube	controller "security.istio.io/v1beta1/PeerAuthentication" is syncing...	controller=crd-controller
2023-11-21T15:23:54.991003Z	info	controllers	starting	controller=validation
2023-11-21T15:23:54.991655Z	info	controllers	starting	controller=webhook patcher
2023-11-21T15:23:54.991876Z	info	controllers	starting	controller=ingress
2023-11-21T15:23:54.992014Z	info	controllers	starting	controller=configmap istio-sidecar-injector
2023-11-21T15:23:54.992224Z	info	controllers	starting	controller=default revision
2023-11-21T15:23:54.992696Z	info	controllers	starting	controller=default revision
2023-11-21T15:23:54.992719Z	info	kube	Pilot K8S CRD controller synced in 32.282906ms	controller=crd-controller
2023-11-21T15:23:55.004431Z	info	controllers	starting	controller=default revision
2023-11-21T15:23:55.015105Z	info	validationController	Not ready to switch validation to fail-closed: dummy invalid config not rejected
2023-11-21T15:23:55.015151Z	info	validationController	validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Ignore, resourceVersion=16135352) is up-to-date. No change required.
2023-11-21T15:23:55.015165Z	error	controllers	error handling /istio-validator-istio-system, retrying (retry count: 1): webhook is not ready, retry	controller=validation
2023-11-21T15:23:55.057511Z	info	Waiting for caches to be synced
2023-11-21T15:23:55.088314Z	info	kube	kube controller for cd-dev-fra-1698928345 synced after 130.261003ms
2023-11-21T15:23:55.088409Z	info	model	reloading network gateways
2023-11-21T15:23:55.090921Z	info	model	gateways changed, triggering push
2023-11-21T15:23:55.091248Z	info	ads	Full push, new service istio-system/istio-ingressgateway-public.istio-system.svc.cluster.local
2023-11-21T15:23:55.091319Z	info	ads	Full push, new service istio-system/istio-eastwestgateway.istio-system.svc.cluster.local
2023-11-21T15:23:55.091414Z	info	ads	Incremental push, service istiod.istio-system.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.091476Z	info	ads	Full push, new service istio-system/istio-ingressgateway-microservices.istio-system.svc.cluster.local
2023-11-21T15:23:55.093057Z	info	ads	Full push, new service cert-manager/cert-manager-istio-csr-metrics.cert-manager.svc.cluster.local
2023-11-21T15:23:55.093106Z	info	ads	Full push, new service default/kubernetes.default.svc.cluster.local
2023-11-21T15:23:55.093239Z	info	ads	Full push, new service kube-system/datadog-agent.kube-system.svc.cluster.local
2023-11-21T15:23:55.093290Z	info	ads	Full push, new service istio-operator/istio-operator.istio-operator.svc.cluster.local
2023-11-21T15:23:55.093328Z	info	ads	Full push, new service tutorium/tutorium-argocd-server.tutorium.svc.cluster.local
2023-11-21T15:23:55.093386Z	info	ads	Full push, new service kyverno/kyverno-cleanup-controller.kyverno.svc.cluster.local
2023-11-21T15:23:55.093427Z	info	ads	Full push, new service cert-manager/cert-manager-webhook.cert-manager.svc.cluster.local
2023-11-21T15:23:55.093560Z	info	ads	Full push, new service kube-system/cilium-agent.kube-system.svc.cluster.local
2023-11-21T15:23:55.093613Z	info	ads	Full push, new service kube-system/kube-dns-upstream.kube-system.svc.cluster.local
2023-11-21T15:23:55.093646Z	info	ads	Full push, new service argocd/argocd-repo-server.argocd.svc.cluster.local
2023-11-21T15:23:55.093682Z	info	ads	Full push, new service argocd/argocd-application-controller-metrics.argocd.svc.cluster.local
2023-11-21T15:23:55.093715Z	info	ads	Full push, new service argocd/argocd-server.argocd.svc.cluster.local
2023-11-21T15:23:55.093767Z	info	ads	Full push, new service tutorium/tutorium-argocd-repo-server.tutorium.svc.cluster.local
2023-11-21T15:23:55.093800Z	info	ads	Full push, new service kube-system/velero.kube-system.svc.cluster.local
2023-11-21T15:23:55.093845Z	info	ads	Full push, new service argocd/argo-redis-ha-announce-0.argocd.svc.cluster.local
2023-11-21T15:23:55.093882Z	info	ads	Full push, new service argocd/argocd-repo-server-metrics.argocd.svc.cluster.local
2023-11-21T15:23:55.093923Z	info	ads	Full push, new service kube-system/datadog-agent-cluster-agent-metrics-api.kube-system.svc.cluster.local
2023-11-21T15:23:55.093972Z	info	ads	Full push, new service kyverno/kyverno-policy-reporter.kyverno.svc.cluster.local
2023-11-21T15:23:55.094039Z	info	ads	Full push, new service kyverno/kyverno-background-controller-metrics.kyverno.svc.cluster.local
2023-11-21T15:23:55.094256Z	info	ads	Full push, new service kube-system/traefik.kube-system.svc.cluster.local
2023-11-21T15:23:55.094323Z	info	ads	Full push, new service argo/argo-workflows-workflow-controller.argo.svc.cluster.local
2023-11-21T15:23:55.094357Z	info	ads	Full push, new service kargo/kargo-api.kargo.svc.cluster.local
2023-11-21T15:23:55.094403Z	info	ads	Full push, new service kyverno/kyverno-svc-metrics.kyverno.svc.cluster.local
2023-11-21T15:23:55.094441Z	info	ads	Full push, new service tutorium/tutorium-argocd-repo-server-metrics.tutorium.svc.cluster.local
2023-11-21T15:23:55.094474Z	info	ads	Full push, new service argocd/argocd-applicationset-controller.argocd.svc.cluster.local
2023-11-21T15:23:55.094549Z	info	ads	Incremental push, service traefik-catch-all.kube-system.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.094595Z	info	ads	Full push, new service cert-manager/cert-manager-istio-csr.cert-manager.svc.cluster.local
2023-11-21T15:23:55.094636Z	info	ads	Full push, new service kube-system/kube-dns.kube-system.svc.cluster.local
2023-11-21T15:23:55.094681Z	info	ads	Full push, new service kyverno/kyverno-svc.kyverno.svc.cluster.local
2023-11-21T15:23:55.094714Z	info	ads	Full push, new service argo/argo-workflows-server.argo.svc.cluster.local
2023-11-21T15:23:55.094755Z	info	ads	Full push, new service kyverno/kyverno-cleanup-controller-metrics.kyverno.svc.cluster.local
2023-11-21T15:23:55.094790Z	info	ads	Full push, new service tutorium/tutorium-argocd-server-metrics.tutorium.svc.cluster.local
2023-11-21T15:23:55.094826Z	info	ads	Full push, new service argocd/argo-redis-ha-announce-1.argocd.svc.cluster.local
2023-11-21T15:23:55.094871Z	info	ads	Full push, new service argocd/argo-redis-ha-haproxy.argocd.svc.cluster.local
2023-11-21T15:23:55.094916Z	info	ads	Full push, new service argocd/argo-redis-ha.argocd.svc.cluster.local
2023-11-21T15:23:55.094963Z	info	ads	Full push, new service kube-system/bank-vaults.kube-system.svc.cluster.local
2023-11-21T15:23:55.095006Z	info	ads	Full push, new service tutorium/tutorium-argocd-redis.tutorium.svc.cluster.local
2023-11-21T15:23:55.095086Z	info	ads	Full push, new service kyverno/kyverno-reports-controller-metrics.kyverno.svc.cluster.local
2023-11-21T15:23:55.095131Z	info	ads	Full push, new service argocd/argocd-server-metrics.argocd.svc.cluster.local
2023-11-21T15:23:55.095172Z	info	ads	Full push, new service kargo/kargo-webhooks-server.kargo.svc.cluster.local
2023-11-21T15:23:55.095228Z	info	ads	Full push, new service kube-system/datadog-agent-cluster-agent.kube-system.svc.cluster.local
2023-11-21T15:23:55.095273Z	info	ads	Full push, new service core-public/oauth2-proxy.core-public.svc.cluster.local
2023-11-21T15:23:55.095309Z	info	ads	Full push, new service argocd/saiph.argocd.svc.cluster.local
2023-11-21T15:23:55.095733Z	info	ads	Full push, new service kube-system/spot-metrics.kube-system.svc.cluster.local
2023-11-21T15:23:55.095992Z	info	ads	Full push, new service cert-manager/cert-manager.cert-manager.svc.cluster.local
2023-11-21T15:23:55.096223Z	info	ads	Full push, new service core-public/dex.core-public.svc.cluster.local
2023-11-21T15:23:55.096372Z	info	ads	Incremental push, service tutorium-argocd-application-controller-metrics.tutorium.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.096525Z	info	ads	Incremental push, service istiod.istio-system.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.096687Z	info	ads	Full push, new service argocd/argo-redis-ha-announce-2.argocd.svc.cluster.local
2023-11-21T15:23:55.097032Z	info	ads	Full push, new service core-public/dashboard.core-public.svc.cluster.local
2023-11-21T15:23:55.097250Z	info	ads	Full push, new service kube-system/metrics-server.kube-system.svc.cluster.local
2023-11-21T15:23:55.100892Z	info	ads	Incremental push, service traefik-catch-all.kube-system.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.101542Z	info	ads	Incremental push, service tutorium-argocd-application-controller-metrics.tutorium.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.102135Z	info	ads	Incremental push, service traefik-catch-all.kube-system.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.102284Z	info	ads	Incremental push, service tutorium-argocd-application-controller-metrics.tutorium.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.102374Z	info	ads	Incremental push, service istiod.istio-system.svc.cluster.local at shard Kubernetes/cd-dev-fra-1698928345 has no endpoints
2023-11-21T15:23:55.120972Z	info	All controller caches have been synced up in 63.459395ms
2023-11-21T15:23:55.121195Z	info	validationController	Not ready to switch validation to fail-closed: dummy invalid config not rejected
2023-11-21T15:23:55.121229Z	info	validationController	validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Ignore, resourceVersion=16135352) is up-to-date. No change required.
2023-11-21T15:23:55.121243Z	error	controllers	error handling /istio-validator-istio-system, retrying (retry count: 2): webhook is not ready, retry	controller=validation
2023-11-21T15:23:55.204335Z	info	ads	Push debounce stable[1] 380 for reason config and 379 more reasons: 100.305843ms since last change, 211.352915ms since last push, full=true
panic: assignment to entry in nil map

goroutine 497 [running]:
istio.io/istio/pkg/util/sets.Set[...].Insert(...)
	istio.io/istio/pkg/util/sets/set.go:40
istio.io/istio/pilot/pkg/model.addHostsFromMeshConfig(0x3243a00?, 0xc001978330?)
	istio.io/istio/pilot/pkg/model/push_context.go:840 +0x91
istio.io/istio/pilot/pkg/model.(*PushContext).initVirtualServices(0xc00194e380, 0xc000572000)
	istio.io/istio/pilot/pkg/model/push_context.go:1558 +0xe55
istio.io/istio/pilot/pkg/model.(*PushContext).createNewContext(0xc00194e380, 0xc000572000)
	istio.io/istio/pilot/pkg/model/push_context.go:1208 +0xb3
istio.io/istio/pilot/pkg/model.(*PushContext).InitContext(0xc00194e380, 0xc000572000, 0xc00014bc00, 0xc001062fc0)
	istio.io/istio/pilot/pkg/model/push_context.go:1184 +0x24d
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).initPushContext(0xc000bab400, 0xc000ae7410?, 0x6311a60?, {0xc000ae7428, 0x16})
	istio.io/istio/pilot/pkg/xds/discovery.go:524 +0xc5
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Push(0x0?, 0xc001062fc0)
	istio.io/istio/pilot/pkg/xds/discovery.go:301 +0x105
istio.io/istio/pilot/pkg/xds.debounce.func1(0xc0008f6480?, 0x17c, {0x2d6ba0a?, 0xc000bab400?, 0x6311a60?})
	istio.io/istio/pilot/pkg/xds/discovery.go:374 +0x4d
created by istio.io/istio/pilot/pkg/xds.debounce.func2
	istio.io/istio/pilot/pkg/xds/discovery.go:397 +0x4b5

```

This is only recoverable after rolling back changes to HTTPRoute and istiod pods are no longer in crashloop

### Question

What could be possibly causing this panic, as it is a mere change from HTTPRoute to HTTPRedirect based on this documentation https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRedirect ? We had a similar migration a couple of month ago in istio 1.16 and it went fine. 

### Version

```Text
$ istioctl version
client version: 1.18.2
control plane version: 1.18.2

$ kubectl version        
Client Version: v1.28.2
Server Version: v1.26.10
```

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/45956, linked to https://github.com/istio/istio/pull/47980.

**Comment by hanxiaop** [comment]
Fixed.
