### ISSUE TITLE
Failed to acquire resource (boskos / mason)

### ISSUE THREAD

**Issue by ayj** [istio/istio#4862]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/4778/e2e-simpleTests/2443/

```bash
I0410 22:26:41.233] failed to get a Boskos resource
I0410 22:26:41.233] failed to kill mason client
I0410 22:26:41.234] time="2018-04-10T22:16:51Z" level=info msg="Attempting to acquire resource"
I0410 22:26:41.234] time="2018-04-10T22:16:51Z" level=info msg="Failed to acquire resource"

...

I0410 22:26:41.245] time="2018-04-10T22:26:24Z" level=info msg="Failed to acquire resource"
I0410 22:26:41.245] time="2018-04-10T22:26:34Z" level=info msg="Attempting to acquire resource"
I0410 22:26:41.245] time="2018-04-10T22:26:40Z" level=info msg="Failed to acquire resource"
I0410 22:26:41.246] time="2018-04-10T22:26:41Z" level=panic msg="unable to find a resource" error="context deadline exceeded"
I0410 22:26:41.246] panic: (*logrus.Entry) (0x8cd4c0,0xc4202e4dc0)
I0410 22:26:41.246] 
I0410 22:26:41.246] goroutine 1 [running]:
I0410 22:26:41.246] istio.io/test-infra/vendor/github.com/sirupsen/logrus.Entry.log(0xc42009e140, 0xc420322ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0410 22:26:41.246] 	/home/bootstrap/go/src/istio.io/test-infra/vendor/github.com/sirupsen/logrus/entry.go:128 +0x59c
I0410 22:26:41.246] istio.io/test-infra/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc4202e4d70, 0xc4201add88, 0x1, 0x1)
I0410 22:26:41.246] 	/home/bootstrap/go/src/istio.io/test-infra/vendor/github.com/sirupsen/logrus/entry.go:173 +0xaa
I0410 22:26:41.246] istio.io/test-infra/vendor/github.com/sirupsen/logrus.(*Entry).Panicf(0xc4202e4d70, 0x8e9a01, 0x19, 0x0, 0x0, 0x0)
I0410 22:26:41.247] 	/home/bootstrap/go/src/istio.io/test-infra/vendor/github.com/sirupsen/logrus/entry.go:221 +0xed
I0410 22:26:41.247] main.main()
I0410 22:26:41.247] 	/home/bootstrap/go/src/istio.io/test-infra/boskos/cmd/mason_client/main.go:147 +0x8c4
W0410 22:26:41.247] + echo 'failed to get a Boskos resource'
```

**Comment by hklai** [comment]
I think this has been fixed, and boskos resources can be monitored at https://velodrome.istio.io/dashboard/db/boskos-dashboard?orgId=1.
