### ISSUE TITLE
Istio Operator dies on Pruning removed resources

### ISSUE THREAD

**Issue by petersutter5** [istio/istio#48964]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We've upgraded from 1.18.5 to 1.19.6 and are getting stuck here. The ingress and system pods get created, but I think the operator is just dead. After this error, the operator doesn't reconcile any changes made by hand to the ingress/system pods. I've seen this error on other issues, but the operator usually continues on. Ours stops logging completely. The operator pod is still running, and in the container itself I can see the operator process running. 

We use the operator helm chart version 1.19.6, and flux to deploy onto k8s. 

Thank you
```
✔ Istiod installed
{"level":"info","time":"2024-01-24T17:39:23.185192Z","scope":"installer","msg":"using server side apply to update obj: PodDisruptionBudget/istio-ingress/istio-ingressgateway"}
{"level":"info","time":"2024-01-24T17:39:23.198381Z","scope":"installer","msg":"using server side apply to update obj: Role/istio-ingress/istio-ingressgateway-sds"}
{"level":"info","time":"2024-01-24T17:39:23.212807Z","scope":"installer","msg":"using server side apply to update obj: RoleBinding/istio-ingress/istio-ingressgateway-sds"}
{"level":"info","time":"2024-01-24T17:39:23.223893Z","scope":"installer","msg":"using server side apply to update obj: HorizontalPodAutoscaler/istio-ingress/istio-ingressgateway"}
{"level":"info","time":"2024-01-24T17:39:23.235387Z","scope":"installer","msg":"using server side apply to update obj: Service/istio-ingress/istio-ingressgateway"}
- Processing resources for Ingress gateways.
✔ Ingress gateways installed
**- Pruning removed resources[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.**
Detected at:
	>  goroutine 415 [running]:
	>  runtime/debug.Stack()
	>  	runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc00310ab80, 0x0?)
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/log/deleg.go:111 +0x32
	>  github.com/go-logr/logr.Logger.Enabled(...)
	>  	github.com/go-logr/logr@v1.2.4/logr.go:261
	>  github.com/go-logr/logr.Logger.Info({{0x3446c68?, 0xc00310ab80?}, 0xc003238870?}, {0x2ea6971, 0x14}, {0x0, 0x0, 0x0})
	>  	github.com/go-logr/logr@v1.2.4/logr.go:274 +0x72
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000bfa1e0, {0x3440c08, 0xc0006f2e10}, {0x2a8e980?, 0xc000614520?})
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:344 +0x505
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000bfa1e0, {0x3440c08, 0xc0006f2e10})
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:266 +0x1c9
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:227 +0x79
	>  created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 86
	>  	sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:223 +0x565

```

### Version

```Text
$ istioctl version
client version: 1.20.2
control plane version: 1.19.6
data plane version: 1.18.3 (1 proxies), 1.18.5 (1 proxies), 1.19.6 (1 proxies)
$ kubectl  version --short
Client Version: v1.22.4
Server Version: v1.26.11-eks-8cb36c9
WARNING: version difference between client (1.22) and server (1.26) exceeds the supported minor version skew of +/-1
$ helm version --short
v3.8.0+gd141386
```

**Comment by petersutter5** [comment]
Looks like the operator is still working and maintaining our ingress/system deployments. It's just that with no vklog level set on the operator server command, we still getting logs after the pruning message.

**Comment by petersutter5** [comment]
Does the Go error matter?

**Comment by hanxiaop** [comment]
> Yes it seems that logging is fine also, if you wait for a message to come in..

I think this is just a display error which should not affect the operator and the next reconcile loop.

**Comment by hanxiaop** [comment]
> Does the Go error matter?

Will have no effect on the operator's functionality.
