### ISSUE TITLE
discovery fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by ayj** [istio/istio#4903]
@farcaller commented on [Thu Apr 12 2018](https://github.com/istio/issues/issues/285)

**Is this a BUG or FEATURE REQUEST?:**

Bug

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

Yes

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**

Yes, istio-auth.yaml

**What happened**:

discovery crashed after I added the following ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: http
```

**What you expected to happen:**

Discovery not crashing.

**How to reproduce it:**

N/A (cannot reproduce yet)

**Stacktrace:**

```
istio-pilot-fd8fb6957-rd2j5 discovery fatal error: concurrent map read and map write
istio-pilot-fd8fb6957-rd2j5 discovery
istio-pilot-fd8fb6957-rd2j5 discovery goroutine 16329 [running]:
istio-pilot-fd8fb6957-rd2j5 discovery runtime.throw(0x17b9212, 0x21)
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420937790 sp=0xc420937770 pc=0x42bb85
istio-pilot-fd8fb6957-rd2j5 discovery runtime.mapaccess2(0x159fc40, 0xc4202d0900, 0xc420176d10, 0xc4209e5808, 0xc4209e5501)
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/runtime/hashmap.go:413 +0x24e fp=0xc4209377d8 sp=0xc420937790 pc=0x40887e
istio-pilot-fd8fb6957-rd2j5 discovery reflect.mapaccess(0x159fc40, 0xc4202d0900, 0xc420176d10, 0xc4202d0900)
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/runtime/hashmap.go:1218 +0x3f fp=0xc420937810 sp=0xc4209377d8 pc=0x40b19f
istio-pilot-fd8fb6957-rd2j5 discovery reflect.Value.MapIndex(0x159fc40, 0xc4202d0900, 0x15, 0x1532a00, 0xc420176d10, 0x98, 0x14cd660, 0xc4207fdbd0, 0x16)
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/reflect/value.go:1058 +0x126 fp=0xc420937898 sp=0xc420937810 pc=0x4ba756
istio-pilot-fd8fb6957-rd2j5 discovery fmt.(*pp).printValue(0xc420318000, 0x159fc40, 0xc4202d0900, 0x15, 0x76, 0x0)
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/fmt/print.go:750 +0xf47 fp=0xc420937ad8 sp=0xc420937898 pc=0x4d0397
istio-pilot-fd8fb6957-rd2j5 discovery fmt.(*pp).printArg(0xc420318000, 0x159fc40, 0xc4202d0900, 0xc400000076)
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/fmt/print.go:682 +0x1e5 fp=0xc420937b58 sp=0xc420937ad8 pc=0x4cec45
istio-pilot-fd8fb6957-rd2j5 discovery fmt.(*pp).doPrintf(0xc420318000, 0x17df892, 0x34, 0xc420937e88, 0x3, 0x3)
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/fmt/print.go:996 +0x15a fp=0xc420937c88 sp=0xc420937b58 pc=0x4d2baa
istio-pilot-fd8fb6957-rd2j5 discovery fmt.Sprintf(0x17df892, 0x34, 0xc420937e88, 0x3, 0x3, 0x1532a00, 0xc42001e070)
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/fmt/print.go:196 +0x66 fp=0xc420937ce0 sp=0xc420937c88 pc=0x4cb0e6
istio-pilot-fd8fb6957-rd2j5 discovery istio.io/istio/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc4204664f8, 0x7fd08d94b800, 0x17df892, 0x34, 0xc420937e88, 0x3, 0x3, 0x0, 0x0, 0x0)
istio-pilot-fd8fb6957-rd2j5 discovery 	/workspace/go/src/istio.io/istio/vendor/go.uber.org/zap/sugar.go:230 +0x127 fp=0xc420937d30 sp=0xc420937ce0 pc=0x83dfb7
istio-pilot-fd8fb6957-rd2j5 discovery istio.io/istio/vendor/go.uber.org/zap.(*SugaredLogger).Infof(0xc4204664f8, 0x17df892, 0x34, 0xc420937e88, 0x3, 0x3)
istio-pilot-fd8fb6957-rd2j5 discovery 	/workspace/go/src/istio.io/istio/vendor/go.uber.org/zap/sugar.go:138 +0x83 fp=0xc420937d90 sp=0xc420937d30 pc=0x83d693
istio-pilot-fd8fb6957-rd2j5 discovery istio.io/istio/pkg/log.Infof(0x17df892, 0x34, 0xc420937e88, 0x3, 0x3)
istio-pilot-fd8fb6957-rd2j5 discovery 	/workspace/go/src/istio.io/istio/pkg/log/log.go:174 +0x5f fp=0xc420937dd0 sp=0xc420937d90 pc=0xa6b0bf
istio-pilot-fd8fb6957-rd2j5 discovery istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).removeEdsCon(0xc420394620, 0xc42026e270, 0x26, 0xc4208fc310, 0x64, 0xc420f32460)
istio-pilot-fd8fb6957-rd2j5 discovery 	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:521 +0x3b2 fp=0xc420937ec8 sp=0xc420937dd0 pc=0x128ec42
istio-pilot-fd8fb6957-rd2j5 discovery istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamEndpoints.func1(0xc4208ae180, 0x2226b40, 0xc420177130, 0xc420177150, 0xc4202642e0, 0x11, 0xc420f32460, 0xc420394620, 0xc420177140)
istio-pilot-fd8fb6957-rd2j5 discovery 	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:304 +0x247 fp=0xc420937f98 sp=0xc420937ec8 pc=0x1290ca7
istio-pilot-fd8fb6957-rd2j5 discovery runtime.goexit()
istio-pilot-fd8fb6957-rd2j5 discovery 	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420937fa0 sp=0xc420937f98 pc=0x45caf1
istio-pilot-fd8fb6957-rd2j5 discovery created by istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamEndpoints
istio-pilot-fd8fb6957-rd2j5 discovery 	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:296 +0x2a0
```

**Comment by ayj** [comment]
Looks like `edsClusterMutex` should be held when logging the edsClusters map.

```diff
diff --git a/pilot/pkg/proxy/envoy/v2/eds.go b/pilot/pkg/proxy/envoy/v2/eds.go
index e2e9e06f6..693a0a74e 100644
--- a/pilot/pkg/proxy/envoy/v2/eds.go
+++ b/pilot/pkg/proxy/envoy/v2/eds.go
@@ -475,8 +475,8 @@ func (s *DiscoveryServer) removeEdsCon(clusterName string, node string, connecti
        }
        delete(c.EdsClients, node)
        if len(c.EdsClients) == 0 {
-               log.Infof("EDS: remove unused cluster node=%s cluster=%s all=%v", node, clusterName, edsClusters)
                edsClusterMutex.Lock()
+               log.Infof("EDS: remove unused cluster node=%s cluster=%s all=%v", node, clusterName, edsClusters)
                defer edsClusterMutex.Unlock()
                delete(edsClusters, clusterName)
        }
```

**Comment by rlenglet** [comment]
I keep being hit by this in Pilot 0.7.1. It's fairly easy to reproduce by deleting and restarting pods repeatedly. That makes Pilot crash repeatedly and puts it into CrashloopBackoff.

**Comment by kyessenov** [comment]
@costinm was this fixed?

**Comment by rlenglet** [comment]
No, this is still as-is in master.

**Comment by costinm** [comment]
Should be fixed now.
