### ISSUE TITLE
Pruning removed resources[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed. 

### ISSUE THREAD

**Issue by jicki** [istio/istio#49579]
### Bug Description

componentStatus

```
✔ Ingress gateways installed
- Pruning removed resources[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
        >  goroutine 611 [running]:
        >  runtime/debug.Stack()
        >       runtime/debug/stack.go:24 +0x5e
        >  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
        >       sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/log.go:60 +0xcd
        >  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc000fd0440, 0x0?)
        >       sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/deleg.go:111 +0x32
        >  github.com/go-logr/logr.Logger.Info({{0x3603cc8?, 0xc000fd0440?}, 0xc0039d9fb0?}, {0x301e31f, 0x14}, {0x0, 0x0, 0x0})
        >       github.com/go-logr/logr@v1.3.0/logr.go:280 +0x72
        >  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000a66000, {0x35fdb48, 0xc000f90ff0}, {0x2be5280?, 0xc003a023a0?})
        >       sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:344 +0x505
        >  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000a66000, {0x35fdb48, 0xc000f90ff0})
        >       sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266 +0x1c9
        >  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        >       sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227 +0x79
        >  created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 85
        >       sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:223 +0x565


```

### Version

```Text
k8s version v1.22.15
istio version 1.20.3
```

**Comment by hanxiaop** [comment]
I think you will still get logs if you have a new reconcile loop, and this indeed doesn't affect your installation process.
