### ISSUE TITLE
Pilot panics when ENHANCED_RESOURCE_SCOPING is enabled

### ISSUE THREAD

**Issue by leosarra** [istio/istio#49786]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

While working on issue #49719, I found out that all integration suits fail when default scoping is enabled by default and a meshconfig update is received. This appears to be a regression introduced in #49262, **no Istio release is affected (only master branch is)**.

The reason behind this is that `GetGVR()` (called [here](https://github.com/istio/istio/pull/49262/files#diff-108602452df2cf3232cdbb2954b587a8fe5a5c64f3713879069835533d5c2307R323)) creates a zero object of the controllers.Object interface. Subsequently, during the type check in `getGVK()`, a nil value is encountered, leading to a panic in istiod due to an unknown type.

Here is the interesting part of the logs (with some extra debug msgs):
```
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:<nil>} for informer ic &{informer:0xc000ee51e0 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc000c04480 handler:{AddFunc:<nil> UpdateFunc:0x23d52e0 DeleteFunc:<nil>}}]} 
Type of T: kclient.informerClient[*k8s.io/api/core/v1.Namespace]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:<nil>} for informer ic &{informer:0xc000dc2210 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc000d946c0 handler:{AddFunc:0x2413ec0 UpdateFunc:0x2413e60 DeleteFunc:0x2413ec0}}]} 
Type of T: kclient.informerClient[*k8s.io/api/networking/v1.Ingress]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:<nil>} for informer ic &{informer:0xc000dc2370 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc000d94750 handler:{AddFunc:0x2413d20 UpdateFunc:0x2413c00 DeleteFunc:0x2413b60}}]} 
Type of T: kclient.informerClient[*k8s.io/api/core/v1.Service]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:<nil>} for informer ic &{informer:0xc000ee51e0 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc000a51290 handler:{AddFunc:0x23af8c0 UpdateFunc:0x23af720 DeleteFunc:0x23af5e0}}]} 
Type of T: kclient.informerClient[*k8s.io/api/core/v1.Namespace]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:<nil>} for informer ic &{informer:0xc000dc2370 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc000d2c000 handler:{AddFunc:0x23af3a0 UpdateFunc:0x23af200 DeleteFunc:0x23af0c0}}]} 
Type of T: kclient.informerClient[*k8s.io/api/core/v1.Service]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:<nil>} for informer ic &{informer:0xc000897970 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc000d2c090 handler:{AddFunc:0x23adce0 UpdateFunc:0x23adb40 DeleteFunc:0x23ada00}}]} 
Type of T: kclient.informerClient[*k8s.io/api/discovery/v1.EndpointSlice]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:0x21d0a40} for informer ic &{informer:0xc000b7af20 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc000d2c1b0 handler:{AddFunc:0x23ae960 UpdateFunc:0x23ae7c0 DeleteFunc:0x23ae680}}]} 
Type of T: kclient.informerClient[*k8s.io/api/core/v1.Pod]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:<nil>} for informer ic &{informer:0xc000dc2210 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc0015eb200 handler:{AddFunc:0x2419dc0 UpdateFunc:0x2419d60 DeleteFunc:0x2419dc0}}]} 
Type of T: kclient.informerClient[*k8s.io/api/networking/v1.Ingress]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:0x21d0a40} for informer ic &{informer:0xc000b7af20 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc000fae480 handler:{AddFunc:0x2419700 UpdateFunc:0x24196a0 DeleteFunc:0x2419700}}]} 
Type of T: kclient.informerClient[*k8s.io/api/core/v1.Pod]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:0xc000ed1d40 ObjectTransform:<nil>} for informer ic &{informer:0xc000dc2370 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc0015eb320 handler:{AddFunc:0x2419b20 UpdateFunc:0x2419ac0 DeleteFunc:0x2419b20}}]} 
Type of T: kclient.informerClient[*k8s.io/api/core/v1.Service]
Applying dynamic filter {LabelSelector: FieldSelector: Namespace: ObjectFilter:{filter:0xc000ed1d40 extra:[0x21fcf40]} ObjectTransform:<nil>} for informer ic &{informer:0xc000dc24d0 startInformer:0x21e36c0 filter:0x21e3720 handlerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:{_:{} v:1} readerWait:{_:{} v:0}} registeredHandlers:[{registration:0xc001784480 handler:{AddFunc:0x21ecb20 UpdateFunc:0x21ec920 DeleteFunc:0x21ec780}}]} 
Type of T: kclient.informerClient[istio.io/istio/pkg/kube/controllers.Object]
panic: Unknown type <nil>

goroutine 81 [running]:
istio.io/istio/pkg/config/schema/kubetypes.getGvk({0x0?, 0x0?})
	istio.io/istio/pkg/config/schema/kubetypes/resources.gen.go:151 +0x1825
istio.io/istio/pkg/config/schema/kubetypes.GetGVK[...](...)
	istio.io/istio/pkg/config/schema/kubetypes/common.go:38
istio.io/istio/pkg/config/schema/kubetypes.GetGVR[...]()
	istio.io/istio/pkg/config/schema/kubetypes/common.go:29 +0x3d
istio.io/istio/pkg/kube/kclient.applyDynamicFilter[...].func1(0xc0009527e0)
	istio.io/istio/pkg/kube/kclient/client.go:327 +0x1fe
istio.io/istio/pkg/kube/namespace.(*discoveryNamespacesFilter).notifyHandlersLocked(0xc000ed1d40, 0xc0009527b0, 0xc0009527e0)
	istio.io/istio/pkg/kube/namespace/filter.go:98 +0xf9
istio.io/istio/pkg/kube/namespace.(*discoveryNamespacesFilter).selectorsChanged(0xc000ed1d40, {0x0, 0x0, 0xc000952750?}, 0x1)
	istio.io/istio/pkg/kube/namespace/filter.go:170 +0x2ed
istio.io/istio/pkg/kube/namespace.NewDiscoveryNamespacesFilter.func1()
	istio.io/istio/pkg/kube/namespace/filter.go:55 +0x45
istio.io/istio/pkg/config/mesh.(*internalWatcher).handleMeshConfigInternal(0xc0006cb9a0, 0xc0007a8c88)
	istio.io/istio/pkg/config/mesh/watcher.go:224 +0x1ca
istio.io/istio/pkg/config/mesh.(*internalWatcher).HandleMeshConfig(0xc0006cb9f8?, 0x2f8f8ab?)
	istio.io/istio/pkg/config/mesh/watcher.go:203 +0x7d
istio.io/istio/pkg/config/mesh/kubemesh.NewConfigMapWatcher.func1(0xc001460120)
	istio.io/istio/pkg/config/mesh/kubemesh/watcher.go:54 +0x18f
istio.io/istio/pkg/kube/watcher/configmapwatcher.(*Controller).processItem(0xc000b34870, {{0xc0002cc630?, 0xc000bb2250?}, {0xc0002cc48b?, 0x0?}})
	istio.io/istio/pkg/kube/watcher/configmapwatcher/configmapwatcher.go:82 +0x51
istio.io/istio/pkg/kube/watcher/configmapwatcher.NewController.WithReconciler.func2.1({0x2c401e0?, 0xc0010820a0?})
	istio.io/istio/pkg/kube/controllers/queue.go:68 +0x42
istio.io/istio/pkg/kube/controllers.Queue.processNextItem({{0x34acb40, 0xc000316300}, 0xc000b2e298, {0xc000b2e2b0, 0xf}, 0x0, 0xc000b1e550, 0xc000b36120, 0xc000b34900})
	istio.io/istio/pkg/kube/controllers/queue.go:167 +0x18b
istio.io/istio/pkg/kube/controllers.Queue.Run.func1()
	istio.io/istio/pkg/kube/controllers/queue.go:116 +0x45
created by istio.io/istio/pkg/kube/controllers.Queue.Run in goroutine 51
	istio.io/istio/pkg/kube/controllers/queue.go:114 +0x185
```

### Version

```Text
client version: unknown
control plane version: 1.22-alpha.a2a31ec4c7203482471be9f783aa69af759c685f
data plane version: 1.22-alpha.a2a31ec4c7203482471be9f783aa69af759c685f (1 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by leosarra** [comment]
The current fix I have is the one contained in this commit https://github.com/istio/istio/pull/49719/commits/ec0e33e4f0ae2a281eed1d9e62b10ad04086c474 (don't mind the parenthesis, I will change them soon).
With these changes I check, if the type of the zero value is nil, I short-circuit and I don't go into GetGVR() preventing the panic.

**Comment by kfaseela** [comment]
We do have integration tests for this feature , any idea why that passes?

**Comment by leosarra** [comment]
The existing tests did trigger the crash once by updating the meshConfig but istiod recovered fast (and stopped crashing as there were no additional meshConfig updates), therefore there was "no impact" afterwards.
The security tests which made me aware of the issue triggered 2 meshConfig updates which led to multiple restarts and higher unavailability time due to crashloopbackoff -> webhooks failed for a longer period of time leading to test failure.

We could add some checks in existing tests to catch restarts of istiod and raise warnings.

**Comment by leosarra** [comment]
Thank you @howardjohn for looking into it as well.
For sure your fix will be better than the mine which relied on reflection :)

**Comment by kfaseela** [comment]
Thanks @leosarra and @howardjohn !
