### ISSUE TITLE
Pilot goroutine leak and memory leak

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#51838]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Might be related with https://github.com/istio/istio/issues/10822
<img width="1716" alt="Screenshot 2024-07-02 at 08 48 48" src="https://github.com/istio/istio/assets/12857255/44d862d5-8aac-4036-9674-0d8db5561d4a">

istiod goroutine pprof
```
goroutine 5543977867 [sync.Mutex.Lock, 11 minutes]:
sync.runtime_SemacquireMutex(0x47a5a5?, 0x0?, 0xc187b65f50?)
  runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc0014d70d0)
  sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(0x3388120?)
  sync/mutex.go:90 +0x3b
istio.io/istio/pilot/pkg/xds.(*PushQueue).Enqueue(0xc000bf2fc0, 0xc178f6e3c0, 0xc14829acc0)
  istio.io/istio/pilot/pkg/xds/pushqueue.go:52 +0x54
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).startPush(0xc001495900, 0xc14829acc0)
  istio.io/istio/pilot/pkg/xds/ads.go:874 +0x155
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).AdsPushAll(0x0?, {0xc1786d8de0, 0x1b}, 0xc14829acc0)
  istio.io/istio/pilot/pkg/xds/ads.go:860 +0x18b
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Push(0x17fa500?, 0xc14829acc0)
  istio.io/istio/pilot/pkg/xds/discovery.go:284 +0x355
istio.io/istio/pilot/pkg/xds.debounce.func3(0xc0001a3788?)
  istio.io/istio/pilot/pkg/xds/discovery.go:411 +0x26
created by istio.io/istio/pilot/pkg/xds.debounce
  istio.io/istio/pilot/pkg/xds/discovery.go:410 +0x69b

goroutine 5543977868 [sync.Mutex.Lock, 11 minutes]:
sync.runtime_SemacquireMutex(0x47a5a5?, 0x0?, 0xc187b65f80?)
  runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc0014d70d0)
  sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(0x3388120?)
  sync/mutex.go:90 +0x3b
istio.io/istio/pilot/pkg/xds.(*PushQueue).Enqueue(0xc000bf2fc0, 0xc14c71b040, 0xc14829ad20)
  istio.io/istio/pilot/pkg/xds/pushqueue.go:52 +0x54
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).startPush(0xc001495900, 0xc14829ad20)
  istio.io/istio/pilot/pkg/xds/ads.go:874 +0x155
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).AdsPushAll(0x0?, {0xc1786d8de0, 0x1b}, 0xc14829ad20)
  istio.io/istio/pilot/pkg/xds/ads.go:860 +0x18b
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Push(0x97b0de?, 0xc14829ad20)
  istio.io/istio/pilot/pkg/xds/discovery.go:284 +0x355
istio.io/istio/pilot/pkg/xds.debounce.func3(0x0?)
  istio.io/istio/pilot/pkg/xds/discovery.go:411 +0x26
created by istio.io/istio/pilot/pkg/xds.debounce
  istio.io/istio/pilot/pkg/xds/discovery.go:410 +0x69b

goroutine 5543977961 [sync.Mutex.Lock, 11 minutes]:
sync.runtime_SemacquireMutex(0x47a5a5?, 0x0?, 0xc144745e60?)
  runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc0014d70d0)
  sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(0x3388120?)
  sync/mutex.go:90 +0x3b
istio.io/istio/pilot/pkg/xds.(*PushQueue).Enqueue(0xc000bf2fc0, 0xc123384460, 0xc0ff428c60)
  istio.io/istio/pilot/pkg/xds/pushqueue.go:52 +0x54
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).startPush(0xc001495900, 0xc0ff428c60)
  istio.io/istio/pilot/pkg/xds/ads.go:874 +0x155
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).AdsPushAll(0xc092d6b320?, {0xc1786d8de0, 0x1b}, 0xc0ff428c60)
  istio.io/istio/pilot/pkg/xds/ads.go:860 +0x18b
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Push(0xc151fb8260?, 0xc0ff428c60)
  istio.io/istio/pilot/pkg/xds/discovery.go:284 +0x355
istio.io/istio/pilot/pkg/xds.debounce.func3(0xc1af235740?)
  istio.io/istio/pilot/pkg/xds/discovery.go:411 +0x26
created by istio.io/istio/pilot/pkg/xds.debounce
  istio.io/istio/pilot/pkg/xds/discovery.go:410 +0x69b

goroutine 5543978029 [sync.Mutex.Lock, 11 minutes]:
sync.runtime_SemacquireMutex(0x47a5a5?, 0x0?, 0xc0936f0330?)
  runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc0014d70d0)
  sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(0x3388120?)
  sync/mutex.go:90 +0x3b
istio.io/istio/pilot/pkg/xds.(*PushQueue).Enqueue(0xc000bf2fc0, 0xc078282500, 0xc16e52fe00)
  istio.io/istio/pilot/pkg/xds/pushqueue.go:52 +0x54
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).startPush(0xc001495900, 0xc16e52fe00)
  istio.io/istio/pilot/pkg/xds/ads.go:874 +0x155
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).AdsPushAll(0x0?, {0xc1786d8de0, 0x1b}, 0xc16e52fe00)
  istio.io/istio/pilot/pkg/xds/ads.go:860 +0x18b
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Push(0x17fa500?, 0xc16e52fe00)
  istio.io/istio/pilot/pkg/xds/discovery.go:284 +0x355
istio.io/istio/pilot/pkg/xds.debounce.func3(0xc00195ff88?)
  istio.io/istio/pilot/pkg/xds/discovery.go:411 +0x26
created by istio.io/istio/pilot/pkg/xds.debounce
  istio.io/istio/pilot/pkg/xds/discovery.go:410 +0x69b

goroutine 5543978030 [sync.Mutex.Lock, 11 minutes]:
sync.runtime_SemacquireMutex(0x47a5a5?, 0x0?, 0xc0936f0360?)
  runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc0014d70d0)
  sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(0x3388120?)
  sync/mutex.go:90 +0x3b
istio.io/istio/pilot/pkg/xds.(*PushQueue).Enqueue(0xc000bf2fc0, 0xc0db94f400, 0xc16e52fe60)
  istio.io/istio/pilot/pkg/xds/pushqueue.go:52 +0x54
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).startPush(0xc001495900, 0xc16e52fe60)
  istio.io/istio/pilot/pkg/xds/ads.go:874 +0x155
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).AdsPushAll(0xc0dde60a20?, {0xc1786d8de0, 0x1b}, 0xc16e52fe60)
  istio.io/istio/pilot/pkg/xds/ads.go:860 +0x18b
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Push(0xc11fc0c050?, 0xc16e52fe60)
  istio.io/istio/pilot/pkg/xds/discovery.go:284 +0x355
istio.io/istio/pilot/pkg/xds.debounce.func3(0xc0e6cf4240?)
  istio.io/istio/pilot/pkg/xds/discovery.go:411 +0x26
created by istio.io/istio/pilot/pkg/xds.debounce
  istio.io/istio/pilot/pkg/xds/discovery.go:410 +0x69b
```

istiod log
```
24-07-01T07:54:32Z/117029
2024-07-02T00:52:17.368574Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:444 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.369628Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:444 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.374608Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:444 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.456728Z info  ads ADS: new connection for node:idgensvccont-6c9dfcf7f7-9z4gt.idgensvc-staging-2-538320
2024-07-02T00:52:17.457295Z info  ads CDS: PUSH request for node:idgensvccont-6c9dfcf7f7-9z4gt.idgensvc-staging-2 resources:7 size:4.4kB cached:0/2
2024-07-02T00:52:17.457728Z info  ads EDS: PUSH request for node:idgensvccont-6c9dfcf7f7-9z4gt.idgensvc-staging-2 resources:2 size:1.1kB empty:0 cached:0/2
2024-07-02T00:52:17.459765Z info  ads LDS: PUSH request for node:idgensvccont-6c9dfcf7f7-9z4gt.idgensvc-staging-2 resources:3 size:33.1kB
2024-07-02T00:52:17.459852Z info  ads NDS: PUSH request for node:idgensvccont-6c9dfcf7f7-9z4gt.idgensvc-staging-2 resources:1 size:264B
2024-07-02T00:52:17.460035Z info  ads RDS: PUSH request for node:idgensvccont-6c9dfcf7f7-9z4gt.idgensvc-staging-2 resources:1 size:1.4kB cached:0/1
2024-07-02T00:52:17.474779Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.505573Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.523199Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.756057Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.756069Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.756349Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.757017Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.860139Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.887491Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:17.906892Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:18.028673Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
2024-07-02T00:52:18.127666Z info  ads XDS: Incremental Pushing:2024-07-01T07:54:32Z/117029 ConnectedEndpoints:445 Version:2024-07-01T07:54:32Z/117029
```

### Version

```Text
istio 1.17
```

**Comment by zirain** [comment]
1.17 is EOL for a long time, please upgrade to support versions and try to reproduce.

**Comment by hzxuzhonghu** [comment]
Is this still on 1.22?

**Comment by shonecyx** [comment]
I think the ads push code didn't change much for the AdsPushAll, so smilar issue might still be there in latest version. BTW we are going to upgrade to 1.20 soon.

**Comment by zirain** [comment]
> I think the ads push code didn't change much for the AdsPushAll, so smilar issue might still be there in latest version. BTW we are going to upgrade to 1.20 soon.

1.20 is EOL now!

**Comment by howardjohn** [comment]
The goroutine dump showing 3 goroutines is not helpful, can you get the full one?

BTW you can also visualize it as a flamegraph, so if there are 800k goroutines it should be very obvious where they are.

**Comment by shonecyx** [comment]
> The goroutine dump showing 3 goroutines is not helpful, can you get the full one?
> 
> BTW you can also visualize it as a flamegraph, so if there are 800k goroutines it should be very obvious where they are.

@howardjohn   Here is the goroutine pprof, I didn't check the flamegraph(will check next time) and the istiod pod was deleted:
[istiod goroutine dump.txt](https://github.com/user-attachments/files/16076425/istiod.goroutine.dump.txt)

**Comment by hzxuzhonghu** [comment]
22827 Enqueue blocking goroutines.  Seems like blocking on the lock.

How many xds connections do you have?

**Comment by howardjohn** [comment]
How do you even start 22827 pushes? They should be one at a time: https://github.com/istio/istio/blob/e7c4fb50422eaa104487446d53ec906a03b838ab/pilot/pkg/xds/discovery.go#L369.

Looks like you maybe use unstable PILOT_ENABLE_EDS_DEBOUNCE=false feature flag.

I think its not a deadlock probably, you can see there is one goroutine that is inside the mutex 

```
    model             push_context.go:483                 (*PushRequest).CopyMerge(#15489, #14883)
    xds               pushqueue.go:66                     (*PushQueue).Enqueue(#507, #46487, #14883)
    xds               ads.go:874                          (*DiscoveryServer).startPush(#830, #14883)
    xds               ads.go:860                          (*DiscoveryServer).AdsPushAll(#54418, {#48516, 0x1b}, #14883)
    xds               discovery.go:284                    (*DiscoveryServer).Push(0, #14883)
```

Probably because you set the PILOT_ENABLE_EDS_DEBOUNCE flag, backpressure is disabled. So you have an infinitely growing backlog of work to complete, and the work grows faster than you can process it.

**Comment by shonecyx** [comment]
Thanks @howardjohn  I think it should be the case. We disabled PILOT_ENABLE_EDS_DEBOUNCE flag to speed up the EDS push as per the suggestion since we got the issue if the deploy maxSurge is 100% we saw some 503 in data plane for few seconds, but seems this has the downside
https://github.com/istio/istio/issues/14283#issuecomment-521816797

**Comment by howardjohn** [comment]
Might be good to get a COU profile (without PILOT_ENABLE_EDS_DEBOUNCE) to see why the pushing is so slow

**Comment by howardjohn** [comment]
@shonecyx did you get a chance to profile without PILOT_ENABLE_EDS_DEBOUNCE?

**Comment by shonecyx** [comment]
Re-dumped the goroutine profile without PILOT_ENABLE_EDS_DEBOUNCE, and it looks stablized now. Seems if there is high pod/endpoint churn in mesh, it can lead to goroutine leak with PILOT_ENABLE_EDS_DEBOUNCE

![Screenshot 2024-08-01 at 15 26 14](https://github.com/user-attachments/assets/7be3d76f-8cfd-482e-a41c-1c6787de30c9)

[istiod goroutine(without PILOT_ENABLE_EDS_DEBOUNCE).txt](https://github.com/user-attachments/files/16451795/istiod.goroutine.without.PILOT_ENABLE_EDS_DEBOUNCE.txt)

Meanwhile here is the cpu profile without PILOT_ENABLE_EDS_DEBOUNCE and we need to chery-pick this one and re-profile: https://github.com/istio/istio/issues/47216
![Screenshot 2024-08-01 at 15 30 09](https://github.com/user-attachments/assets/1e320bb9-9bf3-4902-8031-439000df7e3c)

**Comment by howardjohn** [comment]
TBH I don't think its worth much investing so much time profiling Istio 1.17. We have made 2 years of performance improvements since then...

**Comment by shonecyx** [comment]
Thanks, Let me re-profile after upgrade to 1.20, closing this issue for now.
