### ISSUE TITLE
Istio (or Envoy?) uses invalid non-LDH characters in SNI hostname

### ISSUE THREAD

**Issue by cfredri4** [istio/istio#52004]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

Feel free to close this if considered a non-issue, or if it's an issue with Envoy and not Istio.

Here's the setup:

I'm doing a version of a proxyless gRPC Java server together with Istio.
On client side I configure a normal plaintext gRPC channel, which is intercepted by client-side Istio proxy and sent over TLS to server.
On server side I _bypass_ the server-side Istio proxy and instead configure the gRPC server like a normal TLS server but using Istio proxy's certificates.
I.e. like this:
`Plaintext client channel -> client-side Istio proxy (does TLS) -> server with TLS using Istio proxy's certificates
`
But the OpenJDK TLS implementation on server throws the below error (on debug) and client-side istio proxy fails to connect. It looks like the client-side Istio proxy sends something "interesting" (and invalid) as SNI.

Can/should this be fixed to only use valid characters? 

```
Caused by: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLProtocolException: Illegal server name, type=host_name(0), name=outbound_.9090_._.my-app.my-namespace.svc.cluster.local, value={6F7574626F756E645F2E393039305F2E5F2E6D792D6170702E6D792D6E616D6573706163652E7376632E636C75737465722E6C6F63616C}
at io.netty.handler.ssl.SslHandler$SslTasksRunner.wrapIfNeeded(SslHandler.java:1756)
... 13 common frames omitted
Caused by: javax.net.ssl.SSLProtocolException: Illegal server name, type=host_name(0), name=outbound_.9090_._.my-app.my-namespace.svc.cluster.local, value={6F7574626F756E645F2E393039305F2E5F2E6D792D6170702E6D792D6E616D6573706163652E7376632E636C75737465722E6C6F63616C}
at java.base/sun.security.ssl.ServerNameExtension$CHServerNamesSpec.<init>(Unknown Source)
at java.base/sun.security.ssl.ServerNameExtension$CHServerNameConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.SSLExtension.consumeOnLoad(Unknown Source)
at java.base/sun.security.ssl.SSLExtensions.consumeOnLoad(Unknown Source)
at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(Unknown Source)
at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
at io.netty.handler.ssl.SslHandler$SslTasksRunner.run(SslHandler.java:1887)
at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(Unknown Source)
at java.base/java.lang.VirtualThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: The encoded server name value is invalid
at java.base/javax.net.ssl.SNIHostName.<init>(Unknown Source)
... 16 common frames omitted
Caused by: java.lang.IllegalArgumentException: Contains non-LDH ASCII characters
at java.base/java.net.IDN.toASCIIInternal(Unknown Source)
at java.base/java.net.IDN.toASCII(Unknown Source)
... 17 common frames omitted
```

### Version

Istio 1.18 everywhere

**Comment by howardjohn** [comment]
I'm 95% sure these are valid in sni and java is wrong here. Would have to double check the RFC. But my recollection is it's a valid SNI but not a valid HTTP hostname (but we don't use it as an http hostname)

**Comment by keithmattix** [comment]
This seems like a bug for sure. I'm not sure if the RFC changed or if we're sending the wrong host name but I'll try and take a look. /cc @ramaraochavali @howardjohn @hzxuzhonghu

**Comment by keithmattix** [comment]
> I'm 95% sure these are valid in sni and java is wrong here. Would have to double check the RFC. But my recollection is it's a valid SNI but not a valid HTTP hostname (but we don't use it as an http hostname)

This issue lays out the RFCs fairly clearly (though the deeper discussion is unrelated): https://github.com/w3c/openscreenprotocol/issues/275.

I think the TLS spec was less defined originally but became more strict in 2011 from what I could find.

**Comment by howardjohn** [comment]
@keithmattix are you saying it is illegal to send these? 

Tbh if it is we are in a tricky situation. The entire point of the format is that it is NOT a valid domain name so we can delimit from the hostname (exactly like ; in the stat prefix). Not to mention back compat

**Comment by keithmattix** [comment]
@howardjohn i need to do some more digging but yeah I have similar concerns. The TLS/SNI spec was originally less restrictive as far as I saw. Then I think it changed in 2011

**Comment by keithmattix** [comment]
Ok, so I don't think this is really a supported use-case; the SNI that Istio sidecar clients use is an internal, non-compliant format because we're not using it as true SNI. To achieve this though, you could theoretically create a `DestinationRule` for the server host, set the tls settings mode to ISTIO_MUTUAL and set sni to a similar, valid value. See the docs [here](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings).

**Comment by cfredri4** [comment]
The issue will occur for the [proxyless gRPC](https://istio.io/latest/blog/2021/proxyless-grpc) use-case in Java, if you use OpenJDK TLS, but maybe that's a bit experimental?

**Comment by keithmattix** [comment]
Yeah all of proxyless gRPC is fairly experimental

**Comment by howardjohn** [comment]
I am still not 100% convinced this is violating the TLS spec, and not just Java being overly strict, but doesn't matter much.

Ultimately, after some discussion with @keithmattix :

* Changing this is very hard due to backwards compatibility
* We still need a delineator that is an illegal character in a hostname but legal in SNI. I don't know of any other than `_`, and if there isn't one our entire scheme is broken
* This is fixed with HBONE eventually (technically its "now", just not used everywhere)
* This can be workaround with an explicitly DR to set the SNI
* This is basically our internal protocol

Based on all of this, I don't really see what we can do. I recommend overriding with DR.

**Comment by cfredri4** [comment]
Thank you for the interesting discussion. That's a totally acceptable workaround.
