### ISSUE TITLE
NullPointerException of netflixoss/eureka:1.3.1

### ISSUE THREAD

**Issue by ccx1024cc** [istio/istio#5243]
hi, guys. I am trying istio1.7.1 on eureka.
First, i find that the rating service not accessable after removing the abort rule for bookinfo sample.
And  i see this log in container which start from image netflixoss/eureka:1.3.1:
...
2018-04-26 14:22:25,234 WARN  com.netflix.discovery.endpoint.EndpointUtils:364 [DiscoveryClient-0] [getZoneOffset] DISCOVERY: Could not pick a zone based on preferred zone settings. My zone - defaultZone, preferSameZone- false. Defaulting to defaultZone
2018-04-26 14:22:34,357 INFO  com.netflix.eureka.registry.PeerAwareInstanceRegistryImpl:525 [ReplicaAwareInstanceRegistry - RenewalThresholdUpdater] [updateRenewalThreshold] Current renewal threshold is : 8
2018-04-26 14:22:34,452 ERROR com.netflix.discovery.DiscoveryClient:1033 [pool-6-thread-1] [fetchRegistry] DiscoveryClient_EUREKA/97a4f14415ca - was unable to refresh its cache! status = null
java.lang.NullPointerException
	at com.netflix.discovery.InstanceRegionChecker.getInstanceRegion(InstanceRegionChecker.java:24)
	at com.netflix.discovery.DiscoveryClient.updateDelta(DiscoveryClient.java:1302)
	at com.netflix.discovery.DiscoveryClient.getAndUpdateDelta(DiscoveryClient.java:1183)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:1028)
	at com.netflix.discovery.DiscoveryClient.access$2000(DiscoveryClient.java:123)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1870)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-26 14:23:04,457 ERROR com.netflix.discovery.DiscoveryClient:1033 [pool-6-thread-1] [fetchRegistry] DiscoveryClient_EUREKA/97a4f14415ca - was unable to refresh its cache! status = null
java.lang.NullPointerException
	at com.netflix.discovery.InstanceRegionChecker.getInstanceRegion(InstanceRegionChecker.java:24)
	at com.netflix.discovery.DiscoveryClient.updateDelta(DiscoveryClient.java:1302)
	at com.netflix.discovery.DiscoveryClient.getAndUpdateDelta(DiscoveryClient.java:1183)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:1028)
	at com.netflix.discovery.DiscoveryClient.access$2000(DiscoveryClient.java:123)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1870)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-26 14:23:34,461 WARN  com.netflix.discovery.DiscoveryClient:1234 [pool-6-thread-1] [reconcileAndLogDifference] The Reconcile hashcodes do not match, client : UP_5_, server : UP_11_. Getting the full registry
2018-04-26 14:23:34,467 WARN  com.netflix.discovery.shared.Applications:290 [pool-6-thread-1] [getReconcileMapDiff] The application %s is not found in local cache :
2018-04-26 14:23:34,467 WARN  com.netflix.discovery.shared.Applications:290 [pool-6-thread-1] [getReconcileMapDiff] The application %s is not found in local cache :
2018-04-26 14:23:34,467 WARN  com.netflix.discovery.shared.Applications:290 [pool-6-thread-1] [getReconcileMapDiff] The application %s is not found in local cache :
2018-04-26 14:23:34,468 WARN  com.netflix.discovery.shared.Applications:290 [pool-6-thread-1] [getReconcileMapDiff] The application %s is not found in local cache :
2018-04-26 14:23:34,468 WARN  com.netflix.discovery.DiscoveryClient:1272 [pool-6-thread-1] [reconcileAndLogDifference] The reconcile string is 
2018-04-26 14:23:34,468 WARN  com.netflix.discovery.DiscoveryClient:1280 [pool-6-thread-1] [reconcileAndLogDifference] The Reconcile hashcodes after complete sync up, client : UP_11_, server : UP_11_.
...

maybe it's a bug or wrong operation caused? Help please~~~~

**Comment by andraxylia** [comment]
@ccx1024cc could you please try with release 0.8?
