### ISSUE TITLE
istioctl analyze panic when vs.spec.routes[].destinations[0].destination null

### ISSUE THREAD

**Issue by nicole-lihui** [istio/istio#52806]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description
```bash
$ istioctl analyze -o json --kubeconfig /var/folders/r1/bjz5dqvs7b52krd7_8rrsm200000gn/T/kubeconfig-3826814466 /var/folders/r1/bjz5dqvs7b52krd7_8rrsm200000gn/T/istio-analyze-1064534466.yaml -n default
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x1048a1a9c]

goroutine 1 [running]:
istio.io/istio/pkg/config/analysis/analyzers/virtualservice.initVirtualServiceDestinations.func1(0x14000afc000)
	istio.io/istio/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go:104 +0xac
istio.io/istio/pkg/config/analysis/local.(*istiodContext).ForEach(0x14001a19880, {{0x104a46b39, 0x13}, {0x104a28927, 0x8}, {0x104a37d52, 0xe}}, 0x140014b57b0)
	istio.io/istio/pkg/config/analysis/local/context.go:138 +0x118
istio.io/istio/pkg/config/analysis/analyzers/virtualservice.initVirtualServiceDestinations({0x105adf160, 0x14001a19880})
	istio.io/istio/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go:99 +0xa8
istio.io/istio/pkg/config/analysis/analyzers/virtualservice.(*DestinationHostAnalyzer).Analyze(0x107b1eb20, {0x105adf160, 0x14001a19880})
	istio.io/istio/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go:56 +0x40
istio.io/istio/pkg/config/analysis.(*InternalCombinedAnalyzer).Analyze(0x14000cebb00, {0x105adf160, 0x14001a19880})
	istio.io/istio/pkg/config/analysis/analyzer.go:83 +0xc4
istio.io/istio/pkg/config/analysis/local.(*IstiodAnalyzer).internalAnalyze(0x14000a00000, {0x105ada9a0, 0x14000cebb00}, 0x140005f5920)
	istio.io/istio/pkg/config/analysis/local/istiod_analyze.go:162 +0x404
istio.io/istio/pkg/config/analysis/local.(*IstiodAnalyzer).ReAnalyze(...)
	istio.io/istio/pkg/config/analysis/local/istiod_analyze.go:138
istio.io/istio/pkg/config/analysis/local.(*IstiodAnalyzer).Analyze(0x14000a00000, 0x140005f5920)
	istio.io/istio/pkg/config/analysis/local/istiod_analyze.go:187 +0xb0
istio.io/istio/istioctl/pkg/analyze.Analyze.func1(0x14000b54008, {0x14000bdf180, 0x1, 0x7})
	istio.io/istio/istioctl/pkg/analyze/analyze.go:233 +0xbd4
github.com/spf13/cobra.(*Command).execute(0x14000b54008, {0x14000bdf110, 0x7, 0x7})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000797b08)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(0x1400006e6d0?)
	github.com/spf13/cobra@v1.8.0/command.go:1039 +0x1c
main.main()
	istio.io/istio/istioctl/cmd/istioctl/main.go:39 +0xd0
$ cat /var/folders/r1/bjz5dqvs7b52krd7_8rrsm200000gn/T/istio-analyze-1064534466.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    mspider.io/istio-synced-hash: hmWdGVTR
    mspider.io/origin-cluster: mspider-dedicated
    mspider.io/synced-from: worker-synchronizer
  name: test
  namespace: default
spec:
  gateways:
    - default/my-gateway
  hosts:
    - '*'
  http:
    - route:
        - {}
        - destination:
            host: productpage.default.svc.cluster.local
            port:
              number: 9080
status: {}
```
### Version

```Text
$ istioctl version  --kubeconfig /var/folders/r1/bjz5dqvs7b52krd7_8rrsm200000gn/T/kubeconfig-3826814466
client version: 1.23.0
control plane version: 1.22.2-mspider
data plane version: 1.20.8-mspider (1 proxies), 1.21.4-mspider (1 proxies), 1.22.2-mspider (12 proxies)
```

**Comment by thiagogcm** [comment]
I'm also getting a similar panic on 1.23 with analysis enabled:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x26ae641]
goroutine 1038 [running]:
istio.io/istio/pkg/config/analysis/incluster.NewController.func2(0xc006e47c00?, {0x29d0660?, 0xc0075080a8?})
	istio.io/istio/pkg/config/analysis/incluster/controller.go:77 +0x41
istio.io/istio/pkg/config/analysis/incluster.NewController.(*Manager).CreateIstioStatusController.func3({0x0?, 0x0?}, {0x29d0660?, 0xc0075080a8?})
	istio.io/istio/pilot/pkg/status/manager.go:97 +0x51
istio.io/istio/pilot/pkg/status.(*WorkerPool).maybeAddWorker.func1()
	istio.io/istio/pilot/pkg/status/resourcelock.go:214 +0x60e
created by istio.io/istio/pilot/pkg/status.(*WorkerPool).maybeAddWorker in goroutine 1037
	istio.io/istio/pilot/pkg/status/resourcelock.go:182 +0x105
```

**Comment by MorrisLaw** [comment]
> I'm also getting a similar panic on 1.23 with analysis enabled:
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x26ae641]
> goroutine 1038 [running]:
> istio.io/istio/pkg/config/analysis/incluster.NewController.func2(0xc006e47c00?, {0x29d0660?, 0xc0075080a8?})
> 	istio.io/istio/pkg/config/analysis/incluster/controller.go:77 +0x41
> istio.io/istio/pkg/config/analysis/incluster.NewController.(*Manager).CreateIstioStatusController.func3({0x0?, 0x0?}, {0x29d0660?, 0xc0075080a8?})
> 	istio.io/istio/pilot/pkg/status/manager.go:97 +0x51
> istio.io/istio/pilot/pkg/status.(*WorkerPool).maybeAddWorker.func1()
> 	istio.io/istio/pilot/pkg/status/resourcelock.go:214 +0x60e
> created by istio.io/istio/pilot/pkg/status.(*WorkerPool).maybeAddWorker in goroutine 1037
> 	istio.io/istio/pilot/pkg/status/resourcelock.go:182 +0x105
> ```

I don't think this is similar, this looks very similar to a previous issue that should be fixed now: https://github.com/istio/istio/pull/52566

The panic occurred when analysis was enabled _and_ a ServiceEntry was added with TCP protocol set but without an address. This was handled improperly in the code and was surfaced as this nil panic despite it being a valid issue that the analyzer should have shown to the user (see [here](https://istio.io/latest/docs/reference/config/analysis/ist0134/)).

Does this match what you did to get this error or were you doing something else?

**Comment by thiagogcm** [comment]
@MorrisLaw you're right! sorry for the confusion.
