### ISSUE TITLE
[Mix] [Ambient] [Sidecar] Init container has been failed when the jenkins's pod enable sidecar mode in ambient mesh

### ISSUE THREAD

**Issue by laiminhtrung1997** [istio/istio#53150]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have to configure the Jenkins to enable sidecar mode to run inside the ambient mesh. The pod has an init container `config-reload-init` that calls the K8S service to get the config map and has the error message below.

```
/usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.0) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[2024-09-16 06:01:35] Starting collector
[2024-09-16 06:01:35] No folder annotation was provided, defaulting to k8s-sidecar-target-directory
[2024-09-16 06:01:35] Selected resource type: ('configmap',)
[2024-09-16 06:01:35] Config for cluster api loaded...
[2024-09-16 06:01:35] Unique filenames will not be enforced.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 352, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 181, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2b2deb6490>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sidecar.py", line 73, in <module>
    main()
  File "/app/sidecar.py", line 66, in main
    currentNamespace, folderAnnotation, res, uniqueFilenames)
  File "/app/resources.py", line 70, in listResources
    ret = getattr(v1, _list_namespaced[resource])(namespace=namespace, label_selector=labelSelector)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 14507, in list_namespaced_config_map
    return self.list_namespaced_config_map_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 14632, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 216, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 75, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ab.xyz.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/service/configmaps?labelSelector=jenkins-jenkins-config (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2b2deb6490>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I have configured the global network policies that block all inbound and outbound traffic, allowing the CIDR ipv4 of the cluster. 

```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  creationTimestamp: "2024-09-16T04:50:00Z"
  generation: 1
  name: global-network-policy-deny-all
  resourceVersion: "1731"
  uid: 414e2e64-2110-489b-97d8-fa69a586ee0a
spec:
  types:
  - Ingress
  - Egress
```

```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  creationTimestamp: "2024-09-16T04:50:00Z"
  generation: 2
  name: tenants
  resourceVersion: "33225"
  uid: 6c6aea85-2108-4675-94f3-80c84556bf98
spec:
  egress:
  - action: Allow
    destination:
      nets:
      - <VPC CIDR>
      - ab.xyz.0.0/16
    protocol: TCP
  ingress:
  - action: Allow
    destination:
      ports:
      - 15008
    protocol: TCP
  namespaceSelector: has(tenant)
  types:
  - Ingress
  - Egress
```

### Version

```Text
$ istioctl version
client version: 1.24-alpha.b957e7bd33d4db0023865d3f3f00b639f14665e5
control plane version: 1.24-alpha.b957e7bd33d4db0023865d3f3f00b639f14665e5
data plane version: 1.24-alpha.b957e7bd33d4db0023865d3f3f00b639f14665e5 (9 proxies)
```

**Comment by howardjohn** [comment]
Is the init container on the pod with a sidecar? If so I think this is https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers

**Comment by laiminhtrung1997** [comment]
Added uid 1337 to jenkins initContainer then the issue is gone. Thanks so much @howardjohn

**Comment by laiminhtrung1997** [comment]
Dear @howardjohn 
I use a sidecar mod in Envoy that makes the initContainer `preprocess-config` fail with this message below
```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/community: temporary error (try again later)
ERROR: unable to select packages:
  perl (no such package):
    required by: world[perl]
```

When I configured the initContainer to run as uid 1337 following your document, a new error occurred with the message below
```
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

I tried configuring the initContainer to run as uid 1337 and with root privileges but it still failed.
