### ISSUE TITLE
multicluster: crash on concurrent map read and map write

### ISSUE THREAD

**Issue by sschepens** [istio/istio#53289]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Even though this is a crashing bug, this should not be a security issue.

We sometimes get pod crashes in our setup which uses a multicluster with lots of clusters. This is happening in Istio 1.22.5 and not on Istio 1.21. 

This is a crash log I got today (logs may be unordered since they have the exact same timestamp):
```
fatal error: concurrent map read and map write
goroutine 1687 [running]:
istio.io/istio/pkg/monitoring.(*gauge).With(0xc0000e2720, {0xc00be68200?, 0xc00d6979c0?, 0x46fd45?})
istio.io/istio/pkg/monitoring/gauge.go:87 +0x18e
istio.io/istio/pkg/queue.newQueueMetrics({0xc0014e4f78, 0x16})
istio.io/istio/pkg/queue/metrics.go:56 +0x188
istio.io/istio/pkg/queue.NewQueueWithID(0x3b9aca00, {0xc0014e4f78, 0x16})
istio.io/istio/pkg/queue/instance.go:81 +0xb5
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.NewController({0x378b7d0, 0xc005c8b680}, {{0xc00007e08e, 0xf}, 0xc000ba2fd0, {0x7ffcaecf8373, 0xd}, {0xc0014e4f78, 0x16}, 0xc0007fed20, ...})
istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:238 +0x4a
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.NewMulticluster.func1(0xc00247c5a0)
istio.io/istio/pilot/pkg/serviceregistry/kube/controller/multicluster.go:139 +0x1c8
istio.io/istio/pkg/kube/multicluster.(*Component[...]).clusterAdded(0x3793e00, 0xc00247c5a0)
istio.io/istio/pkg/kube/multicluster/component.go:56 +0x3f
istio.io/istio/pkg/kube/multicluster.(*Cluster).Run(0xc00247c5a0, {0x3769388, 0xc0008daf50}, {0xc001925740, 0x2, 0x0?}, 0x0)
istio.io/istio/pkg/kube/multicluster/cluster.go:90 +0x2ae
istio.io/istio/pkg/kube/multicluster.(*Controller).addSecret.func1()
istio.io/istio/pkg/kube/multicluster/secretcontroller.go:304 +0x45
created by istio.io/istio/pkg/kube/multicluster.(*Controller).addSecret in goroutine 60
istio.io/istio/pkg/kube/multicluster/secretcontroller.go:303 +0x60b
```

There's a whole dump of other goroutines but I think should not be necessary. From what I can tell the issue is [here](https://github.com/istio/istio/blob/1.22.5/pkg/monitoring/gauge.go#L87-L91) and we're actually writing on the parent's `attributeSets` without obtaining the lock, and in this case, there could be concurrent metrics being created with different labels.

### Version

```Text
istio 1.22.5
```

**Comment by howardjohn** [comment]
yeah I guess we can probably do that, was concerned it was maybe risky, but now 1.23 has released and haven't seen any issues

**Comment by keithmattix** [comment]
Not stale
