### ISSUE TITLE
1.23 Istiod Crash

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#53874]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Running Istio 1.23 and the istiod is crashing with this log.
```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x26cba81]
goroutine 755 [running]:
istio.io/istio/pkg/config/analysis/incluster.NewController.func2(0xc00520bc00?, {0x29eee60?, 0xc002f483c0?})
	istio.io/istio/pkg/config/analysis/incluster/controller.go:77 +0x41
istio.io/istio/pkg/config/analysis/incluster.NewController.(*Manager).CreateIstioStatusController.func3({0x0?, 0x0?}, {0x29eee60?, 0xc002f483c0?})
	istio.io/istio/pilot/pkg/status/manager.go:97 +0x51
istio.io/istio/pilot/pkg/status.(*WorkerPool).maybeAddWorker.func1()
	istio.io/istio/pilot/pkg/status/resourcelock.go:214 +0x60e
created by istio.io/istio/pilot/pkg/status.(*WorkerPool).maybeAddWorker in goroutine 718
	istio.io/istio/pilot/pkg/status/resourcelock.go:182 +0x105
```

### Version

```Text
1.23.x
```

**Comment by hzxuzhonghu** [comment]
maybe https://github.com/istio/istio/pull/52566 has fixed it

**Comment by howardjohn** [comment]
> maybe #52566 has fixed it

Yes I think this did. We should work on a similar smaller patch for backport probably. Maybe @ilrudie or @MorrisLaw would be interested

**Comment by MorrisLaw** [comment]
I can look into this
