### ISSUE TITLE
e2e tests fails on GKE 1.10.2-gke.1

### ISSUE THREAD

**Issue by lizan** [istio/istio#5723]
e2e tests fails on GKE cluster created with: 

```
gcloud container clusters create cluster-1 --cluster-version=1.10.2-gke.1
```

while with `1.9.6-gke.1` the e2e test works.

`make e2e_pilot` log:
https://gist.github.com/lizan/a8ded72fa0ea75d4101fa31cbe927933

Note `1.10.2-gke.1` is [GA](https://cloud.google.com/kubernetes-engine/release-notes).

Tested on dec9966b5a80719cac5c148fb48fc662f1f2bbf2

**Comment by trisberg** [comment]
I'm seeing issues as well with `1.10.2-gke.1` - trying a kafka helm chart [1] install that worked fine on `1.9.7-gke.0` but showing connection errors when kafka pod tries to connect to zookeeper service. The same chart works fine on minikube with `1.10.1` as well.

```
[2018-05-22 18:28:35,793] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,793] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,793] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,793] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,793] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,793] INFO Client environment:os.version=4.14.22+ (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,793] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,793] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,795] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,796] INFO Initiating client connection, connectString=projectriff-zookeeper:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@6ac13091 (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:35,819] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-05-22 18:28:35,839] INFO Opening socket connection to server projectriff-zookeeper.riff-system.svc.cluster.local/10.11.253.238:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-05-22 18:28:35,846] INFO Socket connection established to projectriff-zookeeper.riff-system.svc.cluster.local/10.11.253.238:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-05-22 18:28:41,820] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2018-05-22 18:28:41,850] WARN Client session timed out, have not heard from server in 6000ms for sessionid 0x0 (org.apache.zookeeper.ClientCnxn)
[2018-05-22 18:28:41,953] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
[2018-05-22 18:28:41,956] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
[2018-05-22 18:28:41,957] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'projectriff-zookeeper:2181' with timeout of 6000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:103)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:85)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:341)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:191)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:65)
	at kafka.Kafka.main(Kafka.scala)
[2018-05-22 18:28:41,961] INFO shutting down (kafka.server.KafkaServer)
[2018-05-22 18:28:41,978] INFO shut down completed (kafka.server.KafkaServer)
[2018-05-22 18:28:41,981] FATAL Exiting Kafka. (kafka.server.KafkaServerStartable)
[2018-05-22 18:28:41,992] INFO shutting down (kafka.server.KafkaServer)
```

[1] https://github.com/projectriff/riff/tree/master/helm-charts/kafka

**Comment by plasticine** [comment]
Yep, can confirm there seems to be something pretty busted here. We’re actually seeing GKE Nodes be rebooted by the node health monitor with;

```
INFO: task envoy:6501 blocked for more than 300 seconds.
```

**Comment by plasticine** [comment]
```
Linux version 4.14.22+
chrome-bot@build12-m2.golo.chromium.org
gcc version 4.9.x 20150123 (prerelease)
4.9.2_cos_gg_4.9.2-r182-2cdcfd30c27f0d836cc477f2ae9f456287fd6b1b_4.9.2-r182
```

**Comment by kyessenov** [comment]
Yeap. Found by conduit folks https://github.com/runconduit/conduit/issues/982

**Comment by lizan** [comment]
Good catch! I'll try ubuntu as node-images to see if it works.

**Comment by trisberg** [comment]
Using Ubuntu solved my issue above

**Comment by lizan** [comment]
I also confirmed with Ubuntu nodes, e2e test runs.

**Comment by tcnghia** [comment]
It seems that 0.8 may not work well on 1.10 yet https://github.com/istio/istio/issues/5723

**Comment by ankurcha** [comment]
FYI: This issue happens in 0.7.1. It would be nice to either have a note somewhere to get GKE to fix the COS image kernel.

**Comment by missnebun** [comment]
Is this affecting CentOS 7.5 The kernel is 3.10.0-862.el7.x86_64 ?

**Comment by lizan** [comment]
@missnebun No, the affect kernel is 4.14.22-40.

**Comment by lizan** [comment]
[GKE 1.10.4-gke.0](https://cloud.google.com/kubernetes-engine/release-notes) is rolling out this week, and it contains the fix of this issue.
