### ISSUE TITLE
istio mc does not work with ingressgateway

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#5905]
I was using dailybuild
```
[root@gyliu-icp-1 multicluster]# istioctl version
Version: release-0.8-20180528-09-15
GitRevision: d91d44ead27d9b4018ab5997ef7ec0f0a4621d9d
User: root@3f83fc3699ba
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

And deployed two clusters, all of the pods in the two clusters can reach each other.

Cluster1
```
[root@gyliu-icp-1 multicluster]# kubectl get svc -n istio-system
NAME                       TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)                                                               AGE
grafana                    NodePort       10.0.0.222   <none>        3000:30733/TCP                                                        23h
istio-citadel              ClusterIP      10.0.0.251   <none>        8060/TCP,9093/TCP                                                     23h
istio-egressgateway        ClusterIP      10.0.0.63    <none>        80/TCP,443/TCP                                                        23h
istio-ingressgateway       LoadBalancer   10.0.0.117   9.111.255.8   12346:31380/TCP,443:31390/TCP,31400:31400/TCP                         23h
istio-pilot                ClusterIP      10.0.0.124   <none>        15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   23h
istio-policy               ClusterIP      10.0.0.18    <none>        9091/TCP,15004/TCP,9093/TCP                                           23h
istio-sidecar-injector     ClusterIP      10.0.0.151   <none>        443/TCP                                                               23h
istio-statsd-prom-bridge   ClusterIP      10.0.0.173   <none>        9102/TCP,9125/UDP                                                     23h
istio-telemetry            ClusterIP      10.0.0.97    <none>        9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 23h
kiali                      NodePort       10.0.0.187   <none>        20001:31042/TCP                                                       23h
prometheus                 NodePort       10.0.0.157   <none>        9090:32458/TCP                                                        23h
servicegraph               NodePort       10.0.0.144   <none>        8088:32676/TCP                                                        23h
tracing                    LoadBalancer   10.0.0.137   9.111.255.9   12345:30491/TCP                                                       23h
zipkin                     ClusterIP      10.0.0.106   <none>        9411/TCP
```

Cluster2
```
root@gyliu-ubuntu-1:~# kubectl get svc -n istio-system
NAME                       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                                                               AGE
istio-citadel              ClusterIP   20.0.0.56    <none>        8060/TCP,9093/TCP                                                     34m
istio-pilot                ClusterIP   None         <none>        15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   34m
istio-policy               ClusterIP   None         <none>        9091/TCP,15004/TCP,9093/TCP,9094/TCP,9102/TCP,9125/UDP,42422/TCP      34m
istio-statsd-prom-bridge   ClusterIP   None         <none>        9102/TCP,9125/UDP
```

In Cluster1, deployed `bookinfo` without `review-v3`
```
[root@gyliu-icp-1 multicluster]# kubectl get pods -owide
NAME                              READY     STATUS    RESTARTS   AGE       IP             NODE
details-v1-7648b54588-c2zmt       2/2       Running   0          1d        10.1.43.13     9.111.255.29
productpage-v1-6d5b9dffc6-7kzwk   2/2       Running   0          1d        10.1.158.205   9.111.255.129
ratings-v1-6bc9c966f6-lv26b       2/2       Running   0          1d        10.1.158.203   9.111.255.129
reviews-v1-8588df7d98-spzkz       2/2       Running   0          1d        10.1.158.204   9.111.255.129
reviews-v2-5ff5fbb4b8-x8nns       2/2       Running   0          1d        10.1.43.11     9.111.255.29
```

In Cluster2, deployed `review-v3`
```
root@gyliu-ubuntu-1:~# kubectl get pods -owide
NAME                          READY     STATUS    RESTARTS   AGE       IP            NODE
reviews-v3-6dd497f5db-84rn2   2/2       Running   0          6m        20.1.31.131   9.111.255.152
```

In Cluster1, I can access `review-v3` from the pod of `productpage` in Cluster1.
```
[root@gyliu-icp-1 mc]# kubectl exec -it productpage-v1-6d5b9dffc6-7kzwk -c istio-proxy bash
istio-proxy@productpage-v1-6d5b9dffc6-7kzwk:/$ ping
Usage: ping [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
istio-proxy@productpage-v1-6d5b9dffc6-7kzwk:/$ ping 20.1.31.131
PING 20.1.31.131 (20.1.31.131) 56(84) bytes of data.
64 bytes from 20.1.31.131: icmp_seq=1 ttl=62 time=0.838 ms
^C
--- 20.1.31.131 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.838/0.838/0.838/0.000 ms
istio-proxy@productpage-v1-6d5b9dffc6-7kzwk:/$ curl 20.1.31.131:9080
istio-proxy@productpage-v1-6d5b9dffc6-7kzwk:/$ curl 20.1.31.131:9080
```

Defined `virtualservices` and redirect the request to `review-v3`
```
[root@gyliu-icp-1 mc]# istioctl get virtualservices
NAME          KIND                                          NAMESPACE
bookinfo      VirtualService.networking.istio.io.v1alpha3   default
details       VirtualService.networking.istio.io.v1alpha3   default
productpage   VirtualService.networking.istio.io.v1alpha3   default
ratings       VirtualService.networking.istio.io.v1alpha3   default
reviews       VirtualService.networking.istio.io.v1alpha3   default
```
```
[root@gyliu-icp-1 mc]# istioctl get virtualservices reviews -oyaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: reviews
  namespace: default
  resourceVersion: "273600"
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v3
---
```

And then access `productpage` via `http://9.111.255.8:12346/productpage`, product page report error as follows:

![image](https://user-images.githubusercontent.com/4461983/40706147-6e0d4a5e-641f-11e8-8f2e-70b5c55706d4.png)

But from `productpage` container `istio-proxy`, I can see the request was direct to pod of `review-v3` in cluster2
```
[2018-05-30T07:27:31.818Z] "GET /details/0 HTTP/1.1" 200 - 0 178 2 2 "-" "python-requests/2.18.4" "40a3fca8-667b-9a70-a708-fe600b94765d" "details:9080" "10.1.43.13:9080"
[2018-05-30T07:27:31.824Z] "GET /reviews/0 HTTP/1.1" 500 - 0 4221 21 21 "-" "python-requests/2.18.4" "40a3fca8-667b-9a70-a708-fe600b94765d" "reviews:9080" "20.1.31.131:9080"
[2018-05-30T07:27:31.848Z] "GET /reviews/0 HTTP/1.1" 500 - 0 4221 20 20 "-" "python-requests/2.18.4" "40a3fca8-667b-9a70-a708-fe600b94765d" "reviews:9080" "20.1.31.131:9080"
[2018-05-30T07:27:31.815Z] "GET /productpage HTTP/1.1" 200 - 0 4083 56 55 "10.1.198.128" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "40a3fca8-667b-9a70-a708-fe600b94765d" "9.111.255.8:12346" "127.0.0.1:9080"
```

But the bookinfo page show error.

/cc @sdake @sbezverk @costinm

**Comment by gyliu513** [comment]
[pilot.log](https://github.com/istio/istio/files/2052852/pilot.log)

Attachment is pilot log, from the log, I can see that it continues reporting the pod ip in remote cluster not found.

```
2018-05-30T07:39:38.491317Z	error	ip not found, listeners will be broken 20.1.31.131 reviews-v3-6dd497f5db-84rn2.default
2018-05-30T07:39:38.754106Z	info	ads	LDS: PUSH for node:{ sidecar 20.1.31.131 reviews-v3-6dd497f5db-84rn2.default default.svc.cluster.local map[POD_NAME:reviews-v3-6dd497f5db-84rn2 istio:sidecar INTERCEPTION_MODE:REDIRECT]} addr:"9.111.255.152:43792" listeners:68
2018-05-30T07:40:38.541301Z	error	ip not found, listeners will be broken 20.1.31.131 reviews-v3-6dd497f5db-84rn2.default
2018-05-30T07:40:38.546009Z	info	ads	CDS: PUSH for { sidecar 20.1.31.131 reviews-v3-6dd497f5db-84rn2.default default.svc.cluster.local map[POD_NAME:reviews-v3-6dd497f5db-84rn2 istio:sidecar INTERCEPTION_MODE:REDIRECT]} "9.111.255.152:43792", Response: 92
2018-05-30T07:40:38.546495Z	info	ads	EDS: PUSH for sidecar~20.1.31.131~reviews-v3-6dd497f5db-84rn2.default~default.svc.cluster.local-17 "9.111.255.152:43792" clusters 85 endpoints 81 empty 4 [outbound|9080|v2-mysql-vm|ratings.default.svc.cluster.local outbound|9080|v2-mysql|ratings.default.svc.cluster.local outbound|9080|v2|ratings.default.svc.cluster.local outbound|9080|v2|details.default.svc.cluster.local]
2018-05-30T07:40:38.546869Z	error	ip not found, listeners will be broken 20.1.31.131 reviews-v3-6dd497f5db-84rn2.default
2018-05-30T07:40:38.724651Z	info	ads	LDS: PUSH for node:{ sidecar 20.1.31.131 reviews-v3-6dd497f5db-84rn2.default default.svc.cluster.local map[POD_NAME:reviews-v3-6dd497f5db-84rn2 istio:sidecar INTERCEPTION_MODE:REDIRECT]} addr:"9.111.255.152:43792" listeners:68
```

**Comment by gyliu513** [comment]
My bad, I forgot to create the `rating` service in remote cluster, and this caused the `reviews-v3` failed to call `rating` services, after adding `rating` service in remote cluster, it works fine.

```
[WARNING ] Interceptor for {http://ratings:9080/ratings/0}WebClient has thrown exception, unwinding now
Could not send Message.
##################################################################################################
[WARNING ] Application {http://rest.application/}LibertyRestEndpoint has thrown exception, unwinding now
java.net.UnknownHostException: UnknownHostException invoking http://ratings:9080/ratings/0: ratings
[WARNING ] Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@c12fe9a5
java.net.UnknownHostException: UnknownHostException invoking http://ratings:9080/ratings/0: ratings
[ERROR   ] Error occurred during error handling, give up!
java.net.UnknownHostException: UnknownHostException invoking http://ratings:9080/ratings/0: ratings
[ERROR   ] SRVE0777E: Exception thrown by application class 'org.apache.cxf.jaxrs.client.AbstractClient.checkClientException:636'
javax.ws.rs.ProcessingException: java.net.UnknownHostException: UnknownHostException invoking http://ratings:9080/ratings/0: ratings
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:636)
	at [internal classes]
	at application.rest.LibertyRestEndpoint.getRatings(LibertyRestEndpoint.java:119)
	at application.rest.LibertyRestEndpoint.bookReviewsById(LibertyRestEndpoint.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:633)
	at [internal classes]
Caused by: java.net.UnknownHostException: UnknownHostException invoking http://ratings:9080/ratings/0: ratings
	at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1390)
	... 9 more
Caused by: java.net.UnknownHostException: ratings
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:214)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.net.Socket.connect(Socket.java:666)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:187)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:494)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:589)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:256)
	at sun.net.www.http.HttpClient.New(HttpClient.java:360)
	at sun.net.www.http.HttpClient.New(HttpClient.java:378)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1233)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1212)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1063)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1579)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1507)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:491)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream$2.run(URLConnectionHTTPConduit.java:379)
	... 9 more
```

**Comment by gyliu513** [comment]
I would like to say Jaeger is cool, and it tell me which call failed and helped me finally found the root cause of this issue.
