### ISSUE TITLE
telemetry: missing gateway telemetry

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#6155]
Currently, there is no telemetry or policy checks enabled on the gateway.

**Comment by kyessenov** [comment]
depends on #6162

**Comment by kyessenov** [comment]
Sample failure: https://circleci.com/gh/istio/istio/111093#artifacts/containers/0.
No segfaults are present.

**Comment by ostromart** [comment]
I think this is a regression. @bianpengyuan is looking at it atm and I can help with that.

**Comment by kyessenov** [comment]
backtrace:
```
[2018-06-12 23:16:06.940][38][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_443'
[2018-06-12 23:16:07.433][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:125] Caught Segmentation fault, suspect faulting address 0x0
[2018-06-12 23:16:07.435][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:94] Backtrace thr<44> obj</usr/local/bin/envoy> (If unsymbolized, use tools/stack_decode.py):
[2018-06-12 23:16:07.470][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<44> #0 0x13e74c8 backward::details::unwind<>()
[2018-06-12 23:16:07.480][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<44> #1 0x13e669a backward::StackTraceImpl<>::load_here()
[2018-06-12 23:16:07.491][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<44> #2 0x13e6d70 Envoy::BackwardsTrace::capture()
[2018-06-12 23:16:07.498][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<44> #3 0x13e4e7e Envoy::SignalAction::sigHandler()
[2018-06-12 23:16:07.498][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<44> obj</lib/x86_64-linux-gnu/libpthread.so.0>
[2018-06-12 23:16:07.498][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<44> #4 0x7f701479838f (unknown)
[2018-06-12 23:16:07.498][44][critical][backtrace] bazel-out/k8-dbg/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:121] end backtrace thread 44
```

Does not look like mixerfilter at fault here.

**Comment by kyessenov** [comment]
Finally got the stack trace
```
#0  0x0000000000000000 in ?? ()
#1  0x00000000013d70e8 in google::protobuf::MessageLite::AppendToString (this=0x43f4000, output=0x7ff445366600) at external/com_google_protobuf/src/google/protobuf/message_lite.cc:281
#2  0x00000000013d7421 in google::protobuf::MessageLite::SerializeToString (this=0x43f4000, output=0x7ff445366600)
    at external/com_google_protobuf/src/google/protobuf/message_lite.cc:305
#3  0x00000000004c5dfe in Envoy::Utils::GrpcTransport<istio::mixer::v1::ReportRequest, istio::mixer::v1::ReportResponse>::onCreateInitialMetadata (this=0x453c320, metadata=...)
    at src/envoy/utils/grpc_transport.cc:59
#4  0x0000000000b49548 in Envoy::Grpc::AsyncRequestImpl::onCreateInitialMetadata (this=0x37489c0, metadata=...) at external/envoy/source/common/grpc/async_client_impl.cc:234
#5  0x0000000000b48636 in Envoy::Grpc::AsyncStreamImpl::initialize (this=0x37489c8, buffer_body_for_retry=true) at external/envoy/source/common/grpc/async_client_impl.cc:89
#6  0x0000000000b493b1 in Envoy::Grpc::AsyncRequestImpl::initialize (this=0x37489c0, buffer_body_for_retry=true) at external/envoy/source/common/grpc/async_client_impl.cc:215
#7  0x0000000000b47f73 in Envoy::Grpc::AsyncClientImpl::send (this=0x4729bc0, service_method=..., request=..., callbacks=..., parent_span=..., timeout=...)
    at external/envoy/source/common/grpc/async_client_impl.cc:32
#8  0x00000000004c4979 in Envoy::Utils::GrpcTransport<istio::mixer::v1::ReportRequest, istio::mixer::v1::ReportResponse>::GrpcTransport(std::unique_ptr<Envoy::Grpc::AsyncClient, std::default_delete<Envoy::Grpc::AsyncClient> >, istio::mixer::v1::ReportRequest const&, istio::mixer::v1::ReportResponse*, Envoy::Tracing::Span&, istio::mixer::v1::Attributes const&, std::function<void (google::protobuf::util::Status const&)>) (this=0x453c320, async_client=..., request=..., response=0x478f380, parent_span=..., forward_attributes=..., on_done=...)
    at src/envoy/utils/grpc_transport.cc:43
#9  0x00000000004c3849 in Envoy::Utils::GrpcTransport<istio::mixer::v1::ReportRequest, istio::mixer::v1::ReportResponse>::GetFunc(Envoy::Grpc::AsyncClientFactory&, Envoy::Tracing::Span&, istio::mixer::v1::Attributes const&)::{lambda(istio::mixer::v1::ReportRequest const&, istio::mixer::v1::ReportResponse*, std::function<void (google::protobuf::util::Status const&)>)#1}::operator()(istio::mixer::v1::ReportRequest const&, istio::mixer::v1::ReportResponse*, std::function<void (google::protobuf::util::Status const&)>) const (__closure=0x43c27e0,
    request=..., response=0x478f380, on_done=...) at src/envoy/utils/grpc_transport.cc:101
#10 0x00000000004c552a in std::_Function_handler<std::function<void ()> (istio::mixer::v1::ReportRequest const&, istio::mixer::v1::ReportResponse*, std::function<void (google::protobuf::util::Status const&)>), Envoy::Utils::GrpcTransport<istio::mixer::v1::ReportRequest, istio::mixer::v1::ReportResponse>::GetFunc(Envoy::Grpc::AsyncClientFactory&, Envoy::Tracing::Span&, istio::mixer::v1::Attributes const&)::{lambda(istio::mixer::v1::ReportRequest const&, istio::mixer::v1::ReportResponse*, std::function<void (google::protobuf::util::Status const&)>)#1}>::_M_invoke(std::_Any_data const&, istio::mixer::v1::ReportRequest const&, istio::mixer::v1::ReportResponse*&&, std::function<void (google::protobuf::util::Status const&)>&&) (
    __functor=..., __args#0=...,
    __args#1=<unknown type in /home/kuat/.cache/bazel/_bazel_kuat/07b8bed9e338582cf007b4dbfc8a07c2/execroot/__main__/bazel-out/k8-dbg/bin/src/envoy/envoy, CU 0x9a8733, DIE 0xa1c7c5>,
    __args#2=<unknown type in /home/kuat/.cache/bazel/_bazel_kuat/07b8bed9e338582cf007b4dbfc8a07c2/execroot/__main__/bazel-out/k8-dbg/bin/src/envoy/envoy, CU 0x9a8733, DIE 0xa1c7ca>)
    at /usr/include/c++/5/functional:1857
#11 0x0000000000525dce in std::function<std::function<void ()> (istio::mixer::v1::ReportRequest const&, istio::mixer::v1::ReportResponse*, std::function<void (google::protobuf::util::Status const&)>)>::operator()(istio::mixer::v1::ReportRequest const&, istio::mixer::v1::ReportResponse*, std::function<void (google::protobuf::util::Status const&)>) const (
    this=0x42c1c30, __args#0=..., __args#1=0x478f380, __args#2=...) at /usr/include/c++/5/functional:2267
#12 0x0000000000524fb4 in istio::mixerclient::ReportBatch::FlushWithLock (this=0x42c1c20) at src/istio/mixerclient/report_batch.cc:88
#13 0x0000000000525066 in istio::mixerclient::ReportBatch::Flush (this=0x42c1c20) at src/istio/mixerclient/report_batch.cc:93
#14 0x0000000000524940 in istio::mixerclient::ReportBatch::~ReportBatch (this=0x42c1c20, __in_chrg=<optimized out>) at src/istio/mixerclient/report_batch.cc:39
#15 0x00000000005249b2 in istio::mixerclient::ReportBatch::~ReportBatch (this=0x42c1c20, __in_chrg=<optimized out>) at src/istio/mixerclient/report_batch.cc:39
#16 0x0000000000523a6c in std::default_delete<istio::mixerclient::ReportBatch>::operator() (this=0x36e6668, __ptr=0x42c1c20) at /usr/include/c++/5/bits/unique_ptr.h:76
#17 0x0000000000522997 in std::unique_ptr<istio::mixerclient::ReportBatch, std::default_delete<istio::mixerclient::ReportBatch> >::~unique_ptr (this=0x36e6668,
    __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#18 0x0000000000520b2a in istio::mixerclient::MixerClientImpl::~MixerClientImpl (this=0x36e6580, __in_chrg=<optimized out>) at src/istio/mixerclient/client_impl.cc:52
#19 0x0000000000520b9a in istio::mixerclient::MixerClientImpl::~MixerClientImpl (this=0x36e6580, __in_chrg=<optimized out>) at src/istio/mixerclient/client_impl.cc:52
#20 0x00000000004e1038 in std::default_delete<istio::mixerclient::MixerClient>::operator() (this=0x40bc888, __ptr=0x36e6580) at /usr/include/c++/5/bits/unique_ptr.h:76
#21 0x00000000004e0e23 in std::unique_ptr<istio::mixerclient::MixerClient, std::default_delete<istio::mixerclient::MixerClient> >::~unique_ptr (this=0x40bc888,
    __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:236
```
cc @qiwzhang

**Comment by andraxylia** [comment]
This regression is not in 0.8 release, it happened after 0.8 and only in master.

**Comment by kyessenov** [comment]
Fixed by https://github.com/istio/istio/pull/6262
