### ISSUE TITLE
Pilot restarts and apps are not available anymore

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6564]
@dpacierpnik commented on [Mon Apr 30 2018](https://github.com/istio/old_issues_repo/issues/313)

**Is this a BUG or FEATURE REQUEST?:**
BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
YES

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
Istio version: 0.7.1
Kubernetes version: 1.9.0 

**Is Istio Auth enabled or not ?**
NO (istio.yaml used)

**What happened**:
After some time (it is random how long it takes) Pilot fails and is restarted. After restart my applications are not available anymore (I have 503 when trying to access application via Istio controller). In the Pilot logs there is a stack trace from goroutine with the following error:
```
fatal error: concurrent map read and map write

goroutine 1409 [running]:
runtime.throw(0x17b9212, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420d6a790 sp=0xc420d6a770 pc=0x42bb85
runtime.mapaccess2(0x159fc40, 0xc4202bef90, 0xc42038d480, 0xc4208999d8, 0xc420899a01)
	/usr/local/go/src/runtime/hashmap.go:413 +0x24e fp=0xc420d6a7d8 sp=0xc420d6a790 pc=0x40887e
reflect.mapaccess(0x159fc40, 0xc4202bef90, 0xc42038d480, 0xc4202bef90)
	/usr/local/go/src/runtime/hashmap.go:1218 +0x3f fp=0xc420d6a810 sp=0xc420d6a7d8 pc=0x40b19f
reflect.Value.MapIndex(0x159fc40, 0xc4202bef90, 0x15, 0x1532a00, 0xc42038d480, 0x98, 0x14cd660, 0xc420d78690, 0x16)
	/usr/local/go/src/reflect/value.go:1058 +0x126 fp=0xc420d6a898 sp=0xc420d6a810 pc=0x4ba756
fmt.(*pp).printValue(0xc420384000, 0x159fc40, 0xc4202bef90, 0x15, 0x76, 0x0)
	/usr/local/go/src/fmt/print.go:750 +0xf47 fp=0xc420d6aad8 sp=0xc420d6a898 pc=0x4d0397
fmt.(*pp).printArg(0xc420384000, 0x159fc40, 0xc4202bef90, 0xc400000076)
	/usr/local/go/src/fmt/print.go:682 +0x1e5 fp=0xc420d6ab58 sp=0xc420d6aad8 pc=0x4cec45
fmt.(*pp).doPrintf(0xc420384000, 0x17df892, 0x34, 0xc420d6ae88, 0x3, 0x3)
	/usr/local/go/src/fmt/print.go:996 +0x15a fp=0xc420d6ac88 sp=0xc420d6ab58 pc=0x4d2baa
fmt.Sprintf(0x17df892, 0x34, 0xc420d6ae88, 0x3, 0x3, 0x1532a00, 0xc42001e070)
	/usr/local/go/src/fmt/print.go:196 +0x66 fp=0xc420d6ace0 sp=0xc420d6ac88 pc=0x4cb0e6
istio.io/istio/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc420066538, 0x7facad587c00, 0x17df892, 0x34, 0xc420d6ae88, 0x3, 0x3, 0x0, 0x0, 0x0)
	/workspace/go/src/istio.io/istio/vendor/go.uber.org/zap/sugar.go:230 +0x127 fp=0xc420d6ad30 sp=0xc420d6ace0 pc=0x83dfb7
istio.io/istio/vendor/go.uber.org/zap.(*SugaredLogger).Infof(0xc420066538, 0x17df892, 0x34, 0xc420d6ae88, 0x3, 0x3)
	/workspace/go/src/istio.io/istio/vendor/go.uber.org/zap/sugar.go:138 +0x83 fp=0xc420d6ad90 sp=0xc420d6ad30 pc=0x83d693
istio.io/istio/pkg/log.Infof(0x17df892, 0x34, 0xc420d6ae88, 0x3, 0x3)
	/workspace/go/src/istio.io/istio/pkg/log/log.go:174 +0x5f fp=0xc420d6add0 sp=0xc420d6ad90 pc=0xa6b0bf
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).removeEdsCon(0xc420293960, 0xc42089cf00, 0x3a, 0xc420777da0, 0x5c, 0xc420c321e0)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:521 +0x3b2 fp=0xc420d6aec8 sp=0xc420d6add0 pc=0x128ec42
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamEndpoints.func1(0xc420b08d20, 0x2226b40, 0xc420047cf0, 0xc420047d10, 0xc420e04a40, 0x10, 0xc420c321e0, 0xc420293960, 0xc420047d00)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:304 +0x247 fp=0xc420d6af98 sp=0xc420d6aec8 pc=0x1290ca7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420d6afa0 sp=0xc420d6af98 pc=0x45caf1
created by istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamEndpoints
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:296 +0x2a0
```
More detailed logs can be found here: https://github.com/dpacierpnik/istio-0.7-issues/tree/master/issue_logs/01_istio_no_auth

**What you expected to happen:**
I expect the Pilot works stable and my apps are available all the time ;) 

**How to reproduce it:**
To reproduce, you can use the following application https://github.com/dpacierpnik/istio-0.7-issues
Just follow the README

**Comment by andraxylia** [comment]
A similar issue was fixed in 0.8.
