### ISSUE TITLE
Irregular connection reset.

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6577]
@fudali113 commented on [Sun Apr 08 2018](https://github.com/istio/old_issues_repo/issues/275)

**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
YES
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version

Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
kubectl version

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
not， i am use istio.yaml

**What happened**:
In some cases, the connection is reset when I make an HTTP request between services.
**What you expected to happen:**
Normal access to HTTP services.
**How to reproduce it:**
i don`t know

**Feature Request:**
Y/N

**Describe the feature:**

i has
gateway service:
```
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: api
  labels:
    app: gateway
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        version: 1.0.5
    spec:
      containers:
      - name: gateway
        image: registry.cn-hangzhou.aliyuncs.com/***/gateway:1.0.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
```
user service:
```
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: api
  labels:
    app: user
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: user
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user
  namespace: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
        version: 1.1.0
    spec:
      containers:
      - name: common
        image: registry.cn-hangzhou.aliyuncs.com/***/user:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: beta
      imagePullSecrets:
      - name: ali-docker-images
---
```

sct service ：
```
apiVersion: v1
kind: Service
metadata:
  name: sct
  namespace: api
  labels:
    app: sct
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sct
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sct
  namespace: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sct
        version: 1.0.13
    spec:
      containers:
      - name: sct
        image: registry.cn-hangzhou.aliyuncs.com/***/sct:1.0.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: beta
      imagePullSecrets:
      - name: ali-docker-images
---
```

my istio gateway yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-gateway
  namespace: api
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /api/.*
        backend:
          serviceName: gateway
          servicePort: 80
      - path: /v1/.*
        backend: 
          serviceName: gateway
          servicePort: 80
      - path: /v2/.*
        backend:
          serviceName: gateway
          servicePort: 80
      - path: /v3/.*
        backend:
          serviceName: gateway
          servicePort: 80
      - path: /v4/.*
        backend:
          serviceName: gateway
          servicePort: 80
      - path: /v6/.*
        backend:
          serviceName: gateway
          servicePort: 80
      - path: /v7/.*
        backend:
          serviceName: gateway
          servicePort: 80
      - path: /v7/.*
        backend:
          serviceName: gateway
          servicePort: 80
      - path: /v8/.*
        backend:
          serviceName: gateway
          servicePort: 80
      - path: /v9/.*
        backend:
          serviceName: gateway
          servicePort: 80
```

my gateway service is use zuul, He will forward the request to the user service and the SCT service.
My SCT service will access the user service.

I access the url/API/SCT of the SCT service, which requests the user service /v1/user/barcodes,but this is an error.
```
feign.RetryableException: Connection reset executing GET http://user/v1/user/barcodes?bind=false
	at feign.FeignException.errorExecuting(FeignException.java:67)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:104)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy92.getBarcodes(Unknown Source)
	at com.mofang.sct.controller.SctInfoController.getInfos(SctInfoController.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:675)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at feign.Client$Default.convertResponse(Client.java:152)
	at feign.Client$Default.execute(Client.java:74)
	at com.mofang.spring.support.feign.K8sFeignClient.execute(K8sFeignClient.java:36)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	... 70 common frames omitted
```

But I can access it directly through access /v1/user/barcodes.

This performance is roughly the ability of some services to communicate with each other, but some services cannot communicate with each other, and whether the communication between services can change over time.

Who can help me?  

---

@fudali113 commented on [Mon Apr 09 2018](https://github.com/istio/old_issues_repo/issues/275#issuecomment-379684514)

I found this to happen when I deployed a new service or restarted a service.

---

@fudali113 commented on [Mon Apr 09 2018](https://github.com/istio/old_issues_repo/issues/275#issuecomment-379687871)

istio-proxy log:
```
[2018-04-09 08:56:41.390][11][info][upstream] external/envoy/source/server/lds_api.cc:60] lds: add/update listener 'http_10.244.2.141_80'
[2018-04-09 08:56:41.397][11][info][upstream] external/envoy/source/server/lds_api.cc:60] lds: add/update listener 'tcp_10.96.0.10_53'
[2018-04-09 08:56:41.397][11][info][upstream] external/envoy/source/server/lds_api.cc:60] lds: add/update listener 'tcp_10.96.0.1_443'
2018-04-09T08:57:08.611134Z	info	Proxy availability zone: 
2018-04-09T08:57:38.613345Z	info	Proxy availability zone: 
[2018-04-09 08:57:38.854][11][info][main] external/envoy/source/server/drain_manager_impl.cc:63] shutting down parent after drain
2018-04-09T08:58:08.615521Z	info	Proxy availability zone: 
2018-04-09T08:58:38.621944Z	info	Proxy availability zone: 
2018-04-09T08:59:08.624222Z	info	Proxy availability zone: 
2018-04-09T08:59:38.630019Z	info	Proxy availability zone: 
2018-04-09T09:00:08.632338Z	info	Proxy availability zone: 
2018-04-09T09:00:38.637770Z	info	Proxy availability zone: 
2018-04-09T09:01:08.639960Z	info	Proxy availability zone: 
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:155] Add a new Referenced for check cache: Absence-keys: Exact-keys: context.protocol, destination.service, destination.uid, source.ip, source.uid, 
[2018-04-09T09:01:23.132Z] "GET /v3/questionnaire/link?token=d93dd09a9a0c11f6bf4e9d87be18ee4855b3116c74ca820ad7964de85e69f236d5ef03d4b1ff83a0ac2608ae54e4e4c8 HTTP/1.1" 500 - 0 366 1046 1020 "10.244.0.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "dc821858-8ae0-9f3f-a9eb-cad392802e44" "47.95.143.20:31494" "127.0.0.1:80"
[2018-04-09T09:01:31.524Z] "GET /v3/questionnaire/link?token=d93dd09a9a0c11f6bf4e9d87be18ee4855b3116c74ca820ad7964de85e69f236d5ef03d4b1ff83a0ac2608ae54e4e4c8 HTTP/1.1" 500 - 0 366 59 58 "10.244.0.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "d73d17d4-cf78-9cf6-804b-27e3f97af49c" "47.95.143.20:31494" "127.0.0.1:80"
2018-04-09T09:01:38.642278Z	info	Proxy availability zone: 
[2018-04-09T09:01:39.514Z] "GET /v3/questionnaire/link?token=sample-report HTTP/1.1" 500 - 0 366 90 85 "10.244.0.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "04d80e88-23b4-9bc7-81bb-5c5feef47b61" "47.95.143.20:31494" "127.0.0.1:80"
2018-04-09T09:02:08.644457Z	info	Proxy availability zone: 
2018-04-09T09:02:08.644645Z	info	Availability zone not set, proxy will default to not using zone aware routing.
[2018-04-09T09:02:28.067Z] "GET /api/sct?token=d93dd09a9a0c11f6bf4e9d87be18ee4855b3116c74ca820ad7964de85e69f236d5ef03d4b1ff83a0ac2608ae54e4e4c8 HTTP/1.1" 500 - 0 352 55 47 "10.244.0.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "c7358278-62d4-9b74-b179-f8e19767f0ef" "47.95.143.20:31494" "127.0.0.1:80"
[2018-04-09T09:02:33.477Z] "GET /api/sct?token=d93dd09a9a0c11f6bf4e9d87be18ee4855b3116c74ca820ad7964de85e69f236d5ef03d4b1ff83a0ac2608ae54e4e4c8 HTTP/1.1" 500 - 0 352 39 39 "10.244.0.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "c114dceb-f6c6-91a5-a89d-3d0ccba01168" "47.95.143.20:31494" "127.0.0.1:80"
[2018-04-09T09:02:34.946Z] "GET /api/sct?token=d93dd09a9a0c11f6bf4e9d87be18ee4855b3116c74ca820ad7964de85e69f236d5ef03d4b1ff83a0ac2608ae54e4e4c8 HTTP/1.1" 500 - 0 352 18 17 "10.244.0.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "231294f3-61a0-9c40-8357-ce6585cd8da1" "47.95.143.20:31494" "127.0.0.1:80"
```

what is Proxy availability zone?

---

@linsun commented on [Mon Apr 09 2018](https://github.com/istio/old_issues_repo/issues/275#issuecomment-379858271)

@andraxylia should this one be added to https://github.com/istio/istio/issues/4810?

---

@linsun commented on [Mon Apr 09 2018](https://github.com/istio/old_issues_repo/issues/275#issuecomment-379858352)

proxy AZ msg should be harmless, fyi

---

@fudali113 commented on [Mon Apr 09 2018](https://github.com/istio/old_issues_repo/issues/275#issuecomment-379955874)

hi @linsun ,Can you tell me the reason or the convenient document?

---

@fudali113 commented on [Tue Apr 10 2018](https://github.com/istio/old_issues_repo/issues/275#issuecomment-380016354)

my gateway server istio-procy log:
```
[2018-04-10 07:52:56.202][34][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:388] add/update cluster out.push.api.svc.cluster.local|http starting warming
[2018-04-10 07:52:56.235][34][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:395] warming cluster out.push.api.svc.cluster.local|http complete
[2018-04-10 07:53:41.569][34][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2018-04-10 07:53:44.007][34][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2018-04-10 07:53:46.627][34][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2018-04-10 08:02:52.215][34][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:388] add/update cluster out.order.api.svc.cluster.local|http starting warming
[2018-04-10 08:02:52.243][34][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:395] warming cluster out.order.api.svc.cluster.local|http complete
```

---

@fudali113 commented on [Thu Apr 12 2018](https://github.com/istio/old_issues_repo/issues/275#issuecomment-380797199)

I find this problem seems to be caused by the conflict of Egress configuration, but I think the Egress conflict should not cause this result.   @linsun  Do you think?

---

@louiscryan commented on [Fri Jun 22 2018](https://github.com/istio/old_issues_repo/issues/275#issuecomment-399605727)

@fudali113 the networking APIs and the pipeline for configuring Envoy have changed quite a bit in 0.8

Can you retest using the new APIs

https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3

**Comment by smawson** [comment]
Closing due to staleness, please reopen if this remains an issue.

**Comment by gavinfish** [comment]
@fudali113 Have you solved this problem?
