### ISSUE TITLE
Constant update of Listeners resetting TCP Connections

### ISSUE THREAD

**Issue by Justin-Ahn** [istio/istio#7045]
**Describe the bug**
The Istio sidecars for RabbitMQ-HA and Zookeeper update the listener for the application's ports every couple of minutes, causing resets for all ports communicating with it. Note that both of these are deployed as statefulsets. 

Using the logs from the run w/ Istio 1.0:

---
RabbitMQ's sidecar: (This happens every couple of minutes) 
``` 
[2018-07-12 14:14:31.208][15][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '172.17.0.19_61614'
[2018-07-12 14:14:31.209][15][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '172.17.0.19_4369'
[2018-07-12 14:14:31.212][15][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '172.17.0.19_15672'
[2018-07-12 14:14:31.213][15][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '172.17.0.19_5672'
[2018-07-12 14:14:31.214][15][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '172.17.0.19_61613'
```
Causes:
```
2018-07-12 14:15:15.243 [warning] <0.18883.2> closing AMQP connection <0.18883.2> (127.0.0.1:40900 -> 127.0.0.1:5672 - SpringAMQP#33a7331:0, vhost: '/', user: 'skyscraper'):
client unexpectedly closed TCP connection
2018-07-12 14:15:15.243 [info] <0.18900.2> closing STOMP connection <0.18900.2> (127.0.0.1:41550 -> 127.0.0.1:61613)
```
in RabbitMQ.

---

Zookeeper: (This happens every couple of minutes) 
``` 
[2018-07-12 14:19:31.028][17][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '172.17.0.20_2181'
```
Causes:
```
2018-07-12 14:20:15,041 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@368] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x1648b771aa70006, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:239)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
	at java.lang.Thread.run(Thread.java:748)
```
in Zookeeper. 

I've fiddled around with the drain durations and discovery refresh delays, but they didn't help with the disconnections. 
I've disabled the RabbitMQ readiness/liveness probes as well (to get it running). 
Similar log output & behavior occured w/ Istio 0.8

**Expected behavior**
It seemed to me looking at other applications running on Istio that constant listener updates were not the norm. 
I'd expect that the rmq and zookeeper connections not get changed in any way when running on top of Istio. 

**Steps to reproduce the bug**
Try downloading Zookeeper and RabbitMQ-HA from helm and deploying it on Istio. You will see the constant listener updates.

**Version**
Attempted on both Istio 0.8 and the 1.0 snapshot.
Kubernetes 1.10

**Is Istio Auth enabled or not?**
Istio Auth is not enabled. I also attempted the solution outlined here: https://istio.io/help/troubleshooting/#headless-tcp-services-losing-connection-from-istiofied-containers
But it had no impact. 

**Environment**
Minikube

**Comment by Justin-Ahn** [comment]
Let me know if you need any more info!
