### ISSUE TITLE
TLS handshake failure connecting from application container to api server

### ISSUE THREAD

**Issue by awalmsley** [istio/istio#7512]
**Describe the bug**
When calling the Kubernetes API server from an application container, there is a TLS handshake failure. This only occurs when mutual TLS is enabled. Worked in Istio 0.7 and fails in Istio 0.8.
```
Caused by: java.io.EOFException: SSL peer shut down incorrectly
```

**Expected behavior**
Expect the API server call to return with no exceptions.

**Steps to reproduce the bug**
SSH into an application container and call the API server from a groovy script. This works when mutual auth is disabled.
```
Caught: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: [api-car-v1]  in namespace: [default]  failed.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: [api-car-v1]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:228)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:184)
	at io.fabric8.kubernetes.client.dsl.Gettable$get.call(Unknown Source)
	at com.swacorp.dotcom.service.KubernetesApi.getConfigMap(KubernetesApi.groovy:22)
	at com.swacorp.dotcom.service.KubernetesApi$getConfigMap.call(Unknown Source)
	at com.swacorp.dotcom.service.StartService.main(StartService.groovy:20)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:312)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:295)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:787)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:217)
	... 5 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	... 33 more
```

**Version**
```
istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:16:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
Installed Istio with auth enabled.
```
kubectl apply -f $ISTIO_HOME/install/kubernetes/istio-demo-auth.yaml
```

**Environment**
AWS, Kubernetes, Linux

**Comment by awalmsley** [comment]
Are there any comments on this issue? Have there been any TLS implementation changes since 0.7 that might cause this problem?

thanks

**Comment by ChrisCooney** [comment]
@awalmsley  - did you get anywhere with this? Experiencing the same thing now.

**Comment by krichter722** [comment]
@kyessenov pinging you as a main contributor (hopefully administrator as meant by the stale bot). This is still an issue as confirmed by the reporter and others (including me).

BTW, please consider turning of the stale bot as it's almost never constructive to close issues automatically, especially not based on elapsed time.
