### ISSUE TITLE
istio-pilot stuck in crash loop

### ISSUE THREAD

**Issue by Stono** [istio/istio#7591]
All of our pilots are currently crashing.

```
/Users/karl.stoney/git/autotrader/docker.kbot git/master
❯ kis logs istio-pilot-654d8bbc7b-bl9gk discovery
2018-08-02T10:20:24.094039Z     warn    Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2018-08-02T10:20:24.776476Z     error   ads     CDS: Generated invalid cluster for node &{Kubernetes sidecar 10.198.8.24 mercury-admin-tool-556854cbc4-5n6vr.mercury-admin-tool mercury-admin-tool.svc.cluster.local map[POD_NAME:mercury-admin-tool-556854cbc4-5n6vr istio:sidecar INTERCEPTION_MODE:REDIRECT ISTIO_PROXY_VERSION:1.0.0 ISTIO_PROXY_SHA:istio-proxy:6166ae7ebac7f630206b2fe4e6767516bf198313 ISTIO_VERSION:1.0.0]}: invalid Cluster.TlsContext: embedded message failed validation | caused by: invalid UpstreamTlsContext.CommonTlsContext: embedded message failed validation | caused by: invalid CommonTlsContext.TlsCertificates[0]: embedded message failed validation | caused by: invalid TlsCertificate.CertificateChain: embedded message failed validation | caused by: invalid DataSource.Filename: value length must be at least 1 bytes, name:"outbound|80||app.supply-and-demand-service.svc.cluster.local" type:EDS eds_cluster_config:<eds_config:<ads:<> > service_name:"outbound|80||app.supply-and-demand-service.svc.cluster.local" > connect_timeout:<seconds:1 > lb_policy:LEAST_REQUEST circuit_breakers:<thresholds:<> > tls_context:<common_tls_context:<tls_certificates:<certificate_chain:<filename:"" > private_key:<filename:"" > > validation_context:/* nil */ > >
panic: CDS: Generated invalid cluster for node &{Kubernetes sidecar 10.198.8.24 mercury-admin-tool-556854cbc4-5n6vr.mercury-admin-tool mercury-admin-tool.svc.cluster.local map[istio:sidecar INTERCEPTION_MODE:REDIRECT ISTIO_PROXY_VERSION:1.0.0 ISTIO_PROXY_SHA:istio-proxy:6166ae7ebac7f630206b2fe4e6767516bf198313 ISTIO_VERSION:1.0.0 POD_NAME:mercury-admin-tool-556854cbc4-5n6vr]}: invalid Cluster.TlsContext: embedded message failed validation | caused by: invalid UpstreamTlsContext.CommonTlsContext: embedded message failed validation | caused by: invalid CommonTlsContext.TlsCertificates[0]: embedded message failed validation | caused by: invalid TlsCertificate.CertificateChain: embedded message failed validation | caused by: invalid DataSource.Filename: value length must be at least 1 bytes

goroutine 466 [running]:
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawClusters(0xc4201c39e0, 0xc420dae1c0, 0x17b0300, 0xc4209866e0, 0x1822920, 0xc421179140, 0xc42119e600)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:85 +0x5e3
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds(0xc4201c39e0, 0xc420dae1c0, 0x1b, 0xc420f87508)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:49 +0x50
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc4201c39e0, 0x1a33ce0, 0xc4202f3980, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:410 +0x12d2
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1870dc0, 0xc4201c39e0, 0x1a2d9e0, 0xc4207de4d0, 0x24e9118, 0xc420426960)
        /workspace/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:160 +0xb2
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4205ea380, 0x1a35ae0, 0xc420bb2000, 0xc420d68000, 0xc4206eacf0, 0x24b5dc0, 0xc420426900, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1160 +0xa2d
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4205ea380, 0x1a35ae0, 0xc420bb2000, 0xc420d68000, 0xc420426900)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1253 +0x12b1
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420bb0050, 0xc4205ea380, 0x1a35ae0, 0xc420bb2000, 0xc420d68000)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:678 +0xa1
```

**Comment by vadimeisenbergibm** [comment]
Caused by specifying tls mode `MUTUAL` without the certificate/key, mistakenly instead of `ISTIO_MUTUAL`.

**Comment by Stono** [comment]
Thanks @vadimeisenbergibm - might be good for it to do something other than crash! :)

**Comment by ijsnellf** [comment]
@vadimeisenbergibm: can we catch this in validation somewhere?

**Comment by mandarjog** [comment]
Yes web validation hook can reject the config if it specifies mutual without keys.
