### ISSUE TITLE
go generate broken on master

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#8208]
`go generate ./mixer/...` fails with:
```
panic: runtime error: index out of range

goroutine 1 [running]:
istio.io/istio/mixer/tools/mixgen/cmd.apiGenCmd.func1(0xc42020af00, 0xc42024cc60, 0x0, 0x12)
        /home/kuat/go/src/istio.io/istio/mixer/tools/mixgen/cmd/api.go:60 +0x61e
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).execute(0xc42020af00, 0xc42024cb40, 0x12, 0x12, 0xc42020af00, 0xc42024cb40)
        /home/kuat/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42020a780, 0xc42020aa00, 0xc42020af00, 0xc42020ac80)
        /home/kuat/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:846 +0x30a
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42020a780, 0x13, 0x13)
        /home/kuat/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        /home/kuat/go/src/istio.io/istio/mixer/tools/mixgen/main.go:27 +0x8d
exit status 2
mixer/adapter/kubernetesenv/kubernetesenv.go:17: running "/home/kuat/go/src/istio.io/istio/bin/mixer_codegen.sh": exit status 1
```

/assign @douglas-reid

**Comment by hzxuzhonghu** [comment]
@kyessenov I think we should also validate flags `-m`

**Comment by kyessenov** [comment]
Certainly. There is a PR somewhere that should run go generate on presubmit. Seems like it hasn't been merged yet.
