### ISSUE TITLE
Mixer Policy's custom proto cannot be encoded by proto.Marshal()

### ISSUE THREAD

**Issue by ayj** [istio/istio#8486]
Issue originally reported in https://github.com/istio/istio/pull/8356. Some of the Mixer Policy protobufs are re-written to use `interface{}` instead of `google.protobuf.Struct`. This causes problems when the standard protobuf code tries to encode/marshal the proto, e.g. Galley and MCP.

We either need to write a custom encoder or switch the Mixer types back to the standard `google.protobuf.Struct` type.

```bash
$ cat handler.go 
package main

import (
        "github.com/gogo/protobuf/proto"
        cfg "istio.io/api/policy/v1beta1"
)

func main() {
        c := &cfg.Handler{Name: "foo"}
        proto.Marshal(c)
}

$ go run handler.go 
panic: unknown or mismatched type: type: interface {}, wire type: bytes

goroutine 1 [running]:
istio.io/istio/vendor/github.com/gogo/protobuf/proto.typeMarshaler(0x5db940, 0x589c00, 0xc420056080, 0x4, 0x4, 0xc420050000, 0x4, 0x4)
        /home/jasonyoung/work/src/istio.io/istio/vendor/github.com/gogo/protobuf/proto/table_marshal.go:882 +0x1d90
istio.io/istio/vendor/github.com/gogo/protobuf/proto.(*marshalFieldInfo).setMarshaler(0xc420001158, 0xc420088150, 0xc420056080, 0x4, 0x4)
        /home/jasonyoung/work/src/istio.io/istio/vendor/github.com/gogo/protobuf/proto/table_marshal.go:553 +0x9d
istio.io/istio/vendor/github.com/gogo/protobuf/proto.(*marshalFieldInfo).computeMarshalFieldInfo(0xc420001158, 0xc420088150)
        /home/jasonyoung/work/src/istio.io/istio/vendor/github.com/gogo/protobuf/proto/table_marshal.go:481 +0x1a5
istio.io/istio/vendor/github.com/gogo/protobuf/proto.(*marshalInfo).computeMarshalInfo(0xc420086000)
        /home/jasonyoung/work/src/istio.io/istio/vendor/github.com/gogo/protobuf/proto/table_marshal.go:411 +0xb0f
istio.io/istio/vendor/github.com/gogo/protobuf/proto.(*marshalInfo).size(0xc420086000, 0xc42006a140, 0xc42000a080)
        /home/jasonyoung/work/src/istio.io/istio/vendor/github.com/gogo/protobuf/proto/table_marshal.go:170 +0x3b1
istio.io/istio/vendor/github.com/gogo/protobuf/proto.(*InternalMessageInfo).Size(0xc42000a080, 0x5d99c0, 0xc42006a140, 0x0)
        /home/jasonyoung/work/src/istio.io/istio/vendor/github.com/gogo/protobuf/proto/table_marshal.go:129 +0x65
istio.io/istio/vendor/github.com/gogo/protobuf/proto.Marshal(0x5d99c0, 0xc42006a140, 0x0, 0x0, 0xc4200645a0, 0xc420045f78, 0xc420062058)
        /home/jasonyoung/work/src/istio.io/istio/vendor/github.com/gogo/protobuf/proto/table_marshal.go:2749 +0xf4
main.main()
        /home/jasonyoung/work/src/istio.io/istio/handler.go:10 +0x63
exit status 2
```

**Comment by ayj** [comment]
cc @ozevren @douglas-reid

**Comment by kyessenov** [comment]
Worth to track upstream api-v2 branch with proto reflection:
https://github.com/golang/protobuf/commit/dbc9a12dbdd230536931ac3028b20578546dac72

**Comment by ozevren** [comment]
Removed the custom proto format (which was not marshallable):https://github.com/istio/api/pull/631
