### ISSUE TITLE
gRPC : protocol error: http/1.1 protocol error: HPE_INVALID_CONSTANT

### ISSUE THREAD

**Issue by shettyh** [istio/istio#9045]
**Describe the bug**
gRPC routing to Java service is failing

**Expected behavior**
gRPC proxying should work

**Steps to reproduce the bug**
- Have java service that use the gRPC 1.3.0
- Create Gateway and VS to route the traffic to service from ingress

**Version**

Istio Version

```
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

```

Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Installation**
Helm based installation

**Environment**
Bare metal

**Logs**

Istio Logs

```
[2018-09-29 06:08:29.359][23][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 2, RDS: Failed to generate route http.17000 for node &{Kubernetes router 10.244.0.116 istio-ingressgateway-677f4547f5-5rj8w.istio-system istio-system.svc.cluster.local map[ISTIO_VERSION:1.0.2 POD_NAME:istio-ingressgateway-677f4547f5-5rj8w istio:sidecar ISTIO_PROXY_VERSION:1.0.2 ISTIO_PROXY_SHA:istio-proxy:99cfc3f74c414dd4fa4aa784a0f8b13e22b81893]}: buildGatewayRoutes: could not find server for routeName http.17000, have map[http.15031:[port:<number:15031 protocol:"HTTP2" name:"http2-grafana" > hosts:"*" ] http.15030:[port:<number:15030 protocol:"HTTP2" name:"http2-prometheus" > hosts:"*" ]]
[2018-09-29 06:08:29.658][23][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 2, RDS: Failed to generate route http.17000 for node &{Kubernetes router 10.244.0.116 istio-ingressgateway-677f4547f5-5rj8w.istio-system istio-system.svc.cluster.local map[ISTIO_VERSION:1.0.2 POD_NAME:istio-ingressgateway-677f4547f5-5rj8w istio:sidecar ISTIO_PROXY_VERSION:1.0.2 ISTIO_PROXY_SHA:istio-proxy:99cfc3f74c414dd4fa4aa784a0f8b13e22b81893]}: buildGatewayRoutes: could not find server for routeName http.17000, have map[http.15030:[port:<number:15030 protocol:"HTTP2" name:"http2-prometheus" > hosts:"*" ] http.15031:[port:<number:15031 protocol:"HTTP2" name:"http2-grafana" > hosts:"*" ]]
[2018-09-29 06:08:30.118][23][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '0.0.0.0_17000'
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:160] Add a new Referenced for check cache: Absence-keys: destination.namespace, destination.port, destination.uid, source.ip, Exact-keys: context.protocol, context.reporter.kind, destination.service, source.namespace, source.uid,
[2018-09-29 06:08:49.349][28][info][client] external/envoy/source/common/http/codec_client.cc:117] [C73] protocol error: http/1.1 protocol error: HPE_INVALID_CONSTANT
[2018-09-29T06:08:49.346Z] "POST /om.rpc.Registration/Register HTTP/2" 200 UC 342 0 2 - "10.244.0.1" "grpc-java-netty/1.12.0" "c31b0286-56ec-90a2-972d-bf098adc0933" "10.142.138.254:17000" "10.244.0.115:17001"
[2018-09-29T06:10:27.676Z] "- - HTTP/2" 0 - 0 0 0 - "-" "-" "-" "-" "-"
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:160] Add a new Referenced for check cache: Absence-keys: destination.namespace, destination.port, destination.uid, source.ip, Exact-keys: context.protocol, context.reporter.kind, destination.service, source.namespace, source.uid,
[2018-09-29 06:10:56.755][39][info][client] external/envoy/source/common/http/codec_client.cc:117] [C76] protocol error: http/1.1 protocol error: HPE_INVALID_CONSTANT
[2018-09-29T06:10:56.749Z] "POST /telemetry.rpc.Telemetry/GetDeviceLocationForTimestamp HTTP/2" 200 UC 5 0 5 - "10.244.0.1" "grpc-go/1.12.3-dev" "d6675e08-e152-97c3-b086-6f2655ae1591" "10.142.138.254:17000" "10.244.0.91:17002"

```

gRPC Service logs

```
Sep 29, 2018 6:00:47 AM io.grpc.netty.NettyServerHandler onConnectionError
WARNING: Connection Error
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 504f5354202f6f6d2e7270632e526567697374726174696f
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:277)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:217)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:401)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)

Sep 29, 2018 6:00:47 AM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 504f5354202f6f6d2e7270632e526567697374726174696f
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:277)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:217)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:401)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
```

**Observation**

Strange thing is gRPC proxying to a Golang service that use the latest gRPC version works just fine.
Is there any restrictions which version of gRPC should be used ?

**Comment by shettyh** [comment]
Upgraded to latest version of gRPC. Now i cam getting the same error on istio but on service i am getting this

```
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /om.rpc.Registration/Register
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:314)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)


```

**Comment by shettyh** [comment]
Strangely the problem was the k8s service not having the name for the port. If i give the name to the port it works.

**Comment by majelbstoat** [comment]
More precisely, when I had this problem running within k8s, I found I needed to give the services a named port that followed a very specific format: `grpc-*`. (I understand `http2-*` might also have worked.) When it was named `http-*`, it did not work, as requests were sent at HTTP 1.1.

**Comment by lishuhao** [comment]
@majelbstoat This helped me! But why?

**Comment by shikanon** [comment]
It used to me. But I want to know why?

**Comment by shikanon** [comment]
> @majelbstoat This helped me! But why?

istio document has instructions:
https://istio.io/latest/zh/docs/ops/deployment/requirements/
