### ISSUE TITLE
Latest nightly-release-1.0 throws "function "toJson" not defined"

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#9467]
**K8**: 1.10.7
**Istio**: Nightly-1.0

Pulled the latest nightly,

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
  --set global.hub=istionightly \
  --set global.tag=nightly-release-1.0 \
  --set global.imagePullPolicy=Always \
  --set sidecarInjectorWebhook.enabled=true \
  --set global.proxy.envoyStatsd.enabled=false \
  --set global.mtls.enabled=true \
  --set global.controlPlaneSecurityEnabled=true \
  --set security.selfSigned=true \
  --set global.enableTracing=false \
  --set global.proxy.autoInject=enabled \
  --set tracing.enabled=false \
  --set prometheus.enabled=false
```

However it appears to be broken when auto-injecting the sidecar,

```
2018-10-23T01:16:11.779395Z	info	http2: panic serving 10.4.3.1:41814: template: inject:96: function "toJson" not defined
goroutine 463 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc42045f2b0, 0xc4200adfaf, 0xc420106000)
	/usr/local/go/src/net/http/h2_bundle.go:5753 +0x190
panic(0x1296580, 0xc4202e4aa0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
text/template.Must(0x0, 0x157cea0, 0xc4202e4aa0, 0x0)
	/usr/local/go/src/text/template/helper.go:23 +0x54
istio.io/istio/pilot/pkg/kube/inject.injectionData(0xc420262a00, 0x1330, 0xc420304ac0, 0x40, 0xc42010b288, 0xc42010b1a0, 0xc4200b6960, 0xc4202241c0, 0x0, 0x0, ...)
	/go/src/istio.io/istio/pilot/pkg/kube/inject/inject.go:453 +0x477
istio.io/istio/pilot/pkg/kube/inject.(*Webhook).inject(0xc42047cd10, 0xc4204a94d0, 0xf3b)
	/go/src/istio.io/istio/pilot/pkg/kube/inject/webhook.go:504 +0x68f
istio.io/istio/pilot/pkg/kube/inject.(*Webhook).serveInject(0xc42047cd10, 0x1598a60, 0xc42045f2b0, 0xc420642000)
	/go/src/istio.io/istio/pilot/pkg/kube/inject/webhook.go:557 +0x669
istio.io/istio/pilot/pkg/kube/inject.(*Webhook).(istio.io/istio/pilot/pkg/kube/inject.serveInject)-fm(0x1598a60, 0xc42045f2b0, 0xc420642000)
	/go/src/istio.io/istio/pilot/pkg/kube/inject/webhook.go:182 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202980e0, 0x1598a60, 0xc42045f2b0, 0xc420642000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420286ae0, 0x1598a60, 0xc42045f2b0, 0xc420642000)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc420092dd0, 0x1598a60, 0xc42045f2b0, 0xc420642000)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.initNPNRequest.ServeHTTP(0xc4201da380, 0xc420092dd0, 0x1598a60, 0xc42045f2b0, 0xc420642000)
	/usr/local/go/src/net/http/server.go:3260 +0x9a
net/http.(Handler).ServeHTTP-fm(0x1598a60, 0xc42045f2b0, 0xc420642000)
	/usr/local/go/src/net/http/h2_bundle.go:5475 +0x4d
net/http.(*http2serverConn).runHandler(0xc420106000, 0xc42045f2b0, 0xc420642000, 0xc4206ca940)
	/usr/local/go/src/net/http/h2_bundle.go:5760 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5494 +0x46b
```

**Comment by nixgadget** [comment]
Never mind. Looks like this has not been updated lately so switching to `1.1.0.snapshot.1` which appears to work.

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
  --set global.hub=istio \
  --set global.tag=1.1.0.snapshot.1 \
  --set global.imagePullPolicy=Always \
  --set sidecarInjectorWebhook.enabled=true \
  --set global.proxy.envoyStatsd.enabled=false \
  --set global.mtls.enabled=true \
  --set global.controlPlaneSecurityEnabled=true \
  --set security.selfSigned=true \
  --set global.enableTracing=false \
  --set global.proxy.autoInject=enabled \
  --set tracing.enabled=false \
  --set prometheus.enabled=false
```
