### ISSUE TITLE
Creation of Gateway is failed on EKS

### ISSUE THREAD

**Issue by dshmatov** [istio/istio#9503]
I'm trying to apply simple Gateway, like:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
      - "*"
  - port:
      number: 80
      name: http
      protocol: HTTP
```
And got an error while applying config via `kubectl` command:
```
Error from server (InternalError): error when creating "/home/ds/istio/1-gateway.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: stream error: stream ID 5; INTERNAL_ERROR
```
What I got in Galley logs:
```
2018-10-24T13:39:11.383414Z	info	http2: panic serving 10.33.179.184:40600: runtime error: invalid memory address or nil pointer dereference
goroutine 88771 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc42000cb48, 0xc420957faf, 0xc42018e8c0)
	/usr/local/go/src/net/http/h2_bundle.go:5753 +0x190
panic(0x18c00a0, 0x28c49e0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
istio.io/istio/pilot/pkg/model.ValidateGateway(0xc42039e5f0, 0x10, 0xc42039e5e8, 0x7, 0x1d1a400, 0xc42051e7c0, 0xa, 0x1b49b21)
	/workspace/go/src/istio.io/istio/pilot/pkg/model/validation.go:392 +0x242
istio.io/istio/galley/pkg/crd/validation.(*Webhook).admitPilot(0xc420367180, 0xc42020b040, 0xc4203c4570)
	/workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:398 +0x45e
istio.io/istio/galley/pkg/crd/validation.(*Webhook).(istio.io/istio/galley/pkg/crd/validation.admitPilot)-fm(0xc42020b040, 0xc4203a1000)
	/workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:364 +0x34
istio.io/istio/galley/pkg/crd/validation.serve(0x1d24d00, 0xc42000cb48, 0xc4203d7500, 0xc42072fcc0)
	/workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:340 +0x4ee
istio.io/istio/galley/pkg/crd/validation.(*Webhook).serveAdmitPilot(0xc420367180, 0x1d24d00, 0xc42000cb48, 0xc4203d7500)
	/workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:364 +0x5f
istio.io/istio/galley/pkg/crd/validation.(*Webhook).(istio.io/istio/galley/pkg/crd/validation.serveAdmitPilot)-fm(0x1d24d00, 0xc42000cb48, 0xc4203d7500)
	/workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:224 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420242bb0, 0x1d24d00, 0xc42000cb48, 0xc4203d7500)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420246f60, 0x1d24d00, 0xc42000cb48, 0xc4203d7500)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42054c9c0, 0x1d24d00, 0xc42000cb48, 0xc4203d7500)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.initNPNRequest.ServeHTTP(0xc420518380, 0xc42054c9c0, 0x1d24d00, 0xc42000cb48, 0xc4203d7500)
	/usr/local/go/src/net/http/server.go:3260 +0x9a
net/http.(Handler).ServeHTTP-fm(0x1d24d00, 0xc42000cb48, 0xc4203d7500)
	/usr/local/go/src/net/http/h2_bundle.go:5475 +0x4d
net/http.(*http2serverConn).runHandler(0xc42018e8c0, 0xc42000cb48, 0xc4203d7500, 0xc4200c81a0)
	/usr/local/go/src/net/http/h2_bundle.go:5760 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5494 +0x46b
```
I've tried to reproduce on v1.0.1 and v1.0.2 Istio both. My platform is EKS

**Comment by dshmatov** [comment]
Thanks @ayj ! I was too tired to see my typo but helped to catch a validation error
