### ISSUE TITLE
build pilot has error

### ISSUE THREAD

**Issue by yiqinguo** [istio/istio#985]
When build pilot there is a error:

ERROR: /root/project/src/istio.io/pilot/tools/version/BUILD:3:1: in go_library rule //tools/version:go_default_library:
Traceback (most recent call last):
	File "/root/project/src/istio.io/pilot/tools/version/BUILD", line 3
		go_library(name = 'go_default_library')
	File "/root/.cache/bazel/_bazel_root/45507ab381605003f52f903ce085fa3d/external/io_bazel_rules_go/go/private/library.bzl", line 143, in _go_library_impl
		emit_library_actions(ctx, sources = depset(ctx.files.sr...), <4 more arguments>)
	File "/root/.cache/bazel/_bazel_root/45507ab381605003f52f903ce085fa3d/external/io_bazel_rules_go/go/private/library.bzl", line 44, in emit_library_actions
		depset([], order = "link")
Order name 'link' is deprecated, use 'topological' instead.
ERROR: Analysis of target '//tools/version:go_default_library' failed; build aborted.

**Comment by ldemailly** [comment]
which OS and bazel version are you using ? 
did you run `make setup` ?
(per https://github.com/istio/pilot/blob/master/doc/build.md )

also please do not file pilot specific issues in istio/istio

use either https://github.com/istio/issues/issues or in this case https://github.com/istio/pilot/issues/new

Thanks!

**Comment by yiqinguo** [comment]
I have sloved it.Change the file /root/.cache/bazel/_bazel_root/45507ab381605003f52f903ce085fa3d/external/io_bazel_rules_go/go/private/library.bzl line 44 link to topological. But I can not fundamentally solve it.
