### ISSUE TITLE
Pilot 1.1 deadlock - release-1.1-20181109-09-15

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#9882]
Pilot 1.1 in long running tests quiets down. Pilot maintains open connections to all sidecars but stops pushing any more updates.

**Version**
`gcr.io/istio-release/pilot:release-1.1-20181109-09-15`

Pilot is in a 3-way deadlock

```
Holds: updateChannel wants: updateMutex

goroutine 145 [semacquire, 234 minutes]: 1 times: [[145]
sync.runtime_SemacquireMutex(0xc420600d8c, 0xc420118800)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420600d88)
	/usr/local/go/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0xc420600d88)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).handleUpdates(0xc420600d00)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:510 +0xa6
created by istio.io/istio/pilot/pkg/proxy/envoy/v2.NewDiscoveryServer
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:247 +0x216
```
```
Holds: updateMutex  wants: mutex
goroutine 1849830 [semacquire, 234 minutes]: 1 times: [[1849830]
sync.runtime_SemacquireMutex(0xc420600d50, 0x27dcdb0064201)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420600d4c)
	/usr/local/go/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0xc420600d4c)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).doPush(0xc420600d00)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:471 +0xa8
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).debouncePush(0xc420600d00, 0xbef19ea4a3d49bc2, 0x7376837742, 0x27f7f60)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:452 +0x247
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).handleUpdates.func1()
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:523 +0x45
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
```
```
Holds: mutex wants: updateChannel
goroutine 1847659 [chan send, 234 minutes]: 1 times: [[1847659]
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).ConfigUpdate(...)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:496
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).edsUpdate(0xc420600d00, 0x1aae732, 0xa, 0xc422878390, 0x2d, 0xc456c12840, 0x2, 0x2, 0x1, 0x0, ...)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:563 +0x504
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).updateServiceShards(0xc420600d00, 0xc42bcd8000, 0xc42bcd8000, 0x0)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:354 +0x70b
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).Push(0xc420600d00, 0x7361dcca01, 0xc423636210)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:362 +0x3c3
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).doPush(0xc420600d00)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:484 +0x11f
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).debouncePush(0xc420600d00, 0xbef19ea476d53088, 0x734de941dd, 0x27f7f60)
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:452 +0x247
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).debouncePush.func1()
	/workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/discovery.go:456 +0x45
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
```

**Comment by mandarjog** [comment]
@costinm @rshriram
